Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2018-06, with the labels that each got.

#9497 Save for Later: Prevent saved posts being deleted with their topics
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/ViewRelated/Reader/ReaderCellConfiguration.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
Labels: Reader, Save for Later

#9501 Enable Zendesk
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Zendesk

#9498 Fix IDN domain login
  WordPress/Classes/Models/Blog.m
  WordPressAuthenticator/WordPressAuthenticator/Authenticator/WordPressAuthenticator.swift
  WordPressAuthenticator/WordPressAuthenticator/Signin/LoginSelfHostedViewController.swift
  WordPressAuthenticator/WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorTests.swift
Labels: Login

#9503 Remove username changing flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
Labels: NUX

#9500 Reader: Clear saved posts on account change
  WordPress/Classes/Services/ReaderPostService.h
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
Labels: Reader, Save for Later

#9505 Reader Cards: Update Save for Later button title / style
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
  WordPress/WordPressTest/ReaderPostCardCellTests.swift
Labels: Design, Reader, Save for Later

#9495 Display Zendesk views from correct view controller
  WordPress/Classes/ViewRelated/Me/MeViewController.swift
Labels: Zendesk

#9502 Integrates initial Gutenberg compatibility fixes from Aztec.
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#9499 Save for later: Add 'remove from saved posts' animation
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.h
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.m
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterRemovedPosts.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostUndoCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostUndoCell.xib
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader, Save for Later, [Type] Task

#9506 Save for Later: Enable feature flag for all
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Reader, Save for Later, [Type] Task

#9511 Reader: Improve item alignment in reader headers
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
Labels: Design, Reader

#9515 Zendesk Mobile: Support email prompt - update text.
  WordPress/Classes/Utility/ZendeskUtils.swift
Labels: Zendesk

#9519 Extensions: fixed site list ordering
  WordPress/Classes/Services/ShareExtensionService.swift
  WordPress/Classes/System/Constants.h
  WordPress/Classes/System/Constants.m
  WordPress/Classes/System/WordPressAppDelegate+Swift.swift
  WordPress/WordPressShareExtension/AppExtensionsService.swift
Labels: Draft Extension, Share Extension

#9520 Add the word `draft` in the appropriate local push notification titles…
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/ExtensionNotificationManager.swift
  WordPress/WordPressShareExtension/ShareNoticeConstants.swift
  WordPress/WordPressShareExtension/ShareNoticeViewModel.swift
Labels: Draft Extension, Share Extension

#9524 Nuking AFNetworking: AztecPostViewController!
  WordPress/Classes/Utility/Media/ImageDownloader.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#9529 Notifications: Extending Comment's "Source" Clickable Area
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockTextTableViewCell.swift
Labels: Notifications

#9522 Issue/9476 truncated buttons
  WordPressAuthenticator/WordPressAuthenticator/NUX/NUXCollectionViewController.swift
  WordPressAuthenticator/WordPressAuthenticator/NUX/NUXTableViewController.swift
  WordPressAuthenticator/WordPressAuthenticator/NUX/NUXViewController.swift
  WordPressAuthenticator/WordPressAuthenticator/NUX/NUXViewControllerBase.swift
  WordPressAuthenticator/WordPressAuthenticator/Signin/Login.storyboard
Labels: Localization

#9521 Don’t show ‘Need help’ button on 'Unable to Sync' alert if internet not accessible.
  WordPress/Classes/Utility/WPError.h
  WordPress/Classes/Utility/WPError.m
Labels: Network/Sync, [Status] Ready to Merge

#9534 Fix issue where images could get cropped on the reader detail
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift
Labels: Reader, [Type] Bug

#9516 Update delete site alert
  WordPress/Classes/ViewRelated/Blog/SiteManagement/DeleteSiteViewController.swift
Labels: Delete Site, [Status] Needs Code Review

#9517 Nuking AFNetworking: Notifications Media Downloader
  WordPress/Classes/Utility/Media/ImageDownloader.swift
  WordPress/Classes/ViewRelated/Notifications/Tools/NotificationMediaDownloader.swift
Labels: [Type] Tech Debt

#9526 Share extension: Associate Post and uploaded Media items
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
Labels: Draft Extension, Share Extension, [Type] Bug

#9540 Sets up hockeyapp daily notifications
  WordPress/Classes/Utility/HockeyManager.m
Labels: [Type] Enhancement

#9533 Notifications: Pingbacks Read Source footer
  WordPress/Classes/Models/Notifications/Notification.swift
  WordPress/Classes/Models/Notifications/NotificationBlock.swift
  WordPress/Classes/Models/Notifications/NotificationBlockGroup.swift
  WordPress/Classes/Models/Notifications/NotificationRange.swift
Labels: Notifications

#9543 App extensions now use NSExtensionActivationRule predicates
  WordPress/WordPressDraftActionExtension/Info-Alpha.plist
  WordPress/WordPressDraftActionExtension/Info-Internal.plist
  WordPress/WordPressDraftActionExtension/Info.plist
  WordPress/WordPressShareExtension/Info-Alpha.plist
  WordPress/WordPressShareExtension/Info-Internal.plist
  WordPress/WordPressShareExtension/Info.plist
Labels: Draft Extension, Share Extension

#9537 Stop using simple previews as fallback
  WordPress/Classes/Extensions/NotificationCenter+ObserveOnce.swift
  WordPress/Classes/Utility/ReachabilityUtils+OnlineActions.swift
  WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
  WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Extensions/NotificationCenterObserveOnceTests.swift
Labels: Posting/Editing

#9539 HotFix: Check for existing featuredImage url befo…
  WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.h
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: [Type] Crash

#9546 Check for NoResultsViewController before using it.
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Labels: NoResultsView

#9553 Update Gemfile.lock after running rake dependencies
  Gemfile.lock
Labels: General

#9554 Ensures account_created events are not sent as an anon user.
  WordPress/Classes/Services/AccountService.m
  WordPressAuthenticator/WordPressAuthenticator/NUX/NUXLinkAuthViewController.swift
  WordPressAuthenticator/WordPressAuthenticator/Signin/LoginViewController.swift
Labels: Analytics

#9545 Uploading media via the Share extension silently fails for Contributors
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/RemoteBlog+Capabilities.swift
  WordPress/WordPressShareExtension/ShareModularViewController.swift
Labels: Draft Extension, Share Extension, [Type] Bug

#9531 WebKitViewController nav bar buttons color for accessibility bold text
  WordPress/Classes/Utility/CookieJar.swift
  WordPress/Classes/Utility/WPWebViewController.m
  WordPress/Classes/Utility/WebKitViewController.swift
Labels: Accessibility

#9548 Avoid removing label from follow icon on the reader
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Labels: Reader

#9552 Present "Discover" as a site stream
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
Labels: Reader

#9559 Fixing Warning
  WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
Labels: [Type] Bug

#9542 Remove extra whitespace in the comments of notifications
  WordPress/Classes/Extensions/Notifications/NotificationBlock+Interface.swift
Labels: Notifications

#9544 Hide masterbar in webviews
  WordPress/Classes/Extensions/URL+Helpers.swift
  WordPress/Classes/System/Constants.h
  WordPress/Classes/System/Constants.m
  WordPress/Classes/Utility/WPWebViewController.h
  WordPress/Classes/Utility/WPWebViewController.m
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/Classes/Utility/WebViewControllerConfiguration.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/NUX/SiteCreationSitePreviewViewController.swift
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Labels: Masterbar

#9523 Update to WordPressKit that only uses AlamoFire
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Test Data/WordPressOAuthClientNeed2FAFail.json
  WordPress/WordPressTest/Test Data/WordPressOAuthClientSuccess.json
  WordPress/WordPressTest/Test Data/WordPressOAuthClientWrongPasswordFail.json
  WordPress/WordPressTest/Test Data/xmlrpc-bad-username-password-error.xml
  WordPress/WordPressTest/Test Data/xmlrpc-malformed-request-xml-error.xml
  WordPress/WordPressTest/Test Data/xmlrpc-response-fault.xml
  WordPress/WordPressTest/Test Data/xmlrpc-response-newpost.xml
  WordPress/WordPressTest/Test Data/xmlrpc-response-redirect.html
  WordPress/WordPressTest/Test Data/xmlrpc-response-system-listmethods.xml
  WordPress/WordPressTest/WordPressAPI/WordPressComOAuthClientTests.swift
Labels: [Type] Enhancement

#9570 Issue/9530 featured image bug
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: [Type] Bug

#9557 Adds basic Core Data model checks when changing things in a release branch
  Dangerfile
Labels: General

#9562 Adding Zendesk push notification test.
  WordPress/WordPressTest/PushNotificationsManagerTests.m
Labels: Zendesk

#9571 Removing unused Support tracks.
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/Utility/HelpshiftUtils.m
  WordPress/Classes/ViewRelated/Me/SupportViewController.m
  WordPress/Vendor/Helpshift/HelpshiftSupport.h
Labels: Zendesk

#9568 Remove Helpshift supporting code
  WordPress/Classes/Utility/WPImmuTableRows.swift
  WordPress/Classes/ViewRelated/Me/MeViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/NUX/WordPressSupportSourceTag+Helpers.swift
Labels: Zendesk

#9575 Remove Helpshift code from NUX View Controllers
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Zendesk

#9577 Remove helpshift credentials
  WordPress/Credentials/ApiCredentials.h
  WordPress/Credentials/ApiCredentials.m
  WordPress/Credentials/gencredentials.rb
  WordPress/Credentials/wpcom_app_credentials.txt
Labels: Zendesk

#9573 Remove unused AFNetwork references
  WordPress/Classes/Categories/UIImageView+AFNetworkingExtra.h
  WordPress/Classes/Categories/UIImageView+AFNetworkingExtra.m
  WordPress/Classes/System/WordPressAppDelegate.m
  WordPress/Classes/ViewRelated/Blog/SharingConnectionsViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingViewController.m
  WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General, [Status] In Progress

#9586 Track whether a post includes Gutenberg blocks
  WordPress/Classes/Models/AbstractPost.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: Analytics, Posting/Editing

#9569 Update gifu pod to 3.1.0
  Podfile
  Podfile.lock
Labels: [Type] Tech Debt

#9588 Activity List: replace No Results view
  WordPress/Classes/Extensions/NoResultsViewController+Model.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
  WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: NoResultsView

#9590 Plan List: replace No Results view
  WordPress/Classes/Extensions/NoResultsViewController+Model.swift
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
  WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
  WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
  WordPress/Classes/ViewRelated/Views/NoResults.storyboard
Labels: NoResultsView

#9597 Reader Saved Posts: Display promo alert the first time the feature is used
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+SavedPosts.swift
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-mobile-save-for-later.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-mobile-save-for-later.imageset/illustration-mobile-save-for-later.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader, Save for Later, [Type] Enhancement

#9592 Update Aztec pod to beta 20
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Aztec/Processors/DocumentUploadProcessor.swift
  WordPress/Classes/ViewRelated/Aztec/Processors/ImgUploadProcessor.swift
  WordPress/Classes/ViewRelated/Aztec/Processors/VideoUploadProcessor.swift
Labels: Aztec

#9598 Add new analytics events for OS notification alert
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/Utility/InteractiveNotificationsManager.swift
Labels: Analytics

#9603 Update cocoapods to 1.5.3
  Gemfile
  Gemfile.lock
Labels: General

#9605 AztecPostViewController: Preventing UIViewControllerHierarchyInconsistency
  WordPress/Classes/ViewRelated/Aztec/Stock Photos/AztecMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Aztec/Stock Photos/MediaPickingOptionsDelegate.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecNavigationController.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Crash

#9527 Flip icons for RTL layout
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
  WordPress/Classes/ViewRelated/Aztec/Extensions/FormatBarItemProviders.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Post/PostCardActionBarItem.m
  WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib
  WordPress/Classes/ViewRelated/Post/PostCardTextCell.xib
  WordPress/Classes/ViewRelated/Reader/Reader.storyboard
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Labels: Localization

#9550 ReaderPostCardCell.xib: Bigger action buttons
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
Labels: Reader

#9593 Remove unused source tag
  WordPress/Classes/Utility/WPError.h
  WordPress/Classes/Utility/WPError.m
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: Support

#9619 Integrates the latest from Aztec.
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecAttachmentViewController.swift
  WordPress/WordPressTest/Posts/PostAttachmentTests.swift
Labels: Posting/Editing

#9620 Roles: change button text on alert
  WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
Labels: People Management

#9624 Extensions: Exclude WPiOS extensions from login share sheet
  WordPress/WordPressDraftActionExtension/Info-Alpha.plist
  WordPress/WordPressDraftActionExtension/Info-Internal.plist
  WordPress/WordPressDraftActionExtension/Info.plist
  WordPress/WordPressShareExtension/Info-Alpha.plist
  WordPress/WordPressShareExtension/Info-Internal.plist
  WordPress/WordPressShareExtension/Info.plist
Labels: Draft Extension, Share Extension, [Type] Bug

#9622 When associating posts and images uploaded via share extension, set the postID within the work item
  WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
Labels: Share Extension, [Type] Bug

#9629 Update media picker to 1.1
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Media/ImageLoader.swift
Labels: Media

#9613 CommentViewController: Bad URL Failsafe
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
Labels: [Type] Crash

#9627 Hide WP masterbar in post previews.
  WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
Labels: Masterbar

#9609 Update 'clear media cache' labelling
  WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
Labels: Media

#9628 Add gravatar upload to signup epilogue
  WordPress/Classes/ViewRelated/Me/GravatarUploader.swift
  WordPress/Classes/ViewRelated/Me/MeViewController.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
  WordPress/Resources/AppImages.xcassets/gravatar-add-button.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/gravatar-add-button.imageset/gravatar-add-button.pdf
  WordPress/Resources/AppImages.xcassets/gravatar-hollow.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/gravatar-hollow.imageset/gravatar-hollow.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: NUX

#9621 Feature/9356 gif support in mediapicker preview
  WordPress/Classes/Utility/Media/ImageLoader.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Media/CircularProgressView.swift
  WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaPreviewHelper.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/WPImageViewController.h
  WordPress/Classes/ViewRelated/Reader/WPImageViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: gif support

#9637 Fix/9623 crash post settings view controller release
  WordPress/Classes/Models/Page.swift
  WordPress/Classes/ViewRelated/Pages/PageSettingsViewController.m
Labels: [Type] Crash

#9632 Logout: Let's be friendly!
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/ViewRelated/Me/MeViewController.swift
Labels: Groundskeeping, [Type] Enhancement

#9644 Setting log timestamp locale to English.
  WordPress/Classes/Utility/Logging/CocoaLumberjack.swift
  WordPress/Classes/Utility/Logging/CustomLogFormatter.swift
  WordPress/Classes/Utility/Logging/WPLogger.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Zendesk

#9649 Send Free Space to Zendesk in English.
  WordPress/Classes/Utility/ZendeskUtils.swift
Labels: Zendesk

#9648 Update Aztec to beta 21.
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Labels: Aztec, Gutenberg compatibility

#9642 Update Gridicons to 0.16
  Podfile
  Podfile.lock
Labels: [Type] Task

#9640 FeatureFlag: Activating `gifSupportInReaderDetail` feature for everyone.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: gif support

#9635 Version management script update
  Scripts/manage-version.sh
Labels: General

#9655 Make SiteCreationParams.theme non-optional
  WordPress/Classes/Services/SiteCreationService.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationCreateSiteViewController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationFields.swift
Labels: NUX

#9656 [Activity Log] Implement the Flux ActivityStore.
  WordPress/Classes/Stores/ActivityStore.swift
  WordPress/Classes/Stores/StoreContainer.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Activity Log

#9652 Fix a flaky test
  WordPress/WordPressTest/ReaderTopicServiceTest.swift
Labels: [Type] Tech Debt

#9657 Extract notifications: refactor actions actions
  WordPress/Classes/Models/Notifications/Actions/ApproveComment.swift
  WordPress/Classes/Models/Notifications/Actions/EditComment.swift
  WordPress/Classes/Models/Notifications/Actions/Follow.swift
  WordPress/Classes/Models/Notifications/Actions/Identifier.swift
  WordPress/Classes/Models/Notifications/Actions/LikeComment.swift
  WordPress/Classes/Models/Notifications/Actions/LikePost.swift
  WordPress/Classes/Models/Notifications/Actions/MarkAsSpam.swift
  WordPress/Classes/Models/Notifications/Actions/NotificationAction.swift
  WordPress/Classes/Models/Notifications/Actions/NotificationActionParser.swift
  WordPress/Classes/Models/Notifications/Actions/ReplyToComment.swift
  WordPress/Classes/Models/Notifications/Actions/TrashComment.swift
  WordPress/Classes/Models/Notifications/Notification.swift
  WordPress/Classes/Models/Notifications/NotificationBlock.swift
  WordPress/Classes/Services/NotificationActionsService.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Activity Log, Notifications, Refactor, [Type] Tech Debt

#9658 Updates to the latest from Aztec.
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Aztec/Extensions/VideoAttachment+WordPress.swift
  WordPress/Classes/ViewRelated/Aztec/Processors/VideoUploadProcessor.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
Labels: Aztec

#9672 Fix warning in xib
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
Labels: [Type] Tech Debt

#9666 Activity Log: UI updates
  WordPress/Classes/Extensions/Array.swift
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Stores/ActivityStore.swift
  WordPress/Classes/ViewRelated/Activity/ActivityDateFormatting.swift
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
  WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
  WordPress/Classes/ViewRelated/Activity/RewindStatusRow.swift
  WordPress/Classes/ViewRelated/Activity/RewindStatusTableViewCell.xib
  WordPress/Classes/ViewRelated/Plans/PlanListViewModel.swift
  WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewModel.swift
  WordPress/Classes/ViewRelated/Plugins/PluginListViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Activity Log

#9676 Issues/track support identity usage
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/ActivityStore.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: Activity Log, Analytics, Zendesk

#9675 [ActivityLog] Remove the Activity feature flag.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Labels: Activity Log
