Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2018-10, with the labels that each got.

#10209 Update Podfile to reference an official Zendesk release
  Podfile
  Podfile.lock
Labels: Zendesk

#10171 Issue/9856 make active plan optional
  Podfile
  Podfile.lock
  WordPress/Classes/Services/PlanService.swift
  WordPress/Classes/ViewRelated/Plans/PlanComparisonViewController.swift
  WordPress/Classes/ViewRelated/Plans/PlanDetailViewController.swift
  WordPress/Classes/ViewRelated/Plans/PlanDetailViewModel.swift
Labels: Plans & Checkout

#10220 Fix crash caused by posting a notice off the main thread
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
Labels: [Type] Bug, [Type] Crash

#10219 Use the URL keyboard when adding a followed site
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
Labels: Reader, [Type] Enhancement

#10229 Update Podfile to the released versions
  Podfile
  Podfile.lock
Labels: General

#10195 Copy comment link from notifications, reader and comment details (my site)
  WordPress/Classes/Extensions/UIAlertController+Helpers.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Views/LongPressGestureLabel.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.xib
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.xib
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#10199 Added missing tracking events
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Labels: Analytics

#10235 Proposal to fix crash on ReaderStreamViewController
  WordPress/Classes/ViewRelated/Reader/Reader.storyboard
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTableConfiguration.swift
Labels: Reader

#10225 Exposed existing NSUserActivity instances as Siri Shortcuts
  WordPress/Classes/Utility/Spotlight/SearchableActivityConvertable.swift
  WordPress/Resources/en.lproj/Localizable.strings
Labels: Spotlight

#10203 Properly Placed Pages: Tags
  WordPress/Classes/Extensions/UIAlertController+Helpers.swift
  WordPress/Classes/Models/Page.swift
  WordPress/Classes/ViewRelated/Notifications/Views/LongPressGestureLabel.swift
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
  WordPress/Classes/ViewRelated/Pages/PageListTableViewHandler.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: Properly Placed Pages

#10232 Add stalebot config
  .github/stale.yml
Labels: [Status] Needs Code Review

#10246 Use frame instead of constraint
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: [Type] Bug

#10241 Added rich notification support for Mentions
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Notifiable.swift
  WordPress/WordPressNotificationContentExtension/Info-Alpha.plist
  WordPress/WordPressNotificationContentExtension/Info-Internal.plist
  WordPress/WordPressNotificationContentExtension/Info.plist
  WordPress/WordPressNotificationServiceExtension/Sources/FormattableContent/RemoteNotificationStyles.swift
  WordPress/WordPressNotificationServiceExtension/Sources/FormattableContent/RichNotificationContentFormatter.swift
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
Labels: Rich Notifications

#10255 Fix pages list including blog predicate
  WordPress/Classes/ViewRelated/Pages/PageListTableViewHandler.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: Properly Placed Pages, [Type] Bug

#10251 Fix Undo action
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Labels: [Type] Bug

#10244 Add rule to check Podfile against commit hashes
  Dangerfile
Labels: General

#10256 Update screenshot tooling
  Gemfile
  Gemfile.lock
  Scripts/fastlane/Pluginfile
  Scripts/fastlane/ScreenshotFastfile
  Scripts/fastlane/Snapfile
  Scripts/fastlane/appstoreres/assets/ios-phone-5-65-template.png
  Scripts/fastlane/appstoreres/assets/ios-phone-notch.png
  Scripts/fastlane/appstoreres/metadata/en-US/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/es-ES/app_store_screenshot_3.txt
  Scripts/fastlane/appstoreres/metadata/fr-FR/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/ja/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/ja/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/ja/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/ja/app_store_screenshot_5.txt
  Scripts/fastlane/appstoreres/metadata/nl-NL/app_store_screenshot_5.txt
  Scripts/fastlane/appstoreres/metadata/pt-BR/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/pt-BR/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/pt-BR/app_store_screenshot_3.txt
  Scripts/fastlane/appstoreres/metadata/pt-BR/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/pt-BR/app_store_screenshot_5.txt
  Scripts/fastlane/appstoreres/metadata/pt-PT/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/pt-PT/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/pt-PT/app_store_screenshot_5.txt
  Scripts/fastlane/appstoreres/metadata/ru/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/sv/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/sv/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/sv/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/tr/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/tr/app_store_screenshot_5.txt
  WordPress/WordPressScreenshotGeneration/SnapshotHelper.swift
Labels: General

#10259 Self-hosted non Jetpack set a parent page
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: [Type] Bug

#10252 Feature/placed pages search
  Podfile
  Podfile.lock
  WordPress/Classes/Extensions/Array+Page.swift
  WordPress/Classes/ViewRelated/Pages/BasePageListCell.m
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
  WordPress/Classes/ViewRelated/Pages/PageListTableViewHandler.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Pages/Pages.storyboard
  WordPress/Classes/ViewRelated/Pages/ParentPageSettingsViewController.swift
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Labels: NoDeadEnds, Properly Placed Pages

#10267 Empty States: fix truncated text.
  WordPress/Classes/ViewRelated/Views/NoResults.storyboard
Labels: Actionable Empty States

#10265 Add "Reviewed by Hound" badge
  README.md
Labels: Documentation

#10274 Updated README to reflect the in-use versions of Xcode & Swift
  README.md
Labels: Documentation

#10275 Capture analytics for push notification actions
  WordPress/Classes/Utility/InteractiveNotificationsManager.swift
Labels: Notifications, Rich Notifications

#10257 Quick Start: add the last three tours
  WordPress/Classes/Stores/NoticeStore.swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartNavigationWatcher.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartSpotlightView.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
  WordPress/Classes/ViewRelated/Blog/SharingViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+QuickStart.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserHeaderView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: What's Next

#10278 Issue/9447 suggestion behaviour
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
Labels: What's Next

#10266 Reader empty states: adjust empty view for keyboard
  WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Tools/KeyboardDismissHelper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
Labels: Actionable Empty States, Reader

#10270 Move credential files to the dedicated repository
  README.md
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/buddybuild_prebuild.sh
Labels: General

#10264 Feature/placed pages pagination
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/Utility/WPContentSyncHelper.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Labels: Properly Placed Pages

#10287 Capture more analytics info for push notification actions
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/Utility/InteractiveNotificationsManager.swift
Labels: Notifications, Rich Notifications

#10283 Quick Start: Checklist improvements
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartCongratulationsCell.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartCongratulationsCell.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartSkipAllCell.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartSkipAllCell.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+QuickStart.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: What's Next

#10288 Quick Start: add analytics events
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+QuickStart.swift
Labels: What's Next

#10289 Quick Start: completion award
  WordPress/Classes/Services/SiteManagementService.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
Labels: What's Next

#10290 Turn on Quick Start for everyone
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: What's Next

#10285 Updating Aztec reference to pre-release hash (for release v1.1)
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Aztec

#10299 Quick Start: Fix notice view container from swallowing all taps
  WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift
Labels: Quick Start, [Type] Bug

#10340 Only add .strings files to git when updating translations
  Scripts/fastlane/helpers/ios_git_helper.rb
Labels: Localization, [Type] Enhancement

#10339 Introduced feature flag for enhanced site creation
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/FeatureFlagTests.swift
Labels: Site Creation

#10349 Fastlane: Added check for clean git status to remaining lanes
  Scripts/fastlane/actions/ios_finalize_prechecks.rb
  Scripts/fastlane/actions/ios_update_metadata_source.rb
Labels: [Type] Enhancement

#10346 History / Revision: new CoreData model version
  MIGRATIONS.md
  WordPress/Classes/Models/AbstractPost.h
  WordPress/Classes/Models/AbstractPost.m
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 82.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Revisions / History

#10345 Place 'Derived Sources' relative to BUILT_PRODUCTS_DIR
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Proposal, [Type] Enhancement

#10350 History / Revisions: Assign the revisions array to the local post
  WordPress/Classes/Services/PostService.m
Labels: Revisions / History

#10338 First draft to SiteTypesService
  WordPress/Classes/Models/PendingSiteType.swift
  WordPress/Classes/Models/SiteVertical.swift
  WordPress/Classes/Services/SiteTypesService.swift
  WordPress/Classes/Services/SiteVerticalsService.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/SiteTypeTests.swift
  WordPress/WordPressTest/SiteVerticalTests.swift
  WordPress/WordPressTest/Test Data/site-type.json
  WordPress/WordPressTest/Test Data/site-vertical.json
Labels: Site Creation, [Type] Task

#10359 Reader: don't set refresh control to zero frame
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: Reader, [Type] Bug

#10363 Plans: Don't unwrap optional during assignment.
  WordPress/Classes/ViewRelated/Plans/PlanComparisonViewController.swift
Labels: Plans & Checkout, [Type] Crash

#10365 Post Editor media search: Check for search query before showing no results view
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Labels: Media

#10364 Resolve crash in WPRichContentView with content set to empty string.
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ViewRelated/Views/WPRichText/WPRichContentViewTests.swift
  WordPress/WordPressTest/ViewRelated/Views/WPRichText/WPRichTextFormatterTests.swift
Labels: [Type] Crash

#10353 [Site creation] Wizard and WizardStep
  WordPress/Classes/Models/SiteSegment.swift
  WordPress/Classes/Services/SiteTypesService.swift
  WordPress/Classes/ViewRelated/Site Creation/SiteCreationWizard.swift
  WordPress/Classes/ViewRelated/Wizards/Wizard.swift
  WordPress/Classes/ViewRelated/Wizards/WizardDelegate.swift
  WordPress/Classes/ViewRelated/Wizards/WizardStep.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/SiteTypeTests.swift
Labels: Site Creation, [Type] Task

#10348 Stats Refresh: create initial view
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboard.storyboard
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/Stats/StatsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh
