Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2019-01, with the labels that each got.

#10725 Gutenberg: refresh `mediaPickerHelper` after post has changed.
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#10730 Gutenberg - Scroll to caret position on focused field
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg integration

#10733 Modified the segment & vertical identifier types to match services
  WordPress/Classes/Models/SiteSegment.swift
  WordPress/Classes/Models/SiteVertical.swift
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreatorOutput.swift
  WordPress/WordPressTest/SiteCreation/SiteAssemblyServiceTests.swift
  WordPress/WordPressTest/SiteCreation/SiteCreatorTests.swift
  WordPress/WordPressTest/SiteCreation/SiteSegmentTests.swift
  WordPress/WordPressTest/Test Data/site-segment.json
Labels: Site Creation

#10751 Track Giphy analytics events
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
  WordPress/Classes/ViewRelated/Media/Giphy/GiphyDataLoader.swift
  WordPress/Classes/ViewRelated/Media/Giphy/GiphyPicker.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Labels: Analytics, Giphy, Media

#10755 Improve screenshot performance and reliability
  .gitignore
  Scripts/fastlane/ScreenshotFastfile
  Scripts/fastlane/Snapfile
Labels: Tooling

#10761 Notification Details: Refresh router on Note change
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
Labels: Notifications, [Type] Bug

#10762 Resolved crash by restoring progress KVO observer
  WordPress/Classes/ViewRelated/Cells/WPProgressTableViewCell.m
Labels: [Type] Bug

#10696 [Stats Refresh] Add Insights Comments card
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.xib
Labels: Stats Refresh

#10748 Attempted fix crash: "NSInternalInconsistencyException negative sizes are not supported in the flow layout"
  WordPress/Classes/Extensions/Math.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
  WordPress/Classes/ViewRelated/Themes/WPStyleGuide+Themes.swift
Labels: [Type] Crash

#10734 [Stats Refresh] Stat Row: add percentage data bar
  WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SimpleTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.xib
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.xib
Labels: Stats Refresh

#10737 [Stats Refresh] Tabbed cards - update filter bar colors
  WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
  WordPress/Classes/ViewRelated/System/FilterBar.swift
Labels: Stats Refresh

#10749 Localize title of the button to edit comments
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
Labels: [Type] Bug, i18n

#10750 Localise Done button in view presented after publishing a new post
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
Labels: [Type] Bug, i18n

#10757 Fix cropped localized text
  WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m
  WordPress/Classes/ViewRelated/Cells/SwitchTableViewCell.swift
  WordPress/Classes/ViewRelated/Cells/WPReusableTableViewCells.swift
Labels: Accessibility, Localization, i18n

#10769 Update README to remove 'pod install'
  README.md
Labels: Tooling

#10753 Fix/screenshots us locale
  Gemfile.lock
  Scripts/fastlane/Pluginfile
  Scripts/fastlane/ScreenshotFastfile
  Scripts/fastlane/appstoreres/metadata/de-DE/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/de-DE/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/de-DE/app_store_screenshot_5.txt
  Scripts/fastlane/appstoreres/metadata/en-US/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/id/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/id/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/id/app_store_screenshot_3.txt
  Scripts/fastlane/appstoreres/metadata/id/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/it/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/it/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/it/app_store_screenshot_5.txt
  Scripts/fastlane/appstoreres/metadata/no/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/no/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/no/app_store_screenshot_3.txt
  Scripts/fastlane/appstoreres/metadata/no/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/no/app_store_screenshot_5.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hans/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hans/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hans/app_store_screenshot_3.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hans/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hans/app_store_screenshot_5.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hant/app_store_screenshot_1.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hant/app_store_screenshot_2.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hant/app_store_screenshot_3.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hant/app_store_screenshot_4.txt
  Scripts/fastlane/appstoreres/metadata/zh-Hant/app_store_screenshot_5.txt
Labels: Localization, Tooling

#10763 Login Epilogue: Don’t show empty ‘My Sites’ section
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
Labels: Login

#10765 Site Creation > type selection: wrap 'Start with' label
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/NUX/SiteCreation.storyboard
  WordPress/Classes/ViewRelated/NUX/SiteCreationCategoryTableViewCell.xib
Labels: Site Creation

#10772 NoResults: Stop WPAnimatedBox animation when removing from superview
  WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
Labels: [Type] Bug

#10760 Transitioned to use new site creation service
  Podfile
  Podfile.lock
  WordPress/Classes/Services/SiteAssembly.swift
  WordPress/Classes/Services/SiteAssemblyService.swift
  WordPress/Classes/Services/SiteCreationService.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyContentView.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteCreationRequest+Validation.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreatorOutput.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/SiteCreation/SiteAssemblyServiceTests.swift
  WordPress/WordPressTest/SiteCreation/SiteAssemblyViewTests.swift
Labels: Site Creation

#10764 Stats Today extension: use the user-selected site
  RELEASE-NOTES.txt
  WordPress/Classes/Services/AccountService.m
Labels: Stats

#10771 Make `Me` header view height adjust to text size
  WordPress/Classes/ViewRelated/Me/MeHeaderView.m
  WordPress/Classes/ViewRelated/Me/MeViewController.swift
Labels: Accessibility

#10768 Fix MediaSizeSliderCell text cropped
  WordPress/Classes/ViewRelated/Cells/MediaSizeSliderCell.swift
  WordPress/Classes/ViewRelated/Cells/MediaSizeSliderCell.xib
  WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
Labels: Accessibility, Localization

#10779 Present localised TOS
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/URL+Helpers.swift
  WordPress/Classes/ViewRelated/Me/AboutViewController.swift
Labels: Localization, i18n

#10774 Prevented stale images from appearing in notifications
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockImageTableViewCell.swift
Labels: [Type] Bug

#10780 Update reader site header to display bigger text sizes.
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
Labels: Accessibility

#10754 Post Epilogue: Pin navigation bar to top layout guide
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostPost.storyboard
Labels: Design, Posting/Editing

#10775 Site People: remove deleted users
  RELEASE-NOTES.txt
  WordPress/Classes/Services/PeopleService.swift
  WordPress/Classes/ViewRelated/People/PeopleViewController.swift
Labels: People Management

#10782 Update WPMediaPicker to include parental control updates
  Podfile
  Podfile.lock
  WordPress/Classes/Categories/Media+WPMediaAsset.m
  WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
  WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift
Labels: Media

#10785 ImageLoader: Fix crashing when attempting to handle error
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Media/ImageLoader.swift
Labels: Media

#10773 Account settings: Change password
  RELEASE-NOTES.txt
  WordPress/Classes/Services/AccountSettingsService.swift
  WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/ChangePasswordViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.h
  WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Status] Needs Design Review, [Type] Enhancement

#10790 Don't run swiftlint on danger
  .circleci/config.yml
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: Tooling

#10786 Site Creation : Integrated working Domains suggestion service
  WordPress/Classes/Models/SiteSegment.swift
  WordPress/Classes/Services/SiteAddressService.swift
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/ErrorStates/InlineErrorRetryTableViewCell.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/ErrorStates/InlineErrorTableViewProvider.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/TableDataCoordinator.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsTableViewProvider.swift
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsTableViewProviders.swift
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressStep.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressTableViewProvider.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Creation

#10797 Site Creation : Integration of Verticals prompt service
  Podfile
  Podfile.lock
  WordPress/Classes/Models/SiteSegment.swift
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/Classes/Services/SiteVerticalsPromptService.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/ErrorStates/InlineErrorTableViewProvider.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationHeaderData.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/WordPressTest/SiteCreation/SiteSegmentTests.swift
  WordPress/WordPressTest/Test Data/site-segment.json
Labels: Site Creation

#10805 Silence xib warnings
  WordPress/Classes/ViewRelated/Cells/MediaSizeSliderCell.xib
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
Labels: [Type] Enhancement

#10796 Post excerpt: increase minimum height
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Tools/SettingsMultiTextViewController.m
Labels: Posting/Editing

#10793 No search results: Wrap message
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
Labels: NoResultsView

#10781 Reader - Comments header view dynamic text type.
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.m
Labels: Accessibility

#10802 Change Password: iOS 12 password generator
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/ChangePasswordViewController.swift
  WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.m
Labels: [Type] Enhancement

#10789 Visual mode for revisions doesn't show image on private site
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/Revisions/Browser/Preview/RevisionPreviewTextViewManager.swift
  WordPress/Classes/ViewRelated/Post/Revisions/Browser/Preview/RevisionPreviewViewController.swift
Labels: [Type] Bug

#10804 Move post epilogue tracking to after post post screen is revealed
  WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
Labels: Analytics

#10809 Removed WPMediaProgressTableViewController as it is no longer in use
  WordPress/Classes/ViewRelated/Post/WPMediaProgressTableViewController.h
  WordPress/Classes/ViewRelated/Post/WPMediaProgressTableViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Low Hanging Fruit, [Type] Tech Debt

#10810 [Site creation]. Remove custom disclosure indicator from segments cell
  WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsCell.swift
Labels: Site Creation

#10815 Resolved verticals selection issue when navigating through site creation
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsStep.swift
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
Labels: Site Creation

#10816 Modified text headers to remain visible on iPad
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
Labels: Site Creation

#10820 Modified Verticals header to properly reset appearance
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
Labels: Site Creation

#10798 Making FancyAlert Scrollable
  Podfile
  Podfile.lock
Labels: [Status] Needs Design Review, [Type] Enhancement

#10839 Update the release notes for 11.6
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Tooling

#10819 Properly Placed Pages: new page cell
  WordPress/Classes/Extensions/WPStyleGuide+Colors.swift
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Pages/ParentPageSettingsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Properly Placed Pages

#10842 Reduce number of conflicts in RELEASE-NOTES.txt
  .gitattributes
Labels: Tooling

#10813 Making Post Card adapt to bigger font sizes.
  WordPress/Classes/ViewRelated/Post/PostCardImageCell.xib
  WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
  WordPress/Classes/ViewRelated/Post/PostCardTextCell.xib
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Accessibility, Posts List

#10783 Update WordPressAuth pod for password autofill
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login

#10857 Replace BuddyBuild status badge with CircleCI
  README.md
Labels: Tooling

#10863 Danger: no check for commit hashes for Gutenberg
  Dangerfile
Labels: Tooling

#10841 [Stats Refresh] Add Insights Annual Site Stats card
  WordPress/Classes/ViewRelated/Stats/Insights/Annual Site Stats/AnnualSiteStatsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Annual Site Stats/AnnualSiteStatsCell.xib
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh

#10849 [Stats Refresh] Insights Publicize: add percentage data bar
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: Stats Refresh

#10861 Plans: Make the plans service send authenticated requests.
  WordPress/Classes/Services/PlanService.swift
Labels: Plans & Checkout

#10822 [Site creation] Style WebAddressWizardContent
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.xib
Labels: Site Creation, [Status] Needs Design Review

#10826 Gutenberg - Scroll to caret while typing
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#10878 Fix a layout issue when we don’t have image size
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Labels: [Type] Bug

#10880 Exclude RNTAztecView from the check against commit hash references
  Dangerfile
Labels: Tooling

#10883 CircleCI: Check that Podfile and Podfile.lock match
  .circleci/config.yml
Labels: Tooling

#10874 [Stats Refresh] Add initial Stats Period view
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/Stores/StoreContainer.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboard.storyboard
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh, [Type] Task

#10893 Fix ios_update_metadata_source action
  Scripts/fastlane/actions/ios_update_metadata_source.rb
Labels: Tooling

#10892 CircleCI: Use re-usable config with CircleCI orbs
  .circleci/config.yml
Labels: Tooling

#10864 Gutenberg: Fetching RNAztecView from gutenberg-mobile
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#10827 Update dependencies for 11.7
  Podfile
  Podfile.lock
  WordPress/Classes/System/WordPressAppDelegate+Swift.swift
Labels: [Status] Needs Code Review

#10885 [Stats Refresh] Add Period > Posts and Pages card
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/UITableViewCell+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Annual Site Stats/AnnualSiteStatsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SimpleTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsNoDataRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh

#10879 Corrected keyboard offset behavior on both Verticals & Domains screens in Site Creation
  WordPress/Classes/ViewRelated/Site Creation/Shared/TableViewOffsetCoordinator.swift
  WordPress/Classes/ViewRelated/Site Creation/Verticals/VerticalsWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Creation

#10897 Bump Gutenberg ref to release 0.3.4
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#10862 Prompt user to logout before connecting to WPCom site
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Models/SiteSegment.swift
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsCell.swift
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/SiteCreation/SiteAssemblyServiceTests.swift
  WordPress/WordPressTest/SiteCreation/SiteCreatorTests.swift
  WordPress/WordPressTest/SiteCreation/SiteSegmentTests.swift
  WordPress/WordPressTest/Test Data/site-segment.json
Labels: [Status] Needs Copy Review, [Status] Needs Design Review

#10794 Implements the editor title in RN for Gutenberg.
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergContainerView.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergContainerView.xib
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: [Status] DO NOT MERGE

#10894 Quick Start V2: update checklist
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCellV1.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistFooter.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistFooter.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistManager.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewControllerV1.swift
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-tasks-complete-audience.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-tasks-complete-audience.imageset/quickStartBlue.pdf
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-tasks-complete-site.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-tasks-complete-site.imageset/quickStartYellow.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Quick Start

#10904 Merge 11.7 into develop
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#10907 Fix an issue where some cells in Activity Log would be visibly smaller for no good reason.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.xib
Labels: [Type] Bug

#10901 [Stats Refresh] Add Period > Videos card
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
Labels: Stats Refresh

#10895 [Stats Refresh] Add Period > Search Terms card
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Labels: Stats Refresh

#10903 [Stats Refresh] Add Period > Published card
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: Stats Refresh

#10877 [Site creation] Implementation of the Segments Service
  Podfile
  Podfile.lock
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/WordPressTest/Test Data/site-segment.json
  WordPress/WordPressTest/WPAnalyticsTrackerAutomatticTracksTests.m
Labels: Site Creation, [Type] Task

#10911 Prevent the code freeze lane to update the release notes key
  Scripts/manage-version.sh
Labels: Tooling

#10905 QS v2: Quick Start Section in Blog Details
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewControllerV1.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartListTitleCell.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartListTitleCell.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Quick Start

#10899 Adds support to share a site (blog) via Reader
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostPost.storyboard
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Sharing.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Resources/AppImages.xcassets/icon-posts-share.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/icon-posts-share.imageset/icons-posts-share.pdf
  WordPress/Shared/SharePost.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressTest/ReaderStreamViewControllerTests.swift
Labels: Reader, Sharing

#10924 CircleCI: Allow resetting of CocoaPods cache
  .circleci/config.yml
Labels: Tooling

#10926 CircleCI: Update Orb version for strict CocoaPods caching
  .circleci/config.yml
Labels: Tooling

#10872 Implement media upload from device in GB.
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Gutenberg/MediaUploadHashTests.swift
Labels: Gutenberg integration

#10920 Removed client-side .blog subdomain handling
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
Labels: Site Creation

#10928 Prevent loadSite from being called twice
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyContentView.swift
Labels: Site Creation, [Type] Bug

#10929 Fix a reader crash caused by images in video tags
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift
  WordPress/WordPressTest/ViewRelated/Views/WPRichText/WPRichTextFormatterTests.swift
Labels: [Type] Bug, [Type] Crash

#10913 Quick Start V2: Bug on Checklist rotation
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.xib
Labels: Quick Start, [Type] Bug

#10916 Integrated updates to both WordPressKit and WordPressAuthenticator
  Podfile
  Podfile.lock
Labels: Network/Sync
