Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2019-06, with the labels that each got.

#11783 Implements an initial version of UploadsManager class and Uploader protocol
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Uploads/Uploader.swift
  WordPress/Classes/Uploads/UploadsManager.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Offline Support, [Type] Task

#11828 Use safeManagedObjectID to retrieval media objects referenced in HTML.
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/Utility/CoreDataHelper.swift
  WordPress/Classes/Utility/WPException.h
  WordPress/Classes/Utility/WPException.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/CoreDataHelperTests.swift
Labels: [Type] Bug, [Type] Crash

#11666 Add responsible disclosure policy
  README.md
  SECURITY.md
Labels: Documentation

#11837 Remove dead code
  WordPress/Classes/Utility/Sentry/WPCrashLogging.swift
Labels: Tooling

#11845 [Stats Refresh] Period Overview chart: show dashes for Likes value
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Labels: Stats Refresh

#11829 Go back to bumping site created
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
Labels: Site Creation

#11841 Implement workaround for slow likes fetches in Stats
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Labels: Stats Refresh

#11839 Implements Uploader protocol in MediaCoordinator and PostCoordinator.
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/MediaService.h
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/Uploads/UploadsManager.swift
Labels: Offline Support

#11854 [Stats Refresh] Period Videos: fix video selection
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
Labels: Stats Refresh

#11850 Merge 12.6 back into `develop`
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#11851 Make universal link router values non optional
  WordPress/Classes/Utility/Universal Links/Route.swift
  WordPress/Classes/Utility/Universal Links/Routes+Banners.swift
  WordPress/Classes/Utility/Universal Links/Routes+Me.swift
  WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
  WordPress/Classes/Utility/Universal Links/Routes+Notifications.swift
  WordPress/Classes/Utility/Universal Links/Routes+Post.swift
  WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
  WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/RouteMatcherTests.swift
Labels: Universal Links, [Type] Task

#11860 Merge 12.5.1 into master
  Podfile
  Podfile.lock
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/Fastfile
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Extensions/UIImage+XCAssetTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#11861 Merge 12.5.1 into 12.6
  Podfile
  Podfile.lock
  Scripts/fastlane/Fastfile
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Extensions/UIImage+XCAssetTests.swift
Labels: Tooling

#11856 [Stats Refresh] remove unused code
  WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: Stats Refresh

#11862 Merge 12.5.1 into develop
  Podfile
  Podfile.lock
  Scripts/fastlane/Fastfile
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Extensions/UIImage+XCAssetTests.swift
Labels: Tooling

#11865 [Stats Refresh] disable preloading Stats
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Labels: Stats Refresh

#11872 [Stats Refresh] Follower detail count: show correct value
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
Labels: Stats Refresh

#11857 Change quick start highlight color to white
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
Labels: Quick Start, [Type] Enhancement

#11871 [Stats Refresh] Show new Follower stats from Follower notification.
  WordPress/Classes/Utility/ContentCoordinator.swift
Labels: Stats Refresh

#11878 [Gutenberg]Make video/quote/more blocks public
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#11881 [Stats Refresh] Insights Comments: don't show 'view more' option
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: Stats Refresh

#11879 [Stats Refresh] Update Y axis chart formatting to match Android's behaviour
  WordPress/Classes/ViewRelated/Stats/Charts/Charts+AxisFormatters.swift
  WordPress/Classes/ViewRelated/Stats/Charts/Charts+LargeValueFormatter.swift
  WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
Labels: Stats Refresh, [Type] Bug

#11886 Bundle patch
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WordPressUIBundleTests.swift
Labels: [Type] Crash

#11883 Fix dates math in Stats graph.
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
Labels: Stats Refresh

#11884 [Stats Refresh] Improve x-axis label formatting
  WordPress/Classes/ViewRelated/Stats/Charts/Charts+AxisFormatters.swift
  WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
  WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
Labels: Stats Refresh

#11788 Network mocking for all UI and screenshot tests
  .gitignore
  Podfile
  Podfile.lock
  Rakefile
  Scripts/BuildPhases/CopyScreenshotCredentials.sh
  Scripts/BuildPhases/CopyUITestCredentials.sh
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
  WordPress/WordPressScreenshotGeneration/Info.plist
  WordPress/WordPressScreenshotGeneration/ScreenshotCredentials.swift
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
  WordPress/WordPressUITests/Info.plist
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginCheckMagicLinkScreen.swift
  WordPress/WordPressUITests/Tests/LoginTests.swift
  WordPress/WordPressUITests/Utils/WireMock.swift
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
  WordPress/WordPressUITests/WPUITestCredentials-Template.swift
  WordPress/WordPressUITests/WPUITestCredentials.swift
  WordPressComStatsiOS/WordPressComStatsiOS/UI/WPStatsViewController.m
Labels: Testing, Tooling

#11891 Update gutenberg to v1.6.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#11892 [Stats Refresh] change Post Stats chart delegate
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
Labels: Stats Refresh

#11887 [Stats Refresh] Show grey bars when chart is empty
  WordPress/Classes/ViewRelated/Stats/Charts/Charts+Support.swift
  WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
  WordPress/Classes/ViewRelated/Stats/Charts/PostChart.swift
  WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Labels: Stats Refresh

#11877 Integrates the latest changes from WordPressShared.
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
  WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
Labels: [Type] Enhancement

#11898 Fixing an issue with post content disappearing on visible editor
  WordPress/Classes/Services/PostService.m
Labels: Offline Support, Posting/Editing, [Type] Bug

#11895 Don't show blocking alert on set feature image
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.h
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
  WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
  WordPress/Classes/ViewRelated/Media/WPAndDeviceMediaLibraryDataSource.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+FeaturedImageUpload.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: Offline Support, [Status] Needs Copy Review

#11899 Remove outdated comments in code.
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
Labels: Refactor

#11896 Run WordPressUITests nightly on CircleCI
  .circleci/config.yml
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing, Tooling

#11665 Testing: Enable UI LoginTests to pass in any language
  WordPress/Classes/ViewRelated/Me/MeHeaderView.m
  WordPress/Classes/ViewRelated/Me/MeViewController.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
  WordPress/WordPressUITests/Flows/LoginFlow.swift
  WordPress/WordPressUITests/Screens/Login/LinkOrPasswordScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginCheckMagicLinkScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginEmailScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginEpilogueScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginSiteAddressScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginUsernamePasswordScreen.swift
  WordPress/WordPressUITests/Screens/MeTabScreen.swift
  WordPress/WordPressUITests/Screens/MySiteScreen.swift
  WordPress/WordPressUITests/Screens/NotificationsScreen.swift
  WordPress/WordPressUITests/Screens/SignupScreen.swift
  WordPress/WordPressUITests/Tests/LoginTests.swift
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Testing, [Status] Needs Code Review

#11917 Update WordPressMocks to include sign up and make development easier
  Podfile
  Podfile.lock
  Rakefile
Labels: Testing, Tooling

#11918 Merge release/12.5 into develop
  WordPress/Resources/en.lproj/Localizable.strings
Labels: Tooling

#11919 Merge release/12.5 into release/12.6
  WordPress/Resources/en.lproj/Localizable.strings
Labels: Tooling

#11920 Revert fix for Discard losing changes
  WordPress/Classes/Services/PostService.m
Labels: Offline Support, [Type] Bug

#11902 [Stats Refresh] remove references to old stats service
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/SiteStatsInformation.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: Stats Refresh, [Type] Tech Debt

#11885 Update Aztec to version 1.7.0 and GB latest (1.7.0)
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#11924 Revert fix for Discard losing changes in develop
  WordPress/Classes/Services/PostService.m
Labels: Offline Support, [Type] Bug

#11923 [Refresh Stats] Fix crash on rotation
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
Labels: Stats Refresh, [Type] Bug

#11930 Use the new create icon for New Post in Quick Actions menu.
  WordPress/Resources/AppImages.xcassets/icon-shortcut-new-post.imageset/icon-shortcut-new-post.pdf
Labels: General

#11932 Update version of WPMediaPicker to version 1.4.2
  Podfile
  Podfile.lock
Labels: Media

#11931 Testing: Add email signup UI test
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Screens/BaseScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginCheckMagicLinkScreen.swift
  WordPress/WordPressUITests/Screens/Login/WelcomeScreen.swift
  WordPress/WordPressUITests/Screens/Signup/SignupCheckMagicLinkScreen.swift
  WordPress/WordPressUITests/Screens/Signup/SignupEmailScreen.swift
  WordPress/WordPressUITests/Screens/Signup/SignupEpilogueScreen.swift
  WordPress/WordPressUITests/Screens/Signup/WelcomeScreenSignupComponent.swift
  WordPress/WordPressUITests/Screens/SignupScreen.swift
  WordPress/WordPressUITests/Tests/LoginTests.swift
  WordPress/WordPressUITests/Tests/SignupTests.swift
  WordPress/WordPressUITests/WPUITestCredentials.swift
Labels: Testing

#11927 [Stats Refresh] Insights All Time: update to new design
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/StatsTwoColumnRow.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/StatsTwoColumnRow.xib
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.xib
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh

#11928 [Stats Refresh] Insights Today: update to new design
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: Stats Refresh

#11940 [Stats Refresh] Insights Most Popular Time: update to new design
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: Stats Refresh

#11941 [Stats Refresh] Insights Annual: update to new design
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Annual Site Stats/AnnualSiteStatsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Annual Site Stats/AnnualSiteStatsCell.xib
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh

#11944 Updated copy for preview unavailable screen
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
Labels: Previews

#11936 [Stats Refresh] Insights Follower Totals: update to new design
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: Stats Refresh

#11945 [Stats Refresh] Insights This Year: add `View more` details
  RELEASE-NOTES.txt
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.xib
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: Stats Refresh

#11955 Fix missing argument
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: [Type] Bug

#11957 [Stats Refresh] Fix locale of large value formatter
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Charts/Charts+LargeValueFormatter.swift
Labels: Stats Refresh

#11958 [Stats Refresh] Fix locale of large value formatter (12.7)
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Charts/Charts+LargeValueFormatter.swift
Labels: Stats Refresh

#11960 [Stats Refresh] Countries section - fix map separator height
  WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/CountriesCell.xib
Labels: Stats Refresh, [Type] Bug

#11901 Resume uploads
  RELEASE-NOTES.txt
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/MediaService.h
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Uploads/Uploader.swift
  WordPress/Classes/Uploads/UploadsManager.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Offline Support, [Type] Enhancement

#11959 Ensure PingHubManager state changes on main thread
  WordPress/Classes/Utility/PingHubManager.swift
Labels: [Type] Crash

#11942 Merge 12.7 into `develop`
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Classes/ViewRelated/Stats/Charts/Charts+LargeValueFormatter.swift
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#11953 [Fix] Launch Screen Blue Icon
  WordPress/Launch Screen.storyboard
Labels: [Type] Bug

#11956 Documents some critical stats we're tracking.
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
Labels: [Type] Task

#11964 [Fix] Fix NSRangeException in Stats running on iOS 11
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
Labels: [Type] Bug

#11969 Merge 12.7 fixes into `develop`
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#11968 Fix merge issue
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#11962 [Stats Refresh] Insights Annual details: change year displayed
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
Labels: Stats Refresh

#11971 [Stats Refresh] Set empty chart bar height to chart height
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
  WordPress/Classes/ViewRelated/Stats/Charts/PostChart.swift
  WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
Labels: Stats Refresh

#11973 [Stats Refresh] Remove unused row types
  WordPress/Classes/ViewRelated/Stats/Insights/SimpleTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SimpleTotalsCell.xib
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh, [Type] Tech Debt

#11981 [Stats Refresh] Some VoiceOver improvements for StatsTotalRow
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
Labels: Stats Refresh

#11985 Fetching a post after update
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Posting/Editing

#11986 [Stats Refresh] Save Insights overview to Core Data when refreshed.
  RELEASE-NOTES.txt
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
Labels: Stats Refresh

#11984 [Stats Refresh] Change stat card subtitles to be normal case.
  WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
Labels: Stats Refresh

#11982 [Stats Refresh] Change stats difference value to grey colour (12.7)
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Helpers/StatsPeriodHelper.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh

#11993 [Stats Refresh] add new analytics tracks
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
Labels: Analytics, Stats Refresh

#11987 Remove release note from 12.8 as it was fixed in 12.7
  RELEASE-NOTES.txt
Labels: General

#11998 [Stats Refresh] Improve accessibility
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsNoDataRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.swift
Labels: Accessibility, Stats Refresh

#11992 Merge 12.7 beta 2 into develop
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#11996 Improve UI test output (logs and screenshots)
  WordPress/WordPressUITests/Flows/LoginFlow.swift
  WordPress/WordPressUITests/Screens/BaseScreen.swift
  WordPress/WordPressUITests/Screens/Editor/AztecEditorScreen.swift
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPressUITests/Tests/EditorAztecTests.swift
  WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
  WordPress/WordPressUITests/Tests/LoginTests.swift
  WordPress/WordPressUITests/Tests/MainNavigationTests.swift
  WordPress/WordPressUITests/Tests/SignupTests.swift
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Testing, [Status] Needs Code Review

#12002 [Stats Refresh] Fix chart legend location
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
Labels: Stats Refresh

#12005 Remove extra editor_session_end tracks event
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Labels: Analytics, [Type] Bug

#12014 [Stats Refresh] Accessibility labels in Period Bar
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
Labels: Accessibility, Stats Refresh

#12017 Add Slack notifications to CircleCI UI tests
  .circleci/config.yml
Labels: Tooling

#12010 [Stats Refresh] Stats details: fix expanding rows
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/DetailDataCell.swift
Labels: Stats Refresh

#12006 [Stats Refresh] Update Countries Map pod and fix autolayout warnings
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/Map/CountriesMapCell.xib
Labels: Stats Refresh, [Type] Bug

#12016 Issue/12015 notification formatting
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
Labels: Notifications, Rich Notifications

#12020 Issues/11683 navigation bar problems
  WordPress/Classes/Extensions/UIColor+MurielColors.swift
  WordPress/Classes/Extensions/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Labels: Muriel

#12012 Muriel colors: fix the dang blue icons on Me tab
  WordPress/Classes/Extensions/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Labels: Muriel

#12025 Fix issue where some cells in Custom Domains would become untappable
  WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
Labels: [Type] Bug

#12024 Fix for publishing private posts on XML-RPC sites
  Podfile
  Podfile.lock
Labels: [Type] Bug

#12022 Muriel Colors: update FancyButtons
  WordPress/Classes/Extensions/UIColor+MurielColors.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/Views/NoResults.storyboard
Labels: Muriel

#11977 Update Gutenberg to 1.8.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#12029 Muriel colors: update NUX colors
  Podfile
  Podfile.lock
  WordPress/Animations/jetpack.json
  WordPress/Animations/notifications.json
  WordPress/Animations/post.json
  WordPress/Animations/reader.json
  WordPress/Animations/stats.json
  WordPress/Classes/Extensions/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Muriel

#12030 Turn on Muriel colors 🎉
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Muriel

#12033 Change launch screen background to Blue-500
  WordPress/Launch Screen.storyboard
Labels: General
