Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2019-04, with the labels that each got.

#11379 Restore strings for release 12.1
  WordPress/Resources/en.lproj/Localizable.strings
Labels: i18n

#11380 [Gutenberg]Integrate logging
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#11392 Fix Notices not being actionable after taking a photo
  WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift
Labels: [Type] Bug

#11338 [Jetpack Remote Installation] Featureflag and Jetpack login screen update
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.swift
  WordPress/Classes/ViewRelated/Stats/JetpackLoginViewController.xib
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-stats.imageset/wp-illustration-stats.pdf
Labels: Jetpack

#11385 Site Creation: Always add a space for the checkmark when selecting domains
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib
Labels: Site Creation, [Type] Enhancement

#11393 Site Creation: Make label taps focus their corresponding text fields
  WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
  WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.xib
Labels: Site Creation, [Type] Bug

#11365 Issue/new domain suggestion parameter
  Podfile
  Podfile.lock
  WordPress/Classes/Services/DomainsService.swift
  WordPress/Classes/Services/SiteAddressService.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Creation, [Type] Enhancement

#11376 Uploading draft and displaying remote preview
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Labels: Posting/Editing, [Type] Enhancement

#11375 Initial TextBundle/TextPack support
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressDraftActionExtension/WordPressDraftActionExtension-Bridging-Header.h
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressShareExtension/TextBundleWrapper.h
  WordPress/WordPressShareExtension/TextBundleWrapper.m
  WordPress/WordPressShareExtension/WordPressShare-Bridging-Header.h
Labels: Share Extension

#11403 Implement copy paste of image in GB mobile
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#11409 Updates GB version to support list blocks
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#11404 SiteCreation: Fix AddressCell height on first load
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib
Labels: [Type] Bug

#11410 Point to latest gutenberg-mobile release v1.2.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#11412 Site Creation: Fixes a warning.
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
Labels: Site Creation, [Type] Tech Debt

#11413 Site Creation: Updated the release notes.
  RELEASE-NOTES.txt
Labels: Documentation, Site Creation

#11405 [Jetpack Remote Install] Install view
  WordPress/Classes/ViewRelated/Jetpack/Install/Data/JetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/Data/JetpackRemoteInstallViewState.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/Error/JetpackInstallError+Blocking.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.xib
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallView.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallView.xib
  WordPress/Classes/ViewRelated/Jetpack/Install/Webview/JetpackConnectionWebViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.xib
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
  WordPress/Resources/AppImages.xcassets/Jetpack Install/Contents.json
  WordPress/Resources/AppImages.xcassets/Jetpack Install/jetpack-install-error.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Jetpack Install/jetpack-install-error.imageset/jetpack-install-error.pdf
  WordPress/Resources/AppImages.xcassets/Jetpack Install/jetpack-install-logo.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Jetpack Install/jetpack-install-logo.imageset/jetpack-install-logo.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack

#11411 Site Creation: Remove feature flag and legacy code.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/BlogListViewController+SiteCreation.swift
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.h
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
  WordPress/Classes/ViewRelated/NUX/SiteCreation.storyboard
  WordPress/Classes/ViewRelated/NUX/SiteCreationCategoryTableViewCell.xib
  WordPress/Classes/ViewRelated/NUX/SiteCreationCategoryTableViewCells.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationCategoryTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationCreateSiteViewController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationDomainSuggestionsTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationDomainsViewController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationFields.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationInstructionTableViewCell.xib
  WordPress/Classes/ViewRelated/NUX/SiteCreationNavigationController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationSiteDetailsViewController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationSitePreviewViewController.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationThemeSelectionViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/FeatureFlagTests.swift
Labels: Site Creation, [Type] Tech Debt

#11402 Add defensive check for crash in plugins
  WordPress/Classes/ViewRelated/Plugins/PluginListViewController.swift
Labels: [Type] Bug

#11407 Update WordPressAuthenticator-iOS pod
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueUserInfo.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Login

#11417 Update Tracks for device_info_is_online
  Podfile
  Podfile.lock
Labels: [Type] Bug

#11437 [Jetpack Remote Install] Remove warnings and unnecessary code
  WordPress/Classes/ViewRelated/Jetpack/Install/Data/JetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.xib
Labels: Jetpack

#11442 Update CocoaPods to 1.6.1
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPressComStatsiOS/WordPressComStatsiOS.xcodeproj/project.pbxproj
Labels: Tooling

#11441 Update WebKitViewController to show notice When offline instead of showing alert
  Podfile.lock
  WordPress/Classes/Utility/ReachabilityUtils+OnlineActions.swift
  WordPress/Classes/Utility/WPWebViewController.m
  WordPress/Classes/Utility/WebKitViewController.swift
Labels: Offline Support

#11455 Podfile Update
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#11453 Fix loading WordPressAuthenticator xibs
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift
Labels: [Type] Crash

#11443 Add more verbose logging to Core Data crashes
  WordPress/Classes/Utility/ContextManager.m
Labels: [Type] Bug

#11459 Merge release notes into `develop`
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Tooling

#11445 [Jetpack Remote Install] JetpackService implementation + Flux
  WordPress/Classes/Services/JetpackService.swift
  WordPress/Classes/Stores/JetpackInstallStore.swift
  WordPress/Classes/Stores/StoreContainer.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/Data/JetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.xib
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallStateView.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallStateView.xib
  WordPress/Classes/ViewRelated/Jetpack/Install/View/State/JetpackRemoteInstallState.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/JetpackRemoteInstallViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack

#11461 Use global env variables in fastlane deliver
  Scripts/fastlane/Deliverfile
Labels: Tooling

#11448 Simplified the wizard navigation index tracking in site creation flow
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Site Creation/Wizard/WizardNavigation.swift
Labels: Site Creation

#11447 Fix my_site_tab_accessed tracking
  WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Bug

#11465 [Stats] Don't fetch insights/period data by default, only on manual refreshes
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Labels: Stats Refresh, [Type] Bug

#11464 Hiding header if there are no item in that section.
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Labels: Offline Support

#11451 Only showing "can't save changes" alert if changes were actually made.
  Podfile.lock
  WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
Labels: Offline Support

#11473 Make Stats Followers/Tags and Categories detail views use the new API.
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
Labels: Stats Refresh

#11475 point WPKit to a release, not a branch name
  Podfile
  Podfile.lock
Labels: [Type] Bug

#11381 Xcode 10.2 compatibility
  .circleci/config.yml
  Podfile
  Podfile.lock
  WordPress/Classes/Models/JetpackSiteRef.swift
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
  WordPress/Classes/Utility/CoreDataHelper.swift
  WordPress/Classes/Utility/FormattableContent/FormattableContentRange.swift
  WordPress/Classes/Utility/FormattableContent/FormattableMediaContent.swift
  WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteSettingsViewController+SiteManagement.swift
  WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.h
  WordPress/Classes/ViewRelated/Media/CachedAnimatedImageView.swift
  WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/ErrorStates/ErrorStateView.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/NSAttributedString+WPRichText.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/OCLint.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Alpha.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Internal.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressScreenshotGeneration.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressShareExtension.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressTodayWidget.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/ShareModularViewController.swift
  WordPress/WordPressShareExtension/ShareSegueHandler.swift
  WordPress/WordPressShareExtension/ShareTagsPickerViewController.swift
  WordPress/WordPressTest/MediaProgressCoordinatorTests.swift
  WordPressComStatsiOS/WordPressComStatsiOS.xcodeproj/project.pbxproj
  WordPressComStatsiOS/WordPressComStatsiOS.xcodeproj/xcshareddata/xcschemes/WordPressComStatsiOS.xcscheme
  WordPressFlux/WordPressFlux.xcodeproj/project.pbxproj
  WordPressFlux/WordPressFlux.xcodeproj/xcshareddata/xcschemes/WordPressFlux.xcscheme
  WordPressFlux/WordPressFlux/Sources/Dispatcher.swift
Labels: Tooling

#11452 Sharing screen to show snack bar instead of alert when offline
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/SharingViewController.m
Labels: Offline Support

#11476 [Stats Refresh] Fix a reuse bug in Last Post Insight
  WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
Labels: Stats Refresh

#11478 Improved accessibility of bar chart views in Stats
  WordPress/Classes/ViewRelated/Stats/Charts/Charts+Support.swift
  WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
  WordPress/Classes/ViewRelated/Stats/Charts/StatsChartLegendView.swift
  WordPress/Classes/ViewRelated/Stats/Charts/Stubs/PeriodDataStub.swift
  WordPress/Classes/ViewRelated/Stats/Charts/Stubs/PostSummaryDataStub.swift
Labels: Accessibility, Stats Refresh

#11479 Send proper locale key to Activity remotes
  RELEASE-NOTES.txt
  WordPress/Classes/Stores/ActivityStore.swift
Labels: [Type] Bug

#11481 Remove blocking interaction when trying to delete a post when offline
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: Offline Support, [Status] Needs Copy Review

#11485 [Stats Refresh] Period Overview card: populate with real data
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Labels: Stats Refresh

#11495 [Stats Refresh] Period stats: restart queries when period or date changes
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Labels: Stats Refresh

#11499 [Stats Refresh] Post Stats: show web view when post title tapped
  WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTitleCell.xib
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: Stats Refresh

#11500 Share Extension: Improve TextBundle/Pack import
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressShareExtension/ShareModularViewController.swift
Labels: Share Extension

#11468 [Jetpack Remote Install] Jetpack Analytics
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/JetpackInstallStore.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/Webview/JetpackConnectionWebViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
  WordPress/Classes/ViewRelated/Stats/StatsViewController.m
Labels: Analytics, Jetpack

#11501 [Jetpack Remote Install] Enable feature flag
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Jetpack

#11484 Merge/12.2 into develop
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupUsernameTableViewController.swift
  WordPress/Resources/release_notes.txt
  WordPress/WordPressShareExtension/ar.lproj/Localizable.strings
  WordPress/WordPressShareExtension/bg.lproj/Localizable.strings
  WordPress/WordPressShareExtension/cs.lproj/Localizable.strings
  WordPress/WordPressShareExtension/cy.lproj/Localizable.strings
  WordPress/WordPressShareExtension/da.lproj/Localizable.strings
  WordPress/WordPressShareExtension/de.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-AU.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-CA.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-GB.lproj/Localizable.strings
  WordPress/WordPressShareExtension/es.lproj/Localizable.strings
  WordPress/WordPressShareExtension/fr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/he.lproj/Localizable.strings
  WordPress/WordPressShareExtension/hr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/hu.lproj/Localizable.strings
  WordPress/WordPressShareExtension/id.lproj/Localizable.strings
  WordPress/WordPressShareExtension/is.lproj/Localizable.strings
  WordPress/WordPressShareExtension/it.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ja.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ko.lproj/Localizable.strings
  WordPress/WordPressShareExtension/nb.lproj/Localizable.strings
  WordPress/WordPressShareExtension/nl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pt-BR.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pt.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ro.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ru.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sk.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sq.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sv.lproj/Localizable.strings
  WordPress/WordPressShareExtension/th.lproj/Localizable.strings
  WordPress/WordPressShareExtension/tr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/zh-Hans.lproj/Localizable.strings
  WordPress/WordPressShareExtension/zh-Hant.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#11502 Point to latest gutenberg-mobile release v1.3.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#11514 Remove newsCard FeatureFlag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
Labels: [Type] Tech Debt

#11516 Only display confirmation alert for unpublished posts
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Labels: [Type] Broken Window

#11524 Remove jetpackRemoteInstallation FeatureFlag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
Labels: [Type] Tech Debt

#11528 Add domain credit feature flag (turned off)
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Domain Credit

#11511 Zendesk: update API methods
  WordPress/Classes/Utility/ZendeskUtils.swift
Labels: Zendesk

#11527 [FIX] Application stuck after Notifications dialog block is called
  WordPress/Classes/Utility/InteractiveNotificationsManager.swift
Labels: Notifications, [Type] Bug

#11519 Remove giphy FeatureFlag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
Labels: [Type] Tech Debt

#11518 Fixing tests for localization.
  WordPress/WordPressTest/AbstractPostTest.swift
  WordPress/WordPressTest/NewsCardTests.swift
  WordPress/WordPressTest/PostTests.swift
  WordPress/WordPressTest/ReaderFollowedSitesStreamHeaderTests.swift
  WordPress/WordPressTest/ReaderPostCardCellTests.swift
  WordPress/WordPressTest/SearchMenuItemCreatorTests.swift
Labels: Localization

#11512 Fixing layout issue in AppFeedbackPromptView
  WordPress/Classes/ViewRelated/Ratings/AppFeedbackPromptView.swift
Labels: Layout

#11504 [Stats Refresh] Post Stats: fetch data for post
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Latest Post Summary/LatestPostSummaryCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
Labels: Stats Refresh

#11534 Merge release notes into develop
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Tooling

#11529 Update Aztec ref to test fix #11515
  Podfile
  Podfile.lock
Labels: Aztec

#11521 Remove revisions FeatureFlag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+MoreActions.swift
Labels: [Type] Tech Debt

#11520 Remove automatedTransfersCustomDomain flag
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
Labels: [Type] Tech Debt

#11539 Fix/update release notes 12.3
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: i18n

#11540 [Jetpack Remote Install] New copy for Jetpack installation success
  WordPress/Classes/ViewRelated/Jetpack/Install/View/State/JetpackRemoteInstallState.swift
Labels: Jetpack

#11535 Improved accessibility experience with the site creation flow
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyContentView.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleHeader.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
  WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsCell.swift
  WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsWizardContent.swift
Labels: Site Creation, VoiceOver

#11541 Merge release 12.3 into develop
  Podfile
  Podfile.lock
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: i18n

#11542 Improved accessibility of close button in Quick Start checklist
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
Labels: Accessibility, Quick Start

#11544 Podfile: Link extension targets at top level
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#11533 Fixing SplitViewController warning:
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: General

#11536 Fix layout issues:
  WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
Labels: Layout

#11507 [Stats Refresh] Post Stats: add Recent Weeks
  WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/StatsDataHelper.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: Stats Refresh

#11508 Zendesk: show alert if user email is a8c
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: Zendesk

#11517 Zendesk: Pass new request configuration to Help Center and My Tickets
  WordPress/Classes/Utility/ZendeskUtils.swift
Labels: Zendesk

#11548 Podfile: Link extension targets at top level
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#11552 Improve SiteAssemblyServiceTests execution time
  WordPress/Classes/Services/SiteAssembly.swift
  WordPress/WordPressTest/SiteCreation/SiteAssemblyServiceTests.swift
Labels: [Type] Tech Debt

#11523 Remove quickStartV2 FeatureFlag
  WordPress/Classes/System/WordPressAppDelegate.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCellV1.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewControllerV1.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+QuickStart.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Tech Debt

#11554 Delete unused Site Creation symbols
  WordPress/Classes/Services/SiteCreationService.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationThemeSelectionCell.swift
  WordPress/Classes/ViewRelated/NUX/SiteCreationThemeSelectionHeaderView.swift
  WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsDelegate.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Creation, [Type] Tech Debt

#11551 Remove unused classes in WordPressTest
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/CoreDataTestHelper.h
  WordPress/WordPressTest/CoreDataTestHelper.m
  WordPress/WordPressTest/UIKitTestHelper.h
  WordPress/WordPressTest/UIKitTestHelper.m
Labels: [Type] Tech Debt

#11522 Remove Gutenberg FeatureFlag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
Labels: [Type] Tech Debt

#11550 Check NRV visibility before modifying constraints
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
Labels: Media, NoResultsView

#11532 Remove AFNetworking from project.
  Podfile
  Podfile.lock
  WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
  WordPress/Classes/System/WordPressAppDelegate+Swift.swift
  WordPress/Classes/System/WordPressAppDelegate.m
  WordPress/Classes/Utility/Media/ImageLoader.swift
  WordPress/Classes/Utility/WPError.m
  WordPress/Classes/ViewRelated/Me/MeHeaderView.h
  WordPress/Classes/ViewRelated/Me/MeHeaderView.m
  WordPress/Classes/ViewRelated/Me/MyProfileHeaderView.swift
  WordPress/Classes/ViewRelated/Plugins/PluginDirectoryCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Plugins/PluginListCell.swift
  WordPress/Classes/ViewRelated/Plugins/PluginListRow.swift
  WordPress/Classes/ViewRelated/Post/PostCardTableViewCell.m
  WordPress/Classes/ViewRelated/Reader/ReaderCardDiscoverAttributionView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/WPImageViewController.m
  WordPress/Classes/ViewRelated/Site Creation/SiteSegments/SiteSegmentsCell.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress_Prefix.pch
  WordPressComStatsiOS/WordPressComStatsiOS.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#11561 [Stats Refresh] Insights: fix getting most popular day
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: Stats Refresh

#11538 Issue/10073 update mediapicker ref to 1.3.4
  Podfile
  Podfile.lock
Labels: [Type] Bug, [Type] Crash

#11545 Share Extension: use first line of Markdown as title
  WordPress/WordPressShareExtension/ShareExtractor.swift
Labels: Share Extension

#11547 Remove some dead code
  WordPress/Classes/Categories/Media+HTML.h
  WordPress/Classes/Categories/Media+HTML.m
  WordPress/Classes/Utility/ReachabilityFacade.h
  WordPress/Classes/Utility/ReachabilityFacade.m
  WordPress/Classes/ViewRelated/Views/WPBackgroundDimmerView.h
  WordPress/Classes/ViewRelated/Views/WPBackgroundDimmerView.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Tech Debt

#11563 Better Error Messaging for Invalid URLs
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Debouncer.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/DebouncerTests.swift
Labels: [Type] Enhancement

#11566 Merge 12.3.0.1 into develop
  Scripts/fastlane/Fastfile
  WordPress/Classes/Utility/Sentry/WPCrashLogging.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/ShareExtractor.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#11568 Merge 12.3.0.2 into develop
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Tooling

#11537 Add domain credit section & UI to be shown on site dashboard
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+DomainCredit.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+SectionHelpers.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogDetailsSectionIndexTests.swift
  WordPress/WordPressTest/BlogDetailsSubsectionToSectionCategoryTests.swift
Labels: Domain Credit

#11562 Added accessibility label to add image in new user epilogue
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
Labels: VoiceOver

#11560 Remove unused View-related classes
  WordPress/Classes/ViewRelated/Blog/QuickStartNoticeView.swift
  WordPress/Classes/ViewRelated/Cells/CustomCellMarginBehavior.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueSegue.swift
  WordPress/Classes/ViewRelated/Plans/PurchaseButton.swift
  WordPress/Classes/ViewRelated/Views/ConfettiView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Tech Debt

#11556 Swift App Delegate 4: Tracks and Keychain
  WordPress/Classes/System/WordPressAppDelegate+Swift.swift
  WordPress/Classes/System/WordPressAppDelegate.h
  WordPress/Classes/System/WordPressAppDelegate.m
Labels: [Type] Tech Debt

#11573 Notifications: Mark as unread
  RELEASE-NOTES.txt
  WordPress/Classes/Services/NotificationSyncMediator.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Labels: Notifications, [Type] Enhancement

#11567 Update the WordPressShared pod to use the latest version
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#11570 [Fix] UIAlertController popover properties
  WordPress/Classes/ViewRelated/Blog/BlogDetailsSectionHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Labels: Quick Start, [Type] Bug

#11574 [Quick Start] Wrong cell selected as soon QuickStart is activated
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Labels: Quick Start, [Type] Bug

#11558 Draft missing from post list
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
Labels: [Type] Bug

#11575 Reader: Enforce max image size to prevent OOM errors due to gigantic images
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Labels: Reader, [Type] Crash

#11578 Improved accessibility of the steps in a Quick Start tour
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistCell.xib
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
Labels: VoiceOver

#11577 Account Settings Primary Site: show URL if site has no name
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Me/AccountSettingsViewController.swift
Labels: /Me

#11579 Improved accessibility of Quick Start checklist header
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistHeader.xib
Labels: VoiceOver

#11582 Issues/improve reader comments performance
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Labels: Reader, [Type] Enhancement

#11588 [Stats Refresh] Post Stats: add Months and Years
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
Labels: Stats Refresh

#11580 Improvements to signup epilogue accessibility
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
Labels: VoiceOver

#11572 Domain credit success UI
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+DomainCredit.swift
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/DomainCredit/DomainCreditRedemptionSuccessViewController.swift
  WordPress/Classes/ViewRelated/Blog/NoResultsViewController.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/Classes/ViewRelated/Menus/MenusViewController.m
  WordPress/Classes/ViewRelated/Post/PostPreviewViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Stats/StatsViewController.m
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-domain-credit-success.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-domain-credit-success.imageset/wp-illustration-domain-credit-success.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Domain Credit

#11589 [Stats Refresh] Post Stats: add Avg Views Per Day
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
Labels: Stats Refresh

#11576 Update README.md
  README.md
Labels: [Type] Enhancement

#11591 Fixes 3 warnings in the project.
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Labels: [Type] Task

#11557 Swift App Delegate 5: Appearance
  WordPress/Classes/System/WordPressAppDelegate+Swift.swift
  WordPress/Classes/System/WordPressAppDelegate.h
  WordPress/Classes/System/WordPressAppDelegate.m
Labels: [Type] Tech Debt
