Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2019-10, with the labels that each got.

#12571 Publish button in Post List should auto-upload the post
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: Offline Support, [Type] Task

#12594 Automatically upload published and draft posts with existing remote
  WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
  WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
Labels: Offline Support, [Type] Bug

#12555 Remote auto-save unconfirmed published posts
  WordPress/Classes/Models/Post.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/WordPressTest/PostBuilder.swift
  WordPress/WordPressTest/PostCardCellTests.swift
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/PostTests.swift
  WordPress/WordPressTest/Services/PostCoordinatorFailedPostsFetcherTests.swift
Labels: Offline Support, [Type] Task

#12551 Fix UI Tests for iOS 13/Xcode 11
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Screens/BaseScreen.swift
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPressUITests/Screens/Signup/SignupEpilogueScreen.swift
Labels: Testing

#12404 Feat: Multiple selection of media in gutenberg
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#12577 [Share Extension] Fix textview inset
  RELEASE-NOTES.txt
  WordPress/WordPressShareExtension/ExtensionPresentationController.swift
Labels: Share Extension, [Type] Bug

#12590 [Dark Mode] Re-enable screenshots when app is in background
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Labels: Dark mode, [Type] Bug

#12585 [SIWA] Handle credential state changes
  Podfile
  Podfile.lock
  WordPress/Classes/System/WordPressAppDelegate.swift
Labels: Sign In With Apple

#12611 Revert "support multiple prop in gutenberg editor"
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#12610 [Dark Mode ]NUX Button Loading
  Podfile
  Podfile.lock
Labels: Dark mode

#12580 Do not automatically retry upload after 3 failures
  MIGRATIONS.md
  WordPress/Classes/Models/AbstractPost.h
  WordPress/Classes/Services/PostAutoUploadInteractor.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/ViewRelated/Post/PostAutoUploadMessages.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 91.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/I18n.swift
  WordPress/WordPressTest/PostBuilder.swift
  WordPress/WordPressTest/PostCardCellTests.swift
  WordPress/WordPressTest/PostCompactCellTests.swift
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
Labels: Offline Support, [Type] Task

#12620 Remove auto-switching of Post List tabs
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: Offline Support

#12609 Use credentials tool to copy/decrypt credentials intead of referencing the secrets repo path
  .configure
  .configure-files/wpcom_alpha_app_credentials.enc
  .configure-files/wpcom_app_credentials.enc
  .configure-files/wpcom_internal_app_credentials.enc
  .gitignore
  README.md
  Rakefile
  WordPress/Credentials/wpcom_app_credentials-example
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#12622 Revert "Use credentials tool to copy/decrypt credentials intead of referencing the secrets repo path"
  .configure
  .configure-files/wpcom_alpha_app_credentials.enc
  .configure-files/wpcom_app_credentials.enc
  .configure-files/wpcom_internal_app_credentials.enc
  .gitignore
  README.md
  Rakefile
  WordPress/Credentials/wpcom_app_credentials.txt
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#12607 Use fastlane match to manage certificates and profiles for AppStore and Enterprise builds
  .configure
  .configure-files/google_cloud_keys.json.enc
  .gitignore
  Scripts/fastlane/Fastfile
  Scripts/fastlane/Matchfile
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#12616 Aztec options picker popover DarkMode
  Podfile
  Podfile.lock
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+Aztec.swift
Labels: Aztec, Dark mode

#12574 Gutenberg/1.14.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#12576 Improve media retry
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/Services/MediaService.swift
  WordPress/Classes/Utility/CoreDataHelper.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Labels: [Type] Bug

#12606 [SIWA] Show email address on WP password entry view
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Sign In With Apple

#12612 Handle link tap inside WPRichContentView instead of in shouldInteractWith URL
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Labels: Reader, iOS 13

#12614 Improve calculation of media directories.
  WordPress/Classes/Utility/Media/MediaFileManager.swift
  WordPress/Classes/ViewRelated/Me/AppSettingsViewController.swift
Labels: [Type] Enhancement

#12623 Revert "Revert "Use credentials tool to copy/decrypt credentials intead of referencing the secrets repo path""
  .configure
  .configure-files/wpcom_alpha_app_credentials.enc
  .configure-files/wpcom_app_credentials.enc
  .configure-files/wpcom_internal_app_credentials.enc
  .gitignore
  Gemfile.lock
  README.md
  Rakefile
  Scripts/fastlane/Pluginfile
  WordPress/Credentials/wpcom_app_credentials-example
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#12636 Update beta pods to release version
  Podfile
  Podfile.lock
Labels: Releases

#12637 [Dark Mode] Fix Reader Detail Like star animation background color
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Labels: Dark mode, Reader

#12613 Support published, private, and pending statuses
  RELEASE-NOTES.txt
  WordPress/Classes/Services/PostAutoUploadInteractor.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
  WordPress/Classes/Services/PostService+RefreshStatus.swift
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostAutoUploadMessages.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostBuilder.swift
  WordPress/WordPressTest/PostCardCellTests.swift
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
  WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
  WordPress/WordPressTest/Services/PostCoordinatorFailedPostsFetcherTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Labels: Offline Support, [Type] Task

#12639 Merge Release/13.4 back into develop
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#12631 Add tracking for auto upload invoked
  Podfile
  Podfile.lock
  WordPress/Classes/Services/PostAutoUploadInteractor.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostCoordinatorTests.swift
Labels: Analytics, Offline Support

#12615 [Gutenberg] Revert "revert-multiple-media-pr"
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#12645 Remove warning in AbstractPost
  WordPress/Classes/Models/AbstractPost.m
Labels: Offline Support, [Type] Task

#12632 [Insights Management] Save settings for each site
  WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: Insights Management

#12633 [Insights Management] Disable already displayed Insights
  WordPress/Classes/ViewRelated/Stats/Insights/Insights Management/AddInsightTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: Insights Management

#12643 *Temporarily* not allowing auto upload for pages
  WordPress/Classes/Services/PostAutoUploadInteractor.swift
  WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
Labels: Offline Support, Pages List

#12640 Issue/12592 Update fancy button border style
  Podfile
  Podfile.lock
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Dark mode, NUX

#12617 [Dark Mode] Update Tag picker colors
  WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
Labels: Dark mode

#12619 [Dark Mode] Remove white background from Site Settings Tags and TimeZone
  WordPress/Classes/ViewRelated/Blog/SiteManagement/SiteTagsViewController.swift
  WordPress/Classes/ViewRelated/Tools/TimeZoneSelectorViewController.swift
Labels: Dark mode

#12624 [Dark Mode] Removed white background in Reader Manage button
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesStreamHeader.swift
Labels: Dark mode

#12618 [Dark Mode] Fix Post Undo cell background and divider
  WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.swift
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.swift
Labels: Dark mode

#12649 Update strings for Offline Support
  WordPress/Classes/ViewRelated/Post/PostAutoUploadMessages.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
  WordPress/WordPressTest/PostCardCellTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Labels: Offline Support, [Type] Task

#12656 Update fastlane and release-toolkit
  Gemfile
  Gemfile.lock
  Scripts/fastlane/Pluginfile
Labels: Tooling

#12650 [Insights Management] Add ability to organize cards
  WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/StatsTwoColumnRow.xib
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.xib
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: Insights Management

#12657 Disable UI tests that use a magic link
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
Labels: Testing

#12658 [Stats] Enable internal testing for Insights async loading.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Stats Refresh

#12652 Make PostCoordinator.autoSave create non-draft posts if necessary and handle failures
  WordPress/Classes/Services/PostService.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Services/PostServiceSelfHostedTests.swift
  WordPress/WordPressTest/Services/PostServiceTests.swift
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: Offline Support

#12666 Merge Release/13.4 into Develop
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#12581 [Gutenberg] Return the media type for uploads
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#12668 Store all credentials under .configure-files to prevent accidental commits
  .configure
  .gitignore
  README.md
  Scripts/fastlane/Matchfile
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#12621 [Dark Mode] Fix Picker background color
  WordPress/Classes/ViewRelated/Cells/PickerTableViewCell.swift
Labels: Dark mode

#12659 [Insights Management] Show empty view
  WordPress/Classes/Extensions/UIViewController+NoResults.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-stats-outline.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-stats-outline.imageset/wp-illustration-stats-outline.pdf
Labels: Insights Management

#12670 Editing a pending/scheduled post keeps it status
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Labels: Offline Support, [Type] Bug

#12683 [Dark Mode] Fix Reader comment background color
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Labels: Dark mode

#12692 Changes Gutenberg VC accordingly with changes in the post
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration, Offline Support, [Type] Bug

#12693 [Insights Management] Add Accessibility support for Add Insight view
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: Insights Management

#12687 [Insights Management] Update when the Customize card is hidden
  WordPress/Classes/ViewRelated/Stats/Insights/Insights Management/AddInsightTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: Insights Management

#12694 [Insights Management] Add Accessibility support for Manage Insight
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.xib
Labels: Insights Management

#12695 [Insights Management] Add Analytics tracking
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: Insights Management

#12700 CircleCI: Update Orb to fix pod install timeouts
  .circleci/config.yml
Labels: Tooling

#12690 Update button works while offline
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Labels: Offline Support, [Type] Task

#12654 Optionally provide installable build on Pull Requests
  .circleci/config.yml
  .configure
  .configure-files/project.env.enc
  Scripts/fastlane/Fastfile
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#12705 Use CocoaPods CDN specs repo for faster pod installs
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
Labels: Tooling

#12712 Add simple tests for MediaCoordinator.uploadMedia
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/MediaService.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/PostBuilder.swift
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/Services/MediaCoordinatorTests.swift
Labels: Offline Support

#12711 [Stats] Enable Insights async loading
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Stats Refresh

#12704 Issue/12697 fix default blog
  MIGRATIONS.md
  WordPress/Classes/Models/WPAccount.h
  WordPress/Classes/Models/WPAccount.m
  WordPress/Classes/Services/AccountService.h
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 91.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Bug

#12710 [Insights Management] Resize subtitles after adding stat
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.xib
Labels: Insights Management

#12707 [Stats] show Posting Activity bottom line
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.xib
Labels: Stats

#12716 [Offline Posting] Fix Page List → Retry regression
  WordPress/Classes/Models/AbstractPost.m
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
  WordPress/Classes/Services/PostService+RefreshStatus.swift
  WordPress/Classes/Services/PostService.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
  WordPress/WordPressTest/TestUtilities/PageBuilder.swift
Labels: Offline Support

#12691 Gutenberg: Update to v1.15.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#12719 Rakefile: Always use latest credentials when running 'rake dependencies'
  Rakefile
Labels: Tooling

#12720 Add release notes for Offline Posting
  RELEASE-NOTES.txt
Labels: Offline Support

#12726 [Insights Management] Replace Customize card image
  WordPress/Classes/ViewRelated/Stats/Insights/Insights Management/CustomizeInsightsCell.xib
  WordPress/Resources/AppImages.xcassets/insights-management-feature-image.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/insights-management-feature-image.imageset/insightsManagementFeatureImage.pdf
  WordPress/Resources/AppImages.xcassets/insights-management-feature-image.imageset/insightsManagementFeatureImage.png
  WordPress/Resources/AppImages.xcassets/insights-management-feature-image.imageset/insightsManagementFeatureImage@2x.png
  WordPress/Resources/AppImages.xcassets/insights-management-feature-image.imageset/insightsManagementFeatureImage@3x.png
Labels: Insights Management

#12723 [Insights Management] Add Analytics tracking
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: Insights Management

#12728 [Insights Management] Enable feature flag
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Insights Management

#12655 Fix build warnings in Xcode 11
  WordPress/Classes/Models/Media.m
  WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift
  WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainDetails/Views/RegisterDomainDetailsErrorSectionFooter.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
  WordPress/Classes/ViewRelated/Plugins/PluginDirectoryAccessoryItem.swift
  WordPress/WordPressShareExtension/ShareExtractor.swift
Labels: [Type] Tech Debt

#12721 [Stats Refresh] Insights detail view async loading
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsStore+Cache.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/GhostViews/StatsGhostCells.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/GhostViews/StatsGhostSingleRowCell.xib
  WordPress/Classes/ViewRelated/Stats/Shared Views/GhostViews/StatsGhostTableViewRows.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/GhostViews/StatsGhostTopCell.xib
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats, Stats Refresh

#12735 Update dependencies to released versions.
  Podfile
  Podfile.lock
Labels: Releases

#12732 Issues/12672 fix notification setup glitch
  WordPress/Classes/Services/AccountService.h
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/WordPressTest/AccountServiceTests.swift
Labels: Notifications, [Type] Bug

#12722 Show snackbar with "We'll publish the post" on failure to upload post with media
  WordPress/Classes/Models/Media.swift
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/WordPressTest/MediaTests.swift
Labels: Offline Support, [Type] Bug

#12739 Fix infinite upload
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Utility/ActionDispatcherFacade.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostCoordinatorTests.swift
Labels: Offline Support

#12743 Add signup_flow param by updating WordPressKit pod
  Podfile
  Podfile.lock
Labels: Signup, [Type] Enhancement

#12737 Merge Release/13.5 into develop
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Classes/Services/AccountService.h
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/WordPressTest/AccountServiceTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#12753 Opening post settings after uploading a featured image from another client displays the image
  WordPress/Classes/Models/BasePost.m
  WordPress/WordPressTest/AbstractPostTest.swift
Labels: Posting/Editing, [Type] Bug

#12752 Update to Gutenberg-Mobile v1.15.1
  Podfile
  Podfile.lock
Labels: Gutenberg compatibility

#12757 Replace GiphyCoreSDK with Giphy pod
  Podfile
  Podfile.lock
Labels: Media, Upgrades

#12758 Issue/fix rotation of photos hotfix
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Media/MediaImageExporter.swift
  WordPress/WordPressTest/MediaImageExporterTests.swift
Labels: [Type] Bug

#12741 Issue/fix rotation of photos
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Media/MediaImageExporter.swift
  WordPress/WordPressTest/MediaImageExporterTests.swift
Labels: [Type] Bug

#12736 Ignore derived-data folder
  .gitignore
Labels: Tooling

#12755 Copy Wiki contents to docs folder
  CODESTYLE.md
  README.md
  docs/README.md
  docs/accessibility-guidelines.md
  docs/best-practices.md
  docs/coding-style-guide.md
  docs/dynamic-type-guidelines.md
  docs/feature-flags.md
  docs/formattable-content.md
  docs/images/dynamic-type-guidelines.png
  docs/images/voiceover-guidelines.png
  docs/pull-request-guidelines.md
  docs/right-to-left-layout-support-guidelines.md
  docs/using-voiceover.md
  docs/voiceover-guidelines.md
Labels: Documentation

#12765 Deleted post with local changes appears only under Trashed tab
  WordPress/Classes/Services/PostService.m
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: Offline Support, [Type] Bug

#12766 Fixes a couple of issues flagged by the static analyzer.
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
Labels: General, Low Hanging Fruit

#12769 Remove Giphy dependency
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Media/Giphy/GiphyService.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/GiphyPageableTests.swift
Labels: Giphy

#12777 Merge release 13.5 into develop
  .gitignore
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Models/AbstractPost.swift
  WordPress/Classes/Utility/Media/MediaImageExporter.swift
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
  WordPress/WordPressTest/AbstractPostTest.swift
  WordPress/WordPressTest/BasePostTests.swift
  WordPress/WordPressTest/MediaImageExporterTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#12764 [Stats Refresh] DWMY Async loading operations and feature flag
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/Stores/StatsStore+Cache.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Stats/Operation/AsyncOperation.swift
  WordPress/Classes/ViewRelated/Stats/Operation/StatsPeriodAsyncOperation.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/AsyncOperationTests.swift
  WordPress/WordPressTest/StatsPeriodAsyncOperationTests.swift
Labels: Stats Refresh

#12767 Stats Today widget: update to use new Stats
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/System/Constants.h
  WordPress/Classes/System/Constants.m
  WordPress/Classes/ViewRelated/Stats/Today Widgets/TodayWidgetStats.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTodayWidget/TodayViewController.swift
Labels: Stats Widgets

#12749 Add Calendar Picker + new Publish Settings screen
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/CalendarMonthView.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/ChosenValueRow.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/HalfScreenPresentationController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/LightNavigationController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingDate+Helpers.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Post Scheduling Enhancements, [Type] Task

#12773 Update gutenberg bridge to support MediaInfo
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: [Type] Bug

#12761 [Gutenberg] Update new editor popup message.
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+InformativeDialog.swift
  WordPress/WordPressTest/GutenbergInformativeDialogTests.swift
Labels: Gutenberg integration

#12772 Do full link selection fix only on 13.0
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Labels: [Type] Bug, [Type] Crash

#12788 Merge release 13.4.1 into 13.5
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/metadata/en-AU/release_notes.txt
  Scripts/fastlane/metadata/en-CA/release_notes.txt
  Scripts/fastlane/metadata/en-GB/release_notes.txt
  Scripts/fastlane/metadata/en-US/release_notes.txt
  WordPress/Classes/ViewRelated/Media/Giphy/GiphyService.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/GiphyPageableTests.swift
Labels: Releases

#12786 Release/13.4.1
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/metadata/en-AU/release_notes.txt
  Scripts/fastlane/metadata/en-CA/release_notes.txt
  Scripts/fastlane/metadata/en-GB/release_notes.txt
  Scripts/fastlane/metadata/en-US/release_notes.txt
  WordPress/Classes/Models/AbstractPost.swift
  WordPress/Classes/Utility/Media/MediaImageExporter.swift
  WordPress/Classes/ViewRelated/Media/Giphy/GiphyService.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/AbstractPostTest.swift
  WordPress/WordPressTest/BasePostTests.swift
  WordPress/WordPressTest/GiphyPageableTests.swift
  WordPress/WordPressTest/MediaImageExporterTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#12771 [Stats Refresh] Remove feature flag
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
  WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+Stats.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/Stats/StatsViewController.h
  WordPress/Classes/ViewRelated/Stats/StatsViewController.m
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Refresh

#12797 Fix:Media & Text - Block validation error occurs if media upload finishes when the post is closed
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergImgUploadProcessor.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergVideoUploadProcessor.swift
Labels: Gutenberg compatibility

#12783 [Gutenberg] Hotfix 1.15.2
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergImgUploadProcessor.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergVideoUploadProcessor.swift
Labels: Gutenberg integration

#12806 Merge release 13.5 into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/metadata/en-AU/release_notes.txt
  Scripts/fastlane/metadata/en-CA/release_notes.txt
  Scripts/fastlane/metadata/en-GB/release_notes.txt
  Scripts/fastlane/metadata/en-US/release_notes.txt
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergImgUploadProcessor.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergVideoUploadProcessor.swift
  WordPress/Classes/ViewRelated/Media/Giphy/GiphyService.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/GiphyPageableTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#12807 Update Gutenberg to latest develop
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#12768 Support Landscape for Post Scheduling Calendar Picker
  WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/CalendarMonthView.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/ChosenValueRow.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/HalfScreenPresentationController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/LightNavigationController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingDate+Helpers.swift
Labels: Post Scheduling Enhancements, [Type] Task

#12815 [Insights Management] Remove feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
Labels: Insights Management

#12817 [Stats Refresh] DWMY Async loading and Ghost views - Part 2
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/Stores/StatsStore+Cache.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
Labels: Stats Refresh

#12814 Fix Me screen when logged in with self hosted site
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Me/MeViewController.swift
Labels: /Me, Self-hosted
