Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2020-02, with the labels that each got.

#13352 Updated News Card to announce Offline Support
  WordPress/News.strings
Labels: [Type] Task, news card

#13351 Strips HTML from the comment view/edit on the site detail views
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
Labels: Comments, [Type] Bug

#13359 Cleanup: remove exampleFeature flag.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Task

#13363 Remove `postScheduling` feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Post/PostCardCell.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/PublishDatePickerView.h
  WordPress/Classes/ViewRelated/Post/PublishDatePickerView.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#13360 Integrates WPKit 4.5.7-beta.1
  Podfile
  Podfile.lock
  WordPress/Classes/Models/AbstractPost.m
  WordPress/Classes/Models/Post.swift
Labels: Sharing, [Type] Bug

#13368 Removed the domain credit feature flag.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Labels: Domain Credit, [Type] Task

#13365 [Dark Mode] Posts list: Re-set ghost style when switching filter tabs.
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: Dark mode, Posts List

#13369 Fix sharing with Facebook.
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/WPWebViewController.h
  WordPress/Classes/Utility/WPWebViewController.m
  WordPress/Classes/Utility/WPWebViewController.xib
  WordPress/Classes/Utility/WebViewAuthenticator.swift
  WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.m
Labels: Webviews, [Type] Bug

#13347 [Media Editing] Load images from Private sites
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergMediaEditorImage.swift
Labels: Media Editing, [Type] Bug

#13372 Zendesk: Replace `ZendeskSDK` with `ZendeskSupportSDK`.
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Zendesk

#13274 Fixed improper spacing on notice for saving drafts offline
  WordPress/Classes/ViewRelated/System/Notices/UntouchableWindow.swift
Labels: Offline Support, Posting/Editing, [Type] Bug

#13384 Removes some code from unit tests that's no longer needed.
  WordPress/Classes/Utility/WPWebViewController.m
  WordPress/WordPressTest/WPUserAgentTests.m
Labels: Webviews

#13375 Fix gallery size labels - 1.22.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#13361 Post Reblogging - Add wp:image markup to posts reblogged with Block Editor
  RELEASE-NOTES.txt
  WordPress/Classes/Services/BlogService.h
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+BlogPicker.swift
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderReblogFormatter.swift
  WordPress/Classes/ViewRelated/Reader/ReaderReblogPresenter.swift
  WordPress/WordPressTest/ReaderPostCardCellTests.swift
  WordPress/WordPressTest/ReaderReblogActionTests.swift
Labels: Post Reblogging, Reader

#13385 Remove UIWebView from comments and method names
  WordPress/Classes/Utility/CookieJar.swift
  WordPress/Classes/Utility/WPUserAgent.m
  WordPress/Classes/Utility/WPWebViewController.m
Labels: Webviews, [Type] Task

#13386 Add localization doc
  docs/README.md
  docs/localization.md
Labels: Documentation

#13060 Add react-native-linear-gradient lib
  Podfile
  Podfile.lock
Labels: Gutenberg compatibility, Gutenberg integration, [Status] DO NOT MERGE

#13362 Autosave: Do not use autosave for drafts. Minor refactor.
  RELEASE-NOTES.txt
  WordPress/Classes/Services/PostService.m
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: Comments, [Type] Bug

#13350 [Media Editing] Load iCloud Photos
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Aztec/Media/MediaEditorOperation+Description.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Media Editing, [Status] DO NOT MERGE

#13387 Fixes an issue where comments made in the Reader may not appear after adding successfully
  RELEASE-NOTES.txt
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Labels: Comments, Reader, [Type] Bug

#13275 Magic Email Clients
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Info.plist
Labels: Login, Signup

#13389 Migrates SharingAuthorizationWebViewController to Swift.
  WordPress/Classes/ViewRelated/Blog/SharingAuthorizationHelper.m
  WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.h
  WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Webviews

#13377 [Gutenberg] Bump phase 2 rollout to 100%
  WordPress/Classes/Utility/Editor/GutenbergRollout.swift
  WordPress/WordPressUITests/Screens/BaseScreen.swift
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPressUITests/Screens/FancyAlertComponent.swift
  WordPress/WordPressUITests/Screens/MySiteScreen.swift
  WordPress/WordPressUITests/Screens/PostsScreen.swift
  WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
Labels: Gutenberg integration

#13392 [Media Editing] Remove Feature Flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
Labels: Media Editing, [Type] Task

#13049 Bug/12996 menu editor issue
  WordPress/Classes/ViewRelated/Menus/MenuItemEditingHeaderView.m
Labels: Menus

#13388 Displays offline messages only when the user is offline
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
  WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
Labels: Offline Support, [Type] Bug

#13396 Removes several comments and improves some method names.
  WordPress/Classes/ViewRelated/Blog/SharingAuthorizationWebViewController.swift
Labels: [Type] Task

#13390 Fix media library pick while offline
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.h
Labels: Offline Support, [Type] Bug

#13394 Auth feature flags
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: [Type] Task

#13373 Information Architecture Quick Actions implementation
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.h
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+Header.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Detail Header/ActionRow.swift
  WordPress/Classes/ViewRelated/Blog/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Detail Header/SiteIconView.swift
  WordPress/Classes/ViewRelated/Views/RoundedButton.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Information Architecture

#13353 Gutenberg: update to v1.22.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#13336 Update Fastlane and the AppCenter plugin
  Gemfile
  Gemfile.lock
  Scripts/fastlane/Fastfile
  Scripts/fastlane/Pluginfile
Labels: Tooling

#13407 Update pods for releases
  Podfile
  Podfile.lock
Labels: Releases

#13404 [Gutenberg] Support Multiple uploads in Gallery
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergStockPhotos.swift
Labels: Gutenberg integration, Stock Photos, [Type] Bug

#13409 Quick Actions: Add Drop Target API for iPad
  WordPress/Classes/ViewRelated/Blog/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Detail Header/SiteIconView.swift
Labels: Information Architecture

#13419 Fixes missing navigation title for a blog on resume
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
Labels: [Type] Task

#13416 Quick Actions: Add spotlight for Quick Start tour
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Detail Header/SiteIconView.swift
Labels: Information Architecture

#13354 After gutenberg-mobile v1.22.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#13408 Merge Release/14.2 into Develop
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#13421 Fix reblog for private sites
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Labels: Post Reblogging, [Type] Bug

#13374 Enable gallery upload options in production
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergStockPhotos.swift
Labels: Gutenberg integration, Media, [Type] Enhancement

#13450 Display "Done" label when editing already published images
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/WPMediaEditor.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Media Editing, [Type] Bug

#13443 Creates a new screen for the Post Sign Up Interstitial
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.xib
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-construct-site.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-construct-site.imageset/wp-illustration-construct-site.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Creation, [Type] Enhancement

#13445 Add Me Menu button to My Site Navigation Bar
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailHeaderView.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailHeaderView.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsSectionFooterView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsSectionHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsSectionHeaderView.xib
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Activity.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+DomainCredit.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Header.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+MeBarButton.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+SectionHelpers.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/ActionRow.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/SiteIconView.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListDataSource.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController+Activity.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController+BlogDetailsFactory.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController+SiteCreation.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Selector/BlogSelectorViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Selector/BlogSelectorViewController.m
  WordPress/Classes/ViewRelated/Blog/Domain Credit/DomainCreditEligibilityChecker.swift
  WordPress/Classes/ViewRelated/Blog/Domain Credit/DomainCreditRedemptionSuccessViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/DeleteSite.storyboard
  WordPress/Classes/ViewRelated/Blog/Site Management/DeleteSiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/SettingsTitleSubtitleController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/SiteSettingsViewController+SiteManagement.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/SiteTagsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/StartOverViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/TableViewHeaderDetailView.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/BlogSiteVisibilityHelper.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/BlogSiteVisibilityHelper.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/DateAndTimeFormatSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/DiscussionSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/JetpackConnectionViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/JetpackSecuritySettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/JetpackSpeedUpSiteSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/LanguageSelectorViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/LanguageViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsPreviewTableViewCell.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsPreviewTableViewCell.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsSettingsViewController.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsSettingsViewController.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/SettingTableViewCell.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/SettingTableViewCell.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteIconPickerPresenter.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
  WordPress/Classes/ViewRelated/Me/Me Presenter/MeScenePresenter.swift
  WordPress/Classes/ViewRelated/Tools/ScenePresenter.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: /Me, Information Architecture, [Type] Enhancement

#13464 Merge release 14.2 into develop
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/WPMediaEditor.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#13468 Merge Release/14.2 into develop
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#13424 Better error-message logic for post uploads (for page reusability).
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/ViewRelated/Post/AutoUploadMessageProvider.swift
  WordPress/Classes/ViewRelated/Post/PageAutoUploadMessageProvider.swift
  WordPress/Classes/ViewRelated/Post/PostAutoUploadMessageProvider.swift
  WordPress/Classes/ViewRelated/Post/PostAutoUploadMessages.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostCardCellTests.swift
  WordPress/WordPressTest/PostCompactCellTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Labels: Offline Support, [Type] Task

#13460 Leverage PostAutoUploadInteractor support for offline pages.
  WordPress/Classes/Services/PostAutoUploadInteractor.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/WordPressTest/Services/PostAutoUploadInteractorTests.swift
  WordPress/WordPressTest/TestUtilities/PageBuilder.swift
  WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
Labels: Offline Support, [Type] Task

#13442 Fix 13436: Preview Publish dismiss Editor w/ Confirm
  WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
Labels: [Pri] Blocking, [Type] Bug

#13459 Adds logic to determine when to show the post signup interstitial
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialCoordinator.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/NUX/Post Signup Interstitial/PostSignUpInterstitialCoordinatorTests.swift
Labels: [Type] Enhancement

#13461 Quick Actions Accessibility + Tracks
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Header.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/ActionRow.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/SiteIconView.swift
Labels: Information Architecture

#13355 Sentry logging: Log filename instead of absolute path
  WordPress/Classes/Utility/Logging/SentryStartupEvent.swift
Labels: Tooling, [Type] Enhancement

#13479 Update Aztec to version 1.16.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Aztec, Posting/Editing

#13480 Leverage PostNoticeViewModel for Offline Pages.
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/ViewRelated/Post/AbstractPostDisplayTextProvider.swift
  WordPress/Classes/ViewRelated/Post/PageDisplayTextProvider.swift
  WordPress/Classes/ViewRelated/Post/PostAutoUploadMessages.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostDisplayTextProvider.swift
  WordPress/Classes/ViewRelated/Post/PostDisplayTextResolver.swift
  WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Offline Support, [Type] Task

#13482 Enable Quick Actions feature flag
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Information Architecture

#13475 Add gravatar to the Me button
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+MeBarButton.swift
  WordPress/Classes/ViewRelated/Me/MeHeaderView.m
  WordPress/Classes/ViewRelated/Me/MyProfileHeaderView.swift
  WordPress/Classes/ViewRelated/Views/CircularImageView.swift
Labels: /Me, Information Architecture, [Type] Enhancement

#13474 Add feature flag + Create Button
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+CreateButton.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Screens/TabNavComponent.swift
Labels: Information Architecture

#13488 Remove duplicate gallery image size release note
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#13490 Fix crash on logout after using Reader
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Labels: Login, Reader, [Type] Crash

#13493 Show new messaging when saving / publishing / scheduling / submitting pages.
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Services/PostService+MarkAsFailedAndDraftIfNeeded.swift
  WordPress/Classes/Services/PostService+RefreshStatus.swift
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
Labels: Offline Support, [Type] Enhancement

#13484 Changes how the Post Signup Interstitial is displayed
  WordPress/Classes/ViewRelated/Blog/BlogListViewController.m
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Login, [Type] Enhancement

#13496 Fixes weekday symbols regional offsets
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/Scheduling/CalendarMonthView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Collection+RotateTests.swift
Labels: Post Scheduling Enhancements, [Type] Bug

#13497 Adjusts the tab index when updating Me Icon
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: Information Architecture, [Type] Bug

#13505 Adds analytics for the Post Signup Interstitial
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
Labels: Analytics, Login

#13508 Disable stripping of HTML when editing a comment from the CommentViewController
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
Labels: Comments

#13516 Fix crash in Post List Action Sheet
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostActionSheet.swift
  WordPress/WordPressTest/PostActionSheetTests.swift
Labels: Posts List, [Type] Crash

#13501 #13440: Adjusts mobile preview on tablets
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
Labels: Previews

#13520 Migrate PageListTableViewCell to Swift.
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.h
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.m
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.swift
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Offline Support, [Type] Task

#13478 Add automation for release wrap up steps
  Scripts/fastlane/Fastfile
Labels: Tooling

#13483 Handle concurrent calls to upload the same post
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/Services/PostServiceUploadingList.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/PostServiceUploadingListTests.swift
Labels: Aztec, Gutenberg integration, Previews, [Type] Crash

#13519 Update Alamofire to 4.8
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#13530 Migrates BasePageListCell and RestorePageTableViewCell to Swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Pages/BasePageListCell.h
  WordPress/Classes/ViewRelated/Pages/BasePageListCell.m
  WordPress/Classes/ViewRelated/Pages/BasePageListCell.swift
  WordPress/Classes/ViewRelated/Pages/PageListSectionHeaderView.xib
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.swift
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
  WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.h
  WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.m
  WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.swift
  WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Offline Support, [Type] Task

#13511 Login Epilogue: updated My Sites list
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Blog.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.xib
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Labels: Login

#13532 Implements progress bar for uploads in the pages list.
  WordPress/Classes/ViewRelated/Pages/BasePageListCell.swift
  WordPress/Classes/ViewRelated/Pages/PageListSectionHeaderView.xib
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.swift
  WordPress/Classes/ViewRelated/Pages/PageListTableViewCell.xib
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostUploadProgressViewController.swift
  WordPress/Classes/ViewRelated/Post/PostUploadProgressViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Offline Support, [Type] Enhancement

#13485 Update to Gutenberg v1.23.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#13538 Add the missing release note for the Block editor
  RELEASE-NOTES.txt
Labels: Documentation

#13541 Update pods for releases
  Podfile
  Podfile.lock
Labels: Releases

#13543 Login Epilogue: update User Info section
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Blog.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
Labels: Login

#13545 Consolidate all Danger workflows into one
  .github/workflows/danger-prs.yml
  .github/workflows/danger.yml
Labels: [Type] Enhancement

#13546 Merge release/14.3 into develop
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#13498 Add navigation to the new Me Scene from Spotlight Search and Universal links.
  WordPress/Classes/Utility/PushNotificationsManager.swift
  WordPress/Classes/Utility/Spotlight/SearchManager.swift
  WordPress/Classes/Utility/Universal Links/Routes+Me.swift
  WordPress/Classes/ViewRelated/Blog/Blog + Me/UIBarButtonItem+MeBarButton.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController+BlogDetailsFactory.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Me/Me Presenter/MeScenePresenter.swift
  WordPress/Classes/ViewRelated/Me/MeViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+MeNavigation.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/Classes/ViewRelated/Tools/ScenePresenter.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogDetailsViewController+MeButtonTests.swift
  WordPress/WordPressUITests/Screens/MeTabScreen.swift
  WordPress/WordPressUITests/Screens/TabNavComponent.swift
  WordPress/WordPressUITests/Tests/EditorAztecTests.swift
  WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
  WordPress/WordPressUITests/Tests/MainNavigationTests.swift
Labels: /Me, Information Architecture, [Type] Enhancement

#13518 Fixes a bug that was causing the share flow to be broken in internal.
  WordPress/WordPressShareExtension/MainShareViewController.swift
Labels: Share Extension, [Type] Bug

#13533 Migrated PostCompactCell and PostCardCell to use PostUploadProgressVi…
  WordPress/Classes/ViewRelated/Post/PostCardCell.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostCompactCell.swift
Labels: [Type] Enhancement, [Type] Task

#13551 Wrong publish string in post settings
  RELEASE-NOTES.txt
  WordPress/Classes/Models/AbstractPost.m
  WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
  WordPress/WordPressTest/ViewRelated/Post/Controllers/PublishSettingsControllerTests.swift
Labels: [Type] Bug

#13503 Add GitHub release creation to the release tooling
  Gemfile.lock
  Scripts/fastlane/Fastfile
  Scripts/fastlane/Pluginfile
Labels: Tooling

#13523 Adds a welcome screen after the user sign ups or logs in with no sites added
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialCoordinator.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.xib
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-construct-site.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-construct-site.imageset/wp-illustration-construct-site.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/NUX/Post Signup Interstitial/PostSignUpInterstitialCoordinatorTests.swift
Labels: Login, [Type] Enhancement

#13510 [Gutenberg] Issue 1883 Starter Page Template metrics
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
Labels: Analytics, Gutenberg compatibility, Gutenberg integration

#13555 Add hide/show animation to floating action button
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+CreateButton.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+HideShowCreate.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Screens/TabNavComponent.swift
  WordPress/WordPressUITests/Tests/MainNavigationTests.swift
Labels: Information Architecture

#13548 Remove UISplitViewController from the new Me screen
  WordPress/Classes/Extensions/UINavigationController+Helpers.swift
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Me/Account Settings/AccountSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/Account Settings/ChangePasswordViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AboutViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AboutViewController.xib
  WordPress/Classes/ViewRelated/Me/App Settings/AppIconViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/DebugMenuViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/PrivacySettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/Help & Support/Activity Logs/ActivityLogViewController.h
  WordPress/Classes/ViewRelated/Me/Help & Support/Activity Logs/ActivityLogViewController.m
  WordPress/Classes/ViewRelated/Me/Help & Support/Activity Logs/Log Detail/ActivityLogDetailViewController.h
  WordPress/Classes/ViewRelated/Me/Help & Support/Activity Logs/Log Detail/ActivityLogDetailViewController.m
  WordPress/Classes/ViewRelated/Me/Help & Support/SupportTableViewController+Activity.swift
  WordPress/Classes/ViewRelated/Me/Me Main/Header/MeHeaderView.h
  WordPress/Classes/ViewRelated/Me/Me Main/Header/MeHeaderView.m
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController+UIViewControllerRestoration.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/Presenter/MeScenePresenter.swift
  WordPress/Classes/ViewRelated/Me/My Profile/Change Username/ChangeUsernameViewController.swift
  WordPress/Classes/ViewRelated/Me/My Profile/Change Username/View Model/ChangeUsernameViewModel.swift
  WordPress/Classes/ViewRelated/Me/My Profile/Gravatar/GravatarPickerViewController.swift
  WordPress/Classes/ViewRelated/Me/My Profile/Gravatar/GravatarUploader.swift
  WordPress/Classes/ViewRelated/Me/My Profile/MyProfileHeaderView.swift
  WordPress/Classes/ViewRelated/Me/My Profile/MyProfileHeaderView.xib
  WordPress/Classes/ViewRelated/Me/My Profile/MyProfileViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/Classes/ViewRelated/Tools/SettingsCommon.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: /Me, Information Architecture, [Type] Enhancement

#13565 Merge release/14.3 into develop
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialCoordinator.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.xib
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-construct-site.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Illustrations/wp-illustration-construct-site.imageset/wp-illustration-construct-site.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/NUX/Post Signup Interstitial/PostSignUpInterstitialCoordinatorTests.swift
Labels: Releases

#13561 Login Epilogue: move connect site option
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Blog.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueConnectSiteCell.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueConnectSiteCell.xib
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Screens/Login/LoginEpilogueScreen.swift
Labels: Login

#13574 Merge release/14.3 into develop
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#13569 Wait to activate trailing constraint until update
  WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+CreateButton.swift
Labels: Information Architecture, [Type] Bug

#13575 Track adding tags in Post Settings
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: Analytics, [Type] Task

#13570 Login Epilogue: updated button panel view
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Labels: Login

#13573 Refactoring the Create FAB into coordinator
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/UIView+SpringAnimations.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/WPTabBarController+CreateButton.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Information Architecture

#13572 Enlarge tappable area behind the `Me` gravatar button
  WordPress/Classes/ViewRelated/Blog/Blog + Me/UIBarButtonItem+MeBarButton.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AboutViewController.swift
  WordPress/Classes/ViewRelated/Views/CircularImageView.swift
  WordPress/WordPressTest/BlogDetailsViewController+MeButtonTests.swift
Labels: /Me, Information Architecture, [Type] Enhancement
