Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2020-11, with the labels that each got.

#15196 Remove two unused methods.
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: [Type] Task

#15203 Merge 16.1 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#15189 Update "Story post" icon in FAB action sheet
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/System/Floating Create Button/SheetActions.swift
Labels: WP Stories

#15197 [Home Page Picker] Populate thumbnail cells of the Home Page Picker Container
  Podfile
  Podfile.lock
  WordPress/Classes/Services/PageCoordinator.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collabsable Header Filter Bar/CollabsableHeaderFilterCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collabsable Header Filter Bar/CollabsableHeaderFilterCollectionViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collabsable Header Filter Bar/CollapsableHeaderFilterBar.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collapsable Header Collection View Cell/CollapsableHeaderCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collapsable Header Collection View Cell/CollapsableHeaderCollectionViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerStoryboard.storyboard
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPreviewViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPreviewViewController.xib
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.xib
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignStep.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Part of a WIP Feature, [Type] Enhancement

#15198 iOS14 Today widget: add Tracks extension
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressHomeWidgetToday/Tracks+TodayHomeWidget.swift
Labels: [Type] Enhancement, iOS 14 Widgets

#15206 Today widgets: revert translations fix
  RELEASE-NOTES.txt
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressAllTimeWidget/Base.lproj/Localizable.strings
  WordPress/WordPressThisWeekWidget/Base.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/Base.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ar.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/bg.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/cs.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/cy.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/da.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/de.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-AU.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-CA.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-GB.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/es.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/fr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/he.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/hr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/hu.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/id.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/is.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/it.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ja.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ko.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/nb.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/nl.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pl.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pt-BR.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pt.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ro.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ru.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sk.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sq.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sv.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/th.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/tr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/zh-Hans.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/zh-Hant.lproj/Localizable.strings
Labels: Stats Widgets, [Type] Bug

#15204 Zendesk: Update to 5.1.1
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Zendesk, [Type] Enhancement

#15207 Page Settings: set display titles to "Page Settings" if a page is being editing.
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+MoreActions.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: Post Settings, [Type] Bug

#15205 Issue/15165 xcode12 misc build warnings
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
  WordPress/Info.plist
  WordPress/Resources/AppImages.xcassets/democover01.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/democover01.imageset/democover01.png
  WordPress/Resources/AppImages.xcassets/democover02.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/democover02.imageset/democover02.png
Labels: Tooling, Xcode 12

#15202 Remove IPHONEOS_DEPLOYMENT_TARGET for all Pods by letting Pod targets inherit deployment target from main app
  .circleci/cache-version
  Podfile
  Podfile.lock
Labels: Tooling, Xcode 12

#15208 [Home Page Picker] Handle Selected states of the footer and the thumbnails
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
Labels: Part of a WIP Feature, Site Creation, [Type] Enhancement

#15210 Support contact info: Fix text entry issues
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/ZendeskUtils.swift
Labels: Support, [Type] Bug

#15214 Change the loading indicator from a ghost view to an activity indicator
  WordPress/Classes/ViewRelated/Menus/MenuItemSourceFooterView.m
Labels: Menus, [Type] Enhancement

#15218 Prologue Carousel: Disable the feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Task

#15211 Add initial A/B testing support
  WordPress/Classes/Utility/ABTesting/ABTesting.swift
  WordPress/Classes/Utility/ABTesting/Assignments.swift
  WordPress/Classes/Utility/ABTesting/ExPlat.swift
  WordPress/Classes/Utility/ABTesting/ExPlatService.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ABTesting/ExPlatServiceTests.swift
  WordPress/WordPressTest/ABTesting/ExPlatTests.swift
  WordPress/WordPressTest/Test Data/explat-assignments.json
  WordPress/WordPressTest/Test Data/explat-malformed-assignments.json
Labels: Analytics, [Type] Task

#15220 Support contact email: update with email from contact info prompt
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: Support, [Type] Bug

#15222 Pages: add Edit to options menu
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: Pages List, [Type] Enhancement

#15226 AB testing: schedule a refresh based on TTL
  WordPress/Classes/Utility/ABTesting/ExPlat.swift
  WordPress/Classes/Utility/ABTesting/ExPlatService.swift
  WordPress/WordPressTest/ABTesting/ExPlatServiceTests.swift
  WordPress/WordPressTest/ABTesting/ExPlatTests.swift
Labels: Analytics, [Type] Task

#15213 [Home Page Picker] Add Skip button and Close button
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLightNavigationController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/WizardNavigation.swift
Labels: Part of a WIP Feature, Site Creation, [Type] Enhancement

#15227 Some changes to BlogDetailsViewController+MeButtonTests for reusability
  WordPress/Classes/Utility/Gesture Recognizer/BindableTapGestureRecognizer.swift
  WordPress/Classes/ViewRelated/Blog/Blog + Me/UIBarButtonItem+MeBarButton.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogDetailsViewController+MeButtonTests.swift
Labels: [Type] Task

#15217 [Home Page Picker] No Network handling
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
Labels: Part of a WIP Feature, Site Creation, [Type] Enhancement

#15235 Update issue-triage to reference medium priority instead of normal
  docs/issue-triage.md
Labels: Documentation

#15234 Remove ExPlat from WPiOS
  WordPress/Classes/Utility/ABTesting/ABTesting.swift
  WordPress/Classes/Utility/ABTesting/Assignments.swift
  WordPress/Classes/Utility/ABTesting/ExPlat.swift
  WordPress/Classes/Utility/ABTesting/ExPlatService.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ABTesting/ExPlatServiceTests.swift
  WordPress/WordPressTest/ABTesting/ExPlatTests.swift
  WordPress/WordPressTest/Test Data/explat-assignments.json
  WordPress/WordPressTest/Test Data/explat-malformed-assignments.json
Labels: Analytics, [Type] Task

#15225 Fix failing UI tests in block editor
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
Labels: Testing, [Type] Bug

#15228 Account Settings Email: show indicator if pending email change
  WordPress/Classes/Utility/WPImmuTableRows.swift
  WordPress/Classes/ViewRelated/Me/Account Settings/AccountSettingsViewController.swift
Labels: /Me, [Type] Enhancement

#15232 Login Prologue button view: make constraints optional.
  Podfile
  Podfile.lock
Labels: Login

#15243 Fix direct call to CoreDataManager
  WordPress/Classes/ViewRelated/What's New/Dependency container/WPTabBarController+WhatIsNew.swift
Labels: Core Data, [Type] Bug

#15249 Removes story option from post list when unsupported
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: [Type] Bug

#15250 Change Password: update placeholder text.
  WordPress/Classes/ViewRelated/Me/Account Settings/ChangePasswordViewController.swift
Labels: /Me, [Type] Enhancement

#15259 Ensure noto font is fully loaded before building attributed strings.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Labels: Reader, [Type] Bug

#15260 iOS14 Today widget: remove localizations
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, iOS 14 Widgets

#15254 Adding Categories to Prepublishing bottom sheet
  WordPress/Classes/ViewRelated/Post/Categories/PostCategoriesViewController.swift
  WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: Prepublishing Nudges, [Type] Enhancement

#15245 Improves some initializers.
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: [Type] Bug

#15262 Fix crash where UIBarButtonItem is not a UIView
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: New Reader iOS, [Type] Crash

#15261 Update CircleCI to use iOS 14
  .circleci/config.yml
  Scripts/fastlane/Fastfile
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Testing, Xcode 12, [Type] Bug, iOS 14

#15268 New P2s: hide Activity Log and Themes
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: P2, [Type] Enhancement

#15253 Approve 2fa challenges via notification action.
  WordPress/Classes/Utility/InteractiveNotificationsManager.swift
  WordPress/Classes/Utility/PushAuthenticationManager.swift
  WordPress/Classes/Utility/PushNotificationsManager.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Notifiable.swift
  WordPress/WordPressNotificationContentExtension/Info-Alpha.plist
  WordPress/WordPressNotificationContentExtension/Info-Internal.plist
  WordPress/WordPressNotificationContentExtension/Info.plist
  WordPress/WordPressNotificationContentExtension/Sources/Views/NotificationContentView.swift
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
Labels: Login, Notifications

#15283 Update Stories support Jetpack version to 9.1
  WordPress/Classes/Models/Blog.m
Labels: WP Stories

#15122 Implement File Block - I
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergFilesAppMediaSource.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg integration

#15274 Activity Log: adds pagination and fix NoResultsController
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/ActivityStore.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Activity/ActivityListViewModelTests.swift
  WordPress/WordPressTest/Classes/Stores/ActivityStoreTests.swift
  WordPress/WordPressTest/RegisterDomainDetailsViewModelTests.swift
Labels: Activity Log, Jetpack, [Type] Bug, [Type] Task

#15282 Replace instance of QuickStartTourGuide inside WPTabBarController with separate singleton
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/BlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistManager.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartNavigationSettings.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/Blog/SharingViewController.m
  WordPress/Classes/ViewRelated/Me/App Settings/DebugMenuViewController.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+QuickStart.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/SheetActions.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+QuickStart.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserHeaderView.swift
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Labels: [Pri] High, [Type] Crash

#15286 Reader: As a precaution, cancel previous downloads when configuring cells
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
Labels: Comments, Reader, [Type] Bug

#15295 Fixed wrong QuickStartGuide calls in NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Labels: [Type] Bug

#15298 Fixes a bug with the background of the blog details view.
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Labels: [Type] Bug

#15257 Integrate gutenberg-mobile release 1.41.0
  .circleci/cache-version
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#15231 [Home Page Picker] Connect Choose and Skip Actions in site creation
  Podfile
  Podfile.lock
  WordPress/Classes/Services/SiteAddressService.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignStep.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteCreationRequest+Validation.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/WizardNavigation.swift
Labels: Part of a WIP Feature, Site Creation, [Type] Enhancement

#15247 [Home Page Picker] Analytic Events
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Part of a WIP Feature, Site Creation, [Type] Enhancement

#15252 [Home Page Picker] Poll while thumbnail is not generated
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collapsable Header Collection View Cell/CollapsableHeaderCollectionViewCell.swift
Labels: Part of a WIP Feature, Site Creation, [Type] Enhancement

#15300 Fix force-unwrapped optional for SuggestionsTableView in NotificationDetailsViewController
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
Labels: Notifications, [Type] Bug

#15299 Integrate gutenberg-mobile release 1.41.1
  .circleci/cache-version
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#15287 Jetpack section in My Site
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackConnectionViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackSettingsViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackSpeedUpSiteSettingsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack Mobile

#15312 Gutenberg related changes to land after 16.2 App cut
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergFilesAppMediaSource.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg integration

#15311 Merge 16.2 code freeze into develop
  .circleci/cache-version
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#15315 Reader: update header for P2 postcards to show author
  WordPress/Classes/ViewRelated/Reader/ReaderCellConfiguration.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
Labels: P2, [Type] Enhancement

#15302 Fix status bar override for app store screenshots
  Podfile
  Podfile.lock
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
Labels: Testing, Tooling, [Status] Needs Code Review

#15307 Reader Detail Post: Support common link protocols in post
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/URL+Helpers.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
Labels: Reader, [Type] Bug

#15310 Reader Detail Post: Support common link protocols in webview
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/WebKitViewController.swift
Labels: Reader, Webviews, [Type] Bug

#15316 Reader: Post and Cross Post Card code cleanup
  WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Labels: P2, [Type] Enhancement

#15318 Reader cross post card: Add border to avatar images.
  WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
Labels: Reader, [Type] Enhancement

#15320 Removes a bad workaround for an issue that was introduced in 16.0
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: [Type] Bug

#15321 Removes a bad workaround for an issue that was introduced in 16.0
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: [Type] Bug

#15322 Removes a bad workaround for an issue that was introduced in 16.0
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: [Type] Bug

#15325 My Sites: fix first site not selectable
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: My Site, [Type] Bug

#15327 My Sites: fix first site not selectable
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: [Type] Bug

#15328 My Sites: fix first site not selectable
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: [Type] Bug

#15293 [Home Page Picker] Connect Preview Button
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.xib
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Creation, [Type] Enhancement

#15346 Accessibility: add VoiceOver description to trash button in Media Details
  WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
Labels: Accessibility, VoiceOver, [Type] Bug

#15348 Adds some logging to try and narrow down a Media issue.
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Labels: [Type] Task

#15324 [Home Page Picker] Update the design of the “Choose a Domain” screen
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collabsable Header Filter Bar/CollapsableHeaderFilterBar.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/ErrorStates/InlineErrorRetryTableViewCell.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/ErrorStates/InlineErrorTableViewProvider.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressTableViewProvider.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Creation, [Status] Needs Design Review, [Type] Enhancement

#15349 [Home Page Picker] Move to Page sheet
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.xib
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/TitleSubtitleTextfieldHeader.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
Labels: Site Creation, [Type] Enhancement

#15345 Update stats in the iOS 14 today widget from the app
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/System/Constants.h
  WordPress/Classes/System/Constants.m
  WordPress/Classes/ViewRelated/Stats/Today Widgets/iOS 14 Widgets/HomeWidgetCache.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/iOS 14 Widgets/HomeWidgetTodayData.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressHomeWidgetToday/Model/TodayWidgetContent.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetMediumView.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetSmallView.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetView.swift
  WordPress/WordPressHomeWidgetToday/WordPressHomeWidgetToday.swift
Labels: [Type] Enhancement, iOS 14 Widgets

#15339 [Gutenberg] Adding upload processor for File block
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergFileUploadProcessor.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg integration

#15362 Analytics: Adds property to flag sites as blogs or p2s
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/WordPressTest/WPAppAnalyticsTests.m
Labels: Analytics, [Type] Enhancement

#15376 [Home Page Picker] Add the WP custom user agent to site creation webviews
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
Labels: Site Creation, [Type] Bug

#15365 [Home Page Picker] Add Template to Preview analytics
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
Labels: Site Creation, [Type] Enhancement

#15364 Issues/15352 comment analytics
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/ViewRelated/Comments/CommentAnalytics.swift
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Analytics, [Type] Enhancement

#15360 [Home Page Picker] Bug fixes
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
Labels: Site Creation, [Type] Bug

#15379 only show Jetpack Section title as "Jetpack" if it's a paid Jetpack site
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: Jetpack Mobile

#15380 Removing unnecessary print statements
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration, [Pri] High

#15317 Enable @-mentions on Atomic sites
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Atomic, Gutenberg integration, Mentions, [Type] Bug

#15303 [Home Page Picker] Enable Home Page Picker feature
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/AssembledSiteView.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/AddressCell.xib
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/WordPressTest/SiteCreation/SiteCreatorTests.swift
Labels: Site Creation, [Type] Enhancement

#15382 Remove `newReaderNavigation` feature flag.
  WordPress/Classes/Extensions/Notifications/NotificationName+Names.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLater+Analytics.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: New Reader iOS, Reader, [Type] Tech Debt

#15384 Updates the WordPressKit pod version.
  Podfile
  Podfile.lock
Labels: [Type] Enhancement

#15309 Issues/15266 fix preview url
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Utility/Networking/RequestAuthenticator.swift
  WordPress/Classes/ViewRelated/Post/Preview/PreviewNonceHandler.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostMenu.swift
Labels: [Type] Bug

#15383 Activity Log: change it to UIViewController and change ImmuTable to accepts VCs with tableView
  WordPress/Classes/Utility/ImmuTable.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
Labels: Activity Log, [Type] Task

#15392 Fix display of time picker for post scheduling on iOS 14
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift
Labels: Post Scheduling Enhancements, iOS 14

#15385 Update reference to WPAuthenticator
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: [Type] Task, dependencies

#15291 [Gutenberg] File block - Implementing WP media picker source
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergFilesAppMediaSource.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/StockPhotosStrings.swift
Labels: Gutenberg integration

#15395 Add xpost data model to Core Data
  MIGRATIONS.md
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/SiteSuggestion+CoreDataClass.swift
  WordPress/Classes/Models/SiteSuggestion+CoreDataProperties.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 103.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg compatibility, Gutenberg integration

#15398 Fix Jetpack header and add Whitelisted IPs tracking
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackSettingsViewController.swift
Labels: Jetpack, [Type] Bug

#15358 Localization: translation key exceeds character limit for GlotPress
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Site Management/StartOverViewController.swift
Labels: Localization, [Type] Bug

#15402 Revert "Add xpost data model to Core Data"
  MIGRATIONS.md
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/SiteSuggestion+CoreDataClass.swift
  WordPress/Classes/Models/SiteSuggestion+CoreDataProperties.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 103.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg compatibility, Gutenberg integration

#15403 Add xpost data model to Core Data
  MIGRATIONS.md
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/SiteSuggestion+CoreDataClass.swift
  WordPress/Classes/Models/SiteSuggestion+CoreDataProperties.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 103.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg compatibility, Gutenberg integration

#15375 Integrate gutenberg-mobile release 1.42.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#15391 Today Widget - Fetch remote stats
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/iOS 14 Widgets/HomeWidgetCache.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/iOS 14 Widgets/HomeWidgetData.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressHomeWidgetToday.xcscheme
  WordPress/WordPressHomeWidgetToday/Model/HomeWidgetTodayData.swift
  WordPress/WordPressHomeWidgetToday/Remote service/HomeWidgetTodayRemoteService.swift
  WordPress/WordPressHomeWidgetToday/Supporting Files/WordPressHomeWidgetToday.entitlements
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetView.swift
  WordPress/WordPressHomeWidgetToday/WordPressHomeWidgetToday.swift
Labels: [Type] Enhancement, iOS 14 Widgets

#15408 [Home Page Picker] Mark Theme Selection as Completed as part of the Site Creation Flow
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+QuickStart.swift
Labels: [Type] Enhancement

#15409 Merge 16.1.1 into trunk
  Scripts/fastlane/Deliverfile
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#15413 [Home Page Picker] Adjust Home Page Picker Image Ratio
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
Labels: Site Creation, [Type] Bug
