Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2020-10, with the labels that each got.

#14965 Reader: Support Stories in detail view
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderWebView.swift
Labels: Reader, WP Stories

#14917 Menu Section: VoiceOver improvements Mark II
  WordPress/Classes/ViewRelated/Menus/MenuDetailsViewController.m
  WordPress/Classes/ViewRelated/Menus/MenuItemAbstractView.m
  WordPress/Classes/ViewRelated/Menus/MenuItemView.m
Labels: Accessibility

#15021 Media Picker: Prevent crash when no access given to assets
  Podfile
  Podfile.lock
Labels: Media, iOS 14

#15023 What's New - Add accessibility
  WordPress/Classes/ViewRelated/What's New/Views/FindOutMoreCell.swift
  WordPress/Classes/ViewRelated/What's New/Views/WhatIsNewView.swift
Labels: What's New, [Type] Enhancement

#15011 Change CropViewController to 2.5.3 to remove a warning
  Podfile.lock
Labels: [Type] Task

#15031 Revert CropViewController Podfile.lock change
  Podfile.lock
Labels: [Type] Task

#15020 What's New - Show announcements only when needed; + unit tests
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/What's New/Data store/AnnouncementsStore.swift
  WordPress/Classes/ViewRelated/What's New/Data store/Cache/AnnouncementsCache.swift
  WordPress/Classes/ViewRelated/What's New/Dependency container/WPTabBarController+WhatIsNew.swift
  WordPress/Classes/ViewRelated/What's New/Presenter/WhatIsNewScenePresenter.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/What's New/Data store/AnnouncementsDataStoreTests.swift
Labels: What's New, [Type] Enhancement

#15018 UL&S: Implements re-authentication flow tracking.
  .circleci/cache-version
  Podfile.lock
  WordPress/Classes/System/WordPressAppDelegate.swift
Labels: Login, Unified Login & Signup

#15028 Updates to the screenshot generation test
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
  WordPress/WordPressUITests/Flows/LoginFlow.swift
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPressUITests/Screens/MySiteScreen.swift
  WordPress/WordPressUITests/Screens/ReaderScreen.swift
Labels: Testing

#15030 Use Reader V2 posts endpoint for topics
  Podfile.lock
  WordPress/Classes/Services/FollowCommentsService.swift
  WordPress/Classes/Services/ReaderCardService.swift
  WordPress/Classes/Services/ReaderPostService+PostsV2.swift
  WordPress/Classes/Services/ReaderPostService.h
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: New Reader iOS, [Type] Task

#15027 Reader: Fixes anchor links not responding to taps
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/URL+Helpers.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderWebView.swift
  WordPress/WordPressTest/ReaderDetailCoordinatorTests.swift
  WordPress/WordPressTest/ReaderDetailViewControllerTests.swift
Labels: Reader, [Type] Bug

#15008 Integrate gutenberg-mobile release 1.38.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#15034 enable what's new feature flag for all
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
Labels: What's New, [Type] Enhancement

#15036 Reader: change copy tags to topics
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/Manage/OffsetTableViewHandler.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderManageScenePresenter.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewController+Cells.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderMenuViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderMenuViewModel.swift
Labels: New Reader iOS, Reader, [Type] Task

#15039 Temporary code to gather information for fixing #14960
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Labels: Media, [Type] Task

#15041 Revert CropViewController manual update
  Podfile.lock
Labels: [Type] Task

#15040 Reader Improvements: Adds comment action to the bottom of the content
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.storyboard
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.xib
  WordPress/Classes/ViewRelated/Reader/ReaderCommentAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.h
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: New Reader iOS, Reader, [Type] Task

#15025 Added `Block site` and `Report post` to more menu in `Following` feed (only for sites you don't follow)
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
Labels: New Reader iOS, [Type] Enhancement

#14948 Update PostCategoriesViewController and WPCategoryTree to Swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
  WordPress/Classes/ViewRelated/Menus/MenuItemCategoriesViewController.m
  WordPress/Classes/ViewRelated/Post/Categories/PostCategoriesViewController.h
  WordPress/Classes/ViewRelated/Post/Categories/PostCategoriesViewController.m
  WordPress/Classes/ViewRelated/Post/Categories/PostCategoriesViewController.swift
  WordPress/Classes/ViewRelated/Post/Categories/WPAddPostCategoryViewController.m
  WordPress/Classes/ViewRelated/Post/Categories/WPCategoryTree.h
  WordPress/Classes/ViewRelated/Post/Categories/WPCategoryTree.m
  WordPress/Classes/ViewRelated/Post/Categories/WPCategoryTree.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Refactor, Tag/Category Management, [Type] Enhancement

#15029 WebView: Configure WKWebView to support inline media playback on iPhones
  WordPress/Classes/Utility/WebKitViewController.swift
Labels: WP Stories, [Type] Enhancement

#14987 [Modal Layout Picker] Cache the response of fetching the layout picker
  WordPress/Classes/Models/PageTemplateCategory+CoreDataClass.swift
  WordPress/Classes/Models/PageTemplateCategory+CoreDataProperties.swift
  WordPress/Classes/Models/PageTemplateLayout+CoreDataClass.swift
  WordPress/Classes/Models/PageTemplateLayout+CoreDataProperties.swift
  WordPress/Classes/Services/GutenbergLayouts.swift
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPreviewViewController.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 99.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Core Data, Gutenberg compatibility, Part of a WIP Feature, [Type] Enhancement

#15051 Reader Improvements Detail: Fixes some small issues
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: New Reader iOS, Reader, [Type] Task

#15045 Requests a larger site icon in the site stream header
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
Labels: Reader, [Type] Enhancement

#15035 [Gutenberg]: Update masked-view version
  .circleci/cache-version
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#14886 [Modal Layout Picker] Show toast messages after creating a new page
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg compatibility, Part of a WIP Feature, [Type] Enhancement

#15053 My Sites > no sites: show NRV on rotation
  WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Labels: [Type] Broken Window, [Type] Bug

#15038 [Modal Layout Picker] Add analytics metrics for the layout picker
  WordPress/Classes/Services/PageCoordinator.swift
  WordPress/Classes/Utility/Editor/EditorFactory.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPreviewViewController.swift
  WordPress/Classes/ViewRelated/Pages/EditPageViewController.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Analytics, Part of a WIP Feature, [Type] Enhancement

#15042 Remove the FAB + Me feature flags
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/Universal Links/Routes+Me.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController+UIViewControllerRestoration.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+MeNavigation.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: Information Architecture

#15055 Update screenshot test with new mocks
  Podfile
  Podfile.lock
  WordPress/Classes/Models/Notifications/Actions/ReplyToComment.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginEpilogueScreen.swift
  WordPress/WordPressUITests/Screens/NotificationsScreen.swift
  WordPress/WordPressUITests/Screens/StatsScreen.swift
  WordPress/WordPressUITests/Screens/TabNavComponent.swift
  WordPress/WordPressUITests/Tests/MainNavigationTests.swift
  WordPress/WordPressUITests/WPUITestCredentials.swift
Labels: Releases

#15063 Prologue Carousel: add a feature flag
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Login, Signup, [Type] Enhancement

#15058 Notifications: Don't dim the detail view when the filtered NRV is displayed.
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Labels: Notifications, iPad

#15066 Plugins: Attempts to resolve a crash by adding an extra session count check
  WordPress/Classes/ViewRelated/Plugins/PluginListViewController.swift
Labels: Jetpack Plugins, [Type] Bug, [Type] Crash

#15048 Moves settings button to the navigation bar from the tab bar
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/WordPressTest/ReaderTabViewModelTests.swift
  WordPress/WordPressTest/ReaderTabViewTests.swift
Labels: New Reader iOS, Reader, [Type] Task

#15068 Revert CropViewController manual update
  Podfile.lock
Labels: [Type] Task

#15071 Fixes some unit tests.
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: [Type] Task

#15050 Use correct analytics event for save draft action
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Labels: Analytics, [Type] Bug

#15070 Notifications > Jetpack install prompt: show view on rotation
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Labels: Notifications, [Type] Bug

#15069 Prologue Carousel: update headlines
  Podfile.lock
Labels: Login, Signup, [Type] Enhancement

#15065 Feature announcements improvements
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/What's New/Presenter/WhatIsNewScenePresenter.swift
  WordPress/Classes/ViewRelated/What's New/Views/FindOutMoreCell.swift
Labels: What's New, [Type] Enhancement

#15076 Add null check around date fetching in ReaderCommentCell
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
Labels: [Type] Crash

#15077 Merge 15.9 code freeze and release notes into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/What's New/Presenter/WhatIsNewScenePresenter.swift
  WordPress/Classes/ViewRelated/What's New/Views/FindOutMoreCell.swift
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#15061 Previews: Fix for previewing posts on sites with mapped domains.
  .circleci/cache-version
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Networking/RequestAuthenticator.swift
  WordPress/Classes/ViewRelated/Post/Preview/PreviewNonceHandler.swift
Labels: Previews, [Type] Enhancement

#15059 Bug fix to stock photo selection
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/StockPhotosPicker.swift
Labels: Media

#14988 Fix Gutenberg image block render in Xcode 12
  Podfile
  Podfile.lock
  patches/RN-RCTUIImageViewAnimated.patch
Labels: Gutenberg integration

#15010 Add support for dark mode screenshots
  Scripts/fastlane/ScreenshotFastfile
  Scripts/fastlane/Snapfile
  WordPress/WordPressScreenshotGeneration/SnapshotHelper.swift
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
  WordPress/WordPressUITests/Screens/ReaderScreen.swift
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Tooling, [Status] Needs Code Review

#15081 [iPad] No Sites: fix view sizes on rotation
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
  WordPress/Classes/ViewRelated/Views/NoResults.storyboard
Labels: NoResultsView, iPad

#15075 Small changes to try and fix a Media issue.
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
  WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
Labels: [Type] Bug

#15087 Use a default timestamp for custom Sentry event
  WordPress/Classes/Utility/Logging/SentryStartupEvent.swift
Labels: [Type] Bug

#15085 Enforce use of bundle exec in Fastfile+Podfile
  Podfile
  Podfile.lock
  Scripts/fastlane/Fastfile
Labels: Tooling

#15072 Reader Improvements Detail: Address design review feedback
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.xib
  WordPress/WordPressTest/ReaderDetailCoordinatorTests.swift
Labels: New Reader iOS, Reader, [Status] Needs Design Review

#14994 Modal Layout Picker Design Review Feedback fixes
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutFilterBar.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerFilterCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerFilterCollectionViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerStoryboard.storyboard
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPreviewViewController.swift
Labels: Part of a WIP Feature, [Type] Enhancement

#15099 Fix screenshot test for Russian & Thai
  Podfile
  Podfile.lock
  WordPress/WordPressUITests/Screens/Login/LoginUsernamePasswordScreen.swift
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Releases

#15097 Reader: Moves Select Interests to be displayed under the Discover tab
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderManageScenePresenter.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
Labels: New Reader iOS, [Type] Task

#15106 Pin CropViewController to 2.5.3
  Podfile
  Podfile.lock
Labels: [Type] Task

#15105 Fixes a memory leak with ImageDimensionsFetcher
  WordPress/Classes/Utility/Image Dimension Parser/ImageDimensionFetcher.swift
Labels: Reader, [Type] Bug

#14743 Use persistent storage for @-mentions suggestions
  MIGRATIONS.md
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Models/Suggestion.swift
  WordPress/Classes/Models/UserSuggestion+CoreDataClass.swift
  WordPress/Classes/Models/UserSuggestion+CoreDataProperties.swift
  WordPress/Classes/Models/UserSuggestion+ImageHelpers.swift
  WordPress/Classes/Services/SuggestionService.swift
  WordPress/Classes/ViewRelated/Comments/CommentViewController.swift
  WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
  WordPress/Classes/ViewRelated/SuggestionsTableView.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 100.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg integration, Mentions, Reader

#15107 Enable New Reader Detail
  WordPress/Classes/Extensions/Interpolation.swift
  WordPress/Classes/Utility/Image Dimension Parser/ImageDimensionFetcher.swift
  WordPress/Classes/Utility/Image Dimension Parser/ImageDimensionParser.swift
  WordPress/Classes/Utility/Media/ImageLoader.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.storyboard
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderScrollView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/reader.css
  WordPress/Classes/ViewRelated/Reader/ReaderCommentAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.h
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderFollowAction.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsCollectionViewFlowLayout.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/Classes/ViewRelated/Views/LinearGradientView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ImageDimensionParserTests.swift
  WordPress/WordPressTest/ReaderDetailCoordinatorTests.swift
  WordPress/WordPressTest/Test Images/100x100-png
  WordPress/WordPressTest/Test Images/100x100.gif
  WordPress/WordPressTest/Test Images/100x100.jpg
  WordPress/WordPressTest/Test Images/invalid-gif.gif
  WordPress/WordPressTest/Test Images/invalid-jpeg-header.jpg
  WordPress/WordPressTest/Test Images/valid-gif-header.gif
  WordPress/WordPressTest/Test Images/valid-jpeg-header.jpg
  WordPress/WordPressTest/Test Images/valid-png-header
Labels: New Reader iOS, Reader, [Type] Task

#15112 Update priority matrix and crash prioritization guidelines
  docs/issue-triage.md
Labels: Documentation

#15114 Update Release Notes to include Reader Detail Updates
  RELEASE-NOTES.txt
Labels: [Type] Enhancement

#15113 Remove Reader Improvements Phase 2 Feature Flag
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterSheetView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
Labels: Reader, [Type] Task

#14934 Update syntax to support multiple trailing closures
  WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
  WordPress/Classes/Utility/iAds/SearchAdsAttribution.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
Labels: Upgrades

#15083 Integrate gutenberg-mobile release 1.38.1
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#15115 Reader: Do not override images that already have an anchor link
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderWebView.swift
Labels: Reader, [Type] Bug

#15110 Stories: Feature Flag
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/System/WordPressAppDelegate+openURL.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FAB.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Media/MediaNoticeNavigationCoordinator.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Part of a WIP Feature, WP Stories

#15086 Integrate gutenberg-mobile release 1.39.0
  .circleci/cache-version
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#15116 Reader Improvements Phase 3: Adds recommended sites in the Discover feed
  MIGRATIONS.md
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Models/ReaderCard+CoreDataClass.swift
  WordPress/Classes/Models/ReaderCard+CoreDataProperties.swift
  WordPress/Classes/Models/ReaderSiteInfoSubscriptions.swift
  WordPress/Classes/Models/ReaderSiteTopic.swift
  WordPress/Classes/Services/ReaderCardService.swift
  WordPress/Classes/Services/ReaderTopicService+SiteInfo.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderRecommendedSiteCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderRecommendedSiteCardCell.xib
  WordPress/Classes/ViewRelated/Reader/ReaderSitesCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTableCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTopicsCardCell.swift
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 101.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderCardServiceTests.swift
  WordPress/WordPressTest/ReaderCardTests.swift
  WordPress/WordPressTest/Test Data/reader-cards-success.json
Labels: New Reader iOS, Reader, [Status] Needs Design Review, [Type] Task

#15117 Reader Detail: fix/add events
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.swift
Labels: Analytics, Reader, [Type] Task

#15118 Extracts the header and footer container from Modal Layout Picker to be reusable for the upcoming Home Page Picker
  WordPress/Classes/Models/PageTemplateCategory+CoreDataProperties.swift
  WordPress/Classes/Services/PageCoordinator.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/Collabsable Header Filter Bar/CollabsableHeaderFilterCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/Collabsable Header Filter Bar/CollabsableHeaderFilterCollectionViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/Collabsable Header Filter Bar/CollapsableHeaderFilterBar.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerStoryboard.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Part of a WIP Feature, [Type] Enhancement, [Type] Tech Debt

#14848 Update to Xcode 12
  .circleci/config.yml
  Scripts/fastlane/Fastfile
  WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
  WordPress/Classes/Utility/iAds/SearchAdsAttribution.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: Tooling

#15129 Adjust PageTemplateCategories to be associated to the Blog
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Models/PageTemplateCategory+CoreDataProperties.swift
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 102.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Part of a WIP Feature, [Type] Bug

#15134 Add back in the estimated heights cache
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: New Reader iOS, Reader, [Type] Bug

#15128 Stories: Removes "Story" Tooltip Notice & A11y stories hint of FAB
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
Labels: WP Stories

#15136 Fixes spinning wheel on top of blog list.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: [Type] Bug

#15131 New AddSiteAlertFactory convenience class.
  WordPress/Classes/ViewRelated/Blog/Add Site/AddSiteAlertFactory.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, [Type] Task

#15080 Fix some tracks events having user_id=0
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/NotificationSupportService.swift
  WordPress/Classes/System/Constants.h
  WordPress/Classes/System/Constants.m
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressShareExtension/Tracks.swift
Labels: Analytics

#15123 Add new AppID for iOS 14 Home Widget
  Scripts/fastlane/Fastfile
Labels: Tooling

#15135 Prepare suggestions to handle xposts
  WordPress/Classes/Models/UserSuggestion+ImageHelpers.swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableViewCell.h
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableViewCell.m
  WordPress/Classes/ViewRelated/SuggestionsTableView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg compatibility, Gutenberg integration

#15144 Fix reader_article_detail_more_tapped event
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostMenu.swift
Labels: Analytics, [Type] Task

#15145 Add "New" badge for Story post
  WordPress/Classes/ViewRelated/System/Action Sheet/ActionSheetViewController.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonActionSheet.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: WP Stories

#15143 Improves MySitesCoordinator.
  WordPress/Classes/Utility/Spotlight/SearchManager.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPressShareExtension/ShareNoticeNavigationCoordinator.swift
Labels: [Type] Task

#15147 Merge 16.0 Beta 2 into develop
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostMenu.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#15149 Adds the FAB to the Post and Page List screens
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FAB.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonActionSheet.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/SheetActions.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Information Architecture

#15137 [Modal Layout Picker] Retry view
  WordPress/Classes/Extensions/UIViewController+NoResults.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
Labels: [Type] Enhancement

#15141 Integrate gutenberg-mobile release 1.39.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#15154 Merge 16.0 release notes into develop
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#15132 iOS 14 Today Widget: Small Size UI
  Scripts/fastlane/Fastfile
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressHomeWidgetToday.xcscheme
  WordPress/WordPressHomeWidgetToday/Model/TodayWidgetContent.swift
  WordPress/WordPressHomeWidgetToday/Supporting Files/WordPressHomeWidgetTodayRelease-Alpha.entitlements
  WordPress/WordPressHomeWidgetToday/Supporting Files/WordPressHomeWidgetTodayRelease-Internal.entitlements
  WordPress/WordPressHomeWidgetToday/Supporting Files/WordPressHomeWidgetTodayRelease.entitlements
  WordPress/WordPressHomeWidgetToday/View/TodayWidgetView.swift
  WordPress/WordPressHomeWidgetToday/WordPressHomeWidgetToday.swift
Labels: [Type] Enhancement, iOS 14 Widgets

#15156 Fixes showCreateButton method calls
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: [Pri] Blocking

#15150 Removes some duplicated methods.
  WordPress/Classes/Utility/Spotlight/SearchManager.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPressShareExtension/ShareNoticeNavigationCoordinator.swift
Labels: [Type] Task

#15160 Resolves issue where extra space was being added to the scrollable area
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/CollapsableHeaderViewController.swift
Labels: [Type] Bug, iPad

#15109 Add accessibility label for media share button
  WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
Labels: VoiceOver

#15170 CONTRIBUTING.md: Add information about or PR merge policy
  CONTRIBUTING.md
Labels: Documentation, Tooling

#15126 Migrate fetching of Page Layouts call from WPiOS to WPKit
  Podfile
  Podfile.lock
  WordPress/Classes/Models/PageTemplateCategory+CoreDataProperties.swift
  WordPress/Classes/Models/PageTemplateLayout+CoreDataProperties.swift
  WordPress/Classes/Services/GutenbergLayouts.swift
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Tech Debt

#15174 Add translations download on new beta releases
  Scripts/fastlane/Fastfile
Labels: Tooling

#15057 Update LayoutChanged notification
  WordPress/Classes/ViewRelated/Menus/MenusSelectionView.m
Labels: Accessibility, Menus, [Type] Bug

#15175 Update Modal Layout Picker Preview Bar to use the Light Navigation Style
  WordPress/Classes/Services/PageCoordinator.swift
Labels: [Type] Bug

#15176 [Home Page Picker] Create Base Container for step 1 of the site creation
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/CollapsableHeader/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.xib
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignStep.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Part of a WIP Feature, [Type] Enhancement

#15151 Adds the medium size iOS 14 Today Widget
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressHomeWidgetToday/View/TodayWidgetView.swift
  WordPress/WordPressHomeWidgetToday/Views/Cards/FlexibleCard.swift
  WordPress/WordPressHomeWidgetToday/Views/Cards/VerticalCard.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetMediumView.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetSmallView.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetView.swift
  WordPress/WordPressHomeWidgetToday/WordPressHomeWidgetToday.swift
Labels: [Type] Enhancement, iOS 14 Widgets

#15181 Remove trailing whitespaces from Fastfile
  Scripts/fastlane/Fastfile
Labels: Tooling

#15183 Track Cards API response
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
Labels: Analytics, Reader, [Type] Task

#15185 Today widgets: fix translations
  RELEASE-NOTES.txt
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressAllTimeWidget/Base.lproj/Localizable.strings
  WordPress/WordPressThisWeekWidget/Base.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/Base.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ar.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/bg.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/cs.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/cy.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/da.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/de.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-AU.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-CA.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-GB.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/es.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/fr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/he.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/hr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/hu.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/id.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/is.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/it.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ja.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ko.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/nb.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/nl.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pl.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pt-BR.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pt.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ro.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ru.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sk.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sq.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sv.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/th.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/tr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/zh-Hans.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/zh-Hant.lproj/Localizable.strings
Labels: Stats Widgets, [Type] Bug

#15186 iOS14 Today widget: add localizations and RTL support
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressHomeWidgetToday/Views/Cards/VerticalCard.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetSmallView.swift
Labels: Localization, [Type] Enhancement, iOS 14 Widgets

#15166 Integrate gutenberg-mobile release 1.40.0
  .circleci/cache-version
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#15188 Workaround for a crashing bug with Bulgarian keyboards.
  WordPress/Classes/Extensions/UITextField+WorkaroundContinueIssue.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Bug, [Type] Crash, iOS 14

#15194 iOS14 Today widget: combine stat title and value in accessibility label
  WordPress/WordPressHomeWidgetToday/Views/Cards/VerticalCard.swift
Labels: Accessibility, [Type] Enhancement, iOS 14 Widgets

#15195 Feature/15104 today widget data
  Podfile
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressHomeWidgetToday/Model/TodayWidgetContent.swift
  WordPress/WordPressHomeWidgetToday/Supporting Files/WordPressHomeWidgetToday-Bridging-Header.h
  WordPress/WordPressHomeWidgetToday/Supporting Files/WordPressHomeWidgetToday.entitlements
  WordPress/WordPressHomeWidgetToday/Supporting Files/WordPressHomeWidgetTodayRelease.entitlements
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetMediumView.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetSmallView.swift
  WordPress/WordPressHomeWidgetToday/Views/TodayWidgetView.swift
  WordPress/WordPressHomeWidgetToday/WordPressHomeWidgetToday.swift
Labels: [Type] Enhancement, iOS 14 Widgets
