Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2020-08, with the labels that each got.

#14558 ULS: Update Auth to use new password view
  Podfile.lock
Labels: Login, [Type] Enhancement

#14554 Update Discover section when new interests are selected
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderInterestsCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: New Reader iOS, Reader, [Type] Bug

#14557 add ghost view on reader tab bar at the first load
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
Labels: Reader, [Type] Bug

#14563 Removes a silent failure.
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/MediaService.h
Labels: [Type] Bug

#14566 Ensure cookies for private sites when using the Reader
  WordPress/Classes/ViewRelated/Reader/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailWebviewViewController.swift
Labels: Reader, [Type] Bug

#14569 Enable @mentions feature in all flavors for version 15.4
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Posting/Editing

#14567 ULS: Update Auth to use new Password view with content
  Podfile.lock
Labels: Login, [Type] Enhancement

#14562 UL&S: Sign up: send magic link
  Podfile.lock
Labels: Login, [Status] Needs Code Review, [Status] Needs Design Review, [Type] Enhancement

#14519 Update/translation review builds version
  .circleci/config.yml
Labels: Tooling

#14571 Remove old Reader Detail and webview feature flag
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.storyboard
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderScrollView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/OfflineReaderWebView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderCSS.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderWebView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/reader.css
  WordPress/Classes/ViewRelated/Reader/Reader.storyboard
  WordPress/Classes/ViewRelated/Reader/ReaderCardDiscoverAttributionView.xib
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderDetailCoordinatorTests.swift
  WordPress/WordPressTest/ReaderDetailViewControllerTests.swift
  WordPress/WordPressTest/ReaderDetailWebviewViewControllerTests.swift
Labels: New Reader iOS, [Type] Task

#14576 Default Modal layout picker to off
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Gutenberg compatibility

#14573 ULS: update Auth to show email and gravatar on Password view
  Podfile
  Podfile.lock
Labels: Login, [Type] Enhancement

#14587 Add what's new feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: What's New

#14577 [Gutenberg] Fix ghost/loading view position
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#14589 ULS: update Auth to use functional Password view
  Podfile.lock
Labels: Login, [Type] Enhancement

#14582 Follow topics while logged out
  WordPress/Classes/Models/ReaderTagTopic.swift
  WordPress/Classes/Services/ReaderTopicService+FollowedInterests.swift
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
Labels: Reader, [Type] Task

#14593 Implements Google unified Sign In flow tracking.
  Podfile.lock
Labels: Login, [Type] Enhancement

#14598 Add hit area to suggestions UI to allow dismissing on smaller devices
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMentionsViewController.swift
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
Labels: [Type] Bug

#14599 Integrate gutenberg release 1.33.1
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMentionsViewController.swift
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
Labels: Gutenberg integration

#14600 Fixes some issues with the basic Google Authentication flow tracking.
  Podfile
  Podfile.lock
Labels: [Type] Bug

#14565 Integrate gutenberg release 1.34.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/MediaService.h
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMentionsViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Gutenberg integration

#14607 Updates tracks version.
  Podfile
  Podfile.lock
Labels: [Type] Task

#14601 Present Select Interests fullscreen
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.xib
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/WordPressTest/ReaderTabItemsStoreTests.swift
  WordPress/WordPressTest/ReaderTabViewModelTests.swift
Labels: New Reader iOS, [Type] Task

#14588 UL&S: VoiceOver support for site address flow
  Podfile
  Podfile.lock
  WordPress/Classes/Extensions/CollectionType+Helpers.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Login, VoiceOver, [Type] Enhancement

#14604 Disable old tracking events for Google Sign In
  Podfile.lock
Labels: [Type] Enhancement

#14621 Update Follow button UI
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Labels: New Reader iOS, [Type] Enhancement

#14622 Fix/site header layout fixes
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
Labels: Layout, New Reader iOS

#14597 Add What's New entry in App Settings
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/What's New/WhatIsNewViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: What's New, [Type] Enhancement

#14636 Rename Contact Us to Contact Support
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: Zendesk, [Type] Enhancement

#14613 UL&S: TwoFAViewController: add VoiceOver support
  Podfile.lock
Labels: Accessibility, Login, VoiceOver

#14626 Social account logins: Don't update username when using a password manager.
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Bug

#14637 ULS: use Password view with password manager support
  Podfile.lock
Labels: Login, [Type] Enhancement

#14642 New Reader: fix Quick Start
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
Labels: New Reader iOS, Quick Start, [Type] Task

#14645 Reader Improvements Phase 2: Adds a tags chips group to the top of the reader card cell
  WordPress/Classes/Models/PostContentProvider.h
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCellConfiguration.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsCollectionViewFlowLayout.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsStyleGuide.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/DynamicHeightCollectionView.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/ReaderTopicCollectionViewCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/TopicsCollectionView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: New Reader iOS, Reader

#14633 UL&S: SignupMagicLinkViewController: display the "magic link sent" UI
  Podfile.lock
Labels: Login, Signup, [Type] Enhancement

#14619 New Reader: add Tracks
  WordPress/Classes/Services/ReaderTopicService+Subscriptions.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Reader/ReaderBlockSiteAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShareAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderVisitSiteAction.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
Labels: Analytics, New Reader iOS, Reader, [Type] Task

#14647 ULS: update Auth to show new Password and 2FA views in SIWA path
  Podfile.lock
Labels: Login, [Type] Enhancement

#14615 Merge 15.5 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#14653 Merge 15.5 release notes into develop
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
  WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.xib
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#14627 Reader: fix unfollowed sites not being removed from list of followed sites
  WordPress/Classes/Services/ReaderTopicService.h
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/WordPressTest/ReaderTopicServiceTest.swift
Labels: Reader, [Type] Bug

#14658 Fix/unfollowed sites not removed
  WordPress/Classes/Services/ReaderTopicService.h
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/WordPressTest/ReaderTopicServiceTest.swift
Labels: Reader, [Type] Task

#14651 ULS Password: update Auth to use 1Password button action
  Podfile
  Podfile.lock
Labels: Login, [Type] Enhancement

#14652 ULS Password view: update Auth to add VoiceOver support
  Podfile.lock
Labels: Login, VoiceOver, [Type] Enhancement

#14611 Additional tracking for Google Sign In.
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
Labels: Login

#14641 [Reader P2 follow conversations] add button in comments view
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.h
  WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.m
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
Labels: Comments, Reader, [Type] Task

#14661 Reader Improvements: Fix Discover indefinite ghost mode
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
Labels: New Reader iOS, Reader, [Type] Bug

#14667 Reader Improvements Phase 2: Add random posts on pull to refresh support
  Podfile
  Podfile.lock
  WordPress/Classes/Services/ReaderCardService.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
Labels: New Reader iOS, Reader, [Type] Task

#14662 Completes Google tracking for UL&S
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
Labels: Login

#14671 Integrate gutenberg release 1.33.2
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#14673 Integrate gutenberg release 1.34.1
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#14669 Reader Improvements Phase 2: Merge reader cards branch into develop
  Podfile
  Podfile.lock
  WordPress/Classes/Models/PostContentProvider.h
  WordPress/Classes/Models/ReaderCard+CoreDataClass.swift
  WordPress/Classes/Models/ReaderCard+CoreDataProperties.swift
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/Models/ReaderTagTopic.swift
  WordPress/Classes/Services/ReaderCardService.swift
  WordPress/Classes/Services/ReaderTopicService+FollowedInterests.swift
  WordPress/Classes/Services/ReaderTopicService+Subscriptions.swift
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartTours.swift
  WordPress/Classes/ViewRelated/Reader/ReaderBlockSiteAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCellConfiguration.swift
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderInterestsCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.xib
  WordPress/Classes/ViewRelated/Reader/ReaderShareAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Ghost.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTopicsCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderVisitSiteAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderWelcomeBanner.swift
  WordPress/Classes/ViewRelated/Reader/ReaderWelcomeBanner.xib
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsCollectionViewFlowLayout.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsStyleGuide.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.xib
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/DynamicHeightCollectionView.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/ReaderTopicCollectionViewCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/TopicsCollectionView.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 98.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderCardServiceTests.swift
  WordPress/WordPressTest/ReaderCardTests.swift
  WordPress/WordPressTest/ReaderSelectInterestsCoordinatorTests.swift
  WordPress/WordPressTest/ReaderTabItemsStoreTests.swift
  WordPress/WordPressTest/ReaderTabViewModelTests.swift
  WordPress/WordPressTest/ReaderWelcomeBannerTests.swift
  WordPress/WordPressTest/Test Data/reader-cards-success.json
Labels: New Reader iOS, Reader, [Type] Task

#14553 [Modal Layout Picker] Create sections and thumbnail UI using static data
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLightNavigationController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerCollectionViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerStoryboard.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg compatibility, [Type] Enhancement

#14682 Reset the isExpanded flag on reuse
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/ReaderTopicCollectionViewCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/TopicsCollectionView.swift
Labels: New Reader iOS, Reader, [Type] Bug

#14657 Fix site header is not updated when follow / unfollow from post actions
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.xib
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: New Reader iOS, [Type] Bug

#14672 Add view elements to WhatIsNewView
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/What's New/WPTabBarController+WhatIsNew.swift
  WordPress/Classes/ViewRelated/What's New/WhatIsNewView.swift
  WordPress/Classes/ViewRelated/What's New/WhatIsNewViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: What's New, [Type] Enhancement

#14677 Update Core Data model minimum tools version
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 98.xcdatamodel/contents
Labels: Core Data

#14685 Updating podfile.lock
  Podfile.lock
Labels: [Type] Bug

#14678 Merge 15.5 beta 2 into develop
  RELEASE-NOTES.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#14664 ULS: update Auth to show unified 2FA view in Site Address flow.
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Login, [Type] Enhancement

#14670 ULS: update Auth to remove the Waiting for Google view from the navigation stack.
  Podfile.lock
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Login, [Type] Enhancement

#14676 ULS: Update Auth to show updated Social Error view appearance
  Podfile.lock
Labels: Login, [Type] Enhancement

#14686 Fix upload for HEIC files (live photos)
  WordPress/Classes/Services/MediaService.m
Labels: Media, [Type] Bug

#14692 Update MIGRATIONS.md
  MIGRATIONS.md
Labels: Documentation, [Type] Task

#14655 [Reader P2 follow conversations] hookup subscription endpoints
  Podfile
  Podfile.lock
  WordPress/Classes/Services/FollowCommentsService.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.h
  WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/FollowCommentsServiceTests.swift
Labels: Comments, Reader, [Type] Task

#14691 Remove heic from the allowed list of files
  WordPress/Classes/Services/MediaService.m
Labels: Media, [Type] Bug

#14668 Use `main` branch for mobile secrets
  .configure
Labels: [Type] Enhancement

#14665 Integrate gutenberg-mobile release 1.35.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#14696 ULS Site Address: fixing UI tests
  Podfile.lock
  WordPress/WordPressUITests/Screens/Login/LoginSiteAddressScreen.swift
  WordPress/WordPressUITests/Screens/Login/LoginUsernamePasswordScreen.swift
Labels: Testing, [Type] Enhancement

#14732 What's New: header and version scroll with content
  WordPress/Classes/ViewRelated/What's New/Dependency container/WPTabBarController+WhatIsNew.swift
  WordPress/Classes/ViewRelated/What's New/Views/WhatIsNewView.swift
Labels: What's New, [Type] Enhancement

#14639 Improve VoiceOver integration in Menus section - Mark I
  WordPress/Classes/ViewRelated/Menus/MenuHeaderViewController.m
  WordPress/Classes/ViewRelated/Menus/MenusSelectionDetailView.m
  WordPress/Classes/ViewRelated/Menus/MenusSelectionItemView.m
  WordPress/Classes/ViewRelated/Menus/MenusSelectionView.m
Labels: Menus, VoiceOver

#14740 Merge 15.6 code freeze into develop
  .circleci/cache-version
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#14721 Reader P2: Follow/Unfollow comments capability
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Models/ReaderPost+Blog.swift
  WordPress/Classes/Services/FollowCommentsService.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.h
  WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.m
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/FollowCommentsServiceTests.swift
Labels: Comments, Reader, [Type] Task

#14735 Reader Improvements Phase 2: Fixes a potential crash
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsCollectionViewFlowLayout.swift
Labels: New Reader iOS, Reader, [Type] Bug

#14753 Update cards when performing actions on post card
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: New Reader iOS, [Type] Bug

#14742 ULS Site Address: show unified view from "add self-hosted" links
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
Labels: Self-hosted, [Type] Enhancement

#14749 UL&S: Tracks: rename step `username_password` to `password_challenge`
  Podfile
  Podfile.lock
Labels: Analytics, Login, [Type] Bug

#14752 UL&S: Password challenge bugfix
  Podfile
  Podfile.lock
Labels: Login, [Type] Bug

#14761 Change Reader Improvements Phase 2 events
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
Labels: Analytics, New Reader iOS, [Type] Task

#14757 ULS: show initial Get Started view
  Podfile.lock
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Unified Login & Signup, [Type] Enhancement

#14755 Reader Improvements: Removes background from the 'hide' chip
  WordPress/Classes/Models/ReaderCard+CoreDataClass.swift
  WordPress/Classes/Models/ReaderTagTopic.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/ReaderTopicCollectionViewCoordinator.swift
Labels: New Reader iOS, Reader, [Status] Needs Design Review, [Type] Task

#14760 UL&S iCloud Keychain: Add feature flag, implement basic UI
  Podfile.lock
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Login, Unified Login & Signup

#14631 [Modal Layout Picker] Create Layout Picker category bar UI using static data
  WordPress/Classes/Services/PageCoordinator.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutFilterBar.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerCategoryCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerFilterCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerFilterCollectionViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerStoryboard.storyboard
  WordPress/Launch Screen.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg compatibility, [Status] Needs Design Review, [Type] Enhancement

#14773 Hide the tab bar when presenting Reader Detail
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: New Reader iOS, [Type] Task

#14763 ULS Site Address: Updated release note.
  RELEASE-NOTES.txt
Labels: Unified Login & Signup, [Type] Enhancement

#14764 UL&S: PasswordViewController: send magic link
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Login, [Type] Enhancement

#14769 ULS Get Started: show Terms of Service
  Podfile.lock
Labels: Unified Login & Signup, [Type] Enhancement

#14771 ULS Get Started: show Email Address field
  Podfile.lock
Labels: Unified Login & Signup, [Type] Enhancement

#14738 What's New: Add chrome material background to the "Continue" button
  WordPress/Classes/ViewRelated/What's New/Views/WhatIsNewView.swift
Labels: What's New, [Type] Enhancement

#14770 UL&S iCloud Keychain: Simple successful login path
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Login, Unified Login & Signup

#14772 Fixes an issue with the save password prompt.
  Podfile.lock
Labels: Login, Unified Login & Signup, [Type] Bug

#14777 Fix empty notifications on release builds failures
  .circleci/config.yml
Labels: Tooling

#14782 Merge 15.6 Release Notes and fixes
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#14654 Display basic user profile on avatar tap
  Podfile
  Podfile.lock
  WordPress/Classes/Models/GravatarProfile.swift
  WordPress/Classes/Services/GravatarService.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Basic Profile/BasicUserProfile.storyboard
  WordPress/Classes/ViewRelated/Basic Profile/BasicUserProfileViewController.swift
  WordPress/Classes/ViewRelated/Basic Profile/BasicUserProfileViewModel.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/FormattableUserContent.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/FormattableUserContentTests.swift
Labels: User Profiles, [Type] Enhancement

#14781 ULS: show correct nav bar colors in iOS12
  Podfile
  Podfile.lock
Labels: Unified Login & Signup, [Type] Bug

#14783 UL&S iCloud Keychain: implements 2FA support.
  Podfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Login, Unified Login & Signup

#14699 [Modal Layout Picker] Populate UI for WPCOM sites with data from the API
  Podfile
  Podfile.lock
  WordPress/Classes/Services/GutenbergLayouts.swift
  WordPress/Classes/Services/PageCoordinator.swift
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutFilterBar.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerFilterCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerFilterCollectionViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerSectionTableViewCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg compatibility, [Type] Enhancement

#14788 Update Reader Detail's header
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.storyboard
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderScrollView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/reader.css
  WordPress/Classes/ViewRelated/Reader/ReaderFollowAction.swift
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderDetailCoordinatorTests.swift
Labels: Reader, [Status] Needs Design Review, [Type] Task

#14800 ULS Get Started: show Continue button
  Podfile.lock
Labels: Unified Login & Signup, [Type] Enhancement
