Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2020-04, with the labels that each got.

#13773 Ensure non-null Blog url before search
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blog.m
Labels: [Type] Bug

#13733 Remove the .showSignupMethod segue and replace with programmatic nav
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#13782 Add "Visibility" option
  WordPress/Classes/Models/AbstractPost+TitleForVisibility.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/PostVisibilitySelectorViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PasswordAlertController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Prepublishing Nudges, [Type] Task

#13793 Stats Period: light/dark mode ghost colors
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/GhostViews/StatsGhostCells.swift
Labels: Dark mode, Stats

#13797 Add Share action into post "more" button in the Posts list
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/InteractivePostViewDelegate.swift
  WordPress/Classes/ViewRelated/Post/PostActionSheet.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/WordPressTest/PostActionSheetTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
Labels: [Type] Enhancement

#13800 Creates a reusable modal bottom drawer sheet
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Bottom Sheet/BottomSheetViewControllerTests.swift
Labels: Prepublishing Nudges, [Type] Task

#13785 Testing: Make UI tests optional on PRs
  .circleci/config.yml
Labels: Testing

#13804 Add Share action into post "more" button in the Posts list
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/InteractivePostViewDelegate.swift
  WordPress/Classes/ViewRelated/Post/PostActionSheet.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/WordPressTest/PostActionSheetTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
Labels: [Type] Enhancement

#13805 Reader detail: fix background colors when switching appearance
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
Labels: Dark mode, Reader

#13778 Uses reader Topics to populate the new Reader Tab Bar
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderSection.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItem.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/System/FilterTabBar.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Information Architecture, Reader, [Type] Enhancement

#13812 Schedule post in the Nudges view
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController+PresentFrom.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Prepublishing Nudges, [Type] Task

#13796 Change iPad Post Preview presentation to fullscreen
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Spotlight/SearchManager.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
  WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
  WordPress/Classes/ViewRelated/Post/PostNoticeNavigationCoordinator.swift
Labels: Previews

#13808 Safely unwrap searchController in Posts List
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Labels: [Type] Crash

#13786 Remove the .show2FA segue and replace with programmatic nav
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#13809 Display Cancel button in "Other Apps" media browser
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergFilesAppMediaSource.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
Labels: Media, [Status] Needs Design Review, [Type] Bug

#13820 Update dependencies for release
  Podfile
  Podfile.lock
Labels: Releases

#13824 Testing: Disable tab bar navigation test due to unexpected failures
  WordPress/WordPressUITests/WordPressUITests.xctestplan
Labels: Testing

#13813 Adds MediaRequestAuthenticator.
  WordPress/Classes/Extensions/URL+Helpers.swift
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/Models/ReaderPostContentProvider.h
  WordPress/Classes/Networking/MediaHost+AbstractPost.swift
  WordPress/Classes/Networking/MediaHost+Blog.swift
  WordPress/Classes/Networking/MediaHost+ReaderPostContentProvider.swift
  WordPress/Classes/Networking/MediaHost.swift
  WordPress/Classes/Networking/MediaRequestAuthenticator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MediaHostTests.swift
  WordPress/WordPressTest/MediaRequestAuthenticatorTests.swift
  WordPress/WordPressTest/ReaderPostCardCellTests.swift
Labels: Atomic, [Type] Task

#13814 Login Epilogue: adjust table cells for dynamic text
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueBlogCell.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
Labels: Login

#13827 Sign up coming from Jetpack install flow causes black screen
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Jetpack, Login, [Type] Bug

#13829 Add Tenor feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Tenor

#13822 Merge Release/14.6 back into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#13821 Adapt the Bottom Sheet for Landscape
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
Labels: Prepublishing Nudges, [Type] Task

#13837 Drawer Presentation Controller
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#13817 Atomic Private Sites: add support for downloading the site icon.
  Podfile
  Podfile.lock
  WordPress/Classes/Extensions/AbstractPost+PostInformation.swift
  WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
  WordPress/Classes/Models/AbstractPost.h
  WordPress/Classes/Models/AbstractPost.m
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/Services/MediaThumbnailService.swift
  WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
  WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
  WordPress/Classes/ViewRelated/Post/PostPreviewGenerator.swift
Labels: Atomic, [Type] Enhancement

#13838 Change navigation header
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: Prepublishing Nudges, [Type] Task

#13847 Changes the auth-proxy path.
  WordPress/Classes/Networking/MediaRequestAuthenticator.swift
Labels: Atomic, [Type] Task

#13850 Merge Release/14.6 into develop
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#13841 Fix action sheet position for additional Media sources picker on iPad
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
Labels: Media

#13770 Add authentication support to image downloads for Atomic Private Sites.
  Podfile
  Podfile.lock
  WordPress/Classes/Extensions/AbstractPost+PostInformation.swift
  WordPress/Classes/Extensions/Blog+ImageSourceInformation.swift
  WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
  WordPress/Classes/Models/AbstractPost+Autosave.swift
  WordPress/Classes/Models/AbstractPost+Local.swift
  WordPress/Classes/Models/ReaderCardContent+PostInformation.swift
  WordPress/Classes/Networking/MediaHost+ReaderPostContentProvider.swift
  WordPress/Classes/Networking/MediaHost.swift
  WordPress/Classes/Services/MediaThumbnailService.swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/Utility/Media/ImageDownloader.swift
  WordPress/Classes/Utility/Media/ImageLoader.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.h
  WordPress/Classes/ViewRelated/Cells/PostFeaturedImageCell.m
  WordPress/Classes/ViewRelated/Gutenberg/AztecAttachmentDelegate.swift
  WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergMediaEditorImage.swift
  WordPress/Classes/ViewRelated/Post/PostCardCell.swift
  WordPress/Classes/ViewRelated/Post/PostCompactCell.swift
  WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.h
  WordPress/Classes/ViewRelated/Post/PrivateSiteURLProtocol.m
  WordPress/Classes/ViewRelated/Post/Revisions/Browser/Preview/RevisionPreviewTextViewManager.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextImage.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MediaHostTests.swift
Labels: Atomic

#13844 Fix new tab selection logic in WPTabBar
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: [Type] Bug

#13842 Tenor API credentials support
  WordPress/Credentials/ApiCredentials.h
  WordPress/Credentials/ApiCredentials.m
  WordPress/Credentials/gencredentials.rb
  WordPress/Credentials/wpcom_app_credentials-example
Labels: Tenor, [Type] Task, gif support

#13843 Implement Tenor client api
  WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorClient.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorGIF.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorGIFCollection.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorMediaObject.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorReponseParser.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorResponse.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MediaPicker/Tenor/TenorAPIResponseTests.swift
  WordPress/WordPressTest/MediaPicker/Tenor/TenorReponseData.swift
Labels: Tenor, [Type] Task, gif support

#13831 Wires site_is_atomic from the reader endpoint.
  Podfile
  Podfile.lock
  WordPress/Classes/Models/ReaderPost.h
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/ViewRelated/Reader/ReaderCrossPostCell.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 95.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Atomic, [Type] Task

#13851 Prepublishing Nudges Accessibility Improvements
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.xib
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PrepublishingHeaderViewTests.swift
Labels: Accessibility, Prepublishing Nudges, [Type] Task

#13828 Remove segue `showSigninV2`
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Signup, [Type] Enhancement

#13865 Merge/release 14.6 into develop
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#13840 Adds Reader Stream to the new Reader
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/WPContentSyncHelper.swift
  WordPress/Classes/ViewRelated/Reader/NewsCard.xib
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/System/FilterTabBar.swift
  WordPress/Classes/ViewRelated/Views/NoResults.storyboard
Labels: Information Architecture, New Reader iOS, Reader

#13853 Fix UI tests and remove "Publish with confidence" dialog
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/PostEditorState.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+Async.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+SavedPosts.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Screens/Editor/AztecEditorScreen.swift
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
Labels: Prepublishing Nudges, Testing, [Type] Task

#13877 Changes grip button margin
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: Prepublishing Nudges, [Type] Task

#13874 Fixes loading issues in the new Reader
  WordPress/Classes/Utility/WPContentSyncHelper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: Information Architecture, New Reader iOS, [Type] Bug

#13880 Fix crash on Bottom Sheet
  WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
Labels: Prepublishing Nudges, [Type] Bug

#13894 WPAuthenticator: Make Sign Up primary prologue button
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, NUX, Signup

#13881 Adapt Nudges view for iPad
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.xib
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: Prepublishing Nudges, [Type] Task

#13896 Remove the .showURLUsernamePassword segue and replace with navController
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#13882 Remove post reblogging feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/WordPressTest/ReaderDetailViewControllerTests.swift
  WordPress/WordPressTest/ReaderPostCardCellTests.swift
Labels: Post Reblogging

#13860 Login Epilogue: adjust table width for iPad
  WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.xib
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueConnectSiteCell.xib
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Labels: Login

#13861 Implement Tenor picker
  WordPress/Classes/Services/MediaImportService.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
  WordPress/Classes/ViewRelated/Media/Tenor/NoResultsTenorConfiguration.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorDataLoader.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorDataSource.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorMedia.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorMediaGroup.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorPageable.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorPicker.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorResultsPage.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorService.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorStrings.swift
  WordPress/Resources/AppImages.xcassets/tenor-attribution.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/tenor-attribution.imageset/tenor-attribution.png
  WordPress/Resources/AppImages.xcassets/tenor-attribution.imageset/tenor-attribution@2x.png
  WordPress/Resources/AppImages.xcassets/tenor-attribution.imageset/tenor-attribution@3x.png
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MediaPicker/Tenor/MockTenorService.swift
  WordPress/WordPressTest/MediaPicker/Tenor/TenorAPIResponseTests.swift
  WordPress/WordPressTest/MediaPicker/Tenor/TenorDataSouceTests.swift
  WordPress/WordPressTest/MediaPicker/Tenor/TenorMockDataHelper.swift
  WordPress/WordPressTest/MediaPicker/Tenor/TenorPageableTests.swift
  WordPress/WordPressTest/MediaPicker/Tenor/TenorReponseData.swift
  WordPress/WordPressTest/MediaPicker/Tenor/TenorResultsPageTests.swift
  WordPress/WordPressTest/Test Data/tenor-invalid-search-reponse.json
  WordPress/WordPressTest/Test Data/tenor-search-response.json
Labels: Tenor

#13869 Constraint Quick Actions Max Width
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Labels: [Status] Needs Design Review, [Type] Bug

#13907 Tenor picker for Media library
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorStrings.swift
Labels: Tenor

#13910 Tenor GIF picker for Gutenberg editor
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergTenorMediaPicker.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorPicker.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tenor

#13908 Tenor Picker support for Aztec editor
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift
Labels: Tenor

#13810 Testing: Use Fastlane for CI test runs with retries
  .circleci/config.yml
  Gemfile.lock
  Scripts/fastlane/Fastfile
  Scripts/fastlane/Pluginfile
Labels: Testing, [Status] Needs Code Review

#13878 Gutenberg: update to v1.26.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#13912 Update release-toolkit
  Gemfile.lock
  Scripts/fastlane/Pluginfile
Labels: Tooling

#13905 Prepublishing Nudges Tracks
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
Labels: Analytics, Prepublishing Nudges, [Type] Task

#13897 Add Saved Posts to the new Reader
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLater+Analytics.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: Information Architecture, New Reader iOS, [Type] Enhancement

#13904 UL&S: Remove .showSelfHostedLogin segue and replace with navController
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#13914 Login Epilogue: accessibility
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueConnectSiteCell.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
Labels: Login

#13899 Show standard notice for network errors on the Media Library
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
Labels: [Type] Bug

#13913 Testing: Save test output with updated CircleCI Orb
  .circleci/config.yml
Labels: Testing

#13922 Check sections count before accessing section 0
  WordPress/Classes/ViewRelated/Plugins/PluginListViewController.swift
Labels: [Type] Crash

#13926 Update My Sites tab title to My Site
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: General

#13916 Design improvements
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PasswordAlertController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: Prepublishing Nudges, [Type] Task

#13917 Login Epilogue: stop loading User Info when Gravatar can't be downloaded
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, Self-hosted

#13871 13581: Reader Filter Sheet
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterSheetView.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterSheetViewController.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterTableData.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Information Architecture

#13938 Prepublishing Nudges
  RELEASE-NOTES.txt
  WordPress/Classes/Models/AbstractPost+TitleForVisibility.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
  WordPress/Classes/ViewRelated/Post/PostVisibilitySelectorViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/Blog+Title.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PasswordAlertController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.xib
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController+PresentFrom.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+Async.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+SavedPosts.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Bottom Sheet/BottomSheetViewControllerTests.swift
  WordPress/WordPressTest/PrepublishingHeaderViewTests.swift
  WordPress/WordPressTest/PrepublishingNudgesViewControllerTests.swift
  WordPress/WordPressUITests/Screens/Editor/AztecEditorScreen.swift
  WordPress/WordPressUITests/Screens/Editor/BlockEditorScreen.swift
Labels: Prepublishing Nudges, [Type] Task

#13798 Make Post Stats chart difference value grey for current day
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsViewModel.swift
Labels: Stats

#13919 Tenor: correctly parse GIF date
  WordPress/Classes/ViewRelated/Media/Tenor/TenorAPI/TenorReponseParser.swift
  WordPress/WordPressTest/MediaPicker/Tenor/TenorAPIResponseTests.swift
Labels: Tenor

#13944 Update pods for release
  Podfile
  Podfile.lock
Labels: Releases

#13945 Merge Release/14.7 back into develop
  RELEASE-NOTES.txt
  Scripts/fastlane/Deliverfile
  Scripts/fastlane/download_metadata.swift
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#13906 Fixes some issues with GIF images in the reader.
  WordPress/Classes/Utility/Media/GIFPlaybackStrategy.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextImage.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachmentManager.swift
Labels: Reader, [Type] Bug

#13903 Issue/13063 insert captions
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
Labels: [Type] Bug

#13940 Wrong analytics image source for Stock Photo in Gutenberg Editor
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergStockPhotos.swift
Labels: Analytics, Stock Photos

#13923 Tenor analytics support
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergTenorMediaPicker.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorDataLoader.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorPicker.swift
Labels: Analytics, Tenor

#13952 Fix crash when rendering comments
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Labels: Atomic, Comments, [Type] Bug, [Type] Crash

#13957 Refactor the fix for comments crash
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Labels: Atomic, Comments, [Type] Crash

#13960 Fix crash when publishing a Page
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Labels: Prepublishing Nudges, [Type] Crash

#13941 Animating GIFs in Tenor Picker
  WordPress/Classes/Utility/Media/GIFPlaybackStrategy.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorMedia.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorPicker.swift
Labels: Tenor, [Type] Enhancement

#13965 Merge Release/14.7 into develop
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#13968 Fix editor button from being truncated
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
Labels: Posting/Editing, Prepublishing Nudges, [Type] Bug

#13961 Signup Epilogue: update User Info section
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
  WordPress/Classes/ViewRelated/NUX/SignupEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Labels: Signup, [Type] Enhancement

#13962 Signup Epilogue: remove Password table section
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Labels: Signup, [Type] Enhancement

#13948 Add Manage Screen to the new Reader tab
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Me/Me Main/Presenter/MeScenePresenter.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/Manage/OffsetTableViewHandler.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderManageScenePresenter.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewController+Cells.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewController.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Manage/TabbedViewController.swift
  WordPress/Classes/ViewRelated/Reader/Reader.storyboard
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Information Architecture

#13928 [RNMobile] Cover with in Cover support
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergBlockProcessor.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergCoverUploadProcessor.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/GutenbergCoverUploadProcessorTests.swift
Labels: Gutenberg compatibility

#13909 Rnmobile/cover block uploads
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergBlockProcessor.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergCoverUploadProcessor.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/GutenbergCoverUploadProcessorTests.swift
Labels: Gutenberg compatibility

#13970 Change Media Picker label from "Preview %@" to "Edit %@"
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
Labels: Media Editing, [Type] Task

#13958 Remove BottomSheet from WPiOS and move it to WPUI
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Bottom Sheet/BottomSheetViewController.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/BottomSheetAnimationController.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/DrawerPresentationController.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/GripView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Bottom Sheet/BottomSheetViewControllerTests.swift
Labels: Prepublishing Nudges, [Type] Task

#13951 New Reader - State Restoration, Spotlight Search, Universal Links
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: Information Architecture, New Reader iOS, [Type] Enhancement

#13974 Show an alert when trying to preview while uploading media
  WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Labels: Previews, [Type] Enhancement

#13973 Signup Epilogue: update table and cells for new design
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.xib
  WordPress/Classes/ViewRelated/NUX/SignupEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.xib
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
Labels: Signup

#13993 Fix scheduling issues
  WordPress/Classes/ViewRelated/Post/PostEditorState.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/PublishSettingsViewController.swift
Labels: Post Scheduling Enhancements, Prepublishing Nudges, [Type] Bug

#13982 Signup & Login Epilogues: adjust gravatar top margin
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
Labels: Login, Signup

#13975 Empty Filter Sheet View
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/Reader/Filter/EmptyActionView.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterSheetView.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterSheetViewController.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderManageScenePresenter.swift
  WordPress/Classes/ViewRelated/Reader/Manage/TabbedViewController.swift
  WordPress/Classes/ViewRelated/Tools/ScenePresenter.swift
  WordPress/Classes/ViewRelated/Views/NoResults.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Information Architecture

#13999 Update WordPressUI to 1.5.4-beta.3
  Podfile
  Podfile.lock
Labels: [Type] Task

#14003 UL&S: Remove .showMagicLinkFlow segue
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Login, [Type] Enhancement

#13984 Information Architecture Improvements
  WordPress/Classes/ViewRelated/Blog/Blog + Me/GravatarButtonView.swift
  WordPress/Classes/ViewRelated/Blog/Blog + Me/UIBarButtonItem+MeBarButton.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
  WordPress/Classes/ViewRelated/System/FilterTabBar.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: /Me, Information Architecture, New Reader iOS

#13969 Fixes issue: me gravatar image not showing
  Podfile
  Podfile.lock
Labels: /Me, [Type] Bug

#14010 Signup Epilogue: update content margins
  WordPress/Classes/Extensions/UIView+Borders.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueSectionHeaderFooter.xib
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.xib
  WordPress/Classes/ViewRelated/NUX/SignupEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.xib
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Labels: Signup

#14012 Login Epilogue: update content margins
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueConnectSiteCell.xib
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Labels: Signup, [Status] Needs Design Review

#14013 Signup Epilogue: update Done button
  WordPress/Classes/ViewRelated/NUX/SignupEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/WordPressUITests/Screens/Signup/SignupEpilogueScreen.swift
Labels: Signup, [Status] Needs Design Review

#14002 Gutenberg: update to v1.27.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#14018 Signup Epilogue: adjust table width for iPad
  WordPress/Classes/ViewRelated/NUX/SignupEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
Labels: Signup

#14019 Signup Epilogue: accessibility
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueCell.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
Labels: Signup

#14026 Login Epilogue: fix iPad layout issues
  WordPress/Classes/ViewRelated/NUX/LoginEpilogue.storyboard
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
Labels: Login

#14028 Fix bug w/ WPSplitView Rotation Logic
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
Labels: [Type] Bug

#14034 Change options order and fix label and scroll issue
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: Prepublishing Nudges, [Type] Bug

#14038 Track Settings Options usage + fix Media Editor tracking
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: Analytics, Media Editing, Posting/Editing, [Type] Enhancement

#14011 Feature/13580 reader unit tests
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MockContext.swift
  WordPress/WordPressTest/ReaderReblogActionTests.swift
  WordPress/WordPressTest/ReaderTabItemsStoreTests.swift
  WordPress/WordPressTest/ReaderTabViewModelTests.swift
  WordPress/WordPressTest/ReaderTabViewTests.swift
Labels: Information Architecture, New Reader iOS
