Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2021-03, with the labels that each got.

#15974 Stories: Add missing analytics events + Enable Story Block
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Kanvas/KanvasCameraAnalyticsHandler.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FAB.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/SheetActions.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
Labels: WP Stories

#15990 Show categories publishing field in editors
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
Labels: [Type] Bug

#15989 Add "You hit a milestone 🚀" title to view milestone push notifications
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Notifiable.swift
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
Labels: Milestone Notifications, [Type] Enhancement

#15980 Stories: Fix Media Import bugs
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Services/Stories/WPMediaPicker+MediaPicker.swift
  WordPress/Classes/Utility/Media/MediaURLExporter.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergMediaFilesUploadProcessor.swift
Labels: WP Stories

#15982 Stories: Android compatibility
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Services/Stories/StoryMediaLoader.swift
  WordPress/Classes/Services/Stories/StoryPoster.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Processors/GutenbergMediaFilesUploadProcessor.swift
Labels: WP Stories

#15995 Improve appearance of Reader Detail when used in Notifications
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
Labels: New Reader iOS, Reader

#15994 Implement fetch likes in CommentService
  Podfile
  Podfile.lock
  WordPress/Classes/Services/CommentService.h
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/Services/CommentServiceRemoteFactory.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/CommentServiceTests.swift
Labels: Notifications, [Type] Enhancement

#15996 Stories: 16.8 Bug Fixes
  Podfile
  Podfile.lock
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Services/Stories/WPMediaPicker+MediaPicker.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FAB.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
Labels: WP Stories

#16000 Stories: Fixes StoryEditor reference in Gutenberg
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: WP Stories

#15953 Switch Fastlane to API calls
  .circleci/config.yml
  fastlane/Fastfile
Labels: Tooling

#15992 Switch Gutenberg pod reference to use https
  Podfile
  Podfile.lock
Labels: Apple Silicon, [Type] Task

#16003 Standardize tracking sources for blog details subsections
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: Analytics, My Site

#15998 Comments: show Trashed and Spam
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.h
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: Comments, [Type] Enhancement

#16001 Comments: add state restoration
  WordPress/Classes/ViewRelated/Comments/CommentsViewController+Filters.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: Comments, [Type] Enhancement

#15933 Extract filterable categories class and use for layouts and site designs
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Models/PageTemplateCategory+CoreDataProperties.swift
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collabsable Header Filter Bar/CollabsableHeaderFilterCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collabsable Header Filter Bar/CollapsableHeaderFilterBar.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/CategorySectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/CategorySectionTableViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/FilterableCategoriesViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/SiteCreation/SiteCreatorTests.swift
Labels: Site Creation, [Type] Enhancement

#15997 Add issue triage guideline for tracks issues
  docs/issue-triage.md
Labels: Documentation

#15999 Reader Improvements: Renames interests to topics
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.xib
Labels: New Reader iOS, Reader, [Type] Task

#15979 Reader Improvements: Update the suggested topics design
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTopicsCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTopicsCardCell.xib
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsStyleGuide.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: New Reader iOS, Reader, [Type] Task

#16005 Feature/15356 invite link
  WordPress/Classes/Services/PeopleService.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
  WordPress/Classes/ViewRelated/People/People.storyboard
Labels: People Management, [Type] Enhancement

#16007 Likes Notification: Display likes using the new endpoints
  WordPress/Classes/Services/CommentServiceRemoteFactory.swift
  WordPress/Classes/Services/PostServiceRemoteFactory.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Notifications, [Type] Enhancement

#16010 [Tooling] Mark *.enc configure files as binary
  .gitattributes
Labels: Tooling

#16011 Stories: 16.8 Critical Bug Fixes
  Podfile
  Podfile.lock
  WordPress/Classes/Services/Stories/CameraHandler.swift
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Services/Stories/WPMediaPicker+MediaPicker.swift
  WordPress/Classes/ViewRelated/What's New/Views/StoriesIntroViewController.swift
Labels: WP Stories

#16006 Milestone Notifications: Present Insights view instead of time period when showing stats
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationContentRouter.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/WordPressTest/MockContentCoordinator.swift
Labels: Milestone Notifications, Notifications

#16012 Add "This Week" localized string to StatsWidgets target
  WordPress/WordPressStatsWidgets/Supporting Files/Base.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/en.lproj/Localizable.strings
Labels: [Type] Bug, iOS 14 Widgets

#16015 Add missing event to track "This Week" widget installation
  WordPress/WordPressStatsWidgets/Tracks/Tracks+TodayHomeWidget.swift
Labels: [Type] Bug, iOS 14 Widgets

#15984 Reader Improvements: Add "Discover more topics" button to Followed Topics screen
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsFooter.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsFooter.xib
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsDataSource.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderSelectInterestsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderInterestsDataSourceTests.swift
Labels: New Reader iOS, Reader, [Type] Task

#15993 Integrate gutenberg-mobile release 1.48.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#16021 Remove extra reference to All-Time widget storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Stats Widgets, [Type] Task

#16013 Like notifications: show all post and comment likes
  Podfile.lock
  WordPress/Classes/Services/CommentService.h
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/Services/CommentServiceRemoteFactory.swift
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/Services/PostServiceRemoteFactory.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/CommentServiceTests.swift
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: Notifications, [Type] Enhancement

#16022 InviteLinks: Adds a release note.
  RELEASE-NOTES.txt
Labels: [Type] Task

#16004 Small Reader Improvements: Add Related Posts
  Podfile.lock
  WordPress/Classes/Services/ReaderPostService+RelatedPosts.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.storyboard
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderRelatedPostsCell.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderRelatedPostsCell.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderRelatedPostsSectionHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderRelatedPostsSectionHeaderView.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderDetailCoordinatorTests.swift
Labels: New Reader iOS, Reader, [Type] Task

#16017 Small Reader Improvements: Present related posts in a new nav stack
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: New Reader iOS, Reader, [Type] Task

#16029 Jetpack Install: Change error to error_type when tracking jetpack install error
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
Labels: Analytics, Jetpack, Jetpack Mobile, [Type] Bug

#16008 Add classic editor deprecation notice
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Labels: Aztec

#16009 Feature/trig ci jobs via api
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/env/user.env-example
Labels: Tooling

#16027 Fixes minor UI issues in the Design/Layout picker
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/CategorySectionTableViewCell.xib
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/FilterableCategoriesViewController.swift
Labels: [Type] Bug

#16024 Adds Analytics event to capture when a category filter is selected
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/FilterableCategoriesViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
Labels: Analytics, Site Creation, [Type] Enhancement

#16026 Listen for the NoticeAction to track publishing
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
Labels: WP Stories

#16033 Initial .editorconfig setup
  .editorconfig
Labels: Tooling

#16020 Show domain credit claim section for atomic sites
  WordPress/Classes/ViewRelated/Blog/Domain Credit/DomainCreditEligibilityChecker.swift
  WordPress/WordPressTest/DomainCredit/DomainCreditEligibilityTests.swift
Labels: Domain Credit

#16038 Add APP_STORE_STRINGS_FILE_NAME env constant
  fastlane/Fastfile
Labels: Testing

#16041 Merge 16.9 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#16040 Remove unified auth feature flag.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: [Type] Task

#16039 Large Titles / White Headers: Move My Sites VCs to My Sites Coordinator
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: Large titles

#16045 Fix build type on code freeze
  fastlane/Fastfile
Labels: Tooling

#16032 InviteLinks: Add icon to share cell.
  WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
Labels: People Management, [Type] Enhancement

#16042 Remove unseen posts feature flag.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
Labels: [Type] Task

#16049 Comments: always deselect comment row.
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: Comments, [Type] Bug

#16051 Zendesk: update to latest version
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Zendesk, [Type] Task

#16055 Reader post details: show message when (un)following site
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
Labels: Reader, [Type] Enhancement

#16052 Issues/15356 dynamic font
  WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
  WordPress/Classes/ViewRelated/People/People.storyboard
Labels: [Type] Bug

#16060 Reader: fix unfollowing external sites
  RELEASE-NOTES.txt
  WordPress/Classes/Services/ReaderPostService.m
Labels: Reader, [Type] Bug

#16059 16.8.1 Hot Fix
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/Stories/CameraHandler.swift
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Services/Stories/StoryPoster.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
Labels: Gutenberg integration, WP Stories

#16046 Integrate gutenberg-mobile release 1.48.1
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/Stories/CameraHandler.swift
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Services/Stories/StoryPoster.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
Labels: Gutenberg integration

#16067 Comments: support `blockEmailNotifications` from WPKit
  MIGRATIONS.md
  Podfile
  Podfile.lock
  WordPress/Classes/Models/ManagedAccountSettings+CoreDataProperties.swift
  WordPress/Classes/Models/ManagedAccountSettings.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 115.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments, [Type] Enhancement

#16077 InviteLinks: Ensure cell separator is visible in darkmode.
  WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
Labels: [Type] Bug

#16086 Merge 16.9 beta 2 into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/Stories/CameraHandler.swift
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Services/Stories/StoryPoster.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+ShowTab.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/metadata/ar-SA/keywords.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/ar-SA/subtitle.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-CA/release_notes.txt
  fastlane/metadata/en-GB/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/es-MX/release_notes.txt
  fastlane/metadata/es-MX/subtitle.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#16058 My Site: New Site Picker
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/BlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/SiteIconView.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListDataSource.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: Large titles, My Site

#16070 Target 4.28.1 branch to fix Popular Plugins from loading
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Jetpack Plugins, [Type] Bug

#16080 Related Posts: Fix section display logic
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: New Reader iOS, Reader, [Type] Bug

#16090 Merge 16.9 betas into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Logging/EventLoggingDelegate.swift
  WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift
  WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/SitePromptView.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/SitePromptView.xib
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#16074 Stats > Latest Post Summary: don't show error message if there is no post
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Stats, [Type] Bug

#16091 Fix sites intent warning
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressIntents/ar.lproj/Sites.strings
  WordPress/WordPressIntents/bg.lproj/Sites.strings
  WordPress/WordPressIntents/cs.lproj/Sites.strings
  WordPress/WordPressIntents/cy.lproj/Sites.strings
  WordPress/WordPressIntents/da.lproj/Sites.strings
  WordPress/WordPressIntents/de.lproj/Sites.strings
  WordPress/WordPressIntents/en-AU.lproj/Sites.strings
  WordPress/WordPressIntents/en-CA.lproj/Sites.strings
  WordPress/WordPressIntents/en-GB.lproj/Sites.strings
  WordPress/WordPressIntents/en.lproj/Sites.strings
  WordPress/WordPressIntents/es.lproj/Sites.strings
  WordPress/WordPressIntents/fr.lproj/Sites.strings
  WordPress/WordPressIntents/he.lproj/Sites.strings
  WordPress/WordPressIntents/hr.lproj/Sites.strings
  WordPress/WordPressIntents/hu.lproj/Sites.strings
  WordPress/WordPressIntents/id.lproj/Sites.strings
  WordPress/WordPressIntents/is.lproj/Sites.strings
  WordPress/WordPressIntents/it.lproj/Sites.strings
  WordPress/WordPressIntents/ja.lproj/Sites.strings
  WordPress/WordPressIntents/ko.lproj/Sites.strings
  WordPress/WordPressIntents/nb.lproj/Sites.strings
  WordPress/WordPressIntents/nl.lproj/Sites.strings
  WordPress/WordPressIntents/pl.lproj/Sites.strings
  WordPress/WordPressIntents/pt-BR.lproj/Sites.strings
  WordPress/WordPressIntents/pt.lproj/Sites.strings
  WordPress/WordPressIntents/ro.lproj/Sites.strings
  WordPress/WordPressIntents/ru.lproj/Sites.strings
  WordPress/WordPressIntents/sk.lproj/Sites.strings
  WordPress/WordPressIntents/sq.lproj/Sites.strings
  WordPress/WordPressIntents/sv.lproj/Sites.strings
  WordPress/WordPressIntents/th.lproj/Sites.strings
  WordPress/WordPressIntents/tr.lproj/Sites.strings
  WordPress/WordPressIntents/zh-Hans.lproj/Sites.strings
  WordPress/WordPressIntents/zh-Hant.lproj/Sites.strings
Labels: Localization

#16030 Avoid tracking widget events in the preview
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressStatsWidgets/Model/StatsWidgetEntry.swift
  WordPress/WordPressStatsWidgets/SiteListProvider.swift
  WordPress/WordPressStatsWidgets/Tracks/Tracks+StatsWidgets.swift
  WordPress/WordPressStatsWidgets/Views/StatsWidgetsView.swift
  WordPress/WordPressStatsWidgets/Widgets/WordPressHomeWidgetAllTime.swift
  WordPress/WordPressStatsWidgets/Widgets/WordPressHomeWidgetThisWeek.swift
  WordPress/WordPressStatsWidgets/Widgets/WordPressHomeWidgetToday.swift
Labels: [Type] Bug, iOS 14 Widgets

#16092 Merge 16.9 release notes into develop
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#16085 Large Titles / White Headers My Site improvements
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FancyAlerts.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/BlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Labels: Large titles, My Site

#16088 Update fastlane
  Gemfile.lock
Labels: Tooling

#16097 Discover: update Like button state
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderLikeAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
Labels: Reader, [Type] Bug

#16093 Related Posts: Update related posts section header styling
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderRelatedPostsSectionHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderRelatedPostsSectionHeaderView.xib
Labels: New Reader iOS, Reader, [Type] Enhancement

#16025 Update terms in code to use more inclusive language
  MIGRATIONS.md
  Podfile
  Podfile.lock
  WordPress/Classes/Models/BlogSettings+Discussion.swift
  WordPress/Classes/Models/BlogSettings.swift
  WordPress/Classes/Services/BlogJetpackSettingsService.swift
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/DiscussionSettingsViewController.swift
  WordPress/Classes/ViewRelated/Domains/Register/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackSettingsViewController.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 116.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogSettingsDiscussionTests.swift
  WordPress/WordPressTest/Test Data/plugin-directory-jetpack.json
  WordPress/WordPressUITests/Screens/BaseScreen.swift
Labels: [Type] Task

#16107 Fixing black password text in Post Settings when in dark mode
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: Low Hanging Fruit, [Type] Bug

#16102 [Tooling] Podfile: Add internal spec repo as source
  Podfile
  Podfile.lock
Labels: Tooling

#16109 Stories: Rendering engine changes
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/Stories/StoryEditor.swift
Labels: [Type] Bug

#16116 Fix navigation bar styles for WebKitViewController
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderVisitSiteAction.swift
Labels: Webviews

#16108 Comments: save selected filter
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController+Filters.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: Comments, [Type] Enhancement

#16115 Remove unused job
  .circleci/config.yml
Labels: Tooling

#16118 Dismiss alert in UI tests to ensure tests pass the first time around
  WordPress/WordPressUITests/Tests/EditorAztecTests.swift
Labels: Testing

#16121 Add alert dismiss to all Aztec UI tests
  WordPress/WordPressUITests/Tests/EditorAztecTests.swift
Labels: Testing

#16125 Fix wrong label in small Today and All Time widgets
  WordPress/WordPressStatsWidgets/Views/SingleStatView.swift
Labels: [Type] Bug, iOS 14 Widgets

#16105 Comments: show No Connection view
  WordPress/Classes/ViewRelated/Comments/CommentsViewController+NetworkAware.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments, [Type] Enhancement

#16119 Add large titles to the Notifications screen
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
Labels: Large titles, [Type] Enhancement

#16100 Integrate gutenberg-mobile release 1.49.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#16130 Comments: group by date created
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Comment.h
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: Comments, [Type] Enhancement

#16019 Add device mode selection for page layouts
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Models/PageTemplateLayout+CoreDataProperties.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 117.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#16133 Fix webview header colors [16.9]
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderVisitSiteAction.swift
Labels: Large titles, Webviews

#16113 Update colours in PostPostViewController
  WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
  WordPress/Classes/ViewRelated/Post/PostPost.storyboard
  WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
Labels: Posting/Editing

#16129 AB testing: implement the first A/B experiment
  Podfile
  Podfile.lock
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/AB Testing/ABTest.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonActionSheet.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
Labels: Analytics, [Type] Task

#16135 Adds some missing translations for the iOS 14 All Time widget
  WordPress/WordPressStatsWidgets/Supporting Files/ar.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/bg.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/cs.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/cy.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/da.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/de.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/en-AU.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/en-CA.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/en-GB.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/es.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/fr.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/he.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/hr.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/hu.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/id.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/is.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/it.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/ja.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/ko.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/nb.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/nl.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/pl.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/pt-BR.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/pt.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/ro.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/ru.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/sk.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/sq.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/sv.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/th.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/tr.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/zh-Hans.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Supporting Files/zh-Hant.lproj/Localizable.strings
Labels: Localization

#16132 Update NewBlogDetailHeaderView sizing
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Labels: Large titles, [Status] Needs Design Review

#16136 Update bar buttons for new site picker
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
Labels: Large titles, My Site

#16143 Allow MySiteViewController to handle the result of the site creation process
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
Labels: Large titles, Site Creation

#16142 Fix UI tests for large title changes
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Post/PostPostViewController.swift
  WordPress/WordPressUITests/Flows/LoginFlow.swift
  WordPress/WordPressUITests/Screens/MeTabScreen.swift
  WordPress/WordPressUITests/Screens/MySiteScreen.swift
  WordPress/WordPressUITests/Screens/MySitesScreen.swift
  WordPress/WordPressUITests/Screens/TabNavComponent.swift
Labels: Large titles, Testing

#16144 Enable the milestoneNotifications feature flag
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Milestone Notifications, [Type] Task

#16141 Use webview for template previews
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPreviewViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPreviewViewController.xib
  WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/SiteDesignPreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/TemplatePreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/TemplatePreviewViewController.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Previews, [Type] Enhancement

#16146 Fix announcements not showing with large titles
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
Labels: Large titles, [Type] Bug

#16147 Merge 17.0 code freeze into develop
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/System/WordPressAppDelegate.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#16151 [Tooling] Mute fastlane's CHANGELOG and update check
  .circleci/config.yml
Labels: Tooling

#16154 Fix a warning about accessing the main thread
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Logging/EventLoggingDelegate.swift
Labels: [Type] Bug

#16124 Jetpack App: New Target, No App Extensions
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/icon_20pt@2x.png
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/icon_20pt@3x.png
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/icon_29pt@2x.png
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/icon_29pt@3x.png
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/icon_40pt@2x.png
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/icon_40pt@3x.png
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/icon_60pt@2x.png
  WordPress/Jetpack/AppImages.xcassets/AppIcon.appiconset/icon_60pt@3x.png
  WordPress/Jetpack/Info.plist
  WordPress/Jetpack/Launch Screen.storyboard
  WordPress/Launch Screen.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/Jetpack.xcscheme
Labels: Jetpack App

#16140 Jetpack App: Filter Jetpack sites
  Podfile
  Podfile.lock
  WordPress/Classes/Services/BlogService.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/AppExtensionsService.swift
Labels: Jetpack App

#16148 Jetpack App: App Target Configuration
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/Utility/App Configuration/Protocol/TargetConfiguration.swift
  WordPress/Jetpack/AppConfiguration.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack App

#16153 Add basic structure for unified prologue content views
  WordPress/Classes/ViewRelated/NUX/ContentViews/UnifiedPrologueIntroContentView.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/Resources/AppImages.xcassets/Prologue/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite1.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite1.imageset/page1Website1.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite1.imageset/page1Website1@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite1.imageset/page1Website1@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite2.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite2.imageset/page1Website2.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite2.imageset/page1Website2@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite2.imageset/page1Website2@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite3.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite3.imageset/page1Website3.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite3.imageset/page1Website3@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite3.imageset/page1Website3@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite4.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite4.imageset/page1Website4.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite4.imageset/page1Website4@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite4.imageset/page1Website4@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite5.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite5.imageset/page1Website5.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite5.imageset/page1Website5@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite5.imageset/page1Website5@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite6.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite6.imageset/page1Website6.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite6.imageset/page1Website6@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite6.imageset/page1Website6@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite7.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite7.imageset/page1Website7.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite7.imageset/page1Website7@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/introWebsite7.imageset/page1Website7@3x.png
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Unified Login & Signup, [Type] Task

#16149 Fix crash when deleting today widget blog
  WordPress/Classes/Services/AccountService.m
Labels: Stats Widgets, [Type] Crash

#16152 Fix localization script for widgets
  Scripts/localize.py
  WordPress/Resources/en.lproj/Localizable.strings
Labels: Localization, Tooling

#16160 Merge 17.0 beta 2 into develop
  Scripts/localize.py
  WordPress/Classes/Services/AccountService.m
  WordPress/Resources/en.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-CA/release_notes.txt
  fastlane/metadata/en-GB/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/es-MX/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#16162 AB testing: only assign experiments to signed in users and fix a crash
  WordPress/Classes/Utility/AB Testing/ABTest.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueViewController.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonActionSheet.swift
Labels: Analytics, [Type] Task

#16131 Remove switch to classic from gutenberg
  WordPress/Classes/Utility/Editor/EditorFactory.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+MoreActions.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg compatibility, [Status] DO NOT MERGE

#16165 Comment detail: fix crash when replying to a comment
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
Labels: Comments, [Type] Bug

#16172 Update historic Migration models that were missed
  MIGRATIONS.md
Labels: Core Data, Documentation, [Type] Task

#16170 Apply Default Values to the CoreData items added in 117
  MIGRATIONS.md
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 118.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Core Data, [Type] Bug

#16175 Apply Default Values to the CoreData items added in 117
  MIGRATIONS.md
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 118.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Core Data, [Pri] High, [Type] Bug

#16169 Set Reader Comments large title display mode to Never
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Labels: Large titles, Reader

#16181 Add defaultDotComUUID to UserSettings
  WordPress/Classes/Models/UserSettings.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/UserSettingsTests.swift
  WordPress/WordPressTest/UserSettingsTestsObjc.m
  WordPress/WordPressTest/WordPressUnitTests.xctestplan
Labels: [Type] Enhancement

#16159 Add editor screen for unified prologue carousel
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NUX/ContentViews/Components/CircledIcon.swift
  WordPress/Classes/ViewRelated/NUX/ContentViews/Components/RoundRectangleView.swift
  WordPress/Classes/ViewRelated/NUX/ContentViews/Editor/UnifiedPrologueEditorContentView.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img1Sea.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img1Sea.imageset/page2Img1Sea.png
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img1Sea.imageset/page2Img1Sea@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img1Sea.imageset/page2Img1Sea@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img2Trees.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img2Trees.imageset/page2Img2Trees.png
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img2Trees.imageset/page2Img2Trees@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img2Trees.imageset/page2Img2Trees@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img3Food.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img3Food.imageset/page2Img3Food.png
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img3Food.imageset/page2Img3Food@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page2Img3Food.imageset/page2Img3Food@3x.png
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Unified Login & Signup, [Type] Enhancement

#16161 Jetpack App: Change navigation titles to sans serif font
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/Utility/App Configuration/AppStyleGuide.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Jetpack/AppStyleGuide.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack App

#16182 Remove the need for a test with better types
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
  WordPress/WordPressTest/ReaderTabItemsStoreTests.swift
Labels: Core Data, Testing

#16176 Jetpack App: Muriel Colors
  WordPress/Classes/Extensions/Colors and Styles/MurielColor.swift
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/Extensions/Colors and Styles/UIColor+WordPressColors.swift
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+FilterTabBar.swift
  WordPress/Classes/Utility/App Configuration/AppStyleGuide.swift
  WordPress/Jetpack/AppStyleGuide.swift
  WordPress/Jetpack/UIColor+JetpackColors.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack App

#16186 Site address login: correctly remove wp-admin from the url string
  Podfile
  Podfile.lock
Labels: Login, [Type] Bug

#16190 Fixes deep links not working from widgets
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
Labels: [Type] Bug

#16177 Add Notifications screen for unified prologue carousel
  WordPress/Classes/Extensions/NSAttributedString+StyledHTML.swift
  WordPress/Classes/ViewRelated/NUX/ContentViews/Components/Text+BoldSubString.swift
  WordPress/Classes/ViewRelated/NUX/ContentViews/Editor/UnifiedPrologueNotificationsContentView.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar1.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar1.imageset/page3Avatar1.png
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar1.imageset/page3Avatar1@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar1.imageset/page3Avatar1@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar2.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar2.imageset/page3Avatar2.png
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar2.imageset/page3Avatar2@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar2.imageset/page3Avatar2@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar3.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar3.imageset/page3Avatar3.png
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar3.imageset/page3Avatar3@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page3Avatar3.imageset/page3Avatar3@3x.png
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Unified Login & Signup, [Type] Enhancement

#16185 Add Reader screen for unified prologue carousel
  WordPress/Classes/ViewRelated/NUX/ContentViews/Editor/UnifiedPrologueReaderContentView.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar1.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar1.imageset/page5Avatar1.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar1.imageset/page5Avatar1@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar1.imageset/page5Avatar1@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar2.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar2.imageset/page5Avatar2.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar2.imageset/page5Avatar2@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar2.imageset/page5Avatar2@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar3.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar3.imageset/page5Avatar3.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar3.imageset/page5Avatar3@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Avatar3.imageset/page5Avatar3@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img1Coffee.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img1Coffee.imageset/page5Img1Coffee.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img1Coffee.imageset/page5Img1Coffee@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img1Coffee.imageset/page5Img1Coffee@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img2Stadium.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img2Stadium.imageset/page5Img2Stadium.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img2Stadium.imageset/page5Img2Stadium@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img2Stadium.imageset/page5Img2Stadium@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img3Museum.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img3Museum.imageset/page5Img3Museum.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img3Museum.imageset/page5Img3Museum@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page5Img3Museum.imageset/page5Img3Museum@3x.png
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Unified Login & Signup, [Type] Enhancement

#16193 Improve Site Title alignment and sizing
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Labels: Large titles, My Site

#16155 Removes Preview mode from Gutenberg editor
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Editor/EditorFactory.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Pages/EditPageViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
Labels: [Type] Tech Debt

#16194 AB testing: fix refreshIfNeeded
  Podfile
  Podfile.lock
Labels: Analytics, [Type] Bug

#16187 Unified prologue - Stats screen
  WordPress/Classes/ViewRelated/NUX/ContentViews/Editor/UnifiedPrologueEditorContentView.swift
  WordPress/Classes/ViewRelated/NUX/ContentViews/Stats/UnifiedPrologueStatsContentView.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/Resources/AppImages.xcassets/Prologue/barGraph.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/barGraph.imageset/barGraphDark.png
  WordPress/Resources/AppImages.xcassets/Prologue/barGraph.imageset/barGraphDark@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/barGraph.imageset/barGraphDark@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/barGraph.imageset/barGraphLight.png
  WordPress/Resources/AppImages.xcassets/Prologue/barGraph.imageset/barGraphLight@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/barGraph.imageset/barGraphLight@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapDark.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapDark@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapDark@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapLight.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapLight@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapLight@3x.png
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Unified Login & Signup, [Type] Enhancement

#16156 Respect API ordering for page template categories
  MIGRATIONS.md
  RELEASE-NOTES.txt
  WordPress/Classes/Models/PageTemplateCategory+CoreDataProperties.swift
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 119.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Core Data, [Type] Enhancement

#16199 Add feature flagging to large titles for Reader and Notifications
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
Labels: Large titles

#15634 Contact Info - Adding Feature Flag + Jetpack API for version check
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Posting/Editing

#16204 Fix Sharing webview nav bar colors
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColorsObjC.swift
  WordPress/Classes/Utility/WPWebViewController.m
  WordPress/Classes/Utility/WPWebViewController.xib
  WordPress/Classes/ViewRelated/Blog/SharingAccountViewController.swift
  WordPress/Classes/ViewRelated/Blog/SharingAuthorizationHelper.m
Labels: Webviews
