Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2021-08, with the labels that each got.

#16964 Stats: fix crash caused by noResultsVC being nil
  WordPress/Classes/ViewRelated/Stats/StatsViewController.m
Labels: Stats, [Type] Crash

#16427 [RNMobile] Parent PR: Add Setting to Set/Remove a Featured Image Directly from Image Block
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergFeaturedImageHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+FeaturedImageUpload.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.h
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg integration, [Type] Enhancement

#16962 UC: Add extra top space to Notifications and Comments list
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
Labels: Comments, Notifications, [Type] Enhancement

#16946 Reader Post: Update likes summary text to include like from self
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.xib
Labels: Reader, [Type] Enhancement

#16923 Accessibility: Adjust collapsable header text sizes
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderView.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.xib
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Accessibility, [Type] Bug

#16965 Likes summary formats: mark the beginning of the underlined text
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.swift
Labels: Likes, Reader, [Type] Enhancement

#16947 Remove selected_site_self_hosted tag from Zendesk tickets on Atomic sites
  WordPress/Classes/Utility/ZendeskUtils.swift
Labels: Zendesk, [Type] Bug

#16857 [Gutenberg] Add new block type badge to block inserter list
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/Editor/GutenbergSettings.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration, [Type] Enhancement

#16972 Post: Use a post's titleForDisplay for notices.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostNoticeViewModel.swift
Labels: Posting/Editing, [Type] Bug

#16848 [Gallery Refactor] Analytics
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
Labels: Analytics, [Status] Needs Discussion, [Type] Enhancement

#16975 Integrate gutenberg-mobile release 1.58.2
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#16969 Comment model: convert properties to Swift
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/Comment+Interface.swift
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Models/Comment+CoreDataClass.swift
  WordPress/Classes/Models/Comment+CoreDataProperties.swift
  WordPress/Classes/Models/Comment.h
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Comments/CommentAnalytics.swift
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments, [Type] Enhancement

#16914 Themes: Fix theme url to include the correct image resized url
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserCell.swift
Labels: Themes

#16979 Add subtitle support to `CheckmarkRow`
  WordPress/Classes/Utility/WPImmuTableRows.swift
Labels: Themes, [Type] Enhancement

#16983 Merge release 17.9.0.4 into develop
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ar.lproj/Localizable.strings
  WordPress/WordPressShareExtension/bg.lproj/Localizable.strings
  WordPress/WordPressShareExtension/cs.lproj/Localizable.strings
  WordPress/WordPressShareExtension/cy.lproj/Localizable.strings
  WordPress/WordPressShareExtension/da.lproj/Localizable.strings
  WordPress/WordPressShareExtension/de.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-AU.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-CA.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-GB.lproj/Localizable.strings
  WordPress/WordPressShareExtension/es.lproj/Localizable.strings
  WordPress/WordPressShareExtension/fr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/he.lproj/Localizable.strings
  WordPress/WordPressShareExtension/hr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/hu.lproj/Localizable.strings
  WordPress/WordPressShareExtension/id.lproj/Localizable.strings
  WordPress/WordPressShareExtension/is.lproj/Localizable.strings
  WordPress/WordPressShareExtension/it.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ja.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ko.lproj/Localizable.strings
  WordPress/WordPressShareExtension/nb.lproj/Localizable.strings
  WordPress/WordPressShareExtension/nl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pt-BR.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pt.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ro.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ru.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sk.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sq.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sv.lproj/Localizable.strings
  WordPress/WordPressShareExtension/th.lproj/Localizable.strings
  WordPress/WordPressShareExtension/tr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/zh-Hans.lproj/Localizable.strings
  WordPress/WordPressShareExtension/zh-Hant.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/en-CA/release_notes.txt
Labels: Releases

#16902 Add UI test to verify self-hosted site can be added after logging into WordPress.com
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/WordPressUITests/Screens/Login/LoginEpilogueScreen.swift
  WordPress/WordPressUITests/Screens/MySiteScreen.swift
  WordPress/WordPressUITests/Screens/MySitesScreen.swift
  WordPress/WordPressUITests/Tests/LoginTests.swift
Labels: Testing

#16984 Likes Summary: Use format specifiers for singular formats
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.swift
Labels: Likes, [Type] Enhancement

#16974 Update GoogleSignIn to 6.0.1
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueUserInfo.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Login, dependencies

#16985 Enable unified list feature flag for Comments and Notifications
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Enhancement, Notifications, Comments

#16980 Comment entity: set default values on attributes
  MIGRATIONS.md
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Comment+CoreDataClass.swift
  WordPress/Classes/Models/Comment+CoreDataProperties.swift
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 130.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Comments

#16806 Extract swift secret files outside of repo
  .configure
  Scripts/BuildPhases/ApplyConfiguration.sh
  WordPress/Credentials/secrets-manifest.xcfilelist
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/secrets-manifest.xcfilelist
Labels: Tooling

#16973 Logging: Log upload failure due to missing media as message rather than an error
  WordPress/Classes/Services/MediaCoordinator.swift
Labels: General, [Type] Task

#16987 Remove Feature flag for HomePagePicker
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/WizardNavigation.swift
Labels: [Type] Task

#16988 Integrate gutenberg-mobile release 1.59.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#16989 Update My Site after successful domain registration
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+DomainCredit.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: [Type] Bug, Domain Registration

#16920 WebViews Auth issue: Recover from disabled auth token
  RELEASE-NOTES.txt
  WordPress/Classes/Services/AuthenticationService.swift
  WordPress/Classes/Utility/Networking/RequestAuthenticator.swift
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/RequestAuthenticatorTests.swift
Labels: [Type] Bug

#16994 Merge 18.0.0.0 into develop
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Pluginfile
  fastlane/download_metadata.swift
Labels: Releases

#16990 Extract automation to check translations in dedicated lane
  fastlane/Fastfile
Labels: Tooling

#16998 Issue/16957 - Display scan error states
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/View Models/JetpackScanStatusViewModel.swift
Labels: [Type] Enhancement, Jetpack Mobile, Jetpack App, Scan

#16967 Bundle local static React Native assets
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg integration

#16648 Use ScreenObject Swift package
  .circleci/config.yml
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Flows/LoginFlow.swift
  WordPress/WordPressUITests/Screens/MeTabScreen.swift
  WordPress/WordPressUITests/Screens/TabNavComponent.swift
  WordPress/WordPressUITests/Tests/EditorAztecTests.swift
  WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
  WordPress/WordPressUITests/Tests/LoginTests.swift
  WordPress/WordPressUITests/Tests/MainNavigationTests.swift
  WordPress/WordPressUITests/Tests/SignupTests.swift
  WordPress/WordPressUITests/Tests/SupportScreenTests.swift
Labels: Testing, Tooling

#16866 [Gutenberg] Embed block: Implement specific Embed preview
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#17011 Merge editorialized release notes for 18.0 into develop
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#17004 Remove duplicate/replaced UI login tests
  WordPress/WordPressUITests/Tests/LoginTests.swift
Labels: Testing

#17016 Integrate gutenberg-mobile release 1.58.3
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#16935 Improve Cocoapods caching
  .buildkite/cache-builder.yml
  .buildkite/commands/build-for-testing.sh
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
  fastlane/Fastfile
Labels: Tooling

#17019 Remove unused feature flags
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+FAB.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
Labels: [Type] Task, Gutenberg compatibility

#17017 Integrate gutenberg-mobile release 1.59.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#17026 Merge hotfix 17.9.1 into develop
  Gemfile.lock
  fastlane/Fastfile
Labels: Releases

#17024 Blogging Reminders - Time Selection UI
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersAnimator.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersNavigationController.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/Time Selector/TimeSelectionButton.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/Time Selector/TimeSelectionView.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/Time Selector/TimeSelectionViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Blogging Reminders

#17031 Fixes a scrolling issue in the plugins VC.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Plugins/CollectionViewContainerRow.swift
Labels: [Type] Bug

#17025 Merge hotfix 17.9.1 into trunk
  Gemfile.lock
  Podfile
  Podfile.lock
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Releases

#17012 Link XCUITestHelpers Swift package to UITestsFoundation framework
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/UITestsFoundation/XCUIElement+Utils.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Screens/Login/LoginUsernamePasswordScreen.swift
Labels: Testing, Tooling

#17013 Fix build failures in screenshot targets after adding ScreenObject
  WordPress/JetpackScreenshotGeneration/JetpackScreenshotGeneration.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
Labels: Testing

#17040 Integrate gutenberg-mobile release 1.59.2
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#17033 Blogging Reminders - Time Selection
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduler.swift
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersStore.swift
  WordPress/Classes/Utility/Date+TimeStrings.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersTracker.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/Time Selector/TimeSelectionView.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/Time Selector/TimeSelectionViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Blogging Reminders

#16991 Comments: Improved deletion failure.
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: [Type] Bug, Comments

#17044 Likes lists: show specific error messages when fetching fails
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesListController.swift
Labels: [Type] Enhancement, Notifications, Reader, Likes

#17005 Recommend App: Add button with icon cell component
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Cells/SingleButtonTableViewCell.swift
  WordPress/Classes/ViewRelated/Cells/SingleButtonTableViewCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, /Me

#17047 Merge 18.0.0.2 beta into develop
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Plugins/CollectionViewContainerRow.swift
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/ro.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ar.lproj/Localizable.strings
  WordPress/WordPressShareExtension/bg.lproj/Localizable.strings
  WordPress/WordPressShareExtension/cs.lproj/Localizable.strings
  WordPress/WordPressShareExtension/cy.lproj/Localizable.strings
  WordPress/WordPressShareExtension/da.lproj/Localizable.strings
  WordPress/WordPressShareExtension/de.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-AU.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-CA.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-GB.lproj/Localizable.strings
  WordPress/WordPressShareExtension/es.lproj/Localizable.strings
  WordPress/WordPressShareExtension/fr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/he.lproj/Localizable.strings
  WordPress/WordPressShareExtension/hr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/hu.lproj/Localizable.strings
  WordPress/WordPressShareExtension/id.lproj/Localizable.strings
  WordPress/WordPressShareExtension/is.lproj/Localizable.strings
  WordPress/WordPressShareExtension/it.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ja.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ko.lproj/Localizable.strings
  WordPress/WordPressShareExtension/nb.lproj/Localizable.strings
  WordPress/WordPressShareExtension/nl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pt-BR.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pt.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ro.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ru.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sk.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sq.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sv.lproj/Localizable.strings
  WordPress/WordPressShareExtension/th.lproj/Localizable.strings
  WordPress/WordPressShareExtension/tr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/zh-Hans.lproj/Localizable.strings
  WordPress/WordPressShareExtension/zh-Hant.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Jetpack-Fastfile
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
Labels: Releases

#17043 Add 16px padding to top of undo cell
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostUndoCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostUndoCell.xib
Labels: [Type] Enhancement, Reader

#17037 Stats Insights: Fix reloading for empty insights
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: [Type] Bug, Stats Refresh, User-Facing

#17036 Notifications: Adjust filter bar container background color
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Labels: [Type] Bug, Notifications

#17041 Reader: Only adjust insets if there is a featured image.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift
Labels: [Type] Bug, Reader

#17008 Enable editor help menu for eligible users
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+MoreActions.swift
Labels: [Type] Enhancement, Gutenberg integration

#17006 Recommend App: Add presenter to encapsulate display logic
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Sharing/ShareAppContentPresenter.swift
  WordPress/Classes/ViewRelated/Sharing/ShareAppTextActivityItemSource.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ShareAppContentPresenterTests.swift
  WordPress/WordPressTest/ShareAppTextActivityItemSourceTests.swift
  WordPress/WordPressTest/Test Data/share-app-link-success.json
Labels: [Type] Enhancement, /Me

#17007 Recommend App: Implement share app button in About screen
  WordPress/Classes/ViewRelated/Me/App Settings/About/AboutViewController.swift
  WordPress/Classes/ViewRelated/Sharing/ShareAppContentPresenter+TableView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, /Me

#17020 Recommend App: Implement share button in Me screen
  WordPress/Classes/Utility/WPImmuTableRows.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
Labels: [Type] Enhancement, /Me

#17027 Recommend App: Add Tracks
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AboutViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Sharing/ShareAppContentPresenter.swift
  WordPress/WordPressTest/Analytics/Utils/TestAnalyticsTracker.swift
  WordPress/WordPressTest/ShareAppContentPresenterTests.swift
Labels: /Me, Tracks

#17055 Integrate gutenberg-mobile release 1.60.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#17046 Edit Comment: add initial view
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Comments/EditCommentTableViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Comments

#17056 Site Settings: Improve scroll performance
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
Labels: [Type] Enhancement

#17054 Add time labels to Blogging Reminders
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduleFormatter.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowCompletionViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
Labels: [Type] Enhancement, Blogging Reminders

#17053 Blogging Reminders - Fix ui issues
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduleFormatter.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowCompletionViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
Labels: [Type] Bug, Blogging Reminders

#17045 Track analytic event when editor help is shown
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: [Type] Enhancement, Analytics

#17029 Task/16941 - Close account
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/AccountSettingsService.swift
  WordPress/Classes/Utility/ImmuTableViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/DeleteSiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/DestructiveAlertHelper.swift
  WordPress/Classes/ViewRelated/Me/Account Settings/AccountSettingsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Pri] High, /Me, [Type] Task

#17052 Post Settings: Remove ability to set post location
  MIGRATIONS.md
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Post+CoreDataProperties.swift
  WordPress/Classes/Models/Post.swift
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/ViewRelated/Cells/PostGeolocationCell.h
  WordPress/Classes/ViewRelated/Cells/PostGeolocationCell.m
  WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationView.h
  WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationView.m
  WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.h
  WordPress/Classes/ViewRelated/Post/Geolocation/PostGeolocationViewController.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 132.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/CoreDataMigrationTests.m
  WordPress/WordPressTest/PostTests.swift
Labels: [Type] Bug, Post Settings, User-Facing

#17059 Edit Comment: show comment data from selected comment
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Comments/EditCommentSingleLineCell.swift
  WordPress/Classes/ViewRelated/Comments/EditCommentSingleLineCell.xib
  WordPress/Classes/ViewRelated/Comments/EditCommentTableViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Comments

#17048 Remove translations reviewers build
  .circleci/config.yml
  fastlane/Fastfile
Labels: Tooling

#17064 Merge 18.1.0.0 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/download_metadata.swift
Labels: Releases

#17065 Recommend App: Enable feature flag to public
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: /Me

#17075 Fix/16941 - Close account displayed localizable string
  WordPress/Classes/ViewRelated/Me/Account Settings/AccountSettingsViewController.swift
Labels: [Pri] High

#17088 Comment Detail: Create the initial view
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Comments

#17092 Comment edit: validate email address
  WordPress/Classes/ViewRelated/Comments/EditCommentSingleLineCell.swift
  WordPress/Classes/ViewRelated/Comments/EditCommentSingleLineCell.xib
  WordPress/Classes/ViewRelated/Comments/EditCommentTableViewController.swift
Labels: [Type] Enhancement, Comments

#17093 Comment edit: show confirmation alert when cancelling with changes
  WordPress/Classes/ViewRelated/Comments/EditCommentMultiLineCell.swift
  WordPress/Classes/ViewRelated/Comments/EditCommentSingleLineCell.swift
  WordPress/Classes/ViewRelated/Comments/EditCommentTableViewController.swift
Labels: [Type] Enhancement, Comments

#17089 Added pull-to-refresh to My Site.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: [Type] Enhancement
