Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2021-12, with the labels that each got.

#17600 Reader Comments: Handle content cell action buttons
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17602 Reader post comments: set custom button border color
  WordPress/Classes/ViewRelated/Cells/BorderedButtonTableViewCell.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
Labels: Reader, Comments, Part of a WIP Feature

#17608 Onboarding Improvements: Don't show quick start for P2s
  WordPress/Classes/ViewRelated/Blog/QuickStartSettings.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: [Type] Task, Onboarding Improvements: Existing Users

#17604 Reader post comments: don't show Comments table if there are no comments.
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: Reader, Comments, Part of a WIP Feature

#17607 Tweak UI tests to attempt addressing inconsistent failures
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Testing

#17601 Reader Comments: Overflow dropdown menu
  WordPress/Classes/Models/Comment+CoreDataClass.swift
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17611 Onboarding Improvements: fix Quick Start prompt when adding a site and for P2s
  WordPress/Classes/Models/Blog+Lookup.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartPromptViewController.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartSettings.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyStep.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/UITestsFoundation/Screens/Login/LoginUsernamePasswordScreen.swift
  WordPress/WordPressUITests/Tests/LoginTests.swift
Labels: [Type] Bug, Quick Start, Onboarding Improvements: Existing Users

#17584 Update WPMediaPicker from version 1.7.2 to 1.8.0-beta.1
  Podfile
  Podfile.lock
Labels: Tooling

#17612 Adds tracking to the Add Site buttons
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Add Site/AddSiteAlertFactory.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController+SiteCreation.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
Labels: [Type] Task, Site Creation, Tracks

#17609 Fix Reader detail headers with featured images on iOS 15
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: [Type] Bug, Reader

#17613 Reader post comments: align content
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
Labels: Reader, Comments, Part of a WIP Feature

#17610 Switch About screen to use AutomatticAbout Swift package
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AboutHeaderView.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AboutScreenConfiguration.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AppAboutScreenConfiguration.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AutomatticAboutScreen.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AutomatticAppLogosCell.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/System/OrientationLimited.swift
  WordPress/Resources/AppImages.xcassets/Unified About/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/automattic-logo.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/automattic-logo.imageset/automattic-logo-dark.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/automattic-logo.imageset/automattic-logo.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-dayone.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-dayone.imageset/ua-logo-dayone.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-jetpack.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-jetpack.imageset/ua-logo-jetpack.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-pocketcasts.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-pocketcasts.imageset/ua-logo-pocketcasts.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-simplenote.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-simplenote.imageset/ua-logo-simplenote.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-tumblr.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-tumblr.imageset/tumblr-white.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-tumblr.imageset/ua-logo-tumblr.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-woo.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-woo.imageset/ua-logo-woo.pdf
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-wp.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Unified About/ua-logo-wp.imageset/ua-logo-wp.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: About Screen

#17593 Add UI test to verify the site stats are being loaded properly
  WordPress/UITestsFoundation/Screens/StatsScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Tests/StatsTests.swift
Labels: Testing

#17504 Add UI test to check that contact us can be loaded during login flow
  .buildkite/commands/build-for-testing.sh
  WordPress/UITestsFoundation/Screens/Login/Unified/GetStartedScreen.swift
  WordPress/UITestsFoundation/Screens/Me/ContactUsScreen.swift
  WordPress/UITestsFoundation/Screens/Me/SupportScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Tests/SupportScreenTests.swift
Labels: Testing

#17617 Use the correct step when tapping the create buttons on the post signup interstitial
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
Labels: [Type] Task, Login, Tracks

#17619 Merge release/18.8 into develop (Release Notes)
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#17621 Merge release/18.8 into develop (Release Notes, take 2)
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Resources/AppStoreStrings.po
Labels: Releases

#17615 Reader post comments: show no comments view when there are no comments
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNoCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNoCommentCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader, Comments, Part of a WIP Feature

#17627 [Tooling] Fix complete_code_freeze push on tags
  fastlane/Fastfile
Labels: Tooling

#17625 Add notification type to userInfo for weekly roundup
  WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift
Labels: Notifications

#17622 Reader Comments: Add fallback implementation for overflow menu on iOS 13
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Views/MenuSheetViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17623 Reader Comments: Implement edit action on the overflow menu
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17629 Reader Comments: Implement moderation actions
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17599 Convert UI tests screens to be a ScreenObject subclasses – 6 of many
  WordPress/UITestsFoundation/Screens/Editor/AztecEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LinkOrPasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginCheckMagicLinkScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEmailScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginPasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginSiteAddressScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/GetStartedScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PrologueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/WelcomeScreen.swift
  WordPress/UITestsFoundation/Screens/Login/WelcomeScreenLoginComponent.swift
  WordPress/UITestsFoundation/Screens/MySitesScreen.swift
  WordPress/UITestsFoundation/Screens/PostsScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
  WordPress/WordPressUITests/Tests/EditorAztecTests.swift
Labels: Testing

#17631 Reader post comments: no comments and commenting closed view
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17634 Reader Comments: Refactor content cell to have configurable render method
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/ContentRenderer/CommentContentRenderer.swift
  WordPress/Classes/ViewRelated/Comments/ContentRenderer/WebCommentContentRenderer.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17643 Onboarding Improvements: persist the chosen site
  WordPress/Classes/ViewRelated/Blog/QuickStartPromptViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: [Type] Bug, Onboarding Improvements: Existing Users

#17642 Use derived context for WeeklyRoundup background task
  WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift
  WordPress/WordPressTest/LikeUserHelperTests.swift
Labels: [Type] Crash, Notifications

#17630 [Tooling] Migrate iOS13 Widgets to use App strings
  WordPress/Classes/Utility/AppLocalizedString.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetDifferenceCell.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetNoConnectionCell.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/Shared Views/WidgetUnconfiguredCell.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
  WordPress/WordPressAllTimeWidget/Base.lproj/Localizable.strings
  WordPress/WordPressStatsWidgets/Views/Localization/AppLocalizedString.swift
  WordPress/WordPressThisWeekWidget/Base.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/Base.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/TodayViewController.swift
  WordPress/WordPressTodayWidget/ar.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/bg.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/cs.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/cy.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/da.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/de.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-AU.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-CA.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/en-GB.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/es.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/fr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/he.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/hr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/hu.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/id.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/is.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/it.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ja.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ko.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/nb.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/nl.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pl.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pt-BR.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/pt.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ro.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/ru.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sk.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sq.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/sv.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/th.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/tr.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/zh-Hans.lproj/Localizable.strings
  WordPress/WordPressTodayWidget/zh-Hant.lproj/Localizable.strings
Labels: Tooling

#17636 [Tooling] Migrate ShareExtension to use strings from app bundle
  WordPress/Classes/ViewRelated/Aztec/Extensions/FormatBarItemProviders.swift
  WordPress/Classes/ViewRelated/Aztec/Extensions/Header+WordPress.swift
  WordPress/Classes/ViewRelated/Aztec/Extensions/TextList+WordPress.swift
  WordPress/Classes/ViewRelated/Views/NoResultsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/Base.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ShareCategoriesPickerViewController.swift
  WordPress/WordPressShareExtension/ShareData.swift
  WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressShareExtension/ShareModularViewController.swift
  WordPress/WordPressShareExtension/ShareNoticeConstants.swift
  WordPress/WordPressShareExtension/SharePostTypePickerViewController.swift
  WordPress/WordPressShareExtension/ShareTagsPickerViewController.swift
  WordPress/WordPressShareExtension/ar.lproj/Localizable.strings
  WordPress/WordPressShareExtension/bg.lproj/Localizable.strings
  WordPress/WordPressShareExtension/cs.lproj/Localizable.strings
  WordPress/WordPressShareExtension/cy.lproj/Localizable.strings
  WordPress/WordPressShareExtension/da.lproj/Localizable.strings
  WordPress/WordPressShareExtension/de.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-AU.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-CA.lproj/Localizable.strings
  WordPress/WordPressShareExtension/en-GB.lproj/Localizable.strings
  WordPress/WordPressShareExtension/es.lproj/Localizable.strings
  WordPress/WordPressShareExtension/fr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/he.lproj/Localizable.strings
  WordPress/WordPressShareExtension/hr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/hu.lproj/Localizable.strings
  WordPress/WordPressShareExtension/id.lproj/Localizable.strings
  WordPress/WordPressShareExtension/is.lproj/Localizable.strings
  WordPress/WordPressShareExtension/it.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ja.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ko.lproj/Localizable.strings
  WordPress/WordPressShareExtension/nb.lproj/Localizable.strings
  WordPress/WordPressShareExtension/nl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pl.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pt-BR.lproj/Localizable.strings
  WordPress/WordPressShareExtension/pt.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ro.lproj/Localizable.strings
  WordPress/WordPressShareExtension/ru.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sk.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sq.lproj/Localizable.strings
  WordPress/WordPressShareExtension/sv.lproj/Localizable.strings
  WordPress/WordPressShareExtension/th.lproj/Localizable.strings
  WordPress/WordPressShareExtension/tr.lproj/Localizable.strings
  WordPress/WordPressShareExtension/zh-Hans.lproj/Localizable.strings
  WordPress/WordPressShareExtension/zh-Hant.lproj/Localizable.strings
Labels: Tooling

#17637 Reader post details: don't show Comments table until fetching is successful.
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17638 Reader post comments: track source from where comments is viewed
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityContentRouter.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationContentRouter.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.h
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
  WordPress/WordPressTest/LikeUserHelperTests.swift
  WordPress/WordPressTest/MockContentCoordinator.swift
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17648 Onboarding Improvements: make text larger on Quick Start prompt
  WordPress/Classes/ViewRelated/Blog/QuickStartPromptViewController.swift
Labels: [Type] Task, Onboarding Improvements: Existing Users

#17641 Convert some UI tests screens to be `ScreenObject` subclasses – Part 7 of 7
  WordPress/UITestsFoundation/BaseScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginCheckMagicLinkScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginPasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginUsernamePasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/SignupCheckMagicLinkScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/SignupEpilogueScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
  WordPress/WordPressUITests/Screens/BaseScreen.swift
Labels: Testing

#17649 Onboarding Improvements: Fix self-hosted login -> wpcom login flow
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: [Type] Bug, Onboarding Improvements: Existing Users

#17657 Update WordPress-Editor-iOS version to 1.19.6
  Podfile
  Podfile.lock
Labels: Aztec, Gutenberg compatibility

#17651 Fix threaded comments source tracking
  WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityContentRouter.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationContentRouter.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.h
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
Labels: [Type] Bug, Reader, Comments, Tracks

#17650 Enable post details comments.
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Enhancement, Reader, Comments

#17660 Integrate gutenberg-mobile release 1.68.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#17658 Comments: Add tracking for comment sharing intent
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
Labels: [Type] Enhancement, Comments, Tracks

#17645 Comments: Show loading message when fetching data
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: [Type] Enhancement, Comments

#17655 Update AutomatticAbout Swift package to include recent fixes
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: About Screen

#17635 Reader Comments: Implement comment rendering via WPRichContent
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/ContentRenderer/RichCommentContentRenderer.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17652 Merge 18.8.0.4 beta into `develop`
  WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartPromptViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/de.lproj/Localizable.strings
  WordPress/Resources/es.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/sq.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  WordPress/Resources/zh-Hant.lproj/Localizable.strings
  WordPress/WordPressTest/LikeUserHelperTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-GB/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/es-MX/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
Labels: Releases

#17656 Reader Comments: Highlight the cell when it's focused or navigated to
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/WPStyleGuide+CommentDetail.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Labels: [Type] Enhancement, Reader, Comments, Part of a WIP Feature

#17669 Reader Comments: Hide comment thread moderation menu
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.swift
Labels: Reader, [Type] Task, Comments, Part of a WIP Feature

#17659 Reader Comments: Enable the new comment threads.
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Enhancement, Reader, [Status] DO NOT MERGE, Comments, User-Facing

#17662 Onboarding Improvements: Fix font scaling for the Quick Start prompt
  WordPress/Classes/ViewRelated/Blog/QuickStartPromptViewController.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartPromptViewController.xib
Labels: [Type] Bug, Onboarding Improvements: Existing Users

#17667 Merge finalized release 18.8 into `develop`
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#17671 Jetpack: add Sign In With Apple
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/JetpackDebug.entitlements
  WordPress/Jetpack/JetpackRelease.entitlements
Labels: [Type] Task, Sign In With Apple, Jetpack App

#17663 Fixes RTL layout in About screen
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: About Screen

#17664 Workaround for back button not being recognized by XCUITest
  WordPress/UITestsFoundation/Globals.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPostSettings.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorSettingsComponents/CategoriesComponent.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorSettingsComponents/TagsComponent.swift
  WordPress/UITestsFoundation/Screens/SiteSettingsScreen.swift
  WordPress/WordPressUITests/Flows/EditorFlow.swift
  WordPress/WordPressUITests/Flows/LoginFlow.swift
Labels: Testing

#17675 Jetpack: when using SIWA to create an account, show the no Jetpack sites screen
  WordPress/Classes/Utility/App Configuration/AuthenticationHandler.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/Classes/JetpackAuthenticationManager.swift
Labels: Sign In With Apple, Jetpack App

#17672 Merge 18.9 code freeze into develop
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: Releases

#17679 Follow Conversation: Fix cases where the follow button is missing
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Labels: [Type] Bug, Comments

#17678 Reader Comments: Fix crash when the app is backgrounded
  WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
Labels: [Type] Crash, Reader, Comments

#17685 Comments: Track comment editor opened.
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
Labels: [Type] Bug, Comments, Tracks

#17676 Cleanup Xcode project and unused files
  Gemfile.lock
  Podfile.lock
  WordPress/Classes/Models/Notifications/NotificationBlockGroup.swift
  WordPress/Classes/Models/PostTag+Comparable.swift
  WordPress/Classes/Models/ReaderSaveForLaterTopic.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistFooter.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/LayoutPickerCategoryCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/JetpackRestoreViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/Restore Options/JetpackRestoreOptionsCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/DefaultNewsManager.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/iOS 14 Widgets/BlogListViewController+StatsWidgets.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/Jetpack.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/JetpackScreenshotGeneration.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/OCLint.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/UITestsFoundation.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Alpha.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Internal.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressIntents.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressScreenshotGeneration.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressShareExtension.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressStatsWidgets.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressTodayWidget.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
  WordPress/WordPressStatsWidgets/Views/TodayWidgetSmallView.swift
  WordPress/WordPressStatsWidgets/Views/TodayWidgetView.swift
  WordPress/WordPressTest/Aztec/VideoProcessorTests.swift
  WordPress/WordPressTest/PageModelTest.m
  WordPress/WordPressTest/PostModelTest.m
  WordPress/WordPressTest/ViewRelated/Blog/BlogListViewControllerTests.m
  WordPress/WordPressTest/WordPressAPI/WordPressOrgXMLRPCValidatorTests.swift
  WordPressShared/WordPressShared/Core/Analytics/WPAnalytics.h
  WordPressShared/WordPressShared/Core/Utility/WPImageSource.h
  WordPressShared/WordPressShared/Core/Views/WPNoResultsView.h
  WordPressShared/WordPressShared/Core/Views/WPNoResultsView.m
Labels: Tooling

#17690 My Site Dashboard: Add feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Task, My Site Dashboard

#17682 [Tooling] Disable widgets script on L10n download
  Scripts/update-translations.rb
Labels: Tooling

#17683 [Tooling] Cleanup files scanned for NSLocalizedString
  Gemfile.lock
  WordPress/WordPressTest/I18n.swift
  WordPress/WordPressTest/PostTests.swift
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: Tooling

#17693 Jetpack: add SIWA to 18.9
  WordPress/Classes/Utility/App Configuration/AuthenticationHandler.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/Classes/JetpackAuthenticationManager.swift
  WordPress/Jetpack/JetpackDebug.entitlements
  WordPress/Jetpack/JetpackRelease.entitlements
Labels: Sign In With Apple, Jetpack App

#17691 Upgrade XCUITestHelpers from version 0.3.0 to 0.4.0
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/XCUIElement+Scroll.swift
  WordPress/UITestsFoundation/XCUIElement+Utils.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing

#17686 About screen: Disable haptics when app logos cell isn't visible
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: About Screen

#17692 Remove two outdated files
  RELEASE-CYCLE.md
  Scripts/manage-version.sh
Labels: Tooling

#17689 Limit video uploads on free sites
  RELEASE-NOTES.txt
  WordPress/Classes/Services/Stories/WPMediaPicker+MediaPicker.swift
  WordPress/Classes/Utility/Media/Blog+VideoLimits.swift
  WordPress/Classes/Utility/Media/VideoLimitsAlertPresenter.swift
  WordPress/Classes/Utility/Media/WPMediaAsset+VideoLimits.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Media/CameraCaptureCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryPicker.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Media

#17698 Disable domains feature flag for all configurations
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Task
