Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2021-04, with the labels that each got.

#16206 Jetpack: change "My site" icon
  WordPress/Classes/Utility/App Configuration/AppStyleGuide.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Jetpack/AppStyleGuide.swift
Labels: Jetpack App, [Type] Task

#16208 Reader > Related Posts: fix button states when post fails to load
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: Reader, [Type] Bug

#16192 Add WPAccount Lookup
  WordPress/Classes/Models/WPAccount+Lookup.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/AccountBuilder.swift
  WordPress/WordPressTest/WPAccount+LookupTests.swift
  WordPress/WordPressTest/WPAccount+ObjCLookupTests.m
Labels: Core Data, [Type] Enhancement

#16200 Unified Prologue - Fix layout issues
  WordPress/Classes/ViewRelated/NUX/ContentViews/Editor/UnifiedPrologueNotificationsContentView.swift
  WordPress/Classes/ViewRelated/NUX/ContentViews/Editor/UnifiedPrologueReaderContentView.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
Labels: Unified Login & Signup, [Type] Enhancement

#16202 Integrate gutenberg-mobile release 1.50.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#16207 Replace uses of WordPressBlue with Blue50
  WordPress/Classes/Extensions/Colors and Styles/UIColor+WordPressColors.swift
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Media/ImageLoader.swift
  WordPress/Classes/ViewRelated/Blog/SharingAccountViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLightNavigationController.swift
  WordPress/Classes/ViewRelated/Media/CircularProgressView.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Notifications/Milestone Notifications/ConfettiView.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Pages.m
  WordPress/Launch Screen.storyboard
Labels: Color Updates

#16213 Update uses of `accent` color with `primary`, to replace pink with blue
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collapsable Header Collection View Cell/CollapsableHeaderCollectionViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Post/Preview/PreviewWebKitViewController.swift
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/TemplatePreviewViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/Map/CountriesMapView.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
  WordPress/Jetpack/UIColor+JetpackColors.swift
Labels: Color Updates

#16203 Resolve retain cycle around the Filter bar in the Layout picker
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collabsable Header Filter Bar/CollapsableHeaderFilterBar.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignStep.swift
  WordPress/Classes/ViewRelated/Site Creation/FinalAssembly/SiteAssemblyStep.swift
  WordPress/Classes/ViewRelated/Site Creation/WebAddress/WebAddressStep.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizard.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/WizardNavigation.swift
  WordPress/Classes/ViewRelated/Wizards/WizardDelegate.swift
Labels: Site Creation, [Type] Bug

#16217 Unified prologue - add background circles
  WordPress/Classes/ViewRelated/NUX/ContentViews/Background/UnifiedPrologueBackgroundView.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedPrologueViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Unified Login & Signup, [Type] Enhancement

#16219 Unified Prologue - Update intro screen using SwiftUI
  WordPress/Classes/ViewRelated/NUX/ContentViews/UnifiedPrologueIntroContentView.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Unified Login & Signup, [Type] Enhancement

#15766 Limit Classic editor access on Simple WP.com sites to existing Classic posts
  .circleci/cache-version
  WordPress/Classes/Utility/Editor/GutenbergSettings.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
  WordPress/WordPressUITests/Flows/EditorFlow.swift
  WordPress/WordPressUITests/Tests/EditorAztecTests.swift
  WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
Labels: Gutenberg compatibility, Site Settings

#16221 Allow customization of NUX button view shadows constraints
  Podfile
  Podfile.lock
Labels: NUX, Unified Login & Signup

#16222 Unified Prologue - Use large title on iPad
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
Labels: Unified Login & Signup, [Type] Enhancement

#16227 Enable new prologue feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Unified Login & Signup

#16228 Remove target check from Podfile
  Podfile
  Podfile.lock
Labels: Jetpack App, Tooling

#16240 Fix Notifications no results view offset (and other issues)
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Labels: Large titles, Notifications

#16216 Jetpack: remove add site option
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/Utility/App Configuration/Protocol/TargetConfiguration.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Jetpack/AppConfiguration.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack App, [Type] Task

#16211 Jetpack App: Update App Settings and About screens
  WordPress/Classes/System/Constants.h
  WordPress/Classes/System/Constants.m
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/Utility/App Configuration/AppStyleGuide.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AboutViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Jetpack/AppConstants.swift
  WordPress/Jetpack/AppStyleGuide.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16224 Jetpack App: Remove the Connect Site option in the Login Epilogue
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift
  WordPress/Jetpack/AppConfiguration.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16257 Fix webview nav bar styles when using new nav bar appearance
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/WebKitViewController.swift
Labels: Large titles, Webviews

#16259 Notification Likes list: update user cell UI
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Views/LikeUserTableViewCell.swift
  WordPress/Classes/ViewRelated/Notifications/Views/LikeUserTableViewCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Likes, [Type] Enhancement

#16243 Merge 17.1 code freeze into develop
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/WordPressTest/PostCompactCellTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#16226 3D Touch Shortcuts: Fix stats shortcut for new nav appearance feature
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
Labels: Stats, [Type] Bug

#16212 Jetpack App: Disable new post shortcuts
  WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Jetpack/AppConfiguration.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16271 Notification Likes list: show user profile in bottom sheet when user tapped.
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSectionHeader.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSectionHeader.xib
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSheetViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileUserInfoCell.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileUserInfoCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Likes, [Type] Enhancement

#16272 Integrate gutenberg-mobile release 1.50.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#16275 Fix a translation issue
  WordPress/Resources/AppStoreStrings.po
Labels: Releases

#16280 Fix RTL support in NewBlogDetailHeaderView
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Labels: Large titles

#16266 Fix webview navbar colors in release/17.0
  WordPress/Classes/Utility/WebKitViewController.swift
Labels: Large titles, Webviews

#16229 Configure Kanvas aspect ratio cropping
  Podfile
  Podfile.lock
  WordPress/Classes/Services/Stories/StoryEditor.swift
Labels: WP Stories, [Status] In Progress

#16263 Jetpack App: Add dark mode variants to Jetpack Green shades
  WordPress/ColorPalette.xcassets/JetpackGreen0.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen10.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen100.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen20.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen30.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen40.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen5.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen50.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen60.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen70.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen80.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen90.colorset/Contents.json
Labels: Color Updates, Jetpack App, Jetpack Mobile, [Type] Task

#16264 Jetpack App: Update calendar selected color to use semantic colors
  WordPress/Classes/ViewRelated/Post/Scheduling/CalendarCollectionView.swift
Labels: Jetpack App, Jetpack Mobile, [Status] Needs Design Review, [Type] Task

#16265 Jetpack App: Update backup/restore progress colors
  WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
  WordPress/Classes/ViewRelated/Activity/RewindStatusTableViewCell.xib
Labels: Jetpack App, Jetpack Mobile, [Status] Needs Design Review, [Type] Task

#16276 Jetpack Section: Remove Feature Flags
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
  WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
  WordPress/Classes/ViewRelated/Activity/BaseActivityListViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationContentRouter.swift
Labels: Jetpack Mobile, [Type] Task

#16277 Jetpack App: Update lightAppBarTint color for Jetpack
  WordPress/Jetpack/UIColor+JetpackColors.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16279 Jetpack App: Update epilogue user info font
  WordPress/Classes/Utility/App Configuration/AppStyleGuide.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Jetpack/AppStyleGuide.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16284 Notification Likes list: show site row in user profile bottom sheet
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSectionHeader.xib
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSheetViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSiteCell.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSiteCell.xib
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileUserInfoCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Likes, [Type] Enhancement

#16286 Add Jetpack CI
  .circleci/config.yml
  WordPress/Jetpack/JetpackDebug.entitlements
  WordPress/Jetpack/JetpackRelease-Alpha.entitlements
  WordPress/Jetpack/JetpackRelease-Internal.entitlements
  WordPress/Jetpack/JetpackRelease.entitlements
  WordPress/WordPress.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/Jetpack-Fastfile
Labels: Tooling

#16288 Jetpack App: Update filter bar selected color for Jetpack
  WordPress/Jetpack/UIColor+JetpackColors.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16158 [Issue Fix] Task: Remove Site Switcher in the Editor
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
  WordPress/Classes/ViewRelated/Views/LoadingStatusView.swift
  WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
  WordPress/Classes/ViewRelated/Views/WPUploadStatusButton.m
Labels: Posting/Editing

#16300 Do Not Merge – Only here to trigger CI on #16158
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
  WordPress/Classes/ViewRelated/Views/LoadingStatusView.swift
  WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
  WordPress/Classes/ViewRelated/Views/WPUploadStatusButton.m
Labels: [Status] DO NOT MERGE

#16294 Notification Likes list: show user profile sheet from selected row
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSheetViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileUserInfoCell.xib
Labels: Likes, [Type] Enhancement

#16258 Jetpack App: Update the login flow
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/Utility/App Configuration/AppDependency.swift
  WordPress/Classes/Utility/App Configuration/AuthenticationHandler.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/AppConfiguration.swift
  WordPress/Jetpack/AppDependency.swift
  WordPress/Jetpack/Classes/JetpackAuthenticationManager.swift
  WordPress/Jetpack/Classes/ViewRelated/JetpackErrorViewModel.swift
  WordPress/Jetpack/Classes/ViewRelated/JetpackLoginErrorViewController.swift
  WordPress/Jetpack/Classes/ViewRelated/JetpackLoginErrorViewController.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, Jetpack App, Jetpack Mobile, Login, Unified Login & Signup, [Type] Task

#16302 User Profile: show site modal when site row tapped
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSheetViewController.swift
Labels: Likes, [Type] Enhancement

#16303 Comment Filters: remove feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Comments/CommentsList.storyboard
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/Classes/ViewRelated/Comments/WPStyleGuide+Comments.swift
Labels: Comments, [Type] Task

#16308 User Profile: show site in webView if there is no siteID
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSheetViewController.swift
Labels: Likes, [Type] Enhancement

#16298 Query for authors and hide separator in post list UI for empty author names.
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blog+BlogAuthors.swift
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/ViewRelated/Post/PostCardCell.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/Post/Revisions/RevisionsTableViewController.swift
  WordPress/WordPressTest/PostCardCellTests.swift
Labels: [Type] Bug

#16305 Jetpack: change Zendesk ticket subject
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Jetpack/AppConstants.swift
Labels: Jetpack App, Jetpack Mobile, Support, [Type] Task

#16315 Guards against integer overflow error
  WordPress/Classes/Utility/WPTableViewHandler.m
Labels: [Type] Bug

#16318 User Profile Site: views for loading states
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSheetViewController.swift
Labels: Likes, [Type] Enhancement

#16320 User Profile: add more vertical padding to site cell.
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSectionHeader.xib
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSiteCell.xib
Labels: Likes, [Type] Enhancement

#16316 Split custom app icons into colorful and light background sections
  WordPress/Classes/ViewRelated/Me/App Settings/AppIconViewController.swift
Labels: App Settings

#16285 Improve deep link support for mbar links
  WordPress/Classes/Utility/InteractiveNotificationsManager.swift
  WordPress/Classes/Utility/Universal Links/Route+Page.swift
  WordPress/Classes/Utility/Universal Links/Route.swift
  WordPress/Classes/Utility/Universal Links/Routes+Banners.swift
  WordPress/Classes/Utility/Universal Links/Routes+Mbar.swift
  WordPress/Classes/Utility/Universal Links/Routes+Me.swift
  WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
  WordPress/Classes/Utility/Universal Links/Routes+Notifications.swift
  WordPress/Classes/Utility/Universal Links/Routes+Post.swift
  WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
  WordPress/Classes/Utility/Universal Links/Routes+Start.swift
  WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
  WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MBarRouteTests.swift
  WordPress/WordPressTest/RouteMatcherTests.swift
Labels: Universal Links, [Type] Enhancement

#16314 Don't log errors on site icon 404s
  WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
Labels: [Type] Bug

#16282 Rework EditorThemeStore to be stored in CoreData
  MIGRATIONS.md
  Podfile
  Podfile.lock
  WordPress/Classes/Models/BlockEditorSettingElement+CoreDataClass.swift
  WordPress/Classes/Models/BlockEditorSettingElement+CoreDataProperties.swift
  WordPress/Classes/Models/BlockEditorSettings+CoreDataClass.swift
  WordPress/Classes/Models/BlockEditorSettings+CoreDataProperties.swift
  WordPress/Classes/Models/BlockEditorSettings+GutenbergEditorTheme.swift
  WordPress/Classes/Models/Blog+BlockEditorSettings.swift
  WordPress/Classes/Models/EditorTheme.swift
  WordPress/Classes/Services/BlockEditorSettingsService.swift
  WordPress/Classes/Stores/EditorThemeStore.swift
  WordPress/Classes/Stores/StoreContainer.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 120.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlockEditorSettingsServiceTests.swift
  WordPress/WordPressTest/EditorThemeTests.swift
  WordPress/WordPressTest/Test Data/get_wp_v2_themes_twentytwenty.json
  WordPress/WordPressTest/Test Data/get_wp_v2_themes_twentytwentyone.json
Labels: Core Data, Posting/Editing, [Type] Enhancement

#16325 Update prologue map asset
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapDark.pdf
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapDark.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapDark@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapDark@3x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapLight.pdf
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapLight.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapLight@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/page4Map.imageset/page4MapLight@3x.png
Labels: Unified Login & Signup

#16304 Jetpack: change notification constants
  WordPress/Classes/Services/NotificationSettingsService.swift
  WordPress/Classes/System/Constants.m
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Jetpack/AppConstants.swift
Labels: Jetpack App, Jetpack Mobile, Notifications, [Type] Task

#16324 Integrate gutenberg-mobile release 1.51.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#16323 Fix RTL support in NewBlogDetailHeaderView [17.1]
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
Labels: Large titles

#16319 Show posts in the app via their wordpress.com subdomain link
  WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
  WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
  WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
  WordPress/WordPress-Alpha.entitlements
  WordPress/WordPress-Internal.entitlements
  WordPress/WordPress.entitlements
Labels: Universal Links, [Type] Enhancement

#16322 Custom icons: add upgrade alert
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppIconViewController.swift
  WordPress/Classes/ViewRelated/System/FancyAlertViewController+AppIcons.swift
  WordPress/Resources/AppImages.xcassets/custom-icons-alert.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/custom-icons-alert.imageset/custom-icons-alert.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: App Settings, [Type] Enhancement

#16331 Merge 17.0.1 final into trunk
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#16327 User Profile: track events
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSheetViewController.swift
Labels: Likes, [Type] Enhancement

#16336 Merge 17.2 code freeze into develop
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/WordPressTest/CommentServiceTests.swift
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/Services/PostCoordinatorFailedPostsFetcherTests.swift
  WordPress/WordPressTest/Services/PostServiceSelfHostedTests.swift
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Controllers/PostListViewControllerTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Deliverfile
  fastlane/download_metadata.swift
Labels: Releases

#16335 AB testing: remove stories AB testing
  WordPress/Classes/Utility/AB Testing/ABTest.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonActionSheet.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
Labels: Analytics, [Type] Task

#16269 Set author display name on Post / Page creation, send author changes to API.
  Podfile
  Podfile.lock
  WordPress/Classes/Models/AbstractPost.m
  WordPress/Classes/Services/PostService.m
  WordPress/WordPressTest/PostTests.swift
Labels: [Type] Bug

#16333 Jetpack: add 'jpios' tracks prefix
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Jetpack/AppConstants.swift
Labels: Analytics, Jetpack App, Jetpack Mobile, [Type] Task

#16309 Jetpack Section: Display a warning if server credentials are missing
  WordPress/Classes/Services/JetpackWebViewControllerFactory.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/Restore Options/JetpackRestoreOptionsViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanStatusCell.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanStatusCell.xib
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanThreatDetailsViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanThreatDetailsViewController.xib
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/View Models/JetpackScanStatusViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/View Models/JetpackScanThreatViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, Jetpack Mobile, [Type] Task

#16344 Jetpack App: Disable Sign up and update the continue button title
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/AppConstants.swift
Labels: Login, Unified Login & Signup, [Type] Task

#16347 Enabling contact info in prod by toggling on feature flag.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Bug

#16334 Fix #16248: Move scheduling dismiss to didDisappear Verified a6b26d9
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController+PresentFrom.swift
Labels: [Type] Bug

#16283 Disable tracking for UI tests
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Testing

#16215 Feature/16183 unreplied comments filter
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blog+BlogAuthors.swift
  WordPress/Classes/Services/CommentService.h
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Comments/CommentAnalytics.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController+Filters.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: Comments, [Type] Enhancement

#16233 Enable UI tests on Gutenberg releases
  .circleci/config.yml
Labels: Testing

#16339 Jetpack App: Hide Reader
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/Jetpack/AppConfiguration.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16340 Jetpack App: Remove the "Create" floating action button
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Jetpack/AppConfiguration.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16346 Jetpack App: Hide the Jetpack section header title
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Jetpack/AppConfiguration.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16348 Fixes the dark mode color of the navigation bar background.
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/Colors and Styles/UIColor+WordPressColors.swift
Labels: Large titles

#16353 Likes: use WPKit endpoint changes
  Podfile
  Podfile.lock
  WordPress/WordPressTest/CommentServiceTests.swift
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: Likes, [Type] Enhancement

#16354 Fix #16248 in 17.2
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController+PresentFrom.swift
Labels: WP Stories

#16342 Fix: Undo action restores Gutenberg template content as Classic editor
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [Type] Bug

#16358 Fix: Refresh the post list after restoring a post
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Labels: [Type] Bug

#16355 Small UI component color fixes
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.xib
  WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.m
  WordPress/Classes/ViewRelated/Pages/RestorePageTableViewCell.xib
  WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.xib
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Pages.m
Labels: Notifications, Pages List

#16349 Feature: Add and set a property to mark local authors as deleted.
  MIGRATIONS.md
  WordPress/Classes/Models/BlogAuthor.swift
  WordPress/Classes/Services/BlogService+BlogAuthors.swift
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 121.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogServiceAuthorTests.swift
Labels: Posting/Editing

#16306 Hold jetpack installable builds
  .circleci/config.yml
Labels: Tooling

#16367 Add the edit context to the delete post call
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Posts List, [Type] Bug

#16361 Likes Notifications: add core data entities for user details.
  MIGRATIONS.md
  WordPress/Classes/Models/Notifications/Likes/LikeUser+CoreDataClass.swift
  WordPress/Classes/Models/Notifications/Likes/LikeUser+CoreDataProperties.swift
  WordPress/Classes/Models/Notifications/Likes/LikeUserPreferredBlog+CoreDataClass.swift
  WordPress/Classes/Models/Notifications/Likes/LikeUserPreferredBlog+CoreDataProperties.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 122.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Likes, [Type] Enhancement

#16373 Update homebrew before installing other tools
  .circleci/config.yml
Labels: Tooling

#16363 Jetpack App (Emphasis): Hide Quick Actions
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Header.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
  WordPress/Jetpack/AppConfiguration.swift
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16372 Jetpack App (Basics): Update stats highlight colors
  WordPress/Classes/Extensions/Colors and Styles/UIColor+WordPressColors.swift
  WordPress/Classes/ViewRelated/Stats/Charts/PeriodChart.swift
  WordPress/Jetpack/UIColor+JetpackColors.swift
Labels: Jetpack App, Jetpack Mobile, [Status] Needs Design Review, [Type] Task

#16383 Post likes: add to Core Data when fetched
  Podfile.lock
  WordPress/Classes/Models/Notifications/Likes/LikeUser+CoreDataProperties.swift
  WordPress/Classes/Services/LikeUserHelpers.swift
  WordPress/Classes/Services/PostService+Likes.swift
  WordPress/Classes/Services/PostService.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Likes, [Type] Enhancement

#16388 Integrate gutenberg-mobile release 1.51.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#16387 Jetpack App (Basics): Update notifications dot color
  WordPress/Jetpack/AppImages.xcassets/icon-tab-notifications-unread.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/icon-tab-notifications-unread.imageset/icon-tab-notifications-unread-muriel-dark.pdf
  WordPress/Jetpack/AppImages.xcassets/icon-tab-notifications-unread.imageset/icon-tab-notifications-unread-muriel.pdf
Labels: Jetpack App, Jetpack Mobile, [Type] Task

#16374 AB testing: update how experiments are assigned
  Podfile
  Podfile.lock
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/AB Testing/ABTest.swift
Labels: Analytics, [Type] Task

#16394 Comment and Post likes: get relevant IDs
  Podfile
  Podfile.lock
  WordPress/WordPressTest/CommentServiceTests.swift
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: Likes, [Type] Enhancement

#16398 Likes Notifications: add ID attributes to LikeUser entity.
  MIGRATIONS.md
  WordPress/Classes/Models/Notifications/Likes/LikeUser+CoreDataProperties.swift
  WordPress/Classes/Services/LikeUserHelpers.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 123.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Likes, [Type] Enhancement

#16365 Improves the coloring of the search fields throughout the App.
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+Search.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+ReaderComments.swift
Labels: Dark mode

#16390 Switch Prologue strings to use NSLocalizedString
  WordPress/Classes/ViewRelated/NUX/ContentViews/Editor/UnifiedPrologueEditorContentView.swift
  WordPress/Classes/ViewRelated/NUX/ContentViews/Editor/UnifiedPrologueReaderContentView.swift
Labels: Localization, Unified Login & Signup

#16399 Post likes: filter fetch requests when fetching and deleting likes
  WordPress/Classes/Services/PostService+Likes.swift
Labels: Likes, [Type] Enhancement

#16393 Refresh the post list after restoring a post
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Labels: Posts List, [Type] Bug

#16408 [Tooling] Add a linter rule for SwiftUI's LocalizedStringKey
  .swiftlint.yml
Labels: Tooling

#16407 Jetpack App: Updates the prologue screen
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/App Configuration/AuthenticationHandler.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/AppImages.xcassets/Prologue/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Prologue/circle-particle.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Prologue/circle-particle.imageset/circle-particle.pdf
  WordPress/Jetpack/AppImages.xcassets/Prologue/prologue-logo.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Prologue/prologue-logo.imageset/prologue-logo.pdf
  WordPress/Jetpack/Classes/JetpackAuthenticationManager.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueStyleGuide.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.xib
  WordPress/Jetpack/Classes/NUX/StarFieldView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, Jetpack App, Jetpack Mobile, Logged-out, Login, Unified Login & Signup, [Type] Enhancement

#16410 Like Notifications: use cached user info
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Views/LikeUserTableViewCell.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSheetViewController.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileSiteCell.swift
  WordPress/Classes/ViewRelated/User Profile Sheet/UserProfileUserInfoCell.swift
Labels: Likes, [Type] Enhancement

#16404 Adjust i18n issues for Page Design and Site Design flows
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/Preview/TemplatePreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/DesignSelection/SiteDesignContentCollectionViewController.swift
Labels: Site Creation, [Type] Bug, [Type] Tech Debt, i18n

#16416 Update internal icon set
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Contents.json
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-20x20.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-20x20@2x-1.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-20x20@2x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-20x20@3x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-29x29-1.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-29x29.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-29x29@2x-1.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-29x29@2x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-29x29@3x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-40x40.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-40x40@2x-1.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-40x40@2x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-40x40@3x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-60x60@2x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-60x60@3x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-76x76.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-76x76@2x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-83.5x83.5@2x.png
  WordPress/Resources/AppImages.xcassets/AppIcon-Internal.appiconset/Icon-App-iTunes.png
Labels: Tooling
