Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2021-07, with the labels that each got.

#16788 Address new Xcode 12.5 deprecated 'class' for protocol inheritance warning
  WordPress/Classes/Networking/Pinghub.swift
  WordPress/Classes/Utility/ImmuTable.swift
  WordPress/Classes/ViewRelated/Activity/ActivityTypeSelectorViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallStateView.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/StockPhotosDataLoader.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditorState.swift
  WordPress/Classes/ViewRelated/Post/Revisions/ShowRevisionsListManger.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteSearchViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTableCardCell.swift
  WordPress/Classes/ViewRelated/System/NetworkAware.swift
  WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
  WordPressFlux/Sources/WordPressFlux/Receipt.swift
Labels: Tooling

#16778 Track notification details opened when accessing a notification from up/down arrows
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
Labels: Tracks, [Type] Bug

#16784 Fix Blogging Reminders flow when called from Site Settings
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlow.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowIntroViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersNavigationController.swift
Labels: Blogging Reminders, [Type] Bug

#16789 Try/address some warnings
  WordPress/Classes/Extensions/UIViewController+NoResults.swift
  WordPress/Classes/Utility/ImmuTableViewController.swift
  WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
  WordPress/Classes/ViewRelated/Activity/CalendarViewController.swift
  WordPress/Classes/ViewRelated/Aztec/Media/MediaProgressCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Domain Credit/DomainCreditRedemptionSuccessViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/LanguageSelectorViewController.swift
  WordPress/Classes/ViewRelated/Cells/InlineEditableNameValueCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/Collabsable Header Filter Bar/CollapsableHeaderFilterBar.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/CategorySectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/Restore Status/JetpackBackupStatusViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/Restore Status/JetpackRestoreStatusViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanThreatDetailsViewController.swift
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorDataLoader.swift
  WordPress/Classes/ViewRelated/Plugins/PluginDirectoryViewModel.swift
  WordPress/Classes/ViewRelated/Plugins/PluginListViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingHeaderView.swift
  WordPress/Classes/ViewRelated/Post/Revisions/Browser/Diffs/RevisionDiffsPageManager.swift
  WordPress/Classes/ViewRelated/Post/Scheduling/SchedulingCalendarViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSavedPostCellActions.swift
  WordPress/Classes/ViewRelated/Stats/Charts/StatsBarChartView.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityDay.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.swift
  WordPress/Classes/ViewRelated/Stats/StatsForegroundObservable.swift
  WordPress/Classes/ViewRelated/Wizards/WizardDelegate.swift
Labels: [Type] Task

#16783 Comments: set moderation actions based on user role
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Comment.h
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
Labels: Comments, [Type] Enhancement

#16786 Stats Overview card: wrap labels if using accessibility text size
  WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.xib
Labels: Accessibility, Stats

#16411 [Global Styles] Implement Global Styles endpoint
  MIGRATIONS.md
  Podfile
  Podfile.lock
  WordPress/Classes/Models/BlockEditorSettingElement+CoreDataProperties.swift
  WordPress/Classes/Models/BlockEditorSettings+CoreDataProperties.swift
  WordPress/Classes/Models/BlockEditorSettings+GutenbergEditorSettings.swift
  WordPress/Classes/Models/BlockEditorSettings+GutenbergEditorTheme.swift
  WordPress/Classes/Models/Blog+BlockEditorSettings.swift
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Models/EditorTheme.swift
  WordPress/Classes/Services/BlockEditorSettingsService.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 127.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlockEditorSettingsServiceTests.swift
  WordPress/WordPressTest/EditorThemeTests.swift
  WordPress/WordPressTest/Test Data/wp-block-editor-v1-settings-success-NotThemeJSON.json
  WordPress/WordPressTest/Test Data/wp-block-editor-v1-settings-success-ThemeJSON.json
Labels: Core Data, Posting/Editing, Refactor, [Type] Enhancement

#16791 Issues/fixes likes glitch
  WordPress/Classes/Services/CommentService+Likes.swift
  WordPress/Classes/Services/LikeUserHelpers.swift
  WordPress/Classes/Services/PostService+Likes.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: Likes, [Type] Bug

#16781 The blogging reminders configuration is refreshed in Site Settings.
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlow.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersNavigationController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
Labels: Blogging Reminders

#16793 Stats > Published: fix unicode characters displaying in titles
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
Labels: Stats, [Type] Bug

#16790 Fix blogging reminders for the Jetpack App
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduler.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Blogging Reminders, Jetpack App, [Type] Bug

#16799 Adds a frequency label to the day picker for blogging reminders.
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduleFormatter.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowCompletionViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
Labels: Blogging Reminders, [Type] Enhancement

#16800 The blogging reminders configuration is refreshed in Site Settings.
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlow.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersNavigationController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
Labels: Blogging Reminders, [Type] Enhancement

#16798 Temporarily skip EditorGutenbergTests because of missing Blogging Reminders support
  WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
Labels: Testing

#16794 Merge editorialized release notes for 17.7
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#16804 Removes 2 warnings.
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
Labels: [Type] Task

#16801 Jetpack: fix tapping on notifications
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+QuickStart.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Jetpack/AppConstants.swift
Labels: Jetpack App, [Type] Bug

#16810 Merge editorialized release notes for 17.7 into develop
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#16780 Move Fastlane secrets outside of repository
  .configure
  fastlane/Fastfile
  fastlane/Jetpack-Fastfile
  fastlane/Matchfile
Labels: Tooling

#16767 Jetpack Section: do not show Restore when not available
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.storyboard
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Activity/BaseActivityListViewController.swift
  WordPress/Classes/ViewRelated/Activity/RewindStatus+multiSite.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Activity Log, Jetpack, [Type] Bug

#16811 Jetpack App: Fix app review link for Jetpack
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/Utility/Ratings/AppRatingsUtility.swift
  WordPress/Jetpack/AppConstants.swift
Labels: App Review Request, Jetpack App, User-Facing, [Type] Bug

#16802 Notifications: Adds scrolling to the selected comment
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityContentRouter.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationContentRouter.swift
  WordPress/WordPressTest/MockContentCoordinator.swift
Labels: Comments, Notifications, [Type] Enhancement

#16805 Deprecate `Deliverfile` in favor of `Fastfile`
  fastlane/Deliverfile
  fastlane/Fastfile
  fastlane/Jetpack-Fastfile
Labels: Tooling

#16699 Refactor Gallery as nested image blocks
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/GutenbergRefactoredGalleryUploadProcessorTests.swift
Labels: Posting/Editing, Refactor

#16809 Improve logging for site icon download errors
  WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
Labels: [Type] Task

#16818 [Gutenberg] Add /oembed/1.0 endpoint support for wpcom API
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergNetworking.swift
Labels: Gutenberg integration

#16803 Fix Blogging Reminders flow when called from Site Settings
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlow.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowIntroViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersNavigationController.swift
Labels: Blogging Reminders, [Type] Bug

#16819 Fix follow site button refresh issues
  RELEASE-NOTES.txt
  WordPress/Classes/Services/ReaderPostService.h
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/Services/ReaderTopicService.h
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
Labels: [Pri] High, [Type] Bug

#16828 Fixes an issue with the SignUp epilogue not dismissing sometimes.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: Signup, [Pri] Blocking, [Type] Bug

#16817 Jetpack App: Fix view state for "unavailable" scan state
  Podfile.lock
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/View Models/JetpackScanStatusViewModel.swift
Labels: Jetpack App, Jetpack Mobile, Scan, User-Facing, [Status] Needs Design Review, [Type] Bug

#16827 Update release toolkit
  Gemfile.lock
  fastlane/Pluginfile
Labels: Tooling

#16835 Try/fix notices lock issue
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersActions.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlow.swift
Labels: Blogging Reminders, [Type] Bug

#16834 Cherry-pick "Fix follow site button refresh issue (#16819)"
  WordPress/Classes/Services/ReaderPostService.h
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/Services/ReaderTopicService.h
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellActions.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
Labels: Releases

#16822 Jetpack App: Show error if the stats module is disabled
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/ViewRelated/Stats/Extensions/NoResultsViewController+StatsModule.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/StatsViewController+JetpackSettings.swift
  WordPress/Classes/ViewRelated/Stats/StatsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack App, Jetpack Mobile, Stats, User-Facing, [Type] Task

#16831 Jetpack: show title after login when no Jetpack sites are present
  WordPress/Jetpack/Classes/ViewRelated/Login Error/JetpackLoginErrorViewController.swift
  WordPress/Jetpack/Classes/ViewRelated/Login Error/JetpackLoginErrorViewController.xib
  WordPress/Jetpack/Classes/ViewRelated/Login Error/View Models/JetpackErrorViewModel.swift
  WordPress/Jetpack/Classes/ViewRelated/Login Error/View Models/JetpackNoSitesErrorViewModel.swift
  WordPress/Jetpack/Classes/ViewRelated/Login Error/View Models/JetpackNotFoundErrorViewModel.swift
  WordPress/Jetpack/Classes/ViewRelated/Login Error/View Models/JetpackNotWPErrorViewModel.swift
Labels: Jetpack App, [Type] Task

#16775 Adds Jetpack Add-ons to Zendesk tickets
  Podfile.lock
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/WordPressTest/ZendeskUtilsTests+Plans.swift
Labels: Zendesk, [Type] Enhancement

#16770 Dismiss suggestions on space keystroke
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: [Type] Enhancement

#16826 Create section header view for Comments and Notifications
  WordPress/Classes/ViewRelated/Views/List/ListTableHeaderView.swift
  WordPress/Classes/ViewRelated/Views/List/ListTableHeaderView.xib
  WordPress/Classes/ViewRelated/Views/List/WPStyleGuide+List.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#16836 Integrate gutenberg-mobile release 1.57.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#16847 Update the glotpress validator reference to ECR
  .buildkite/pipeline.yml
Labels: Tooling

#16842 Merge release 17.8 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/download_metadata.swift
Labels: Releases

#16849 Fix: always shows Stats for sites hosted in WP.com
  WordPress/Classes/Models/Blog.m
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/BlogTests.swift
Labels: Stats, [Pri] High, [Type] Bug

#16825 [Gutenberg] Expose display preview function to Gutenberg
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#16853 Add translation progress check for release notes
  fastlane/Fastfile
Labels: Tooling

#16843 Add List table view cell component
  WordPress/Classes/ViewRelated/Views/List/ListTableViewCell.swift
  WordPress/Classes/ViewRelated/Views/List/ListTableViewCell.xib
  WordPress/Classes/ViewRelated/Views/List/WPStyleGuide+List.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments, Notifications

#16855 Blogging Reminders is available for any user that can edit a post.
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
Labels: Blogging Reminders, [Type] Bug

#16841 Update AppCenter SDK from version 4.1.1 to 4.2.0
  Podfile
  Podfile.lock
Labels: Tooling

#16823 Update Global Styles endpoint to support non-experimental paths
  Podfile
  Podfile.lock
  WordPress/Classes/Services/BlockEditorSettingsService.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/WordPressTest/BlockEditorSettingsServiceTests.swift
  WordPress/WordPressTest/MockWordPressComRestApi.swift
Labels: Posting/Editing, [Type] Enhancement

#16846 [Gutenberg] Global Style Settings Analytics
  WordPress/Classes/Services/BlockEditorSettingsService.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
Labels: Analytics, [Type] Enhancement

#16872 Merge editorialized release notes for 17.8 into develop
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#16856 Implement List component for Comments
  WordPress/Classes/Extensions/Comment+Interface.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/Classes/ViewRelated/Comments/ListTableViewCell+Comments.swift
  WordPress/Classes/ViewRelated/Views/List/ListTableHeaderView.swift
  WordPress/Classes/ViewRelated/Views/List/ListTableHeaderView.xib
  WordPress/Classes/ViewRelated/Views/List/ListTableViewCell.swift
  WordPress/Classes/ViewRelated/Views/List/ListTableViewCell.xib
  WordPress/Classes/ViewRelated/Views/List/WPStyleGuide+List.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments, [Type] Enhancement

#16873 Stats: Fix enable stats module flow
  WordPress/Classes/ViewRelated/Stats/StatsViewController.m
Labels: Jetpack, Stats, [Type] Bug

#16871 Post likes summary: format count to look like a hyperlink.
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.swift
Labels: Likes, Reader, [Type] Enhancement

#16869 Comments: fix moderation options on Atomic sites
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
Labels: Atomic, Comments, [Type] Bug

#16870 Only extract author info on a new Post / Page if the user can query for authors.
  WordPress/Classes/Services/PostService.m
Labels: [Type] Bug

#16875 Like Enhancements: remove feature flags
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: Likes, [Type] Task

#16877 Fixes a crash when the value returned by Blog.version is not a string
  WordPress/Classes/Models/Blog.m
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/BlogTests.swift
Labels: [Pri] High, [Type] Crash

#16879 Integrate gutenberg-mobile release 1.57.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#16881 Likes List: add properties to track event
  WordPress/Classes/Services/CommentService+Likes.swift
  WordPress/Classes/Services/PostService+Likes.swift
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/WordPressTest/CommentServiceTests.swift
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: Analytics, Likes, [Type] Enhancement

#16884 Merge hotfix 17.7.1 into trunk
  WordPress/Classes/Models/Blog.m
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/BlogTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#16880 [Tooling] Fix hotfix lanes
  fastlane/Fastfile
Labels: Tooling

#16883 Merge hotfix 17.7.1 into release 17.8
  WordPress/Classes/Models/Blog.m
  WordPress/WordPressTest/BlockEditorSettingsServiceTests.swift
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/BlogTests.swift
Labels: Releases

#16724 [Gutenberg] Update dependencies from forks to use release tags
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#16893 Add missing files from PR #16856 to Jetpack target
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack App, Tooling

#16891 Reader Detail: Hide the author section when the author name is empty / missing
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.xib
Labels: Reader, [Type] Bug

#16899 Fix wpios_blogging_reminders_flow_dismissed event not showing
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersTracker.swift
Labels: Blogging Reminders, Tracks, [Type] Bug

#16903 Fixes broken tests in merge release 17.8 beta 3 into develop
  WordPress/WordPressTest/BlockEditorSettingsServiceTests.swift
Labels: Testing

#16896 Enable Global Style Support
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blog+BlockEditorSettings.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/WordPressTest/BlockEditorSettingsServiceTests.swift
Labels: Posting/Editing, [Type] Enhancement

#16887 Notifications: Disable swipe actions while the undo overlay is shown
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Labels: Notifications, [Type] Enhancement

#16898 Comment: convert `PostContentProvider` protocol methods to Swift
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Comment.h
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/Models/Comment.swift
  WordPress/Classes/Models/WPCommentContentViewProvider.h
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/ListTableViewCell+Comments.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments, [Type] Enhancement

#16906 Reader: Fixes an issue with reader comments being incorrectly rendered.
  Podfile.lock
  WordPress/Classes/Services/CommentService.m
Labels: Comments, Reader, [Type] Bug

#16885 Implement List component for Notifications
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
  WordPress/Classes/ViewRelated/Notifications/Views/ListTableViewCell+Notifications.swift
  WordPress/Classes/ViewRelated/Views/List/ListSimpleOverlayView.swift
  WordPress/Classes/ViewRelated/Views/List/ListSimpleOverlayView.xib
  WordPress/Classes/ViewRelated/Views/List/ListTableViewCell.swift
  WordPress/Classes/ViewRelated/Views/List/ListTableViewCell.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Notifications, [Type] Enhancement

#16905 Comment: convert ObjC statuses to Swift
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Models/Comment.h
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/Models/Comment.swift
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentsTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/ListTableViewCell+Comments.swift
Labels: Comments, [Type] Enhancement

#16908 Comment: address ObjC private methods
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/Models/Comment.swift
Labels: Comments, [Type] Enhancement

#16907 Redirect Terms and service to open the page in an external web view
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Logged-out, [Type] Bug

#16774 Only prefetch suggestions on supported sites
  WordPress/Classes/Services/SiteSuggestionService.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg compatibility, [Type] Bug

#16911 Integrate gutenberg-mobile release 1.58.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#16913 Comment: address ObjC public methods
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Comment.h
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/Models/Comment.swift
  WordPress/Classes/Models/PostContentProvider.h
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
Labels: Comments, [Type] Enhancement

#16919 Site Comments: swipe moderation options honor user role
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: Comments, [Type] Bug

#16917 Reader Comments: Add styles for table to improve readability
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
Labels: Comments, Reader, [Type] Enhancement

#16787 Use VMs to build on Macs
  .buildkite/commands/build-for-testing.sh
  .buildkite/pipeline.yml
  .bundle/config
  .gitignore
Labels: Tooling

#16925 Merge 17.9 code freeze into develop
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/download_metadata.swift
Labels: Releases

#16932 Tracks when the blogging reminders notification is tapped.
  WordPress/Classes/Utility/InteractiveNotificationsManager.swift
Labels: Tracks, [Type] Task

#16837 Add UI test to verify Help section loads
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Screens/Login/Unified/GetStartedScreen.swift
  WordPress/WordPressUITests/Screens/Me/SupportScreen.swift
  WordPress/WordPressUITests/Tests/SupportScreenTests.swift
Labels: Testing

#16928 Fix domain registration not working under some conditions
  Podfile
  Podfile.lock
Labels: Domain Registration, [Type] Bug

#16937 Correct helpButton accessibilityIdentifier
  WordPress/WordPressUITests/Screens/Login/Unified/GetStartedScreen.swift
Labels: Testing

#16938 Fix WordPressKit version in Podfile
  Podfile
  Podfile.lock
Labels: [Type] Task

#16933 Comment: store raw content
  MIGRATIONS.md
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Comment.h
  WordPress/Classes/Models/Comment.m
  WordPress/Classes/Models/Comment.swift
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/ViewRelated/Reader/ReaderCommentCell.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 128.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments, [Type] Enhancement

#16939 Adds the sandbox store secret debug menu item.
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Developer/StoreSandboxSecretScreen.swift
  WordPress/Classes/ViewRelated/Me/App Settings/DebugMenuViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Domain Registration, [Type] Task

#16936 Reader Post: Add animation to train of likes
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.xib
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.swift
  WordPress/WordPressTest/ReaderDetailCoordinatorTests.swift
Labels: Reader, [Type] Enhancement

#16944 Comments: fix crashes
  WordPress/Classes/Extensions/Comment+Interface.swift
  WordPress/Classes/Models/Comment.swift
  WordPress/Classes/Services/CommentService.m
Labels: Comments, [Type] Bug

#16927 Let http handle cookies when downloading images.
  WordPress/Classes/Services/AccountService+Cookies.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Media/ImageDownloader.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Notifications, [Type] Bug

#16929 Centralize Xcode version definition in Buildkite pipeline
  .buildkite/pipeline.yml
Labels: Tooling

#16948 Comments: merge fixes from 17.9
  WordPress/Classes/Extensions/Comment+Interface.swift
  WordPress/Classes/Models/Comment.swift
  WordPress/Classes/Services/CommentService.m
Labels: Comments, [Type] Bug

#16949 Comment: make `rawContent` optional
  MIGRATIONS.md
  WordPress/Classes/Models/Comment.swift
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Comments/CommentViewController.m
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 129.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments, Self-hosted, [Type] Bug

#16951 Comments: Fix crash when sending a reply that triggers a new section
  WordPress/Classes/Extensions/Comment+Interface.swift
  WordPress/Classes/Models/Comment.swift
Labels: Comments, [Type] Bug

#16955 Fixes an issue with Zendesk support.
  WordPress/Classes/Utility/ZendeskUtils.swift
Labels: [Type] Bug

#16945 Integrate gutenberg-mobile release 1.58.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration
