Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2022-10, with the labels that each got.

#19353 Remove the function that finds posts with upload failure
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
Labels: Core Data

#19363 Remove finding cached comments function from `CommentService`
  WordPress/Classes/Services/CommentService.h
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/Services/PostService.m
Labels: Core Data

#19386 Remove derived context from post coordinator
  WordPress/Classes/Models/AbstractPost+MarkAsFailedAndDraftIfNeeded.swift
  WordPress/Classes/Models/Post+RefreshStatus.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Services/PostService.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/PostService+MarkAsFailedAndDraftIfNeededTests.swift
  WordPress/WordPressTest/PostServiceUploadingListTests.swift
Labels: Core Data

#19349 WP.com abort login flow for self-hosted site
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [Type] Bug

#19354 Move creating post function out of PostService
  WordPress/Classes/Models/AbstractPost+Local.swift
  WordPress/Classes/Models/Blog+Post.swift
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/System/WordPressAppDelegate+openURL.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Pages/EditPageViewController.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+BlogPicker.swift
  WordPress/Classes/ViewRelated/Post/PostListEditorPresenter.swift
  WordPress/Classes/ViewRelated/Reader/ReaderReblogPresenter.swift
  WordPress/WordPressTest/PostTests.swift
  WordPress/WordPressTest/ReaderReblogActionTests.swift
Labels: Core Data

#19365 Move functions that find a comment by id out of CommentService
  WordPress/Classes/Models/Blog+Lookup.swift
  WordPress/Classes/Models/ReaderPost+Helper.swift
  WordPress/Classes/Services/CommentService.h
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationCommentDetailViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Core Data

#19391 Merge changes from 20.9 code freeze into `trunk`
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#19388 Mark `-[CoreDataStack newDerivedContext]` as deprecated
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/Services/ReaderSiteService.m
  WordPress/Classes/Utility/ContextManager.h
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Selector/BlogSelectorViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/WordPressTest/Aztec/AztecPostViewController+MenuTests.swift
  WordPress/WordPressTest/Aztec/AztecPostViewControllerAttachmentTests.swift
  WordPress/WordPressTest/BlogTitleTests.swift
  WordPress/WordPressTest/BlogVideoLimitsTests.swift
  WordPress/WordPressTest/Classes/Stores/StatsWidgetsStoreTests.swift
  WordPress/WordPressTest/Dashboard/BlogDashboardPostsParserTests.swift
  WordPress/WordPressTest/Dashboard/BlogDashboardServiceTests.swift
  WordPress/WordPressTest/Dashboard/DashboardCardTests.swift
  WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift
  WordPress/WordPressTest/PostCardCellTests.swift
  WordPress/WordPressTest/PostListFilterTests.swift
  WordPress/WordPressTest/ReaderCardTests.swift
  WordPress/WordPressTest/Services/PostCoordinatorFailedPostsFetcherTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Utils/PostNoticeViewModelTests.swift
  WordPress/WordPressTest/ViewRelated/Post/Views/PostCardStatusViewModelTests.swift
Labels: Core Data

#19389 PR review follow up
  WordPress/Classes/Models/Post+RefreshStatus.swift
  WordPress/Classes/Services/PostCoordinator.swift
Labels: Core Data

#19393 Stats: Show Views Visitors for this week instead of last 7 days
  WordPress/Classes/ViewRelated/Stats/Helpers/SiteStatsImmuTableRows.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsInsightsDetailsViewModel.swift
  WordPress/WordPressTest/ViewRelated/Stats/Insights/SiteStatsInsightViewModelTests.swift
Labels: Stats, Stats Revamp

#19360 Fix cached notifications appear when logout
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+JetpackPrompt.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Notification/Controllers/NotificationsViewControllerTests.swift
Labels: [Type] Bug

#19382 [CI only] Ci/19075/fix cached notifications appear when logout
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+JetpackPrompt.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Notification/Controllers/NotificationsViewControllerTests.swift
Labels: [Status] DO NOT MERGE

#19392 Stats Revamp: Fix Insights cards not adapting to large device text size
  WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartView.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/WPStyleGuide+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.xib
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityLegend.xib
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityMonth.xib
  WordPress/Classes/ViewRelated/Stats/Insights/StatsBaseCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/StatsLatestPostSummaryInsightsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/StatsMostPopularTimeInsightsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/StatsTotalInsightsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.xib
  WordPress/Classes/ViewRelated/Stats/Insights/ViewsVisitors/ViewsVisitorsLineChartCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/ViewsVisitors/ViewsVisitorsLineChartCell.xib
Labels: [Type] Bug, Accessibility, Stats, Stats Revamp

#19399 Merge editorialized release notes for version 20.9
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#19384 Tooling: Adds support for Jetpack extensions & widgets to code signing lanes
  Gemfile.lock
  WordPress/WordPress.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/lanes/codesign.rb
  fastlane/lanes/localization.rb
Labels: [Type] Task, Tooling, Jetpack Focus

#19409 Update expected Bundler to version 2.3.23
  Gemfile.lock
Labels: Tooling

#19404 Jetpack Landing Screen - Change gradient and button colors
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueStyleGuide.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
Labels: [Type] Task, Jetpack Focus

#19341 Change WordPress / Jetpack launch screen
  RELEASE-NOTES.txt
  WordPress/Jetpack/Launch Screen.storyboard
  WordPress/Launch Screen.storyboard
  WordPress/Resources/AppImages.xcassets/icon-wp-filled.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/icon-wp-filled.imageset/icon-wp-filled-dark.pdf
  WordPress/Resources/AppImages.xcassets/icon-wp-filled.imageset/icon-wp-filled.pdf
Labels: Jetpack Focus

#19395 Reimplement invaliding `Notification` attributes cache
  WordPress/Classes/Models/Notifications/Notification.swift
  WordPress/WordPressTest/NotificationTests.swift
Labels: [Status] DO NOT MERGE, Core Data

#19407 [iOS] Stats: Rename card titles
  WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
Labels: [Type] Enhancement, Stats, Stats Revamp

#19416 Stats Revamp: Two Column Cell with View More button cuts off
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.xib
Labels: [Type] Bug, Stats, Stats Revamp

#19387 Comments Detail Redesign
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Cells/BorderedButtonTableViewCell.swift
  WordPress/Classes/ViewRelated/Cells/SingleButtonTableViewCell.swift
  WordPress/Classes/ViewRelated/Cells/SingleButtonTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/CommentDetailInfoViewController.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailInfoViewModel.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Comments/WPStyleGuide+CommentDetail.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments

#19418 Fix crash on tapping Account Settings menu for accounts with no sites
  Gemfile.lock
  WordPress/Classes/ViewRelated/Me/Account Settings/AccountSettingsViewController.swift
Labels: [Type] Crash, [Pri] High, Account Settings

#19383 Share Extension: Add share extension for the Jetpack app
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/JetpackShareExtension/Info-Alpha.plist
  WordPress/JetpackShareExtension/Info-Internal.plist
  WordPress/JetpackShareExtension/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
  fastlane/Fastfile
  fastlane/lanes/codesign.rb
  fastlane/lanes/localization.rb
Labels: [Type] Task, Share Extension, Jetpack Focus

#19414 Draft Extension: Add draft extension for the Jetpack app
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/AppImages.xcassets/jp-extension-icon.appiconset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/jp-extension-icon.appiconset/jp-extension1024.png
  WordPress/Jetpack/AppImages.xcassets/jp-extension-icon.appiconset/jp-extension167.png
  WordPress/Jetpack/AppImages.xcassets/jp-extension-icon.appiconset/jp-extension76.png
  WordPress/Jetpack/AppImages.xcassets/jp-extension-icon.appiconset/jp-extension@2x.png
  WordPress/Jetpack/AppImages.xcassets/jp-extension-icon.appiconset/jp-extension@3x.png
  WordPress/JetpackDraftActionExtension/Info-Alpha.plist
  WordPress/JetpackDraftActionExtension/Info-Internal.plist
  WordPress/JetpackDraftActionExtension/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/MainShareViewController.swift
Labels: [Type] Task, Draft Extension, Jetpack Focus

#19374 Extra blog query functions in BlogService to BlogQuery
  WordPress/Classes/Models/Blog+History.swift
  WordPress/Classes/Models/Blog+Lookup.swift
  WordPress/Classes/Services/BlogService+JetpackConvenience.swift
  WordPress/Classes/Services/BlogService.h
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/Services/NotificationSettingsService.swift
  WordPress/Classes/Stores/StatsWidgetsStore.swift
  WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift
  WordPress/Classes/Utility/AccountHelper.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/Utility/Automated Transfer/AutomatedTransferHelper.swift
  WordPress/Classes/Utility/BlogQuery.swift
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/Utility/Editor/GutenbergRollout.swift
  WordPress/Classes/Utility/Editor/GutenbergSettings.swift
  WordPress/Classes/Utility/Spotlight/SearchManager.swift
  WordPress/Classes/Utility/Universal Links/NavigationActionHelpers.swift
  WordPress/Classes/Utility/WPAuthTokenIssueSolver.m
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
  WordPress/Classes/ViewRelated/Reader/ReaderReblogPresenter.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/AccountServiceTests.swift
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/BlogJetpackTest.m
  WordPress/WordPressTest/BlogQueryTests.swift
  WordPress/WordPressTest/BlogServiceMock.swift
  WordPress/WordPressTest/BlogServiceTest.m
  WordPress/WordPressTest/Classes/Stores/StatsWidgetsStoreTests.swift
  WordPress/WordPressTest/ReaderReblogActionTests.swift
Labels: Core Data

#19415 Rich Notifications: Enable rich notifications for the Jetpack app
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/JetpackNotificationServiceExtension/Info-Alpha.plist
  WordPress/JetpackNotificationServiceExtension/Info-Internal.plist
  WordPress/JetpackNotificationServiceExtension/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Rich Notifications, Jetpack Focus

#19400 Stats Revamp: Inconsistent rounding of numbers in the cards
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Insights/ViewsVisitors/ViewsVisitorsLineChartCell.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
Labels: Stats, Stats Revamp

#19421 Explicitly prevent `xcodebuild` from changing the binary's build number
  fastlane/lanes/build.rb
Labels: Releases

#19390 Replace a couple usages of `newDerivedContext` with `performAndSave`
  WordPress/Classes/Services/PeopleService.swift
  WordPress/Classes/Utility/Media/MediaFileManager.swift
Labels: Core Data

#19423 Replace some `newDerivedContext` in ObjC with `performAndSave`
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog Selector/BlogSelectorViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
Labels: Core Data

#19422 Replace context object with `CoreDataStack` in `NotificationSettingsService`
  RELEASE-NOTES.txt
  WordPress/Classes/Services/NotificationSettingsService.swift
  WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift
  WordPress/Classes/Utility/PushNotificationsManager.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
  WordPress/WordPressTest/NotificationSettingsServiceTests.swift
Labels: Core Data

#19412 Add reminders schedule syncing for Jetpack
  WordPress/Classes/Stores/UserPersistentRepositoryUtility.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduler.swift
Labels: [Type] Task, Jetpack Focus

#19350 Show prepublish dialog in portrait only if title is present
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
Labels: [Type] Bug, WP Stories

#19410 [Jetpack] Use an infinite scrolling view for Jetpack landing screen
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/ViewModel/JetpackPromptsConfiguration.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/ViewModel/JetpackPromptsViewModel.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/InfiniteScrollerView.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/InfiniteScrollerViewDelegate.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackLandingScreenView.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackPromptView.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackPromptsView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, [Type] Task

#19432 [Jetpack landing screen] Override content offset so we can store sub-point deltas
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/InfiniteScrollerView.swift
Labels: Jetpack, [Type] Task

#19442 [Jetpack landing screen] Add vertical spacing where repeated views are connected
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackLandingScreenView.swift
Labels: Jetpack, [Type] Task

#19441 Shared Login: Remove app check when copying keychain and database
  WordPress/Classes/Utility/ContextManager.m
  WordPress/Classes/Utility/KeychainUtils.swift
Labels: [Type] Bug, Shared Login

#19443 [Jetpack landing screen] Update typography and prompts text
  WordPress/Jetpack/Classes/NUX/New Landing Screen/ViewModel/JetpackPromptsConfiguration.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackPromptView.swift
Labels: Jetpack, [Type] Task

#19434 [Jetpack landing screen] Use device pitch angle to determine velocity and direction of prompts
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
Labels: Jetpack

#19464 Merge release 20.9 finalization into `trunk`
  WordPress/Resources/pt-BR.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#19462 Integrate gutenberg-mobile release 1.84.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#19440 Comment Details: Add Activity Indicator to Moderation Cells
  WordPress/Classes/ViewRelated/Cells/BorderedButtonTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
Labels: Comments

#19461 Fix an issue where the Login navigation bar disappears during a pop a…
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [Type] Bug, Jetpack App

#19468 [Jetpack landing screen] Reduce logo size
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
Labels: Jetpack, [Type] Task

#19469 [Jetpack landing screen] Remove two-line prompt limit
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackPromptView.swift
Labels: Jetpack, [Type] Task

#19470 Hide logo and background image from VoiceOver.
  WordPress/Classes/ViewRelated/NUX/SplashPrologueView.swift
Labels: Accessibility, Jetpack, [Type] Task

#19463 Fix a crash when attempting to purchase domains
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+DomainCredit.swift
  WordPress/Classes/ViewRelated/Domains/Domain credit/DomainCreditRedemptionSuccessViewController.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/DomainSuggestionViewControllerWrapper.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
Labels: [Type] Bug, Domains

#19293 Remote Feature Flags: Refresh feature flags more often and make authenticated request if possible
  WordPress/Classes/Stores/RemoteFeatureFlagStore.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/AccountHelper.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/InMemoryUserDefaults.swift
  WordPress/WordPressTest/RemoteFeatureFlagTests.swift
Labels: [Type] Enhancement, Core

#19428 Stats Revamp: Views and Visitors showing data for the previously selected period or site
  WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift
  WordPress/Classes/ViewRelated/Stats/Insights/InsightType.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: [Type] Bug, Stats, Stats Revamp

#19427 Remove `newDerivedContext` in `ReaderCardService`
  RELEASE-NOTES.txt
  WordPress/Classes/Services/ReaderCardService.swift
  WordPress/WordPressTest/ReaderCardServiceTests.swift
Labels: Core Data

#19458 Remove a few usages of `newDerivedContext`
  RELEASE-NOTES.txt
  WordPress/Classes/Services/ReaderSiteService.m
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
Labels: Core Data

#19459 Attempt to use docker to run danger
  .buildkite/pipeline.yml
Labels: Core

#19473 Tweak a localization to remove any assumption on "+" localization
  WordPress/Classes/ViewRelated/Stats/Insights/ViewsVisitors/ViewsVisitorsLineChartCell.swift
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/StatsSegmentedControlDataTests.swift
Labels: Localization, Releases

#19472 Merge 21.0 (21.0.0) code freeze into `trunk`
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Insights/ViewsVisitors/ViewsVisitorsLineChartCell.swift
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/StatsSegmentedControlDataTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#19435 Remove `newDerivedContext` from `MediaLibraryPickerDataSource`
  WordPress/Classes/Models/Blog+Media.swift
  WordPress/Classes/Services/MediaService.h
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MediaTests.swift
Labels: Core Data

#19433 Turn on feature flag to the new Core Data context structure
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/WordPressTest/ContextManagerTests.swift
Labels: Core Data

#19481 Enables the new Jetpack Landing Screen
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/Classes/JetpackAuthenticationManager.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueStyleGuide.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
Labels: [Type] Task, Jetpack Focus

#19482 Merge editorialized release notes for version 21.0 into `trunk`
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#19486 Integrate gutenberg-mobile release 1.84.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#19483 Core: Add support for remote configuration
  Podfile
  Podfile.lock
  WordPress/Classes/Stores/RemoteConfigStore.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/BuildInformation/RemoteConfig.swift
  WordPress/Classes/Utility/BuildInformation/RemoteConfigParameter.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/RemoteConfigParameterTests.swift
Labels: [Type] Task, Core

#19485 Fix wp landing screen brush image stretching issue on iPad
  WordPress/Classes/ViewRelated/NUX/SplashPrologueView.swift
  WordPress/Resources/AppImages.xcassets/Prologue/SplashPrologue/splashBrushStroke.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Prologue/SplashPrologue/splashBrushStroke.imageset/splashBrushStroke.pdf
  WordPress/Resources/AppImages.xcassets/Prologue/SplashPrologue/splashBrushStroke.imageset/splashBrushStroke.png
  WordPress/Resources/AppImages.xcassets/Prologue/SplashPrologue/splashBrushStroke.imageset/splashBrushStroke@2x.png
  WordPress/Resources/AppImages.xcassets/Prologue/SplashPrologue/splashBrushStroke.imageset/splashBrushStroke@3x.png
Labels: [Type] Bug, [Pri] Low, Login

#19456 Draft Extension: Update display string for Jetpack's draft action
  WordPress/JetpackDraftActionExtension/Info.plist
  WordPress/JetpackDraftActionExtension/en.lproj/InfoPlist.strings
  WordPress/WordPress.xcodeproj/project.pbxproj
  fastlane/lanes/localization.rb
Labels: [Type] Task, Draft Extension, Jetpack Focus

#19497 Tweak Jetpack Landing Screen prompts spacing and colors to align with the design
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/ViewModel/JetpackPromptsConfiguration.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackLandingScreenView.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackPromptView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Login, Jetpack App, Jetpack Focus

#19479 Jetpack Focus: Enable iOS14+ Stats Widgets and Intents for Jetpack
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/TodayExtensionService.m
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/Stores/StatsWidgetsStore.swift
  WordPress/Classes/System/Constants.h
  WordPress/Classes/System/Constants.m
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/Utility/App Configuration/WidgetConfiguration.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/AllTimeWidgetStats.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/ThisWeekWidgetStats.swift
  WordPress/Classes/ViewRelated/Stats/Today Widgets/Data/TodayWidgetStats.swift
  WordPress/Jetpack/AppConstants.swift
  WordPress/Jetpack/WidgetConfiguration.swift
  WordPress/JetpackIntents/Info.plist
  WordPress/JetpackStatsWidgets/Info.plist
  WordPress/JetpackStatsWidgets/LocalizationConfiguration.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/JetpackIntents.xcscheme
  WordPress/WordPressAllTimeWidget/AllTimeViewController.swift
  WordPress/WordPressIntents/SitesDataProvider.swift
  WordPress/WordPressStatsWidgets/Model/HomeWidgetAllTimeData.swift
  WordPress/WordPressStatsWidgets/Model/HomeWidgetThisWeekData.swift
  WordPress/WordPressStatsWidgets/Model/HomeWidgetTodayData.swift
  WordPress/WordPressStatsWidgets/Remote service/StatsWidgetsService.swift
  WordPress/WordPressStatsWidgets/SiteListProvider.swift
  WordPress/WordPressStatsWidgets/Tracks/Tracks+StatsWidgets.swift
  WordPress/WordPressStatsWidgets/Views/Cards/VerticalCard.swift
  WordPress/WordPressStatsWidgets/Views/Localization/LocalizableStrings.swift
  WordPress/WordPressStatsWidgets/Views/Localization/LocalizationConfiguration.swift
  WordPress/WordPressStatsWidgets/Views/UnconfiguredView.swift
  WordPress/WordPressStatsWidgets/Widgets/WordPressHomeWidgetAllTime.swift
  WordPress/WordPressStatsWidgets/Widgets/WordPressHomeWidgetThisWeek.swift
  WordPress/WordPressStatsWidgets/Widgets/WordPressHomeWidgetToday.swift
  WordPress/WordPressThisWeekWidget/ThisWeekViewController.swift
  WordPress/WordPressTodayWidget/TodayViewController.swift
Labels: Stats, Stats Widgets, Jetpack Focus

#19522 Update MediaPicker to 1.8.6
  Podfile.lock
Labels: [Type] Bug

#19520 [Crash] Fix crash on 3 dots menu in Comments Screen
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
Labels: Comments, Releases

#19503 Jetpack Focus: Create Jetpack phases helper
  WordPress/Classes/Stores/RemoteFeatureFlagStore.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackBrandingCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackFeaturesRemovalCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/JetpackFeaturesRemovalCoordinatorTests.swift
  WordPress/WordPressTest/RemoteFeatureFlagTests.swift
Labels: [Type] Task, Jetpack Focus

#19527 Integrate gutenberg-mobile release 1.85.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#19529 [Fix] Comment Details Accessory Icon
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
Labels: Comments, Releases

#19524 Make Jetpack custom icons available for iPad
  WordPress/Jetpack/Info.plist
Labels: [Type] Bug, Jetpack, Jetpack App

#19523 Replace deprecated `mediumString()` usage with valid alternative
  WordPress/WordPressTest/ReaderPostCardCellTests.swift
Labels: Testing

#19532 Merge changes from release 21.0 finalization into `trunk`
  Podfile.lock
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Jetpack/Info.plist
  WordPress/Resources/id.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#19526 Jetpack Focus: Enable separate tracking for Jetpack extensions and widgets
  WordPress/Jetpack/TracksConfiguration.swift
  WordPress/Tracks+ShareExtension.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressDraftActionExtension/Tracks+DraftAction.swift
  WordPress/WordPressNotificationContentExtension/Sources/Tracks/Tracks+ContentExtension.swift
  WordPress/WordPressNotificationServiceExtension/Sources/Tracks/Tracks+ServiceExtension.swift
  WordPress/WordPressShareExtension/Tracks.swift
  WordPress/WordPressShareExtension/TracksConfiguration.swift
  WordPress/WordPressStatsWidgets/Tracks/Tracks+StatsWidgets.swift
Labels: Stats, iOS 14 Widgets

#19506 [Jetpack landing screen] Add padding, enlarge text and enlarge logo on iPad
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackLandingScreenView.swift
Labels: [Type] Enhancement, Jetpack App, Jetpack Focus

#19536 Merge changes from 21.1 code freeze into `trunk`
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#19492 Jetpack Content Migration Flow: Move synced database to single copy
  WordPress/Classes/Utility/ContextManager.m
  WordPress/Classes/Utility/CoreDataHelper.swift
Labels: [Type] Enhancement, Jetpack Focus, Shared Login, Jetpack Content Migration Flow
