Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2022-09, with the labels that each got.

#19265 Rollback to `LegacyContextFactory`
  WordPress/Classes/Utility/ContextManager.m
  WordPress/WordPressTest/ContextManagerTests.swift
Labels: Core Data

#19267 Merge beta 20.6.0.2 (localization smoke testing build) into `trunk`
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/tr/keywords.txt
  fastlane/metadata/tr/name.txt
  fastlane/metadata/tr/subtitle.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#19270 Integrate gutenberg-mobile release 1.82.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#19262 Jetpack Social: Update the jetpack social sharing
  WordPress/Classes/ViewRelated/Blog/SharingConnectionsViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingViewController.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/What's New/Data store/Cache/AnnouncementsCache.swift
Labels: [Status] Needs Code Review, Jetpack

#19275 Merge finalized release 20.6 into `trunk`
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/es-ES/name.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/es-ES/subtitle.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/name.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/name.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/pt-BR/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/tr/description.txt
  fastlane/metadata/tr/keywords.txt
  fastlane/metadata/tr/name.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/tr/subtitle.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#19218 Issue 19058 - Sort user-mentions suggestions by prefix first, then alphabetically
  RELEASE-NOTES.txt
  WordPress/Classes/Models/UserSuggestion+Comparable.swift
  WordPress/Classes/ViewRelated/SuggestionsListViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/String+Extensions.swift
  WordPress/WordPressTest/Mention/SuggestionsListViewModelTests.swift
  WordPress/WordPressTest/Test Data/user-suggestions.json
Labels: [Type] Enhancement, Mentions

#19248 Issue 19051 - Suggestions list disappear after expanding/collapsing the reply input
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Comments/EditCommentViewController.h
  WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift
  WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewModel.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewControllerTests.swift
  WordPress/WordPressTest/Comments/Controllers/FullScreenCommentReplyViewModelTests.swift
  WordPress/WordPressTest/Comments/Controllers/Mocks/FullScreenCommentReplyViewModelMock.swift
Labels: [Type] Bug, Mentions

#19285 Jetpack Social: Update release notes
  RELEASE-NOTES.txt
Labels: [Type] Task

#19288 Merge 20.7 code freeze into `trunk` with conflicts resolution
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#19286 Integrate gutenberg-mobile release 1.81.2
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#19281 Rename `branch_to_build` parameter into `branch`
  fastlane/lanes/release.rb
Labels: Tooling

#19186 Adopt the new Core Data writer API part 2
  WordPress/Classes/Services/BloggingPromptsService.swift
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/Utility/CoreDataHelper.swift
  WordPress/WordPressTest/ContextManagerTests.swift
Labels: Core Data

#19282 [UI Tests] - Update ScreenObject version
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Tests/LoginTests.swift
Labels: Testing

#19240 [Jetpack plugin install prompt] Improve prompt presentation logic and handle install cancellation
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+JetpackInstall.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackInstallCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/JetpackInstallPromptViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack Mobile, Jetpack App, Jetpack Install

#19250 [Jetpack plugin install prompt] Prompt accessibility improvements
  WordPress/Classes/ViewRelated/Jetpack/JetpackInstallPromptViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/JetpackInstallPromptViewController.xib
Labels: Jetpack App, Jetpack Install

#19290 Integrate gutenberg-mobile release 1.82.1
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#19299 Fix Jetpack app review URL
  WordPress/Classes/System/WordPressAppDelegate.swift
Labels: Jetpack, Jetpack App

#19295 Add feature flag to use `ContainerContextFactory`
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/ContextManager.m
Labels: Core Data

#19269 [Jetpack plugin install prompt] Refresh Stats view after Jetpack is installed from the prompt
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackInstallCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
Labels: [Type] Bug, Jetpack Install

#19280 Only notify group observers when the media group is updated
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
  WordPress/WordPressTest/MediaPicker/MediaLibraryPickerDataSourceTests.swift
Labels: Core Data

#19306 Update Charts to 4.1.0
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: [Type] Core

#19119 Make the app compatible with Xcode 14
  .buildkite/pipeline.yml
  Podfile
  Podfile.lock
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/FeaturedImageScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#19297 [Jetpack] Shared Defaults Objc Convenience Constructor
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/Stores/UserPersistentStoreFactory.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/Utility/Logging/WPLogger.m
  WordPress/Classes/Utility/Migrations/10-11/BlogToAccount.m
  WordPress/Classes/Utility/Migrations/10-11/BlogToJetpackAccount.m
  WordPress/Classes/Utility/WPUserAgent.m
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: [Type] Task, Jetpack Focus

#19310 Revert "Disable "Treat Warnings as Errors" in two targets"
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Core

#19312 Merge changes from beta 20.7.0.3
  Gemfile
  Gemfile.lock
  WordPress/Resources/ro.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Pluginfile
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/en-GB/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#19303 I18n: Fix Gutenberg strings appearing in English for pt-BR locale
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+Localization.swift
Labels: [Type] Bug, Posting/Editing, i18n

#18833 Upgrade to support Xcode 14.0
  .buildkite/pipeline.yml
  Podfile
  Podfile.lock
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/FeaturedImageScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/Jetpack.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/JetpackScreenshotGeneration.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/OCLint.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/UITestsFoundation.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Alpha.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress Internal.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPress.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressIntents.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressScreenshotGeneration.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressShareExtension.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressStatsWidgets.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressTodayWidget.xcscheme
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
Labels: [Status] DO NOT MERGE, Tooling, Part of a WIP Feature

#19316 Update fastlane to 2.210
  Gemfile.lock
Labels: Tooling

#19307 Shared Login: Sync UI state between apps while in memory
  WordPress/Classes/System/WindowManager.swift
  WordPress/Classes/Utility/ContextManager.m
  WordPress/Classes/Utility/LegacyContextFactory.m
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
Labels: [Type] Task, Part of a WIP Feature, Jetpack Focus, Shared Login

#19320 Merge finalized 20.7 into `trunk`
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/bg.lproj/Localizable.strings
  WordPress/Resources/cs.lproj/Localizable.strings
  WordPress/Resources/cy.lproj/Localizable.strings
  WordPress/Resources/da.lproj/Localizable.strings
  WordPress/Resources/de.lproj/Localizable.strings
  WordPress/Resources/en-AU.lproj/Localizable.strings
  WordPress/Resources/en-CA.lproj/Localizable.strings
  WordPress/Resources/en-GB.lproj/Localizable.strings
  WordPress/Resources/es.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/hr.lproj/Localizable.strings
  WordPress/Resources/hu.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/is.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/nb.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/pl.lproj/Localizable.strings
  WordPress/Resources/pt-BR.lproj/Localizable.strings
  WordPress/Resources/pt.lproj/Localizable.strings
  WordPress/Resources/ro.lproj/Localizable.strings
  WordPress/Resources/ru.lproj/Localizable.strings
  WordPress/Resources/sk.lproj/Localizable.strings
  WordPress/Resources/sq.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/Resources/th.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  WordPress/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
Labels: Releases

#19315 Update to latest Sentry via Tracks 0.13.0-beta.2
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Tooling

#19322 Merge changes from 20.8 code freeze into `trunk`
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+Localization.swift
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#19324 Use Fastlane's `AccountManager` to manage user in `register_new_device`
  fastlane/lanes/codesign.rb
Labels: Tooling

#19309 Remote Feature Flags: Point to the new endpoint
  Podfile
  Podfile.lock
Labels: [Type] Task, Core

#19318 Shared Login: Prune old database transactions on initialization
  WordPress/Classes/Utility/ContextManager.m
Labels: [Type] Task, Part of a WIP Feature, Jetpack Focus, Shared Login

#19335 Merge Editorialized Release Notes for 20.8
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#19304 Fix push prompt button overlapping on iPad
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersPushPromptViewController.swift
Labels: [Type] Bug, iPad, Blogging Reminders

#19332 [Do not merge - CI] Fix: correct button constraints relative to stackView
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersPushPromptViewController.swift
Labels: [Status] DO NOT MERGE

#19277 Jetpack landing screen: extend background gradient to the whole view and add blur effect to the buttons
  Podfile
  Podfile.lock
  WordPress/Classes/Utility/App Configuration/AuthenticationHandler.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Jetpack/Classes/JetpackAuthenticationManager.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueStyleGuide.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
Labels: [Type] Task, Jetpack Focus

#19330 [Jetpack plugin install prompt] Complete UI and tracking for installation prompt
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Jetpack/JetpackInstallPromptViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/JetpackInstallPromptViewController.xib
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-circle-particle.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-circle-particle.imageset/circle-particle.pdf
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-icon-notifications.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-icon-notifications.imageset/notifications-bell.pdf
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-icon-stats.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-icon-stats.imageset/icon-shortcut-stats.pdf
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-install-prompt-logo.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-install-prompt-logo.imageset/jetpack-install-prompt-logo.pdf
  WordPress/Resources/AppImages.xcassets/Jetpack/Jetpack Install Prompt/jetpack-long-logo.imageset/prologue-logo.pdf
Labels: Jetpack Plugins, Jetpack App, Jetpack Install

#19331 Comment Detail Redesign: Moderation Bar Update
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
Labels: [Type] Task, Comments

#19343 Update lane running Fastlane match to run for both apps
  fastlane/lanes/codesign.rb
Labels: Tooling

#19340 [Jetpack] Shared User Defaults update posts instance
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: [Type] Task, Jetpack Focus

#19328 Add app groups and keychain access groups to Jetpack release entitlements
  WordPress/Jetpack/JetpackRelease-Alpha.entitlements
  WordPress/Jetpack/JetpackRelease-Internal.entitlements
  WordPress/Jetpack/JetpackRelease.entitlements
Labels: [Type] Task, Jetpack Focus, Shared Login

#19323 Remove Bundler workaround from CI setup
  .buildkite/cache-builder.yml
  .buildkite/commands/build-for-testing.sh
  .buildkite/commands/installable-build-jetpack.sh
  .buildkite/commands/installable-build-wordpress.sh
  .buildkite/commands/release-build-jetpack.sh
  .buildkite/commands/release-build-wordpress-internal.sh
  .buildkite/commands/release-build-wordpress.sh
  .buildkite/commands/rubocop-via-danger.sh
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: Tooling

#19321 Move the function that counts local draft out of `PostService`
  WordPress/Classes/Models/AbstractPost+Local.swift
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
Labels: Core Data

#19317 Move the post lookup method out of PostService
  WordPress/Classes/Models/Blog+HomepageSettings.swift
  WordPress/Classes/Models/Blog+Post.swift
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/HomepageSettingsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogTests.swift
Labels: Core Data

#19364 Weekly Roundup: Add support for the Jetpack app
  RELEASE-NOTES.txt
  WordPress/Jetpack/Info.plist
Labels: Notifications, [Type] Task, Jetpack Focus

#19371 Update draft release notes for 20.9
  RELEASE-NOTES.txt
Labels: [Type] Task

#19372 [Do not merge - CI only] Ci/19304 update release note
  RELEASE-NOTES.txt
Labels: [Status] DO NOT MERGE

#19366 Blog service lookup blog
  WordPress/Classes/Models/Blog+History.swift
  WordPress/Classes/Services/BlogService.h
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift
  WordPress/Classes/System/3DTouch/WP3DTouchShortcutHandler.swift
  WordPress/Classes/System/WordPressAppDelegate+openURL.swift
  WordPress/Classes/Utility/Universal Links/NavigationActionHelpers.swift
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Me/Account Settings/AccountSettingsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+JetpackPrompt.swift
  WordPress/Classes/ViewRelated/Reader/ReaderReblogPresenter.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderReblogActionTests.swift
Labels: Core Data

#19358 Comment Detail Redesign: Implement trash & delete
  WordPress/Classes/ViewRelated/Cells/BorderedButtonTableViewCell.swift
  WordPress/Classes/ViewRelated/Cells/SingleButtonTableViewCell.swift
  WordPress/Classes/ViewRelated/Cells/SingleButtonTableViewCell.xib
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Comments

#19003 Stats Revamp: Fix Period Store State when navigating between 1st and 2nd levels
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: Stats, Stats Revamp

#19375 Integrate gutenberg-mobile release 1.83.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#19380 [Jetpack overlay] Set overlay background to white
  WordPress/Classes/ViewRelated/Jetpack/Branding/Overlay/JetpackOverlayView.swift
Labels: [Type] Task, Jetpack Focus

#19369 [Jetpack focus] Prevent looping bug related to banner visibility
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JetpackBannerScrollVisibility.swift
Labels: [Type] Bug, Jetpack Focus

#19368 Stats Revamp: VoiceOver fixes for Stats
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/StatsBaseCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/TabbedTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/StatsTwoColumnRow.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/TopTotalsCell.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: [Type] Bug, Accessibility, Stats, VoiceOver, Stats Revamp

#19370 Stats Revamp: Text in the card not responding to changes between Dark and Light mode
  WordPress/Classes/ViewRelated/Stats/Insights/StatsTotalInsightsCell.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
Labels: [Type] Bug, Stats, Dark mode, Stats Revamp

#19381 Remove VoiceOver from the new Jetpack prologue decorative elements
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/JetpackPromptView.swift
Labels: [Type] Bug, Jetpack Focus

#19377 Stories: Deleting one of the images causes the next one not to load
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [Type] Bug, WP Stories

#19376 [Jetpack] Shared Data `MediaSettings`
  WordPress/Classes/Services/MediaSettings.swift
Labels: [Type] Bug, Jetpack Focus

#19305 Fix oversize label in no result side menu on iPad
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Views/NoResults.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ViewRelated/Views/Controllers/NoResultsViewControllerTests.swift
Labels: [Type] Bug

#19333 [Do not merge - CI] Ci/fix/19244 19246 fix oversize label on no result vc for i pad
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Views/NoResults.storyboard
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ViewRelated/Views/Controllers/NoResultsViewControllerTests.swift
Labels: [Status] DO NOT MERGE
