Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2022-07, with the labels that each got.

#18966 Refactoring PostListViewController: Add ViewModel & extract edit post logic
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostListViewModelTests.swift
Labels: Refactor, Posts List, Part of a WIP Feature

#18912 [UITII] Bumped ScreenObject dependency version to 0.2.1
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing

#18961 [Tooling] Add Buildkite annotation on test failures — DRY using bash-cache plugin
  .buildkite/commands/junit-failures-to-buildkite-annotation.xslt
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
Labels: Tooling

#18952 [Tooling] Add Buildkite annotation on test failures
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
Labels: Tooling

#18984 StatsTotalInsightsCell: Ensure latest post text is formatted
  WordPress/Classes/ViewRelated/Stats/Insights/StatsTotalInsightsCell.swift
Labels: Stats Revamp

#18847 Install Danger and its RuboCop plugin via Bundler
  .buildkite/commands/rubocop-via-danger.sh
  .buildkite/pipeline.yml
  Dangerfile
  Gemfile
  Gemfile.lock
  Rakefile
  fastlane/lanes/localization.rb
Labels: Tooling

#18965 Fix screenshot UI test for JetpackScreenshotGeneration target
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Activity/BaseActivityListViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/UITestsFoundation/Screens/Jetpack/JetpackBackupScreen.swift
  WordPress/UITestsFoundation/Screens/Login/FeatureIntroductionScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing, [Type] Task, Jetpack Mobile, Jetpack App

#18986 Insights Management: Fix an issue when deactivating all cards
  WordPress/Classes/ViewRelated/Stats/Insights/Insights Management/InsightsManagementViewController.swift
Labels: Stats Revamp

#18968 Update `ShareAppContentPresenter` tests to be synchronous
  WordPress/Classes/ViewRelated/Sharing/ShareAppContentPresenter.swift
  WordPress/WordPressTest/ShareAppContentPresenterTests.swift
Labels: [Type] Task

#18970 Fix crash in `PostServiceWPComTests`
  WordPress/WordPressTest/Services/PostServiceWPComTests.swift
Labels: [Type] Task

#18980 Editor: Reset search query when media picker is dismissed
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
Labels: [Type] Bug, Media, Gutenberg integration

#18976 Refactoring PostListViewController: Move `stats` to VM
  WordPress/Classes/ViewRelated/Post/PostListReachabilityUtility.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostBuilder.swift
  WordPress/WordPressTest/PostListViewModelTests.swift
Labels: Refactor, Posts List, Part of a WIP Feature

#19000 Move lint translations and RuboCop in a `group` step in Buildkite
  .buildkite/pipeline.yml
Labels: [Type] Enhancement, Tooling

#19005 Integrate pending Gutenberg Mobile 1.79.0 changes
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
Labels: Gutenberg integration

#18872 Integrate Buildkite Test Analytics
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WordPressUnitTests.xctestplan
  WordPressFlux/Package.swift
Labels: Testing, Tooling

#19006 QR Login: Restrict QR Login screens to portrait
  WordPress/Classes/ViewRelated/QR Login/View Controllers/QRLoginScanningViewController.swift
  WordPress/Classes/ViewRelated/QR Login/View Controllers/QRLoginVerifyAuthorizationViewController.swift
Labels: [Type] Task, Login, QR Login

#18979 Display post / comment authors at the top of the suggestions list
  MIGRATIONS.md
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Notifications/Notification.swift
  WordPress/Classes/Models/UserSuggestion+CoreDataClass.swift
  WordPress/Classes/Models/UserSuggestion+CoreDataProperties.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 144.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Mentions

#19009 [DO NOT MERGE] [CI only] Task/prominent suggestions
  MIGRATIONS.md
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Notifications/Notification.swift
  WordPress/Classes/Models/UserSuggestion+CoreDataClass.swift
  WordPress/Classes/Models/UserSuggestion+CoreDataProperties.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Comments/FullScreenCommentReplyViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.h
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 144.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Status] DO NOT MERGE

#18967 Stories: Upgrade Kanvas version
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Kanvas/KanvasCameraCustomUI.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SiteIconPickerView.swift
Labels: [Type] Enhancement, WP Stories

#19013 Suggestions search was removing the incorrect user from search results
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift
Labels: [Type] Bug, Mentions

#19004 Integrate gutenberg-mobile release 1.79.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
Labels: Gutenberg integration

#19018 Unit Tests for SuggestionsTableView
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Mention/SuggestionsTableViewMockDelegate.swift
  WordPress/WordPressTest/Mention/SuggestionsTableViewTests.swift
  WordPress/WordPressTest/Test Data/user-suggestions.json
Labels: [Type] Task, Mentions

#19019 [DO NOT MERGE] Task/mentions tests ci
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Mention/SuggestionsTableViewMockDelegate.swift
  WordPress/WordPressTest/Mention/SuggestionsTableViewTests.swift
  WordPress/WordPressTest/Test Data/user-suggestions.json
Labels: [Status] DO NOT MERGE

#19022 Merge 20.3 code freeze
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#18995 [Gutenberg] Add React Native FastImage
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#18987 Fixes an issue when navigating to Stats on iPad from onboarding questions
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+OnboardingPrompt.swift
Labels: Stats Revamp

#19007 Add Jetpack badge to Activity log detail
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.storyboard
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Jetpack Branding/JetpackBannerView.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JetpackBannerView.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Common/JetpackButton.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Jetpack

#19020 Retain horizontal scroll position for site and page designs.
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/CategorySectionTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/FilterableCategoriesViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Design Selection/SiteDesignContentCollectionViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Design Selection/SiteDesignSection.swift
Labels: [Type] Bug, Themes, Site Creation

#19049 Adds "Jetpack powered" feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
Labels: Jetpack, [Type] Task

#19040 Adds animation to the Jetpack Powered banner
  WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JPScrollViewDelegate.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JetpackBannerView.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Button/JetpackButton.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/BottomScrollAnalyticsTracker.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboard.storyboard
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, [Type] Task

#19057 [Gutenberg] Add shouldUseFastImage capability
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#19036 [Tooling] Guess the app version when running update_appstore_strings
  fastlane/lanes/localization.rb
Labels: Tooling

#19062 [Jetpack] Add Jetpack powered banner to Reader and limit a11y scaling
  WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JetpackBannerView.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Button/JetpackButton.swift
  WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: Jetpack, [Type] Task

#19052 Use custom emojis for WordPress and Jetpack in Buildkite pipeline
  .buildkite/release-builds.yml
Labels: Tooling

#19016 App Store Screenshots: Ensure overview chart is displayed for Stats screenshot
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_visits-month.json
Labels: Testing, Jetpack Mobile, Jetpack App

#19065 Add Jetpack powered badge to Me and App Settings
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Button/JetpackButton.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
Labels: Jetpack, [Type] Task

#19056 [Jetpack] Remove locale from Jetpack connection URL
  WordPress/Classes/ViewRelated/Jetpack/Install/Webview/JetpackConnectionWebViewController.swift
Labels: [Type] Bug, Jetpack, Jetpack Install

#19073 [Jetpack] Add Jetpack banner to Themes
  WordPress/Classes/ViewRelated/Themes/ThemeBrowser.storyboard
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Labels: Jetpack, [Type] Task

#19077 Merge hotfix 20.2.1 into release 20.3
  WordPress/Classes/ViewRelated/Jetpack/Install/Webview/JetpackConnectionWebViewController.swift
Labels: Releases

#19060 UITII-fix-testAddRemoveFeaturedImage
  WordPress/UITestsFoundation/Screens/Editor/EditorPostSettings.swift
Labels: Testing

#19074 [Jetpack] Animate notifications banner
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Notifications.storyboard
Labels: Jetpack, [Type] Task

#18997 Media - Add large and medium image sizes
  MIGRATIONS.md
  Podfile
  Podfile.lock
  WordPress/Classes/Models/Media.h
  WordPress/Classes/Models/Media.m
  WordPress/Classes/Services/MediaService+Swift.swift
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 145.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Media, Gutenberg integration

#19026 [UITII] Remove the app after each test
  WordPress/WordPressUITests/Flows/LoginFlow.swift
  WordPress/WordPressUITests/Tests/EditorAztecTests.swift
  WordPress/WordPressUITests/Tests/EditorGutenbergTests.swift
  WordPress/WordPressUITests/Tests/LoginTests.swift
  WordPress/WordPressUITests/Tests/MainNavigationTests.swift
  WordPress/WordPressUITests/Tests/ReaderTests.swift
  WordPress/WordPressUITests/Tests/SignupTests.swift
  WordPress/WordPressUITests/Tests/StatsTests.swift
  WordPress/WordPressUITests/Tests/SupportScreenTests.swift
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Testing

#19071 Add JP Banner to MySite->Activity
  WordPress/Classes/ViewRelated/Activity/JetpackActivityLogViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JetpackBannerView.swift
Labels: Jetpack, [Type] Task

#19078 [Tooling] Fix issue with installing hooks in a git worktree setup
  Rakefile
Labels: Tooling

#19059 Add Jetpack powered banner to Reader Search
  WordPress/Classes/ViewRelated/Reader/Reader.storyboard
  WordPress/Classes/ViewRelated/Reader/ReaderSearchSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: Jetpack, [Type] Task

#19082 Upgrade `git-s3-cache` Buildkite plugin to latest version, 1.1.3
  .buildkite/cache-builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: Tooling

#19089 Integrate gutenberg-mobile release 1.80.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg integration

#19094 Replaces the different checks for jetpack branding visibility with a single flag
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Activity/JetpackActivityLogViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/JetpackBrandingVisibility.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, [Type] Task

#19083 Jetpack Focus: Update the Jetpack App Store Listing
  fastlane/jetpack_metadata/default/description.txt
  fastlane/jetpack_metadata/default/name.txt
  fastlane/jetpack_metadata/default/subtitle.txt
Labels: Jetpack App

#19085 [Jetpack] Don't show Jetpack banner on Notifications if not connected to WordPress.com
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+JetpackPrompt.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Labels: Jetpack, [Type] Task

#19096 Add entry for app store name to Jetpack `.po` file
  WordPress/Jetpack/Resources/AppStoreStrings.po
Labels: Localization, Tooling

#19044 Remove `AMScrollingNavbar` dependency
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: Tooling

#19047 Add note regarding React Native pods looking like they're unused
  Podfile
  Podfile.lock
Labels: Tooling

#19100 Missing @ and + signs from suggestions list
  WordPress/Classes/ViewRelated/SuggestionViewModel.swift
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Mention/SuggestionTableViewTests.swift
  WordPress/WordPressTest/Mention/SuggestionViewModelTests.swift
  WordPress/WordPressTest/Mention/SuggestionsTableViewDelegateMock.swift
Labels: [Type] Bug, Mentions

#19102 Add "Jetpack powered" badge to My Site Home
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Badge/DashboardBadgeCell.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, [Type] Task

#19103 [Jetpack] Add Jetpack banner to People view
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JetpackBannerWrapperViewController.swift
  WordPress/Classes/ViewRelated/People/PeopleViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, [Type] Task

#19104 Fix jetpack branding elements in RTL
  WordPress/Classes/ViewRelated/Jetpack/Branding/Button/JetpackButton.swift
Labels: [Type] Bug, Jetpack Mobile

#19105 Update release notes for jetpack branding
  RELEASE-NOTES.txt
Labels: [Type] Task, Jetpack Mobile

#19106 [Jetpack] Add Jetpack banner to Sharing view
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingViewController.m
  WordPress/Classes/ViewRelated/Jetpack/Branding/Banner/JetpackBannerWrapperViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: Jetpack, [Type] Task

#19092 Add "Jetpack powered" badge to Notification Settings
  WordPress/Classes/ViewRelated/Jetpack/Branding/Button/JetpackButton.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack, [Type] Task

#19109 [Jetpack] Revert Jetpack banner on People view
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/People/PeopleViewController.swift
Labels: Jetpack, [Type] Task

#19108 Add Jetpack powered badge to reader detail
  WordPress/Classes/ViewRelated/Cells/BorderedButtonTableViewCell.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNoCommentCell.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNoCommentCell.xib
Labels: [Type] Task, Jetpack Mobile

#19107 [Jetpack] Revert Jetpack banner on Themes #19073
  WordPress/Classes/ViewRelated/Themes/ThemeBrowser.storyboard
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Labels: Jetpack, [Type] Task

#19099 Merge finalized release 20.3 into `trunk`
  Gemfile.lock
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/it/description.txt
  fastlane/metadata/it/keywords.txt
  fastlane/metadata/it/name.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/it/subtitle.txt
Labels: Releases

#19110 Merge version 20.4 code freeze into `trunk`
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Pluginfile
Labels: Releases

#19033 Disable time-wasting Fastlane checks when building from CI
  .buildkite/commands/release-build-wordpress-internal.sh
  .buildkite/commands/release-build-wordpress.sh
  .buildkite/release-builds.yml
Labels: Tooling

#19084 [Gutenberg Mobile] Enable the native editor to receive a host app's namespace
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg integration

#19093 Jetpack Focus: Update raw screenshots
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v2_sites_block_layouts.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v2_sites_blogging_prompts.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/rest_v2_sites_common_starter_site_designs.json
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Site Creation/Site Intent/SiteIntentViewController.swift
  WordPress/JetpackScreenshotGeneration/JetpackScreenshotGeneration.swift
  WordPress/UITestsFoundation/Screens/ActionSheetComponent.swift
  WordPress/UITestsFoundation/Screens/Editor/ChooseLayoutScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/MySitesScreen.swift
  WordPress/UITestsFoundation/Screens/SiteIntentScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
  WordPress/WordPressUITests/Utils/XCTest+Extensions.swift
Labels: Testing, Jetpack App

#19118 [Jetpack] Add Jetpack powered bottom sheet feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Jetpack, [Type] Task

#19117 Merge editorialized release notes for version 20.4
  .buildkite/commands/release-build-wordpress-internal.sh
  .buildkite/commands/release-build-wordpress.sh
  .buildkite/release-builds.yml
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#19127 Fix Jetpack powered badge on Activity detail
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.storyboard
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
Labels: [Type] Bug, Jetpack Mobile
