Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2023-08, with the labels that each got.

#21199 Jetpack Social: Prepublishing sheet accessibility improvements
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingAutoSharingView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsTableFooterView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsViewController.swift
Labels: [Type] Enhancement, Accessibility, Part of a WIP Feature, Jetpack Social

#21216 Fix path calculation of Gutenberg `node_modules` folder
  Gutenberg/cocoapods_helpers.rb
Labels: [Type] Bug, Gutenberg

#21181 Fix incorrect media library count
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [Type] Bug, Media

#21226 Return NSManagedObjectID instead of PublicizeConnection
  WordPress/Classes/Services/SharingService.swift
Labels: Core Data

#21220 Blaze Manage Campaigns: Update campaign details url
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeCampaignDetailsWebViewModel.swift
  WordPress/WordPressTest/Blaze/BlazeCampaignDetailsWebViewModelTests.swift
Labels: [Type] Task, Blaze

#21207 Remove unused code referencing WPAvatarSource from Reader
  WordPress/Classes/Models/ReaderPost.h
  WordPress/Classes/Models/ReaderPost.m
Labels: Reader, [Type] Task

#21210 Fix an issue with unstable order on the media screen
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
Labels: [Type] Bug, Media

#21211 Fix an issue with media screen flashing when opened
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Media.swift
Labels: [Type] Bug, Media

#21219 Jetpack Social: Pre-publishing sheet UI tweaks
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsTableFooterView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsViewController.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21223 Jetpack Social: Fix no connection view issues
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoConnectionView.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
Labels: [Type] Task, Part of a WIP Feature, Jetpack Social

#21224 Jetpack Social: Sync blog information after checkout is dismissed
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
Labels: [Type] Task, Part of a WIP Feature, Jetpack Social

#21236 Update JTAppleCalendar
  Podfile.lock
Labels: [Type] Core

#21231 Avoid WPMediaPickerViewController performBatchUpdates crash by wrapping the call in try-catch block
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [Type] Crash, Media

#21222 Fix crash in ReaderDetailCommentsTableViewDelegate
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
Labels: [Type] Crash, Reader

#21225 Fix an issue with media picker not deallocating after selection
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Media/StockPhotos/StockPhotosPicker.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorPicker.swift
Labels: Media, Memory Management

#21213 [UI Tests] - Update ScreenObject package and revert previous login tests change
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITestsFoundation/Screens/MeTabScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing

#21239 Integrate gutenberg-mobile release 1.100.2
  Gutenberg/version.rb
  Podfile.lock
Labels: Gutenberg

#21240 Integrate gutenberg-mobile release 1.101.0
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#21244 Jetpack Social: Add tracks for the pre-publishing sheet
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController+JetpackSocial.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21243 Fix a crash during Reader topics cleanup
  RELEASE-NOTES.txt
  WordPress/Classes/Services/ReaderTopicService.m
Labels: [Type] Crash, Reader

#21250 Catch NSInternalInconsistencyException in WPTableViewHandler to avoid crashes
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/WPTableViewHandler.m
Labels: [Type] Crash, Table Views

#21249 Jetpack Social: Update social icon opacity when it is disabled
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: [Type] Task, Part of a WIP Feature, Jetpack Social

#21248 Jetpack Social: Create no shares remaining Jetpack Social card
  WordPress/Classes/Services/JetpackSocialService.swift
  WordPress/Classes/Services/SharingSyncService.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoSharesView.swift
  WordPress/Jetpack/Classes/Utility/JetpackSocialError.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21254 Fix incorrectly terminated background task
  RELEASE-NOTES.txt
  WordPress/Classes/System/WordPressAppDelegate.swift
Labels: [Type] Crash, General

#21251 Merge finalized release 22.9
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#21227 Remove the Core Data workaround in EditorMediaUtility
  RELEASE-NOTES.txt
  WordPress/Classes/Networking/MediaHost+Blog.swift
  WordPress/Classes/Services/MediaThumbnailService.swift
  WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
Labels: Core Data

#21235 Fix MRProgressView compiling issue
  Podfile
  Podfile.lock
Labels: [Type] Core

#21256 Jetpack Social: Add tracks to Jetpack Social dashboard cards
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
Labels: [Type] Task, Part of a WIP Feature, Jetpack Social

#21255 Jetpack Social: Add tracks for Jetpack Social in post settings
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
Labels: [Type] Task, Part of a WIP Feature, Jetpack Social

#21257 Jetpack Social: Convert Jetpack Social feature flag to remote flag
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Sharing.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController+JetpackSocial.swift
  WordPress/WordPressTest/Blog Dashboard/Cards/DashboardJetpackSocialCardCellTests.swift
Labels: [Type] Task, Part of a WIP Feature, Jetpack Social

#21258 Jetpack Social: Enable Jetpack Social improvements
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Jetpack/Resources/release_notes.txt
Labels: [Type] Task, Jetpack Social

#21241 [Domain Focus] Card UI
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardGoogleDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardGoogleDomainsCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/Classes/ViewRelated/Blog/BlogPersonalization/BlogDashboardPersonalizationViewModel.swift
  WordPress/Resources/AppImages.xcassets/Domains/wp-domains-icon.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Domains/wp-domains-icon.imageset/wp-domains-icon.png
  WordPress/Resources/AppImages.xcassets/Domains/wp-domains-icon.imageset/wp-domains-icon@2x.png
  WordPress/Resources/AppImages.xcassets/Domains/wp-domains-icon.imageset/wp-domains-icon@3x.png
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Jetpack App, Domains

#21263 Merge version 23.0 code freeze
  Gemfile
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Sharing.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController+JetpackSocial.swift
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  WordPress/WordPressTest/Blog Dashboard/Cards/DashboardJetpackSocialCardCellTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
Labels: Releases

#21267 Support forum: remove feature flag
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift
  WordPress/WordPressTest/Support/SupportConfigurationTests.swift
Labels: [Type] Task, Contact Support

#21268 Contact Support: Add feature flag
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
Labels: [Type] Task, Contact Support

#21281 Remove Unused UI Test Folder
  WordPress/UIAutomationTests/Blog.js
  WordPress/UIAutomationTests/Config.js
  WordPress/UIAutomationTests/Post.js
  WordPress/UIAutomationTests/WPiOSTests.js
Labels: Testing

#21270 Contact Support: Launch Chat Widget
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewModel.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget.html
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget.js
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, [Status] In Progress, Contact Support

#21259 Remove WPAvatarSource usage from SuggestionsTableView.swift
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/SuggestionViewModel.swift
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableView.swift
  WordPress/Classes/ViewRelated/Suggestions/SuggestionsTableViewCell.m
  WordPress/WordPressTest/Mention/SuggestionViewModelTests.swift
Labels: Reader, [Type] Task

#21286 Remove WPAvatarSource
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/Utility/WPAvatarSource.h
  WordPress/Classes/Utility/WPAvatarSource.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WPAvatarSourceTest.m
Labels: Reader, [Type] Task

#21292 Contact Support: Submit ticket to Zendesk with chat history
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewModel.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/SupportChatBotViewModelTests.swift
Labels: [Type] Task, [Status] In Progress, Contact Support

#21282 [Domain Focus] Card Logic
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/GoogleDomains/DashboardGoogleDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/GoogleDomains/DashboardGoogleDomainsCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/GoogleDomains/DashboardGoogleDomainsViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Dashboard/DashboardGoogleDomainsViewModelTests.swift
  WordPress/WordPressTest/MockEventTracker.swift
  WordPress/WordPressTest/WPComJetpackRemoteInstallViewModelTests.swift
Labels: [Type] Task, Jetpack App, Domains

#21295 Blaze Manage Campaigns: Match colors on web
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/BlazeCampaignStatusView.swift
Labels: [Type] Task, Blaze

#21296 Blaze Manage Campaigns: Preserve image aspect for campaign thumbnail
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignTableViewCell.swift
Labels: [Type] Task, Blaze

#21312 Add editorialized release notes for version 23.0
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignTableViewCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/BlazeCampaignStatusView.swift
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#21313 UI Modernization: Update FAB
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
Labels: [Type] Task, UI Modernization

#21327 Fix a crash when opening a page for editing
  WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
Labels: [Type] Crash, Posting/Editing

#21287 Use `AccountBuilder` over `WPAccount.init` in `AccountServiceTests`
  WordPress/WordPressTest/AccountServiceTests.swift
Labels: Testing

#21306 Remove Domain Purchasing during Site Creation A/B experiment
  WordPress/Classes/Services/SiteAddressService.swift
  WordPress/Classes/Utility/AB Testing/ABTest.swift
  WordPress/Classes/Utility/Analytics/WPAnalytics+Domains.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/EnhancedSiteCreationAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/AddressTableViewCell.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Site Creation, Domains

#21314 Contact Support: Configure Chat Widget Design and Presentation logic
  .configure
  .configure-files/Jetpack-Secrets.swift.enc
  .configure-files/Secrets-Alpha.swift.enc
  .configure-files/Secrets-Internal.swift.enc
  .configure-files/Secrets.swift.enc
  .configure-files/project.env.enc
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewModel.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget.css
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget.html
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget.js
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Contact Support

#21328 Fix a crash when opening a page for editing (Release 23.0)
  WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
Labels: [Type] Crash, Posting/Editing

#21332 Jetpack Social: Fix showing no connections for unsupported service
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.h
Labels: [Type] Bug, Jetpack Social

#21335 Jetpack Social: Fix no connections social dashboard card appearing
  WordPress/Classes/Services/JetpackSocialService.swift
  WordPress/Classes/Services/SharingSyncService.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
Labels: [Type] Bug, Jetpack Social

#21321 Clarify placeholders in `stats.insights.totalLikes.guideText.singular`
  WordPress/Classes/ViewRelated/Stats/Insights/StatsTotalInsightsCell.swift
Labels: i18n, Releases

#21288 [UI Tests] - Add reply to comment notification test
  API-Mocks/WordPressMocks/src/main/assets/mocks/__files/__admin/scenarios.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/me/me_sites.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/notifications/notifications_comment_parent.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/notifications/notifications_comment_reply.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/notifications/notifications_comment_reply_after.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/notifications/notifications_comment_reply_before.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/rest_v12_read_sites_discover.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/181851495 - Four Paws Dog Grooming - Free Plan/rest_sites_181851495.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/181977606 - Weekend Bakes - Pro Plan/rest_sites_181977606.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/221670093 - NUX Test Site - NUX Site/rest_sites_221670093.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/Shared/rest_sites_comments.json
  API-Mocks/scripts/start.sh
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
  WordPress/UITests/Tests/NotificationTests.swift
  WordPress/UITests/Utils/XCTest+Extensions.swift
  WordPress/UITestsFoundation/Globals.swift
  WordPress/UITestsFoundation/Screens/NotificationsScreen.swift
  WordPress/UITestsFoundation/WireMock.swift
Labels: Testing

#21337 Avoid WPMediaPickerViewController reloadItemsAtIndexPaths crash by wrapping the call in try-catch block
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: [Type] Crash, Media

#21322 Add release notes when uploading build to TestFlight
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
Labels: Tooling, Releases

#21253 Gutenberg - Hide undo/redo buttons in HTML Mode
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/HTMLEditorScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing, Gutenberg

#21341 Prevent crash when sending `nil` site ID to ReaderHelpers.dispatchToggleFollowSiteMessage
  RELEASE-NOTES.txt
  WordPress/Classes/Models/ReaderSiteTopic+Lookup.swift
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
Labels: [Type] Crash, Reader

#21269 [Gutenberg] - Fixes font customization not getting updated
  Gutenberg/version.rb
  Podfile.lock
Labels: Gutenberg

#21229 Add `testError()` syntax sugar for the self-documenting general purpose errors unit tests
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/AccountSettingsRemoteInterfaceStub.swift
  WordPress/WordPressTest/AccountSettingsServiceTests.swift
  WordPress/WordPressTest/Aztec/AztecPostViewControllerAttachmentTests.swift
  WordPress/WordPressTest/BlogServiceMock.swift
  WordPress/WordPressTest/ContextManagerTests.swift
  WordPress/WordPressTest/MediaProgressCoordinatorTests.swift
  WordPress/WordPressTest/NSError+TestInstance.swift
  WordPress/WordPressTest/PostCoordinatorTests.swift
  WordPress/WordPressTest/SiteManagementServiceTests.swift
  WordPress/WordPressTest/TestError.swift
  WordPress/WordPressTest/ViewRelated/Tools/Time Zone/TimeZoneSelectorViewModelTests.swift
  WordPress/WordPressTest/WPComJetpackRemoteInstallViewModelTests.swift
Labels: Testing, Tooling

#21340 Contact Support: Navigation improvements
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
Labels: [Type] Task, Contact Support

#21336 Jetpack Focus: Adds frequency logic to the phase 4 overlay
  WordPress/Classes/Utility/BuildInformation/RemoteConfigParameter.swift
  WordPress/Classes/Utility/OverlayFrequencyTracker.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackFeaturesRemovalCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayGeneralViewModel.swift
  WordPress/WordPressTest/OverlayFrequencyTrackerTests.swift
Labels: [Type] Task, Jetpack Focus

#21330 Contact Support: Configure chat widget for iPad and horizontal orientation
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewModel.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget.css
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget_page.css
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget_page.html
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Contact Support

#21353 Integrate gutenberg-mobile release 1.101.1
  Gutenberg/version.rb
  Podfile.lock
Labels: Gutenberg

#21356 Jetpack Social: Remove reloading cards locally on social card
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
Labels: [Type] Crash, Jetpack Social

#21346 Make WireMock fetch/reset use `try async` for networking
  WordPress/UITests/Tests/DashboardTests.swift
  WordPress/UITests/Tests/EditorAztecTests.swift
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/MenuNavigationTests.swift
  WordPress/UITests/Tests/NUXTests.swift
  WordPress/UITests/Tests/NotificationTests.swift
  WordPress/UITests/Tests/PostTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITests/Tests/SignupTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITests/Tests/SupportScreenTests.swift
  WordPress/UITests/Utils/XCTest+Extensions.swift
  WordPress/UITestsFoundation/WireMock.swift
Labels: Testing

#21363 Fix Zendesk identity creation flow in chat
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewModel.swift
  WordPress/WordPressTest/SupportChatBotViewModelTests.swift
Labels: [Type] Bug

#21329 [Domain Focus] Add site agnostic card hide logic
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/GoogleDomains/DashboardGoogleDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/WordPressTest/Dashboard/BlogDashboardPersonalizationServiceTests.swift
Labels: Jetpack App, Domains

#21367 Integrate gutenberg-mobile release 1.102.0
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#21368 [Domain Focus] Enable Feature flag
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
Labels: Jetpack App, Domains

#21351 Contact Support: Open from different parts of the app
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Me/Account Settings/AccountSettingsViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportCoordinator.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Contact Support

#21366 Merge finalized release 23.0
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/Fastfile
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/lanes/build.rb
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#21364 Update URL in WordPress `support_url.txt`
  fastlane/jetpack_metadata/default/support_url.txt
  fastlane/metadata/ar-SA/support_url.txt
  fastlane/metadata/da/support_url.txt
  fastlane/metadata/de-DE/support_url.txt
  fastlane/metadata/default/support_url.txt
  fastlane/metadata/en-AU/support_url.txt
  fastlane/metadata/en-CA/support_url.txt
  fastlane/metadata/en-GB/support_url.txt
  fastlane/metadata/en-US/support_url.txt
  fastlane/metadata/es-ES/support_url.txt
  fastlane/metadata/es-MX/support_url.txt
  fastlane/metadata/fr-FR/support_url.txt
  fastlane/metadata/id/support_url.txt
  fastlane/metadata/it/support_url.txt
  fastlane/metadata/ja/support_url.txt
  fastlane/metadata/ko/support_url.txt
  fastlane/metadata/nl-NL/support_url.txt
  fastlane/metadata/no/support_url.txt
  fastlane/metadata/pt-BR/support_url.txt
  fastlane/metadata/pt-PT/support_url.txt
  fastlane/metadata/ru/support_url.txt
  fastlane/metadata/sv/support_url.txt
  fastlane/metadata/th/support_url.txt
  fastlane/metadata/tr/support_url.txt
  fastlane/metadata/zh-Hans/support_url.txt
  fastlane/metadata/zh-Hant/support_url.txt
Labels: i18n

#21362 Jetpack Social: Hide Jetpack Social for private posts
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController+JetpackSocial.swift
Labels: [Type] Bug, Jetpack Social

#21343 Integrate PHPickerViewController in Media library
  WordPress/Classes/Services/MediaImportService.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/Media/ItemProviderMediaExporter.swift
  WordPress/Classes/Utility/Media/MediaAssetExporter.swift
  WordPress/Classes/Utility/Media/MediaFileManager.swift
  WordPress/Classes/Utility/Media/MediaImageExporter.swift
  WordPress/Classes/Utility/Media/MediaVideoExporter.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Media/NSItemProvider+Exportable.swift
  WordPress/Classes/ViewRelated/Media/PHPickerController+Extensions.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ItemProviderMediaExporterTests.swift
  WordPress/WordPressTest/Test Data/test-webp.webp
Labels: Media, [Type] Task, UI Modernization

#21370 Integrate PHPickerViewController in Site Icon picker
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/BlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/SiteIconView.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerViewController+QuickStart.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerViewController+SiteIcon.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteIconPickerPresenter.swift
  WordPress/Classes/ViewRelated/Media/MediaPickerMenu.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Media, [Type] Task, UI Modernization

#21379 Disable testPagesCardHeaderNavigation for fixing.
  WordPress/UITests/JetpackUITests.xctestplan
Labels: Testing

#21354 Jetpack Social: Exclude unshared private connections from other users
  WordPress/Classes/Services/SharingSyncService.swift
  WordPress/WordPressTest/SharingServiceTests.swift
Labels: [Type] Enhancement, Jetpack Social

#21369 Remove the New Photo Post app shortcut
  RELEASE-NOTES.txt
  WordPress/Classes/System/3DTouch/WP3DTouchShortcutCreator.swift
  WordPress/Classes/System/3DTouch/WP3DTouchShortcutHandler.swift
  WordPress/Classes/System/RootViewPresenter+EditorNavigation.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
Labels: Posting/Editing, [Type] Task, UI Modernization

#21352 Fix unbounded growth of number media observers in Post Editor
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
Labels: [Type] Bug, Posting/Editing

#21360 Integrate PHPickerViewController in Page Editor
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Media/PHPickerController+Extensions.swift
Labels: Media, [Type] Task, UI Modernization

#21381 Add TaggedManagedObjectID type
  WordPress/Classes/Utility/TaggedManagedObjectID.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/TaggedManagedObjectIDTests.swift
Labels: Core Data

#21375 Fix a crash when OAuth token becomes invalid
  RELEASE-NOTES.txt
  WordPress/Classes/Models/WPAccount.m
Labels: [Type] Core

#21395 Merge 23.1 code freeze and 23.1.0.1 beta with conflicts resolution
  Podfile.lock
  WordPress/Classes/Services/SharingSyncService.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/GoogleDomains/DashboardGoogleDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/GoogleDomains/DashboardGoogleDomainsCardView.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController+JetpackSocial.swift
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  WordPress/Resources/ro.lproj/Localizable.strings
  WordPress/Resources/sq.lproj/Localizable.strings
  WordPress/WordPressTest/SharingServiceTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/default/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#21390 Use optional chaining to prevent crash in `GutenbergViewController`
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: [Type] Crash, Gutenberg

#21385 Fix error on screenshots test
  WordPress/JetpackScreenshotGeneration/JetpackScreenshotGeneration.swift
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
Labels: Testing

#21396 Update JTAppleCalendar to address a compiling issue in Xcode 15
  Podfile
  Podfile.lock
Labels: Core

#21383 [UI Tests] - Follow New Topic on Discover Tab Test
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/reader_tags_travel.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/reader_tags_travel_follow.json
  WordPress/Classes/ViewRelated/Reader/ReaderTopicsCardCell.swift
  WordPress/UITests/README.md
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
Labels: Testing, [Type] Task

#21389 Remove Gravatar editing support from the Me screen
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Me/Views/Header/MeHeaderView.h
  WordPress/Classes/ViewRelated/Me/Views/Header/MeHeaderView.m
Labels: Media, [Type] Task, UI Modernization

#21382 [UI Tests] - Add Like Notification Test
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/notifications/notifications_comment_like.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/notifications/notifications_comment_parent.json
  WordPress/UITests/README.md
  WordPress/UITests/Tests/NotificationTests.swift
  WordPress/UITestsFoundation/Screens/NotificationsScreen.swift
Labels: Testing, [Type] Task

#21402 [UI Test] Enhance EditorPostSettings Screen Object and reduce testCreateScheduledPost() flakiness.
  WordPress/UITestsFoundation/Screens/Editor/EditorPostSettings.swift
Labels: Testing

#21403 Move PHPickerResult.loadImage
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteIconPickerPresenter.swift
  WordPress/Classes/ViewRelated/Me/My Profile/Gravatar/AvatarMenuController.swift
  WordPress/Classes/ViewRelated/Media/MediaPickerMenu.swift
  WordPress/Classes/ViewRelated/Media/PHPickerController+Extensions.swift
Labels: Media, [Type] Task, UI Modernization

#21398 Fix an issue with camera not working without "All Photos" permission
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Media/Blog+VideoLimits.swift
  WordPress/Classes/Utility/Media/WPMediaAsset+VideoLimits.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Media/CameraCaptureCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaPickerMenu.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Media, [Type] Task, UI Modernization

#21394 Extract a few helper functions from PostService
  WordPress/Classes/Services/PostHelper+JetpackSocial.swift
  WordPress/Classes/Services/PostHelper.h
  WordPress/Classes/Services/PostHelper.m
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PostHelperJetpackSocialTests.swift
Labels: Core

#21361 Add chatbot analytics
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewModel.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_error_handler.js
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget_page.html
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/SupportChatBotViewModelTests.swift
Labels: [Type] Task, Contact Support

#21397 [UI Tests] - Add Save a Post from Reader Test
  WordPress/Classes/ViewRelated/Views/NoResultsViewController.swift
  WordPress/UITests/README.md
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITestsFoundation/FancyAlertComponent.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
Labels: Testing, [Type] Task

#21348 UI Modernization: Move Me to bottom tab bar
  Podfile
  Podfile.lock
  WordPress/Classes/Extensions/UIImage+Gravatar.swift
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/Utility/Media/ImageDownloader+Gravatar.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Me.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+SectionHelpers.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController+UIViewControllerRestoration.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Me/My Profile/MyProfileHeaderView.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+MeTab.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/Jetpack/AppConstants.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, UI Modernization

#21422 UI Modernization: Me tab UI tweaks
  WordPress/Classes/Extensions/UIImage+Gravatar.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Me.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/BlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/SiteIconView.swift
  WordPress/Classes/ViewRelated/Me/Views/Header/MeHeaderView.m
  WordPress/Classes/ViewRelated/System/WPTabBarController+MeTab.swift
Labels: [Type] Enhancement, UI Modernization

#21418 Integrate gutenberg-mobile release 1.101.2
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#21411 Fix media uploads error handling
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Media.swift
  WordPress/Classes/Services/MediaImportService.swift
  WordPress/Classes/Utility/Media/Blog+VideoLimits.swift
  WordPress/Classes/Utility/Media/ItemProviderMediaExporter.swift
  WordPress/Classes/Utility/Media/MediaAssetExporter.swift
  WordPress/Classes/Utility/Media/MediaExporter.swift
  WordPress/Classes/Utility/Media/MediaExternalExporter.swift
  WordPress/Classes/Utility/Media/MediaImageExporter.swift
  WordPress/Classes/Utility/Media/MediaThumbnailExporter.swift
  WordPress/Classes/Utility/Media/MediaURLExporter.swift
  WordPress/Classes/Utility/Media/MediaVideoExporter.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryMediaPickingCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaPickerMenu.swift
  WordPress/Classes/ViewRelated/Media/MediaProgressCoordinatorNoticeViewModel.swift
  WordPress/Classes/ViewRelated/Media/PHPickerController+Extensions.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogVideoLimitsTests.swift
Labels: [Type] Bug, Media, UI Modernization

#21435 Reader: Centers the footer spinner in its view.
  WordPress/Classes/ViewRelated/Post/PostListFooterView.xib
Labels: [Type] Bug, Reader

#21428 [UI Tests] Disable tests involving media picker for maintenance.
  WordPress/UITests/JetpackUITests.xctestplan
Labels: Testing

#21413 Enable Native Photo Picker feature flag
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Media, [Type] Task, UI Modernization

#21437 Merge 23.0.1 hotfix into 23.1
  RELEASE-NOTES.txt
Labels: Releases

#21419 Add a PostRepository type
  WordPress/Classes/Services/PostRepository.swift
  WordPress/Classes/Services/PostService.h
  WordPress/Classes/Utility/CoreDataHelper.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/PostRepositoryTests.swift
Labels: Core Data

#21191 Rewrite Gutenberg configuration file from Ruby to YAML
  .rubocop.yml
  Gutenberg/cocoapods_helpers.rb
  Gutenberg/config.yml
  Gutenberg/version.rb
  Podfile.lock
  fastlane/lanes/release.rb
Labels: [Status] DO NOT MERGE, Tooling

#21416 Checkout Gutenberg source code when generating `strings`
  fastlane/lanes/localization.rb
Labels: i18n, Tooling

#21441 Merge 23.1 release notes into `trunk`
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  fastlane/Fastfile
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
Labels: Releases

#21423 Integrate gutenberg-mobile release 1.102.1
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#21447 [UI Tests] Re-enable media picker tests with support to PHPicker
  WordPress/UITests/JetpackUITests.xctestplan
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPostSettings.swift
  WordPress/UITestsFoundation/Screens/Media/PHPickerScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing

#21420 [UI Tests] - Fix flaky like comment test
  WordPress/Classes/ViewRelated/Comments/CommentContentTableViewCell.swift
  WordPress/UITestsFoundation/Screens/NotificationsScreen.swift
Labels: Testing

#21438 Remove MRProgress
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Cells/WPProgressTableViewCell.m
  WordPress/Classes/ViewRelated/Views/StoppableProgressIndicatorView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Core

#21414 Move post publish notice interaction to BlockEditorScreen
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/PostTests.swift
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/PostsScreen.swift
Labels: Testing

#21452 Merge 23.1.0.2 beta
  Gutenberg/config.yml
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/JetpackDraftActionExtension/en-AU.lproj/InfoPlist.strings
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/bg.lproj/Localizable.strings
  WordPress/Resources/cs.lproj/Localizable.strings
  WordPress/Resources/cy.lproj/Localizable.strings
  WordPress/Resources/da.lproj/Localizable.strings
  WordPress/Resources/de.lproj/Localizable.strings
  WordPress/Resources/en-AU.lproj/InfoPlist.strings
  WordPress/Resources/en-AU.lproj/Localizable.strings
  WordPress/Resources/en-CA.lproj/Localizable.strings
  WordPress/Resources/en-GB.lproj/Localizable.strings
  WordPress/Resources/es.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/hr.lproj/Localizable.strings
  WordPress/Resources/hu.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/is.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/nb.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/pl.lproj/Localizable.strings
  WordPress/Resources/pt-BR.lproj/Localizable.strings
  WordPress/Resources/pt.lproj/Localizable.strings
  WordPress/Resources/ro.lproj/Localizable.strings
  WordPress/Resources/ru.lproj/Localizable.strings
  WordPress/Resources/sk.lproj/Localizable.strings
  WordPress/Resources/sq.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/Resources/th.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  WordPress/Resources/zh-Hant.lproj/Localizable.strings
  WordPress/WordPressDraftActionExtension/en-AU.lproj/InfoPlist.strings
  WordPress/WordPressIntents/en-AU.lproj/Sites.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/default/release_notes.txt
  fastlane/metadata/default/release_notes.txt
Labels: Releases

#21430 Fix an issue with widget data sometimes showing zeros
  RELEASE-NOTES.txt
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
Labels: [Type] Bug, Widgets

#21429 Fix an issue with widget data sometimes showing zeros
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
Labels: [Type] Bug, Widgets

#21440 Use PostRepository.getPost in Post History
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/Revisions/RevisionsTableViewController.swift
Labels: Core Data

#21408 [UI Tests] - Add Like Post on Reader Test
  API-Mocks/WordPressMocks/src/main/assets/mocks/__files/__admin/scenarios.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/reader_like_post_after.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/reader_like_post_before.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/reader_likes_tab_after.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/reader_likes_tab_before.json
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/UITests/README.md
  WordPress/UITests/Tests/NotificationTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITestsFoundation/Screens/NotificationsScreen.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
Labels: Testing, [Type] Task

#21439 Use PostRepository.getPost in SearchManager
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Spotlight/SearchManager.swift
Labels: Core Data

#21451 Update various pods to their latest compatible version
  Podfile
  Podfile.lock
  WordPress/Classes/Services/Stories/CameraHandler.swift
  WordPress/Classes/Utility/Kanvas/KanvasCameraAnalyticsHandler.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#21442 Use PostRepository.getPost in Stats Insights
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: Core Data

#21462 Fix regression in Zendesk identity
  WordPress/Classes/Utility/ZendeskUtils.swift
Labels: [Type] Bug, Contact Support

#21444 Contact Support: Update styles
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
  WordPress/Classes/ViewRelated/Support/SupportChatBot/support_chat_widget.css
  WordPress/Classes/ViewRelated/Support/SupportCoordinator.swift
Labels: [Type] Task, Contact Support

#21465 [UI Tests] - Minor refactor on reader screen/tests
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
Labels: Testing

#21453 Fix flaky test - testContactUsCanBeLoadedDuringLogin()
  WordPress/UITestsFoundation/Screens/Me/SupportScreen.swift
Labels: Testing, [Type] Task

#21466 Contact Support: Prevent memory leaks by removing script message handlers
  WordPress/Classes/ViewRelated/Support/SupportChatBot/SupportChatBotViewController.swift
Labels: [Type] Bug, Contact Support

#21467 Contact Support: Update RELEASE-NOTES.txt
  RELEASE-NOTES.txt
Labels: [Type] Task, Contact Support

#21471 Pages List: Update a `precondition` check to be a `guard`
  RELEASE-NOTES.txt
  WordPress/Classes/Networking/WordPressOrgRestApi+WordPress.swift
Labels: [Type] Crash, Pages List

#21412 Reset reader topic observer upon re-assignment
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: Reader
