Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2023-06, with the labels that each got.

#20770 Blaze Manage Campaigns: Add remote feature flag
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
Labels: [Type] Task, Blaze

#20785 Merge editorialized release notes for version 22.5
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#20755 Catch Objective-C exceptions from Core Data object query
  WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
  WordPress/UITestsFoundation/Screens/DomainsSuggestionsScreen.swift
Labels: Core Data

#20776 Integrate gutenberg-mobile release 1.96.1
  Gutenberg/version.rb
  Podfile.lock
Labels: Gutenberg

#20793 Send Slack notification for UI/Unit test failures
  .buildkite/cache-builder.yml
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: [Type] Task, Tooling

#20787 Hiding Dashboard Cards: Enable feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: My Site Dashboard

#20782 Jetpack Social: Add Jetpack Social feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Task, Jetpack Social

#20786 Domains: Fix app hanging when selecting domain by showing an error notice
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
Labels: [Type] Bug, Domains

#20801 Update CocoaPods to 1.12.1
  Gemfile
  Gemfile.lock
  Podfile.lock
Labels: Tooling

#20795 Read deployment target from `xcconfig` in `Podfile`
  Podfile
  Podfile.lock
Labels: Tooling

#20796 [UI Tests] Added a UI Test for "Activity Log" dashboard card navigation.
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/activity/wpcom_v2_site_activity.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/dashboard/dashboard.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/feature-flags.json
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Activity Log/DashboardActivityLogCardCell.swift
  WordPress/UITests/Tests/DashboardTests.swift
  WordPress/UITestsFoundation/Screens/ActivityLogScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/XCUIApplication+ScrollDownToElement.swift
  WordPress/UITestsFoundation/XCUIElement+Scroll.swift
Labels: Testing

#20810 Plans on JP: Remove unnecessary analytics events
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/PlansTracker.swift
Labels: [Type] Enhancement, WP.com Plans

#20788 [UI Tests] Added a UI Test for "Pages" dashboard card navigation.
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/activity/wpcom_v2_site_activity.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/dashboard/dashboard.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/dashboard/publisize.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/feature-flags.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/pages/pages_offset_0.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/pages/pages_offset_6.json
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Activity Log/DashboardActivityLogCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Pages/DashboardPagesListCardCell.swift
  WordPress/UITests/Tests/DashboardTests.swift
  WordPress/UITestsFoundation/Screens/ActivityLogScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/PagesScreen.swift
  WordPress/UITestsFoundation/XCUIApplication+ScrollDownToElement.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing

#20777 Update release notes to include Hiding Dashboard Cards feature
  RELEASE-NOTES.txt
Labels: My Site Dashboard

#20812 Blaze Manage Campaigns: Add skeleton UI for the campaigns list screen
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
  WordPress/Classes/ViewRelated/Blaze/Overlay/BlazeOverlayViewModel.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeFlowCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Blaze

#20814 Blaze Manage Campaigns: Show loading and empty view in campaigns screen
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
Labels: [Type] Task, Blaze

#20822 Add release note for WP.com plans
  RELEASE-NOTES.txt
Labels: [Type] Task, WP.com Plans

#20807 Blaze Manage Campaigns: Add Blaze campaigns dashboard card
  Podfile
  Podfile.lock
  WordPress/Classes/Services/BlazeService.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignStatusView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Dashboard/DashboardBlazeCampaignViewModelTests.swift
Labels: [Type] Task, Blaze

#20819 Blaze Manage Campaigns: Add contextual menu to Blaze Campaign card
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignCardCell.swift
Labels: [Type] Task, Blaze

#20820 Blaze Manage Campaigns: Add Create Campaign button to Blaze Campaign card
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignCardCell.swift
Labels: [Type] Task, Blaze

#20821 Blaze Manage Campaigns: Add dark mode support to Blaze Campaign card
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignStatusView.swift
Labels: [Type] Task, Blaze

#20808 Jetpack Social: Add Jetpack Social no connection view to post settings
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoConnectionView.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.h
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Jetpack/AppImages.xcassets/Social/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-facebook.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-facebook.imageset/icon-facebook.svg
  WordPress/Jetpack/AppImages.xcassets/Social/icon-linkedin.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-linkedin.imageset/icon-linkedin.svg
  WordPress/Jetpack/AppImages.xcassets/Social/icon-tumblr.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-tumblr.imageset/icon-tumblr-dark.svg
  WordPress/Jetpack/AppImages.xcassets/Social/icon-tumblr.imageset/icon-tumblr.svg
  WordPress/Jetpack/AppImages.xcassets/Social/icon-twitter.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-twitter.imageset/icon-twitter.svg
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#20827 Integrate gutenberg-mobile release 1.97.0
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#20825 [UI Tests] - Refactor tests that crashes test runner in CI
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
Labels: Testing, [Type] Task

#20830 Merge 22.6 code freeze
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#20831 [UI Tests] - Fix featured image assertion
  WordPress/UITestsFoundation/Screens/Editor/EditorPostSettings.swift
Labels: Testing, [Type] Task

#20839 Fix #20837: infinite spinner on pull-to-refresh in Site Settings
  WordPress/Classes/Services/BlogService.m
Labels: [Type] Bug, Site Settings

#20829 [Privacy Compliance] Add Popover UI
  WordPress/Classes/ViewRelated/Reusable SwiftUI Views/CompliancePopover.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/DesignSystem/Spacing.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Account Settings

#20866 Drop iOS 14 Support: Update Share Extensions
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressShareExtension/TextBundleWrapper.m
  WordPress/WordPressShareExtension/UIImage+Extensions.swift
Labels: General, [Type] Task

#20867 Run the "null blog property sanitization" logic as the very first Core Data operation
  RELEASE-NOTES.txt
  WordPress/Classes/Services/NullBlogPropertySanitizer.swift
Labels: Core Data

#20832 [UI Tests] - Remove unused properties and unneeded throws
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
Labels: Testing, [Type] Task

#20854 Blogging Prompts: Fix Core Data concurrency issues in scheduler
  WordPress/Classes/Services/BloggingPromptsService.swift
  WordPress/Classes/Utility/Blogging Prompts/PromptRemindersScheduler.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Prompts/BloggingPromptCoordinator.swift
Labels: [Type] Enhancement, Core Data, Blogging Prompts

#20844 Reader: Fix viewDidDisappear crash
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: [Type] Crash, Reader

#20875 Remove AlertView (dead code)
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingStreamsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+AlertView.swift
  WordPress/Classes/ViewRelated/Views/AlertView/AlertInternalView.swift
  WordPress/Classes/ViewRelated/Views/AlertView/AlertView.swift
  WordPress/Classes/ViewRelated/Views/AlertView/AlertView.xib
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#20884 Drop iOS 14: Remove WPBlogSelectorButton (dead code)
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+BlogPicker.swift
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
  WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.h
  WordPress/Classes/ViewRelated/Views/WPBlogSelectorButton.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#20876 Drop iOS 14 Support: Remove UIApplication/windows usage
  WordPress/Classes/Extensions/UIApplication+mainWindow.swift
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
Labels: [Type] Task

#20863 (1/2) Address Objective-C Static Analysis Issues
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Menu.h
  WordPress/Classes/Models/MenuItem.h
  WordPress/Classes/Networking/WordPressOrgRestApi+WordPress.swift
  WordPress/Classes/Services/PostCategoryService.m
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/Services/PostTagService.m
  WordPress/Classes/Utility/WPTableViewHandler.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsSettingsViewController.m
  WordPress/Classes/ViewRelated/Media/MediaLibraryPickerDataSource.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Tools/SettingsMultiTextViewController.m
Labels: [Type] Task

#20872 Draft post card: Prevent crash when re-opening post mid-upload
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostListEditorPresenter.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: [Type] Crash, Posting/Editing

#20887 Drop iOS 14 Support: Replace deprecated UTType APIs in Media
  WordPress/Classes/Models/Media.h
  WordPress/Classes/Models/Media.m
  WordPress/Classes/Models/Media.swift
  WordPress/Classes/Services/MediaService+Swift.swift
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/Utility/Analytics/WPAppAnalytics+Media.swift
  WordPress/WordPressTest/MediaServiceUpdateTests.m
  WordPress/WordPressTest/MediaTests.swift
Labels: [Type] Task, Drop iOS 14

#20888 Drop iOS 14 Support: Remove WPButtonForNavigationBar
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
  WordPress/Classes/ViewRelated/Post/WPButtonForNavigationBar.h
  WordPress/Classes/ViewRelated/Post/WPButtonForNavigationBar.m
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Pages.h
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Posts.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Drop iOS 14

#20889 Drop iOS 14 Support: Update UTType usages (#1)
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/NSAttributedString+Helpers.swift
  WordPress/Classes/Models/Blog+Files.swift
  WordPress/Classes/Models/SharePost+UIActivityItemSource.swift
  WordPress/Classes/Utility/Media/MediaAssetExporter.swift
  WordPress/Classes/Utility/Media/MediaImageExporter.swift
  WordPress/Classes/Utility/Media/MediaThumbnailExporter.swift
  WordPress/Classes/Utility/Spotlight/SearchableActivityConvertable.swift
  WordPress/Classes/Utility/Spotlight/SearchableItemConvertable.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteIconPickerPresenter.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
  WordPress/Classes/ViewRelated/Me/My Profile/Gravatar/GravatarPickerViewController.swift
  WordPress/Classes/ViewRelated/Media/CameraCaptureCoordinator.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryPicker.swift
  WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorMedia.swift
  WordPress/Classes/ViewRelated/Media/Tenor/TenorPicker.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Sharing.swift
  WordPress/Classes/ViewRelated/Views/RichTextView/RichTextView.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachment.swift
  WordPress/WordPressTest/MediaAssetExporterTests.swift
  WordPress/WordPressTest/MediaExporterTests.swift
  WordPress/WordPressTest/MediaImageExporterTests.swift
Labels: [Type] Task, Drop iOS 14

#20891 [UI Tests] - Add logout at launch capability
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/UITests/Tests/DashboardTests.swift
  WordPress/UITests/Tests/EditorAztecTests.swift
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/MenuNavigationTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITests/Tests/SignupTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITests/Tests/SupportScreenTests.swift
  WordPress/UITests/Utils/XCTest+Extensions.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PrologueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/WelcomeScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
Labels: Testing, [Type] Task

#20846 Fix a Core Data concurrency issue when CrashLogging is called from a background thread
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift
Labels: [Type] Crash, Core Data

#20892 Merge beta 22.6.0.1
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/de.lproj/Localizable.strings
  WordPress/Resources/es.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/ro.lproj/Localizable.strings
  WordPress/Resources/ru.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  WordPress/Resources/zh-Hant.lproj/Localizable.strings
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/default/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/en-GB/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#20901 Remove some unused types from the unit tests target
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/Classes/Services/SiteVerticalsService.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Mention/SuggestionsTableViewMockDelegate.swift
Labels: Testing

#20894 Fix an issue with Related Posts settings not being saved
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsSettingsViewController.m
Labels: [Type] Bug

#20885 PostsList - Disable the menu button/action bar when a post is being uploaded
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Post/PostCardCell.swift
  WordPress/Classes/ViewRelated/Post/PostCompactCell.swift
  WordPress/WordPressTest/PostCardCellGhostableTests.swift
  WordPress/WordPressTest/PostCompactCellGhostableTests.swift
Labels: Posting/Editing, Posts List

#20905 Drop iOS 14 Support: Update remaining UTType usages (#3)
  WordPress/Classes/Categories/Media+WPMediaAsset.m
  WordPress/Classes/Extensions/String+Files.swift
  WordPress/Classes/Extensions/URL+Helpers.swift
  WordPress/Classes/Models/Blog+Files.swift
  WordPress/Classes/Utility/Media/MediaAssetExporter.swift
  WordPress/Classes/Utility/Media/MediaImageExporter.swift
  WordPress/Classes/Utility/Media/MediaThumbnailExporter.swift
  WordPress/Classes/Utility/Media/MediaURLExporter.swift
  WordPress/Classes/Utility/Media/MediaVideoExporter.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MediaExporterTests.swift
  WordPress/WordPressTest/MediaURLExporterTests.swift
Labels: [Type] Task, Drop iOS 14

#20910 Use MediaEditor 1.2.2
  Podfile
  Podfile.lock
Labels: Releases

#20913 Drop iOS 14 Support: Remove unused CommentModerationBar
  WordPress/Classes/Extensions/UIEdgeInsets.swift
  WordPress/Classes/ViewRelated/Comments/CommentModerationBar.swift
  WordPress/Classes/ViewRelated/Comments/CommentModerationBar.xib
  WordPress/Classes/ViewRelated/Comments/WPStyleGuide+CommentDetail.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Drop iOS 14

#20903 [UI Tests] - Move XCTAsserts away from tests
  WordPress/UITests/Flows/EditorFlow.swift
  WordPress/UITests/Flows/LoginFlow.swift
  WordPress/UITests/Tests/DashboardTests.swift
  WordPress/UITests/Tests/EditorAztecTests.swift
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/MenuNavigationTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITests/Tests/SignupTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITestsFoundation/Globals.swift
  WordPress/UITestsFoundation/Screens/ActivityLogScreen.swift
  WordPress/UITestsFoundation/Screens/DomainsScreen.swift
  WordPress/UITestsFoundation/Screens/DomainsSuggestionsScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/GetStartedScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PrologueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/WelcomeScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/PagesScreen.swift
  WordPress/UITestsFoundation/Screens/PlanSelectionScreen.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
Labels: Testing, [Type] Task

#20920 Cherry-pick #20846 into 22.5.1 hotfix
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WPCrashLoggingDataProviderTests.swift
Labels: Core Data

#20924 Cherry pick #20844 into 22.5.1 hotfix
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
Labels: [Type] Bug

#20925 Cherry pick #20867 into 22.5.1 hotfix
  RELEASE-NOTES.txt
  WordPress/Classes/Services/NullBlogPropertySanitizer.swift
Labels: Core Data

#20921 Drop iOS 14 Support: Fix an issue with PostMetaButton not visible from Interface Builder
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Post/PostMetaButton+Swift.swift
  WordPress/Classes/ViewRelated/Post/PostMetaButton.h
  WordPress/Classes/ViewRelated/Post/PostMetaButton.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Drop iOS 14

#20878 Site Settings in SwiftUI: Privacy
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Blog/Settings/SettingsCell.swift
  WordPress/Classes/ViewRelated/Blog/Settings/SettingsPicker.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/BlogSiteVisibilityHelper.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/BlogSiteVisibilityHelper.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteVisibility+Extensions.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogSiteVisibilityHelperTest.m
  WordPress/WordPressTest/SiteVisibilityTests.swift
Labels: Site Settings

#20929 Merge 22.5.1 hotfix into 22.6
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Services/NullBlogPropertySanitizer.swift
Labels: Releases

#20909 Set the `selectedNotification` property within `showDetails`
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
Labels: Notifications

#20916 Blaze: switch to using canBlaze to determine Blaze eligibility
  MIGRATIONS.md
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Models/AbstractPost+Blaze.swift
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Services/BlazeService.swift
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/ViewRelated/Blaze/Helpers/BlazeHelper.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 150.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/PostActionSheetTests.swift
Labels: [Type] Task, Blaze

#20902 Minor `SiteSegmentStepTests` tidy up
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/WordPressTest/SiteCreation/SiteSegmentsStepTests.swift
Labels: Testing

#20932 Blaze Manage Campaigns: Display campaigns card based on context
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignsCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazePromoCardView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Blaze

#20938 Integrate gutenberg-mobile release 1.98.0
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#20926 Add Test Coverage List
  WordPress/UITests/README.md
Labels: Testing

#20753 Comments: Add the new header component
  WordPress/Classes/ViewRelated/Comments/CommentTableHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Comments, Part of a WIP Feature

#20815 Implement action to redirect the user to Privacy Settings screen
  WordPress/Classes/Extensions/CATransaction+Extension.swift
  WordPress/Classes/System/RootViewPresenter+AppSettingsNavigation.swift
  WordPress/Classes/System/RootViewPresenter+MeNavigation.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Account Settings

#20942 Merge finalized release 22.6
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
Labels: Releases

#20935 Enable `overridden_super_call` SwiftLint rule and address violations
  .swiftlint.yml
  Podfile.lock
  WordPress/Classes/ViewRelated/Activity/ActivityDetailViewController.swift
  WordPress/Classes/ViewRelated/Activity/BaseActivityListViewController.swift
  WordPress/Classes/ViewRelated/Activity/CalendarViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/SettingsTitleSubtitleController.swift
  WordPress/Classes/ViewRelated/Cells/ExpandableCell.swift
  WordPress/Classes/ViewRelated/Cells/TitleBadgeDisclosureCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Menu Card/JetpackBrandingMenuCardCell.swift
  WordPress/Classes/ViewRelated/Me/My Profile/Change Username/ChangeUsernameViewController.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/Classes/ViewRelated/People/PeopleCell.swift
  WordPress/Classes/ViewRelated/Plugins/CollectionViewContainerRow.swift
  WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
  WordPress/Classes/ViewRelated/Post/Revisions/Browser/RevisionsNavigationController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesListController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderWebView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Site Intent/IntentCell.swift
  WordPress/Classes/ViewRelated/Site Creation/Site Segments/SiteSegmentsCell.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/AddressTableViewCell.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsCellHeader.swift
  WordPress/Classes/ViewRelated/System/BlurredEmptyViewController.swift
Labels: Tooling

#20918 Core Data: Fixes a Core Data Multithreading violation when unscheduling blogging reminders
  WordPress/Classes/Services/BloggingPromptsService.swift
  WordPress/Classes/Utility/Blogging Prompts/ReminderScheduleCoordinator.swift
Labels: [Type] Bug, Core Data, Blogging Reminders

#20947 Merge 22.7 code freeze
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  WordPress/WordPress.xcodeproj/project.pbxproj
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#20948 Merge hotfix 22.6.1 into release 22.7
  WordPress/Classes/Services/BloggingPromptsService.swift
  WordPress/Classes/Utility/Blogging Prompts/ReminderScheduleCoordinator.swift
Labels: Releases

#20895 Site Settings in SwiftUI: Related Posts
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsPreviewTableViewCell.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsPreviewTableViewCell.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsSettingsViewController.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/Related Posts/RelatedPostsSettingsViewController.m
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsRelatedPostsView.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Settings, [Type] Task

#20917 Drop iOS 14 Support: Increase deployment target to iOS 15
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/Extensions/NSAttributedString+Helpers.swift
  WordPress/Classes/Extensions/UIApplication+mainWindow.swift
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/Classes/ViewRelated/Blaze/Overlay/BlazeOverlayViewController.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeWebViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Pages/DashboardPageCreationCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/QuickStartChecklistViewController.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Domains/Views/DomainsDashboardView.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Menu Card/JetpackBrandingMenuCardCell.swift
  WordPress/Classes/ViewRelated/Menus/MenuItemView.m
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailFeaturedImageView.swift
  WordPress/Classes/ViewRelated/System/Action Sheet/BloggingPromptsHeaderView.swift
  WordPress/Classes/ViewRelated/Views/RichTextView/AnimatedGifAttachmentViewProvider.swift
  WordPress/Classes/ViewRelated/Views/RichTextView/RichTextView.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Common/Navigation/MigrationNavigationController.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Delete WordPress/MigrationDeleteWordPressViewController.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Welcome/MigrationWelcomeViewController.swift
  config/Common.xcconfig
Labels: [Type] Task, Drop iOS 14

#20823 Jetpack Social: Add icon download for social media icons that aren't bundled
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoConnectionView.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Jetpack/AppImages.xcassets/Social/icon-instagram.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-instagram.imageset/icon-instagram.svg
  WordPress/Jetpack/AppImages.xcassets/Social/icon-mastodon.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-mastodon.imageset/icon-mastodon.svg
  WordPress/Jetpack/AppImages.xcassets/Social/icon-tumblr.imageset/icon-tumblr-dark.svg
Labels: [Type] Enhancement, Jetpack Social

#20943 Fix fab overlapping the personalize dashboard card
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift
Labels: [Type] Bug

#20946 Jetpack Social: Add Core Data model for PublicizeInfo
  MIGRATIONS.md
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Models/PublicizeInfo+CoreDataClass.swift
  WordPress/Classes/Models/PublicizeInfo+CoreDataProperties.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 151.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Core Data, Part of a WIP Feature, Jetpack Social

#20955 Add JetpackSocialService to fetch auto-sharing limit
  WordPress/Classes/Models/PublicizeInfo+CoreDataClass.swift
  WordPress/Classes/Services/JetpackSocialService.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/JetpackSocialServiceTests.swift
Labels: [Type] Enhancement, Core Data, Part of a WIP Feature, Jetpack Social

#20940 [UI Tests] - Add Media Blocks UI Test
  WordPress/UITests/Flows/LoginFlow.swift
  WordPress/UITests/README.md
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PrologueScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
Labels: Testing, [Type] Task

#20937 Implement a type to track Privacy Settings analytic events
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsAnalytics.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsAnalyticsTracker.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Analytics, [Type] Task

#20960 Make sure context is saved before calling the completion callback
  RELEASE-NOTES.txt
  WordPress/Classes/Services/PostService.m
Labels: Core Data

#20959 Don't save synced blogs after signed out
  RELEASE-NOTES.txt
  WordPress/Classes/Services/BlogService.m
  WordPress/WordPressTest/BlogJetpackTests.swift
Labels: Login

#20970 Blogging Reminders: Don't show prompt if not allowed for blog
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlow.swift
Labels: [Type] Bug, Blogging Reminders

#20969 Jetpack Social: Add methods and fields to Blog for auto-sharing limit
  MIGRATIONS.md
  Podfile
  Podfile.lock
  WordPress/Classes/Models/Blog+JetpackSocial.swift
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 151.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Blog+PublicizeTests.swift
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/Dashboard/BlazeCampaignViewModelTests.swift
Labels: [Type] Enhancement, Core Data, Part of a WIP Feature, Jetpack Social

#20944 Blaze Manage Campaigns: Integrate the API
  WordPress/Classes/Services/BlazeService.swift
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeWebViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/BlazeCampaignStatusView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignsCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCellViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersistence.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/ViewModel/BlogDashboardViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Dashboard/DashboardBlazeCardCellViewModelTest.swift
  WordPress/WordPressTest/Test Data/blaze-search-response.json
Labels: [Type] Task, Blaze

#20965 Jetpack Social: Add tap actions to the no connections social view on the post settings
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
Labels: [Type] Enhancement, Jetpack Social

#20967 Use Xcode 14.3.1 in CI
  .buildkite/cache-builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  .xcode-version
Labels: Tooling

#20976 Integrate gutenberg-mobile release 1.98.1
  Gutenberg/version.rb
  Podfile.lock
Labels: Gutenberg

#20966 Jetpack Social: Add the remaining social shares view to the post settings screen
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoConnectionView.swift
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialSettingsRemainingSharesView.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.h
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController_Internal.h
  WordPress/Jetpack/AppImages.xcassets/Social/icon-warning.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-warning.imageset/icon-warning.svg
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Jetpack Social

#20305 Use `replacePersistentStore` over `migratePersistentStore`
  WordPress/Classes/Utility/CoreDataHelper.swift
Labels: [Type] Enhancement, Core Data, Jetpack Content Migration Flow
