Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2023-05, with the labels that each got.

#20626 Merge 22.3 code freeze
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#20590 [Domain Purchasing] Add A/B Experiment
  WordPress/Classes/Services/SiteAddressService.swift
  WordPress/Classes/Utility/AB Testing/ABTest.swift
  WordPress/Classes/Utility/Analytics/WPAnalytics+Domains.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController+SiteCreation.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Site Creation/Final Assembly/SiteAssemblyContentView.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/AddressTableViewCell.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Site Creation, Jetpack App

#20613 Improve site creation error handling in the site assembly step
  WordPress/Classes/ViewRelated/Site Creation/Final Assembly/SiteAssemblyWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/ErrorStates/ErrorStateViewConfiguration.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: [Type] Enhancement, Site Creation, Jetpack App, Domains

#20607 Workaround to support ExPlat in Jetpack app
  Podfile
  Podfile.lock
  WordPress/Classes/Services/SiteAddressService.swift
  WordPress/Classes/Utility/AB Testing/ABTest.swift
  WordPress/Classes/Utility/Analytics/WPAnalytics+Domains.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController+SiteCreation.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Site Creation/Final Assembly/SiteAssemblyContentView.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/AddressTableViewCell.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/WebAddressWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreator.swift
  WordPress/Jetpack/AppConstants.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Tracks

#20637 Dashboard Cards: Add internal release notes Activity Log and Pages
  RELEASE-NOTES.txt
Labels: [Type] Task, My Site Dashboard

#20633 Check if object id is a temporary object id
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
Labels: Core Data

#20649 [UI Tests] Make crash reports available in CI
  .buildkite/commands/run-ui-tests.sh
  .buildkite/pipeline.yml
Labels: Testing

#20624 My Site Dashboard: Hide unsupported quick action buttons
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Actions/DashboardQuickActionsCardCell.swift
Labels: [Type] Bug, My Site Dashboard

#20655 [UI Tests] - Small refactoring as prep to turn on parallel testing
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/sites/sites_rewind_capabilities.json
  WordPress/UITests/Flows/LoginFlow.swift
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PasswordScreen.swift
Labels: Testing

#20658 [UI Tests] Simplify the command to copy crash reports into Artifacts
  .buildkite/commands/run-ui-tests.sh
Labels: Testing

#20659 Updates the copy of the Jetpack static poster
  WordPress/Classes/Extensions/String+NonbreakingSpace.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Moved To Jetpack/MovedToJetpackViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Moved To Jetpack/MovedToJetpackViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, [Status] Needs Design Review, Jetpack Focus

#20648 Site Editor: Fetch the editor settings on `PageListViewController`
  WordPress/Classes/Services/BlockEditorSettingsService.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: [Type] Task, Full Site Editing

#20651 Refactor the migration error handling logic to include the underlying error
  WordPress/Classes/Utility/CoreDataHelper.swift
  WordPress/Jetpack/Classes/Utility/DataMigrationError.swift
  WordPress/Jetpack/Classes/Utility/DataMigrator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ContentMigrationCoordinatorTests.swift
  WordPress/WordPressTest/DataMigratorTests.swift
Labels: [Type] Enhancement

#20623 My Site: Hide the Stats row if it is unsupported
  WordPress/Classes/Categories/NSMutableArray+NullableObjects.h
  WordPress/Classes/Categories/NSMutableArray+NullableObjects.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Bug, My Site

#20662 Integrate gutenberg-mobile release 1.95.0
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#20657 [Gutenberg] Avoid sending HTML to the editor when closing
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg

#20670 Enable siteCreationDomainPurchasing feature flag
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: Site Creation, Jetpack App, Domains

#20667 [Tooling] Use Buildkite emojis for Prototype Builds
  fastlane/lanes/build.rb
Labels: Tooling

#20666 Editor: Fix crash when adding images when permissions are missing
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaPickerHelper.swift
Labels: [Type] Crash, Posting/Editing, Media

#20656 Turn on Parallel Testing for UI Tests
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests.sh
  WordPress/UITests/JetpackUITests.xctestplan
  fastlane/lanes/build.rb
Labels: Testing

#20665 Merge finalized release 22.3
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Gutenberg/EditorMediaUtility.swift
  WordPress/Resources/cs.lproj/Localizable.strings
  WordPress/Resources/de.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/ru.lproj/Localizable.strings
  WordPress/Resources/sq.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/default/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#20672 Revert an overlooked comment in the Podfile
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
Labels: General

#20668 Activity Log: Check if route is valid before determining match
  WordPress/Classes/Utility/Universal Links/RouteMatcher.swift
  WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
Labels: [Type] Bug, Activity Log

#20671 Site Editor: Create theme template homepage cell
  WordPress/Classes/ViewRelated/Pages/PageListTableViewHandler.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Pages/TemplatePageTableViewCell.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Full Site Editing

#20673 Merge 22.4 code freeze
  Gemfile
  Gemfile.lock
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/lanes/release.rb
Labels: Releases

#20679 Dashboard Cards: Update title font weight to semibold
  WordPress/Classes/ViewRelated/Activity/ActivityTableViewCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Pages/DashboardPageCell.swift
Labels: [Type] Enhancement, My Site Dashboard

#20663 Update domain purchasing in site creation analytics
  WordPress/Classes/Utility/Analytics/WPAnalytics+Domains.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/DomainPurchasingWebFlowController.swift
  WordPress/Classes/ViewRelated/Site Creation/Final Assembly/SiteAssemblyWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/EnhancedSiteCreationAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Analytics, Jetpack App, Domains

#20678 Site Editor: Open authenticated web view to site editor on homepage tap
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: [Type] Task, Full Site Editing

#20695 Merge editorialized release notes for 22.4
  WordPress/Classes/Utility/Analytics/WPAnalytics+Domains.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/DomainPurchasingWebFlowController.swift
  WordPress/Classes/ViewRelated/Site Creation/Final Assembly/SiteAssemblyWizardContent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/EnhancedSiteCreationAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Site Creation/Shared/SiteCreationAnalyticsHelper.swift
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Releases

#20680 Accessibility Labels for Reader Navigation Buttons
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
Labels: Accessibility, Reader, [Type] Task

#20693 Free to Paid Plans: Create a Dashboard Card with the presentation criteria
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/BaseDashboardDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/DashboardDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansDashboardCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansDashboardCardHelper.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/Classes/ViewRelated/Blog/BlogPersonalization/BlogDashboardPersonalizationViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/Dashboard/FreeToPaidPlansDashboardCardHelperTests.swift
Labels: [Type] Task, WP.com Plans

#20694 Site Editor: Add edit homepage analytics to the page list screen
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Pages/TemplatePageTableViewCell.swift
Labels: [Type] Task, Full Site Editing

#20682 Address a few RuboCop violations
  Gemfile.lock
  fastlane/lanes/build.rb
Labels: Tooling

#20705 Reader: Missing Report and Block actions from the Post Menu Sheet
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Reader/ReaderMenuAction.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderPostCellActionsTests.swift
Labels: [Type] Bug, Reader

#20713 Site Editor: Update site editor MVP to a remote feature flag and enable it
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Pages/PageListTableViewHandler.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: [Type] Task, Full Site Editing

#20697 Plans on JP: Show free for first year offer on domain selection screen
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansDashboardCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+DomainCredit.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/DomainSuggestionViewControllerWrapper.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/DomainSuggestionsTableViewController.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Domains/Views/DomainsDashboardCoordinator.swift
  WordPress/Classes/ViewRelated/Domains/Views/DomainsDashboardFactory.swift
  WordPress/Classes/ViewRelated/Domains/Views/DomainsDashboardView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, WP.com Plans

#20707 Social: Update external services to wpcom/v2
  MIGRATIONS.md
  Podfile
  Podfile.lock
  WordPress/Classes/Models/PublicizeService.swift
  WordPress/Classes/Services/SharingService.swift
  WordPress/Classes/WordPress.xcdatamodeld/.xccurrentversion
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 149.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Core Data, Jetpack Social

#20708 Social: Add deprecated section in connection list
  WordPress/Classes/Models/PublicizeService.swift
  WordPress/Classes/ViewRelated/Blog/SharingViewController.m
Labels: [Type] Enhancement, Jetpack Social

#20709 Social: Show Twitter deprecation footer in connection list screen
  WordPress/Classes/ViewRelated/Blog/SharingViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingViewController.swift
  WordPress/Classes/ViewRelated/Blog/TwitterDeprecationTableFooterView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Jetpack Social

#20714 Social: Show deprecation notice in detail screens
  WordPress/Classes/Models/PublicizeService.swift
  WordPress/Classes/ViewRelated/Blog/SharingConnectionsViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m
  WordPress/Classes/ViewRelated/Blog/TwitterDeprecationTableFooterView.swift
Labels: [Type] Enhancement, Jetpack Social

#20702 Reader: Fix followed topics display for non-latin languages
  RELEASE-NOTES.txt
  WordPress/Classes/Models/ReaderTagTopic.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
Labels: Reader, Localization

#20716 Plans on JP: Add plan step to free-to-paid purchase flow
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansCoordinator.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/PlanSelectionViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, WP.com Plans

#20719 Extract build phase to copy Gutenberg resources in script
  Scripts/BuildPhases/CopyGutenbergJS.inputs.xcfilelist
  Scripts/BuildPhases/CopyGutenbergJS.outputs.xcfilelist
  Scripts/BuildPhases/CopyGutenbergJS.sh
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#20710 Plans on JP: Analytics
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/BaseDashboardDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/DashboardDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansDashboardCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/PlansTracker.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, WP.com Plans

#20725 Social: Track when Twitter notice footer link is tapped
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blog/TwitterDeprecationTableFooterView.swift
Labels: [Type] Enhancement, Jetpack Social

#20731 Plans on JP: Use a single modal for the entire flow
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansCoordinator.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/CheckoutViewController.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/PlanSelectionViewController.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/DomainSuggestionsTableViewController.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Domains/Utility/WebKitViewController+SandboxStore.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, WP.com Plans

#20740 Integrate gutenberg-mobile release 1.96.0
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#20739 Fix crash when initializing SupportTableViewController from WPError alert
  WordPress/Classes/Utility/WPError.m
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: [Type] Crash, Support

#20737 Comments: Add a feature flag for comment moderation updates
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Enhancement, Comments, Part of a WIP Feature

#20743 Merge finalized release 22.4
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
Labels: Releases

#20728 Plans on JP: Update UI tests for Plan Selection
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/dashboard/dashboard.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/domains/rest_v11_suggestions.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/feature-flags.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/me/rest_v11_me_shopping_cart_post.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/products/rest_v11_products.json
  WordPress/Classes/Services/DomainsService.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/BaseDashboardDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Domains/DashboardDomainsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansDashboardCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/ViewModel/BlogDashboardViewModel.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/DomainSuggestionsTableViewController.swift
  WordPress/UITests/Tests/DashboardTests.swift
  WordPress/UITestsFoundation/Screens/DomainsSuggestionsScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/PlanSelectionScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, WP.com Plans

#20752 [UI Test] Removed `tabBar` init from redesigned Domains Suggestions Screen
  WordPress/UITestsFoundation/Screens/DomainsSuggestionsScreen.swift
Labels: Testing

#20750 Merge 22.5 code freeze
  Gemfile.lock
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#20730 Add domain registration card on dashboard
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardDomainRegistrationCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/BlogPersonalization/BlogDashboardPersonalizationViewModel.swift
  WordPress/Classes/ViewRelated/Domains/Domain credit/DomainCreditEligibilityChecker.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, My Site Dashboard

#20736 Check required WordPress version to set galleryWithImageBlocks flag
  RELEASE-NOTES.txt
  WordPress/Classes/Models/BlockEditorSettings+GutenbergEditorSettings.swift
Labels: [Type] Bug, Posting/Editing, Gutenberg

#20767 Include a missing block editor entry to release notes
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/release_notes.txt
Labels: Gutenberg

#20768 Activity Log: Fetch backup status only if site has backup capabilities
  WordPress/Classes/Models/JetpackSiteRef.swift
  WordPress/Classes/Stores/ActivityStore.swift
Labels: [Type] Bug, Activity Log, Jetpack App

#20772 Dashboard: fix blaze card layout when large dynamic type is used
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCell.swift
Labels: [Type] Bug, My Site Dashboard

#20453 Hiding dashboard cards: remove prompts from site settings
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Blogging.swift
Labels: [Type] Task, My Site Dashboard

#20393 Hiding dashboard cards: make quick start cards personalizable
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Activity Log/DashboardActivityLogCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/BlogDashboardPersonalizeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Pages/DashboardPagesListCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/BlogDashboardCardFrameView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsListCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Start/DashboardQuickStartCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Stats/DashboardStatsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Helpers/BlogDashboardHelpers.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/Classes/ViewRelated/Blog/BlogPersonalization/BlogDashboardPersonalizationView.swift
  WordPress/Classes/ViewRelated/Blog/BlogPersonalization/BlogDashboardPersonalizationViewModel.swift
  WordPress/WordPressTest/Dashboard/BlogDashboardPersonalizationServiceTests.swift
  WordPress/WordPressTest/Dashboard/BlogDashboardPersonalizationViewModelTests.swift
Labels: [Type] Enhancement, Part of a WIP Feature, My Site Dashboard

#20454 Hiding dashboard cards: fix scroll position
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/ViewModel/BlogDashboardViewModel.swift
Labels: [Type] Task, My Site Dashboard
