Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2023-02, with the labels that each got.

#20040 Jetpack Focus: Prevent FAB from obscuring the last row
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: [Type] Bug, Jetpack Focus

#20051 Core Spotlight: mark blog as recently used when opening from a spotlight suggestion
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
Labels: [Type] Bug, Spotlight

#20045 Jetpack Focus: Add Jetpack branding for Post Stats screen
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController+JetpackBannerViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsInsightsDetailsTableViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Jetpack Focus

#20031 JP Plugin: Detect Jetpack connection from individual plugins
  Podfile
  Podfile.lock
  WordPress/Classes/Models/Blog+Jetpack.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogJetpackTest.m
  WordPress/WordPressTest/BlogJetpackTests.swift
Labels: [Type] Enhancement, Jetpack App

#20034 Update React Native Reanimated to `2.9.1-wp-3`
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#20049 Quick Start: Prevent tour notice from obscuring FAB
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsSectionHeaderView.xib
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+QuickStart.swift
Labels: [Type] Bug, Quick Start

#20033 Blogging Prompts: Add option to disable blogging prompts feature
  WordPress/Classes/Stores/UserPersistentRepositoryUtility.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Blogging.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Swift.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Blogging Prompts

#20056 Blogging Prompts: Add new prompts social feature flag and move prompt social changes to it
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
Labels: [Type] Task, Blogging Prompts

#20058 Integrate gutenberg-mobile release 1.88.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#20055 Blogging Prompts: enable prompts enhancement feature flag
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Blogging.swift
  WordPress/Classes/ViewRelated/Feature Introduction/Blogging Prompts/BloggingPromptsFeatureDescriptionView.swift
  WordPress/Classes/ViewRelated/Feature Introduction/Blogging Prompts/BloggingPromptsFeatureIntroduction.swift
Labels: [Type] Task, Blogging Prompts

#20059 Jetpack Focus: Fix misalignment of overlay buttons when system font increases
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.swift
Labels: [Type] Bug, Layout, Jetpack Focus

#20037 Log unexpected HTTP requests instead of make the test case fail
  WordPress/WordPressTest/PeopleServiceTests.swift
Labels: Testing

#19920 Replace `BlogJetpackSettingsService.context` with `CoreDataStack`
  WordPress/Classes/Services/BlogJetpackSettingsService.swift
  WordPress/Classes/ViewRelated/Blog/JetpackModuleHelper.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackConnectionViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackSettingsViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackSpeedUpSiteSettingsViewController.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/StatsViewController+JetpackSettings.swift
Labels: Core Data

#20022 [Support Forum] Create a feature flag and configuration
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Support/SupportConfigurationTests.swift
Labels: [Type] Task, Support Forum

#20061 Enable the feature flag for the new WordPress landing screen
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Enhancement, Login

#20044 update `GutenbergSettings` to interact with CoreData safely
  WordPress/Classes/Utility/Editor/GutenbergSettings.swift
Labels: Core Data

#20069 [Support Forum] Add tracks
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: Support Forum

#20070 [Support Forum] Updated the App Store description to point to new .org Mobile forum
  WordPress/Resources/AppStoreStrings.po
  fastlane/metadata/default/description.txt
Labels: Support Forum

#20072 Rename `GHHELPER_REPO` to `GITHUB_REPO`
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/release.rb
Labels: Tooling

#20065 Merge 21.7 code freeze into `trunk`
  Podfile.lock
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#20099 Add higher CI priority to release builds
  .buildkite/release-builds.yml
Labels: Tooling

#20098 Delete some unused functions in `CommentService`
  WordPress/Classes/Services/CommentService.h
  WordPress/Classes/Services/CommentService.m
Labels: Core Data

#19893 Refactor `AccountService` to use `CoreDataStack`
  WordPress/Classes/Models/WPAccount+Lookup.swift
  WordPress/Classes/Services/AccountService+MergeDuplicates.swift
  WordPress/Classes/Services/AccountService.h
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Services/CoreDataService.h
  WordPress/Classes/Services/CoreDataService.m
  WordPress/Classes/Services/SiteAssemblyService.swift
  WordPress/Classes/Services/WordPressComSyncService.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/AccountHelper.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/Utility/WPAuthTokenIssueSolver.m
  WordPress/Classes/ViewRelated/Aztec/Helpers/AztecVerificationPromptHelper.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
  WordPress/Classes/ViewRelated/Blog/Site Management/DeleteSiteViewController.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Me/Account Settings/AccountSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Me/My Profile/Change Username/View Model/ChangeUsernameViewModel.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/System/FancyAlerts+VerificationPrompt.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/AccountServiceTests.swift
  WordPress/WordPressTest/BlogJetpackTests.swift
  WordPress/WordPressTest/BlogServiceDeduplicationTests.swift
  WordPress/WordPressTest/BlogServiceTest.m
  WordPress/WordPressTest/BlogTimeZoneTests.m
  WordPress/WordPressTest/BloggingPromptsServiceTests.swift
  WordPress/WordPressTest/CommentService+RepliesTests.swift
  WordPress/WordPressTest/DomainsServiceTests.swift
  WordPress/WordPressTest/EditorSettingsServiceTests.swift
  WordPress/WordPressTest/GravatarServiceTests.swift
  WordPress/WordPressTest/GutenbergSettingsTests.swift
  WordPress/WordPressTest/MediaRequestAuthenticatorTests.swift
  WordPress/WordPressTest/PromptRemindersSchedulerTests.swift
  WordPress/WordPressTest/ReminderScheduleCoordinatorTests.swift
  WordPress/WordPressTest/WPAppAnalyticsTests.m
Labels: Core Data

#20102 Update release notes with changes in #19893
  RELEASE-NOTES.txt
Labels: Core Data

#19993 New Forum Support Card Help Screen
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: [Type] Enhancement, Support Forum

#20087 Blogging Prompts: Hide blogging prompt options for self-hosted sites
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowSettingsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Blogging.swift
Labels: [Type] Bug, Blogging Prompts

#20088 Blogging Prompts: Update prompts dashboard card and FAB display logic to match
  WordPress/Classes/Models/BloggingPromptSettings+CoreDataClass.swift
  WordPress/Classes/Stores/UserPersistentRepositoryUtility.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController+Blogging.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/CreateButtonCoordinator.swift
Labels: [Type] Bug, Blogging Prompts

#20105 Merge editorialized release notes for version 21.7
  WordPress/Classes/Extensions/Media+Sync.swift
  WordPress/Classes/Services/BlockEditorSettingsService.swift
  WordPress/Classes/Services/BloggingPromptsService.swift
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/PageLayoutService.swift
  WordPress/Classes/Services/PeopleService.swift
  WordPress/Classes/Utility/ContextManager.swift
  WordPress/Classes/Utility/CoreDataHelper.swift
  WordPress/Classes/Utility/CoreDataStack.h
  WordPress/Classes/Utility/Media/MediaFileManager.swift
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
  WordPress/WordPressTest/ContextManagerTests.swift
  WordPress/WordPressTest/DataMigratorTests.swift
  WordPress/WordPressTest/SharedDataIssueSolverTests.swift
Labels: Releases

#20114 Query the blog instance before using it to update a Role
  WordPress/Classes/Services/RoleService.swift
Labels: Core Data

#20125 Add a CoreDataStackSwift type in EditorSettingsService
  WordPress/Classes/Services/EditorSettingsService.swift
Labels: [Type] Bug, Core Data

#20063 [JP Plugin] Add a plugin installation endpoint through Jetpack Proxy
  Podfile
  Podfile.lock
  WordPress/Classes/Services/PluginJetpackProxyService.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/PluginJetpackProxyServiceTests.swift
Labels: [Type] Enhancement, Jetpack App

#20103 Re-enable SwiftLint integration, now vendored via CocoaPods
  .gitignore
  .swiftlint.yml
  Podfile
  Podfile.lock
  Rakefile
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#20067 [JP Plugin] Install Overlay UI
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayGeneralViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlaySiteCreationViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.xib
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackPluginOverlayViewModel.swift
  WordPress/JetpackInstallPluginLogoAnimation_ltr.json
  WordPress/JetpackInstallPluginLogoAnimation_rtl.json
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/JetpackPluginOverlayViewModelTests.swift
Labels: Jetpack, Jetpack Plugins

#20104 Autocorrect SwiftLint violations
  WordPress/Classes/Extensions/String+CondenseWhitespace.swift
  WordPress/Classes/Extensions/UINavigationController+SplitViewFullscreen.swift
  WordPress/Classes/Models/BlockEditorSettings+CoreDataProperties.swift
  WordPress/Classes/Models/Blog+BlockEditorSettings.swift
  WordPress/Classes/Services/AuthenticationService.swift
  WordPress/Classes/Services/CommentService+Likes.swift
  WordPress/Classes/Services/DomainsService.swift
  WordPress/Classes/Services/PostAutoUploadInteractor.swift
  WordPress/Classes/Services/PostService+Likes.swift
  WordPress/Classes/Services/ReaderPostService+RelatedPosts.swift
  WordPress/Classes/Stores/NoticeStore.swift
  WordPress/Classes/System/WindowManager.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Media/ImageLoader.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Start/DashboardQuickStartCardCell.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Sharing.swift
  WordPress/Classes/ViewRelated/Cells/PickerTableViewCell.swift
  WordPress/Classes/ViewRelated/Cells/SwitchTableViewCell.swift
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackPluginOverlayViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanViewController.swift
  WordPress/Classes/ViewRelated/Media/AnimatedImageCache.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/StockPhotosDataLoader.swift
  WordPress/Classes/ViewRelated/NUX/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderInterestsCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsStyleGuide.swift
  WordPress/Classes/ViewRelated/System/Notices/NoticeView.swift
  WordPress/Classes/ViewRelated/Tools/SettingsPickerViewController.swift
  WordPress/Classes/ViewRelated/Views/AlertView/AlertInternalView.swift
  WordPress/UITestsFoundation/Screens/Me/SupportScreen.swift
  WordPress/WordPressNotificationServiceExtension/Sources/FormattableContent/RichNotificationContentFormatter.swift
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/NSExtensionContext+Extensions.swift
  WordPress/WordPressTest/Bundle+LoadFromNib.swift
  WordPress/WordPressTest/NullMockUserDefaults.swift
Labels: Tooling

#20066 [JP Plugin] Make the current Jetpack Install view configurable
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallStateView.swift
Labels: [Type] Enhancement, Jetpack App, Jetpack Install

#20108 [JP Plugin] Move Remote Install tracking logic to the view model
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/JetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/SelfHostedJetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Jetpack App, Jetpack Install

#20130 [JP Plugin] Add view model for installing Jetpack via proxy
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/JetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/SelfHostedJetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/WPComJetpackRemoteInstallViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WPComJetpackRemoteInstallViewModelTests.swift
Labels: [Type] Enhancement, Jetpack App, Jetpack Install

#20120 Blaze: Implement blaze web view wrapper
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/Classes/ViewRelated/Blaze/BlazeWebViewController.swift
  WordPress/Classes/ViewRelated/Blaze/BlazeWebViewCoordinator.swift
  WordPress/Classes/ViewRelated/Blaze/BlazeWebViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Blaze

#20131 [JP Plugin] Add Tracks for the installation flow
  WordPress/Classes/Utility/Analytics/EventTracker.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/JetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/SelfHostedJetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/WPComJetpackRemoteInstallViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WPComJetpackRemoteInstallViewModelTests.swift
Labels: [Type] Enhancement, Jetpack App, Tracks, Jetpack Install

#20115 [Support Forum] Update the WP and JP app's support screen
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
Labels: Support Forum

#20121 Add simple test to load People screen
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/PeopleScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressUITests/Tests/MainNavigationTests.swift
Labels: Tooling

#20139 Fix #19190: Do not delete the previous topic when the same topic is searched
  WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
Labels: Core Data

#20124 Remove some unused functions in `ReaderTopicService`
  WordPress/Classes/Services/ReaderTopicService.h
  WordPress/Classes/Services/ReaderTopicService.m
Labels: [Type] Core

#20140 Remove some unused functions in `ReaderPostService`
  WordPress/Classes/Services/ReaderPostService.h
  WordPress/Classes/Services/ReaderPostService.m
Labels: Core

#20129 Move topic lookup functions out of `ReaderTopicService`
  RELEASE-NOTES.txt
  WordPress/Classes/Models/ReaderAbstractTopic+Lookup.swift
  WordPress/Classes/Models/ReaderListTopic+Creation.swift
  WordPress/Classes/Models/ReaderSiteTopic+Lookup.swift
  WordPress/Classes/Models/ReaderTagTopic+Lookup.swift
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/Services/ReaderSiteService.m
  WordPress/Classes/Services/ReaderTopicService+Subscriptions.swift
  WordPress/Classes/Services/ReaderTopicService.h
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSiteSubscriptionViewController.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/ReaderMenuAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Core Data

#20100 Enable VideoPress block on iOS
  Podfile
  Podfile.lock
  WordPress/Classes/Models/Blog.h
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Posting/Editing, Media, Gutenberg integration

#20143 [JP Plugin] Add cancellation and misc. fixes
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallStateView.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/JetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/SelfHostedJetpackRemoteInstallViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/ViewModel/WPComJetpackRemoteInstallViewModel.swift
Labels: [Type] Enhancement, Jetpack App, Jetpack Install

#20136 JP Plugin: Add Jetpack install card UI
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackInstallCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackPlugin.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallCardView.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallTableViewCell.swift
  WordPress/Resources/AppImages.xcassets/Jetpack Install/Contents.json
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Jetpack App

#20137 Refactor `ReaderTopicService.currentTopic`
  WordPress/Classes/Services/ReaderTopicService.h
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewModel.swift
  WordPress/WordPressTest/ReaderTopicServiceTest.swift
Labels: Core Data

#20107 Use `CoreDataStack` in `CommentService`
  RELEASE-NOTES.txt
  WordPress/Classes/Services/CommentService+Likes.swift
  WordPress/Classes/Services/CommentService+Replies.swift
  WordPress/Classes/Services/CommentService.h
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/Services/NotificationActionsService.swift
  WordPress/Classes/Utility/InteractiveNotificationsManager.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationCommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/WordPressTest/CommentService+RepliesTests.swift
  WordPress/WordPressTest/CommentServiceTests.swift
Labels: Core Data

#20146 Use async version of performAndSave in PlanStorage
  WordPress/Classes/Services/PlanService.swift
Labels: Core Data

#20064 UGC: Add "Report this user" button to Reader Post menu
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderReportPostAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
Labels: [Type] Enhancement, Reader, Jetpack Mobile

#20134 UGC: Track post author reported event
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderReportPostAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
Labels: [Type] Task, Tracks

#20151 Integrate gutenberg-mobile release 1.89.0
  Podfile
  Podfile.lock
Labels: Gutenberg integration

#20145 Document an issue with sync version of `performAndSave` API
  WordPress/WordPressTest/ContextManagerTests.swift
Labels: Core Data

#20150 Use `CoreDataStack` in `ReaderTopicService`
  WordPress/Classes/Services/ReaderCardService.swift
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/Services/ReaderSiteService.m
  WordPress/Classes/Services/ReaderTopicService+FollowedInterests.swift
  WordPress/Classes/Services/ReaderTopicService+Interests.swift
  WordPress/Classes/Services/ReaderTopicService+SiteInfo.swift
  WordPress/Classes/Services/ReaderTopicService+Subscriptions.swift
  WordPress/Classes/Services/ReaderTopicService.h
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSiteSubscriptionViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderInterestsCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSubscribingNotificationAction.swift
  WordPress/Classes/ViewRelated/Reader/Select Interests/ReaderInterestsDataSource.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
  WordPress/WordPressTest/ReaderTabItemsStoreTests.swift
  WordPress/WordPressTest/ReaderTopicServiceTest.swift
Labels: Core Data

#20160 Add a release note
  RELEASE-NOTES.txt
Labels: Core Data

#20156 Take user support to Help screen instead of Zendesk
  WordPress/Classes/ViewRelated/Blog/Site Management/DeleteSiteViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: [Type] Enhancement, Support

#20132 [Jetpack Plugin] Coordinator refactor for VM's
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackDefaultOverlayCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackFeaturesRemovalCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackOverlayCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackPluginOverlayCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayGeneralViewModel+Analytics.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayGeneralViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlaySiteCreationViewModel+Analytics.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlaySiteCreationViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.xib
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackPluginOverlayViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Jetpack App

#20163 Show Zendesk to paying users
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Support/SupportConfiguration.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
  WordPress/WordPressTest/Support/SupportConfigurationTests.swift
Labels: [Type] Enhancement, Support Forum

#20165 [JP Plugin] Fix UI issues for the T&C button
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.xib
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackPluginOverlayViewModel.swift
Labels: [Type] Enhancement, Jetpack App

#20166 [JP Plugin] Implement overlay logic
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackPluginOverlayCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayGeneralViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlaySiteCreationViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewController.xib
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackPluginOverlayViewModel.swift
Labels: [Type] Enhancement, Jetpack App

#20162 Merge finalized release 21.7
  .buildkite/commands/release-build-jetpack.sh
  .buildkite/commands/release-build-wordpress-internal.sh
  .buildkite/commands/release-build-wordpress.sh
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/es.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#20161 Fix potential concurrency issues in some Core Data queries
  WordPress/Classes/Services/ReaderTopicService+FollowedInterests.swift
  WordPress/Classes/Services/ReaderTopicService+Interests.swift
  WordPress/Classes/Services/ReaderTopicService+SiteInfo.swift
  WordPress/Classes/Services/ReaderTopicService+Subscriptions.swift
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/Classes/Services/SiteVerticalsService.swift
  WordPress/Classes/Utility/Editor/GutenbergSettings.swift
Labels: Core Data

#20168 Update header view when the topic is changed
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: Core Data

#20170 Replace some `ContextManager.shared` calls with `coreDataStack` instance variable
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/BlogService+Domains.swift
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Services/CommentService+Likes.swift
  WordPress/Classes/Services/CommentService+Replies.swift
  WordPress/Classes/Services/PlanService.swift
  WordPress/Classes/Services/PostCategoryService.m
  WordPress/Classes/Services/ReaderTopicService.m
Labels: Core Data

#20169 Use `CoreDataStack` in `ReaderSiteService`
  WordPress/Classes/Services/NotificationActionsService.swift
  WordPress/Classes/Services/ReaderPostService.h
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/Classes/Services/ReaderSiteService.h
  WordPress/Classes/Services/ReaderSiteService.m
  WordPress/Classes/Services/ReaderSiteService.swift
  WordPress/Classes/Services/ReaderTopicService.m
  WordPress/Classes/ViewRelated/Reader/ReaderBlockSiteAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
Labels: Core Data

#20164 Remove Buildkite commands that are included in the VM
  .buildkite/commands/run-ui-tests.sh
Labels: Tooling

#20171 Use optional chaining to replace if-let
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: Core

#20173 [Domain Purchasing Site Creation] Add Feature Flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: [Type] Task, Site Creation, Domains

#20179 Remove mobile forum from the release notes of release/21.8
  RELEASE-NOTES.txt
Labels: [Type] Enhancement, Documentation

#20172 Merge 21.8 code freeze
  Gemfile
  Gemfile.lock
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/lanes/release.rb
Labels: Releases

#20109 [Support Forum] Enable feature flag
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewController.swift
  WordPress/UITestsFoundation/Globals.swift
  WordPress/UITestsFoundation/Screens/Me/SupportScreen.swift
  WordPress/WordPressUITests/Tests/SupportScreenTests.swift
Labels: Support Forum

#20174 [JP Plugin] Wire up components and presentation logic
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackInstallCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackPluginOverlayCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackInstallPluginHelper.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackPlugin.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/JetpackRemoteInstallViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/View/JetpackRemoteInstallTableViewCell.swift
Labels: [Type] Enhancement, Jetpack App

#20177 Use `CoreDataStack` in `ThemeService`
  WordPress/Classes/Services/ThemeService.h
  WordPress/Classes/Services/ThemeService.m
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
  WordPress/WordPressTest/ThemeServiceTests.m
Labels: Core Data

#20178 Reduce references to `managedObjectContext` in `ReaderPostService`
  WordPress/Classes/Services/ReaderPostService.m
  WordPress/WordPressTest/ReaderPostServiceTest.m
Labels: Core Data

#20200 Merge editorialized release notes for version 21.8
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#20202 Stats: Fix a crash when a difference substring on Insights cell is at the end of the label
  WordPress/Classes/ViewRelated/Stats/Insights/StatsTotalInsightsCell.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/StatsTotalInsightsCellTests.swift
Labels: [Type] Crash, Stats

#20201 Fix failure block getting called twice in `PostCategoryService`
  WordPress/Classes/Services/PostCategoryService.m
  WordPress/WordPressTest/PostCategoryServiceTests.m
Labels: Core Data

#20206 Merge 21.7.1 hotfix into 21.8
  WordPress/Classes/Services/PostCategoryService.m
  WordPress/WordPressTest/PostCategoryServiceTests.m
Labels: Releases

#20159 Jetpack Focus: Remove footnote in new users overlay
  WordPress/Classes/ViewRelated/Jetpack/Branding/Fullscreen Overlay/JetpackFullscreenOverlayGeneralViewModel.swift
Labels: [Type] Bug, Jetpack Focus

#20135 Blaze: Add entry point for post list
  WordPress/Classes/Models/AbstractPost+Blaze.swift
  WordPress/Classes/ViewRelated/Post/InteractivePostViewDelegate.swift
  WordPress/Classes/ViewRelated/Post/PostActionSheet.swift
  WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/PostActionSheetTests.swift
Labels: [Type] Task, Blaze

#20144 [Gutenberg] Add metadata on media upload success event
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
Labels: Gutenberg integration

#20175 Blaze: Add entry point for dashboard
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/BlazeCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/BlogDashboardCardFrameView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Jetpack/AppImages.xcassets/blaze-flame.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/blaze-flame.imageset/blaze-flame.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Blaze

#20176 Blaze: Hide dashboard card
  WordPress/Classes/Stores/UserPersistentRepositoryUtility.swift
  WordPress/Classes/ViewRelated/Blaze/BlazeHelper.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Blaze

#20194 Blaze: Present blaze flow from entry points
  WordPress/Classes/ViewRelated/Blaze/BlazeWebViewController.swift
  WordPress/Classes/ViewRelated/Blaze/BlazeWebViewCoordinator.swift
  WordPress/Classes/ViewRelated/Blaze/BlazeWebViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/BlazeCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Blaze

#20203 Blaze: Entry point analytics
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blaze/BlazeEventsTracker.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/BlazeCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Post/PostActionSheet.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Blaze

#20193 UGC: Add ability to Block Authors and hide their posts
  MIGRATIONS.md
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Blocking/BlockedAuthor.swift
  WordPress/Classes/Services/Reader Post/ReaderPostService.h
  WordPress/Classes/Services/Reader Post/ReaderPostService.m
  WordPress/Classes/Services/Reader Post/ReaderPostService.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Reader/ReaderBlockUserAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostBlockingController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderShowMenuAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/WordPress.xcdatamodeld/WordPress 148.xcdatamodel/contents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Reader

#20212 Blaze: Add entry point for page list
  WordPress/Classes/ViewRelated/Blaze/BlazeWebViewCoordinator.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
Labels: [Type] Task, Blaze

#20215 Run Flux tests before Jetpack/WordPress unit tests
  WordPress/WordPressTest/WordPressUnitTests.xctestplan
Labels: Tooling

#20217 Fix database migration issue with different database models (#20214 cherry pick on 21.7.2)
  WordPress/Classes/Utility/ContextManager.swift
  WordPress/Classes/Utility/CoreDataHelper.swift
Labels: Releases

#20198 Use `CoreDataStack` in a few service types
  WordPress/Classes/Models/Notifications/Actions/NotificationAction.swift
  WordPress/Classes/Services/JetpackRestoreService.swift
  WordPress/Classes/Services/JetpackScanService.swift
  WordPress/Classes/Services/NotificationActionsService.swift
  WordPress/Classes/Services/PushAuthenticationService.swift
  WordPress/Classes/Services/QRLoginService.swift
  WordPress/Classes/Services/ReaderSiteSearchService.swift
  WordPress/Classes/Services/SiteAddressService.swift
  WordPress/Classes/Utility/PushAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/Restore Status/Coordinators/JetpackRestoreStatusCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/Restore Warning/Coordinators/JetpackRestoreWarningCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanHistoryCoordinator.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/QR Login/Coordinators/QRLoginVerifyCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteSearchViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Wizard/SiteCreationWizardLauncher.swift
  WordPress/WordPressTest/ApproveCommentActionTests.swift
  WordPress/WordPressTest/EditCommentActionTests.swift
  WordPress/WordPressTest/LikeCommentActionTests.swift
  WordPress/WordPressTest/MarkAsSpamActionTests.swift
  WordPress/WordPressTest/PushAuthenticationManagerTests.swift
  WordPress/WordPressTest/PushAuthenticationServiceTests.swift
  WordPress/WordPressTest/QRLogin/QRLoginVerifyCoordinatorTests.swift
  WordPress/WordPressTest/ReplyToCommentActionTests.swift
  WordPress/WordPressTest/SiteAddressServiceTests.swift
  WordPress/WordPressTest/TrashCommentActionTests.swift
Labels: Core Data

#20180 [Domain Purchasing Site Creation] Update tracks
  WordPress/Classes/Utility/Analytics/WPAnalytics+Domains.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/WebAddressWizardContent.swift
Labels: Site Creation, Jetpack App, Domains

#20213 Fix: Do not bounce to Safari when both apps are installed
  WordPress/Classes/Extensions/UIApplication+AppAvailability.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Universal Links/Migration/WPAdminConvertibleRouter.swift
  WordPress/Classes/Utility/Universal Links/Route.swift
  WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Common/MigrationAppDetection.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Universal Links

#20219 Blaze: update child vc after fetching blaze status
  WordPress/Classes/Services/BlazeService.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
Labels: [Type] Task, Blaze
