Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2023-07, with the labels that each got.

#20984 Drop iOS 14 Support: Remove keyboard crash workaround for iOS 14
  WordPress/Classes/Extensions/UITextField+WorkaroundContinueIssue.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Drop iOS 14

#20981 Comments: Remove VisualEffectView usage
  WordPress/Classes/ViewRelated/Comments/CommentTableHeaderView.swift
Labels: [Type] Enhancement, Comments, Drop iOS 14

#20950 Blaze Manage Campaigns: Present campaign details view from campaigns list
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeCampaignDetailsWebViewModel.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeCreateCampaignWebViewModel.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeFlowCoordinator.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeWebViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Blaze/BlazeCampaignDetailsWebViewModelTests.swift
  WordPress/WordPressTest/Blaze/BlazeCreateCampaignWebViewModelTests.swift
Labels: [Type] Task, Blaze

#20978 Fix a memory leak in Reader
  WordPress/Classes/ViewRelated/Reader/Tags View/ReaderTopicCollectionViewCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Tags View/TopicsCollectionView.swift
Labels: Reader

#20996 Fix discarded notification observer in ContentMigrationCoordinator
  WordPress/Classes/Utility/Migration/ContentMigrationCoordinator.swift
  WordPress/WordPressTest/ContentMigrationCoordinatorTests.swift
Labels: [Type] Enhancement

#20998 Capture weak references in some notification observers
  WordPress/Classes/ViewRelated/Gutenberg/Collapsable Header/CollapsableHeaderViewController.swift
Labels: [Type] Bug, Gutenberg

#20995 Fix discarded notification observers in StatsWidgetsStore
  WordPress/Classes/Stores/StatsWidgetsStore.swift
Labels: [Type] Enhancement

#20813 Fix memory leak in domain flow
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+DomainCredit.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/CheckoutViewController.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/PlanSelectionViewController.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/DomainSuggestionsTableViewController.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Domains/Views/DomainsDashboardFactory.swift
  WordPress/Classes/ViewRelated/Plugins/PluginViewModel.swift
Labels: [Type] Bug, Performance, Domains, WP.com Plans

#21007 Use iOS 15 API to simplify `performQuery` implementation
  WordPress/Classes/Utility/CoreDataHelper.swift
Labels: Core Data

#20997 Fix discarded quick start notification observers
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Actions/DashboardQuickActionsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Start/NewQuickStartChecklistView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Start/QuickStartChecklistView.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+QuickStart.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerViewController+QuickStart.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
Labels: [Type] Enhancement, Quick Start

#21004 Dashboard Cards: Add "view" item to context menu
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsListCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Stats/DashboardStatsCardCell.swift
Labels: [Type] Task, My Site Dashboard

#21014 Blaze Manage Campaigns: show campaign details from dashboard card
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignsCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCellViewModel.swift
  WordPress/WordPressTest/Dashboard/DashboardBlazeCardCellViewModelTest.swift
Labels: [Type] Task, Blaze

#21019 Show Plans card for free plans
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Free to Paid Plans/FreeToPaidPlansDashboardCardHelper.swift
  WordPress/WordPressTest/Dashboard/FreeToPaidPlansDashboardCardHelperTests.swift
Labels: [Type] Task, WP.com Plans

#21025 Fix WPTableViewHandler warnings
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
  WordPress/Classes/ViewRelated/Post/Revisions/RevisionsTableViewController.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/WordPressTest/PostListTableViewHandlerTests.swift
Labels: [Type] Task

#21008 Add warnings about incorrect `performQuery` usages
  WordPress/Classes/Utility/CoreDataHelper.swift
Labels: Core Data

#21000 Do not discard notification observers in NoticePresenter
  WordPress/Classes/ViewRelated/System/Notices/NoticePresenter.swift
Labels: [Type] Enhancement

#20862 Use test doubles `AccountSettingsServiceTests`
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/AccountServiceTests.swift
  WordPress/WordPressTest/AccountSettingsRemoteInterfaceStub.swift
  WordPress/WordPressTest/AccountSettingsServiceTests.swift
  WordPress/WordPressTest/BlogTests.swift
  WordPress/WordPressTest/ContextManagerTests.swift
  WordPress/WordPressTest/PeopleServiceTests.swift
  WordPress/WordPressTest/TestError.swift
  WordPress/WordPressTest/WPAccount+Fixture.swift
Labels: Testing

#21015 Fix memory leaks in ReaderStreamViewController
  WordPress/Classes/ViewRelated/Reader/ReaderListStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderRecommendedSiteCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchSuggestionsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTagStreamHeader.swift
Labels: [Type] Bug

#21028 Move liked users query to a static function
  WordPress/Classes/Services/CommentService+Likes.swift
  WordPress/Classes/Services/LikeUserHelpers.swift
  WordPress/Classes/Services/PostService+Likes.swift
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/WordPressTest/LikeUserHelperTests.swift
Labels: Core Data

#21029 Remove a problematic usage of performQuery in Gutenberg settings
  WordPress/Classes/Utility/Editor/GutenbergSettings.swift
  WordPress/WordPressTest/GutenbergSettingsTests.swift
Labels: Core Data

#21030 [UI Tests] - Use default timeout value on screen init
  WordPress/UITestsFoundation/Screens/ActionSheetComponent.swift
  WordPress/UITestsFoundation/Screens/ActivityLogScreen.swift
  WordPress/UITestsFoundation/Screens/CommentsScreen.swift
  WordPress/UITestsFoundation/Screens/DomainsScreen.swift
  WordPress/UITestsFoundation/Screens/DomainsSuggestionsScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/AztecEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/ChooseLayoutScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorNoticeComponent.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPostSettings.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPublishEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorSettingsComponents/CategoriesComponent.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorSettingsComponents/TagsComponent.swift
  WordPress/UITestsFoundation/Screens/Editor/FeaturedImageScreen.swift
  WordPress/UITestsFoundation/Screens/Jetpack/JetpackBackupOptionsScreen.swift
  WordPress/UITestsFoundation/Screens/Jetpack/JetpackBackupScreen.swift
  WordPress/UITestsFoundation/Screens/Jetpack/JetpackScanScreen.swift
  WordPress/UITestsFoundation/Screens/Login/FeatureIntroductionScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LinkOrPasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginCheckMagicLinkScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEmailScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginPasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginSiteAddressScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginUsernamePasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/OnboardingQuestionsPromptScreen.swift
  WordPress/UITestsFoundation/Screens/Login/QuickStartPromptScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/GetStartedScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PrologueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/WelcomeScreen.swift
  WordPress/UITestsFoundation/Screens/Login/WelcomeScreenLoginComponent.swift
  WordPress/UITestsFoundation/Screens/Me/ContactUsScreen.swift
  WordPress/UITestsFoundation/Screens/Me/SupportScreen.swift
  WordPress/UITestsFoundation/Screens/MeTabScreen.swift
  WordPress/UITestsFoundation/Screens/Media/MediaPickerAlbumListScreen.swift
  WordPress/UITestsFoundation/Screens/Media/MediaPickerAlbumScreen.swift
  WordPress/UITestsFoundation/Screens/MediaScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/MySitesScreen.swift
  WordPress/UITestsFoundation/Screens/NotificationsScreen.swift
  WordPress/UITestsFoundation/Screens/PagesScreen.swift
  WordPress/UITestsFoundation/Screens/PeopleScreen.swift
  WordPress/UITestsFoundation/Screens/PlanSelectionScreen.swift
  WordPress/UITestsFoundation/Screens/PostsScreen.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/SignupCheckMagicLinkScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/SignupEmailScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/SignupEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/WelcomeScreenSignupComponent.swift
  WordPress/UITestsFoundation/Screens/SiteIntentScreen.swift
  WordPress/UITestsFoundation/Screens/SiteSettingsScreen.swift
  WordPress/UITestsFoundation/Screens/StatsScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
  WordPress/UITestsFoundation/XCUIApplication+SavePassword.swift
Labels: Testing, [Type] Task

#21031 Merge finalized release 22.7
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/ro.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/default/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/default/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#21023 Drop iOS 14 Support: Address UIButton API deprecations (#3)
  WordPress/Classes/ViewRelated/System/Action Sheet/ActionSheetViewController.swift
Labels: [Type] Task, Drop iOS 14

#21024 Jetpack Social: Update social icons on the post settings screen
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Sharing.swift
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoConnectionView.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/Jetpack/AppImages.xcassets/Social/icon-instagram-business.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Social/icon-instagram-business.imageset/icon-instagram.svg
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21026 Jetpack Social: Open social purchase link on subscribe now tap
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
Labels: [Type] Task, Part of a WIP Feature, Jetpack Social

#20999 Retain a notification observer in StatsForegroundObservable
  WordPress/Classes/ViewRelated/Stats/StatsForegroundObservable.swift
Labels: [Type] Enhancement

#21005 Use Combine API to observe notifications in WPLoggingStack
  WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift
Labels: [Type] Bug

#21013 Fix memory leaks on viewing a post from a notification
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsFollowPresenter.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailLikesView.swift
Labels: [Type] Bug

#21003 Fix text change notification observer in ChangeUsernameViewController
  WordPress/Classes/ViewRelated/Me/My Profile/Change Username/ChangeUsernameViewController.swift
Labels: [Type] Bug

#21033 Drop iOS 14 Support: Address UIButton API deprecations (#4)
  WordPress/Classes/ViewRelated/System/Floating Create Button/SheetActions.swift
  WordPress/Classes/ViewRelated/What's New/Views/WhatIsNewView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, Drop iOS 14

#21032 Blaze Manage Campaigns: Show campaigns list from site menu
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: [Type] Task, Blaze

#20945 Add improved feature flags menu
  WordPress/Classes/Utility/BuildInformation/FeatureFlagOverrideStore.swift
  WordPress/Classes/ViewRelated/Me/App Settings/DebugFeatureFlagsView.swift
  WordPress/Classes/ViewRelated/Me/App Settings/DebugMenuViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#21036 Jetpack Social: Refactor JetpackSocialService enum to PublicizeService
  WordPress/Classes/Models/PublicizeService.swift
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Sharing.swift
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoConnectionView.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21037 Jetpack Social: Add initial view for the pre-publishing social cell
  WordPress/Classes/Models/PublicizeService+Lookup.swift
  WordPress/Classes/Services/Stories/StoryEditor.swift
  WordPress/Classes/ViewRelated/Post/PostEditor.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingAutoSharingView.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21044 Blaze Manage Campaigns: Fix an issue with dashboard card not reloading when switching sites
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCellViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/ViewModel/BlogDashboardViewModel.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
Labels: [Type] Bug, Blaze

#21046 Blaze Manage Campaigns: "Create" bar button item
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
Labels: [Type] Task, Blaze

#21045 Merge 22.8 code freeze to trunk
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#21048 Fix hang when updating remote users
  WordPress/Classes/Services/BlogService.m
Labels: App Hanging

#20930 Editor - Move Undo/Redo to the header
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/Colors and Styles/UIColor+MurielColors.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/SiteIconView.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
  WordPress/Resources/AppImages.xcassets/editor-chevron-down.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/editor-chevron-down.imageset/editor-chevron-down.png
  WordPress/Resources/AppImages.xcassets/editor-chevron-down.imageset/editor-chevron-down@2x.png
  WordPress/Resources/AppImages.xcassets/editor-chevron-down.imageset/editor-chevron-down@3x.png
  WordPress/Resources/AppImages.xcassets/editor-more.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/editor-more.imageset/editor-more.png
  WordPress/Resources/AppImages.xcassets/editor-more.imageset/editor-more@2x.png
  WordPress/Resources/AppImages.xcassets/editor-more.imageset/editor-more@3x.png
  WordPress/Resources/AppImages.xcassets/editor-redo.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/editor-redo.imageset/redo.png
  WordPress/Resources/AppImages.xcassets/editor-redo.imageset/redo@2x.png
  WordPress/Resources/AppImages.xcassets/editor-redo.imageset/redo@3x.png
  WordPress/Resources/AppImages.xcassets/editor-undo.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/editor-undo.imageset/undo.png
  WordPress/Resources/AppImages.xcassets/editor-undo.imageset/undo@2x.png
  WordPress/Resources/AppImages.xcassets/editor-undo.imageset/undo@3x.png
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Gutenberg

#21065 Passes UserDefaults.standard instead of creating new instances of UserDefaults
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/Editor/GutenbergSettings.swift
Labels: [Type] Bug, Gutenberg

#21056 Jetpack Social: Add view model for the pre-publishing social cell
  WordPress/Classes/ViewRelated/Post/PrepublishingAutoSharingView.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController+JetpackSocial.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21042 [UI Tests] - Create Scheduled Post Test
  WordPress/UITests/Flows/LoginFlow.swift
  WordPress/UITests/README.md
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/PostTests.swift
  WordPress/UITests/WPUITestCredentials.swift
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPostSettings.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPublishEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/PostsScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
Labels: Testing, [Type] Task

#21070 UI Test Fix - Properly update all renamed variables
  WordPress/UITests/Tests/EditorGutenbergTests.swift
Labels: Testing, [Type] Task

#21072 [UI Tests] - Remove checks that are no longer needed for tests using self hosted sites
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITestsFoundation/Screens/Login/LoginUsernamePasswordScreen.swift
Labels: Testing, [Type] Task

#21054 [UI Tests] - Removing unnecessary flows to speed up tests
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PasswordScreen.swift
Labels: Testing, [Type] Task

#21017 Track EU/US Compliance Analytics Events
  WordPress/Classes/ViewRelated/EEUUSCompliance/CompliancePopoverViewController.swift
  WordPress/Classes/ViewRelated/EEUUSCompliance/CompliancePopoverViewModel.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsAnalytics.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsAnalyticsTracker.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/EUUSCompliance/CompliancePopoverViewControllerTests.swift
  WordPress/WordPressTest/EUUSCompliance/CompliancePopoverViewModelTests.swift
  WordPress/WordPressTest/Me/PrivacySettingsViewControllerTests.swift
  WordPress/WordPressTest/PrivacySettingsAnalyticsTrackerTests.swift
Labels: Analytics, [Type] Task

#21034 [UI Tests] Disable Auto Fill Passwords for UI Tests
  WordPress/UITests/Utils/XCTest+Extensions.swift
  WordPress/UITestsFoundation/Screens/Login/LoginUsernamePasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/Unified/PrologueScreen.swift
Labels: Testing

#21073 Jetpack Social: Prepublishing auto-sharing view model implementation
  WordPress/Classes/ViewRelated/Post/PrepublishingAutoSharingView.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21074 Jetpack Social: Show no connection view in pre-publishing sheet
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoConnectionView.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingAutoSharingView.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController+JetpackSocial.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21087 Related Posts: Add period to the end of footer
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsRelatedPostsView.swift
Labels: [Type] Bug, Site Settings

#21047 Fix retain cycles preventing objects from being deallocated after logging out
  RELEASE-NOTES.txt
  WordPress/Classes/System/RootViewCoordinator.swift
  WordPress/Classes/System/WindowManager.swift
  WordPress/Classes/System/WordPressAuthenticatorProtocol.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Pages/DashboardPagesListCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Actions/DashboardQuickActionsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Stats/DashboardStatsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/ViewModel/BlogDashboardViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Prompts/RootViewCoordinator+BloggingPrompt.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/RootViewCoordinatorTests.swift
Labels: [Type] Bug, Login, Logged-out, Memory Management

#21055 Blaze Manage Campaigns: Add event tracking
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
  WordPress/Classes/ViewRelated/Blaze/Helpers/BlazeEventsTracker.swift
  WordPress/Classes/ViewRelated/Blaze/Overlay/BlazeOverlayViewModel.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeCampaignDetailsWebViewModel.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeFlowCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignsCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/WordPressTest/Blaze/BlazeCampaignDetailsWebViewModelTests.swift
Labels: [Type] Task, Blaze

#21098 Integrate gutenberg-mobile release 1.99.1
  Gutenberg/version.rb
  Podfile.lock
Labels: Gutenberg

#21107 Merge 22.8.0.1 and editorialized release notes to trunk
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/EEUUSCompliance/CompliancePopoverCoordinator.swift
  WordPress/Classes/ViewRelated/EEUUSCompliance/CompliancePopoverViewController.swift
  WordPress/Classes/ViewRelated/EEUUSCompliance/CompliancePopoverViewModel.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsAnalytics.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsAnalyticsTracker.swift
  WordPress/Classes/ViewRelated/Me/App Settings/Privacy Settings/PrivacySettingsViewController.swift
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/cs.lproj/Localizable.strings
  WordPress/Resources/de.lproj/Localizable.strings
  WordPress/Resources/es.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  WordPress/Resources/ro.lproj/Localizable.strings
  WordPress/Resources/ru.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  WordPress/Resources/zh-Hant.lproj/Localizable.strings
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/EUUSCompliance/CompliancePopoverViewControllerTests.swift
  WordPress/WordPressTest/EUUSCompliance/CompliancePopoverViewModelTests.swift
  WordPress/WordPressTest/Me/PrivacySettingsViewControllerTests.swift
  WordPress/WordPressTest/PrivacySettingsAnalyticsTrackerTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/default/release_notes.txt
  fastlane/lanes/release.rb
  fastlane/metadata/default/release_notes.txt
Labels: Releases

#21092 Fix retain cycles in Login-related classes
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Onboarding Questions Prompt/OnboardingQuestionsCoordinator.swift
  WordPress/Classes/ViewRelated/NUX/SignupEpilogueTableViewController.swift
  WordPress/Classes/ViewRelated/NUX/SignupUsernameViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
Labels: [Type] Bug, Login, Memory Management

#21097 Editor Navigation Bar - Updates the close button icon
  WordPress/Classes/ViewRelated/Post/PostEditorNavigationBarManager.swift
  WordPress/Resources/AppImages.xcassets/editor-chevron-down.imageset/editor-chevron-down.png
  WordPress/Resources/AppImages.xcassets/editor-chevron-down.imageset/editor-chevron-down@2x.png
  WordPress/Resources/AppImages.xcassets/editor-chevron-down.imageset/editor-chevron-down@3x.png
  WordPress/Resources/AppImages.xcassets/editor-chevron-left.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/editor-chevron-left.imageset/chevron_left 1.png
  WordPress/Resources/AppImages.xcassets/editor-chevron-left.imageset/chevron_left 1@2x.png
  WordPress/Resources/AppImages.xcassets/editor-chevron-left.imageset/chevron_left 1@3x.png
Labels: Posting/Editing, Gutenberg

#21108 Merge 22.8.0.2 to trunk
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#21101 Remove custom operators from posts list
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: [Type] Task

#21066 Fix retain cycles in Site Creation
  WordPress/Classes/ViewRelated/Site Creation/Design Selection/Preview/TemplatePreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Site Segments/SiteSegmentsStep.swift
Labels: Memory Management

#21038 Fix discarded notification observers in a few places
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/EncryptedLogTableViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
Labels: [Type] Bug

#21113 Jetpack Social: Add tap actions to No Connection view in prepublishing
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21110 Dashboard Cards: Remove first and next post cards
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardEmptyPostsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/ViewModel/BlogDashboardViewModel.swift
  WordPress/Classes/ViewRelated/Blog/BlogPersonalization/BlogDashboardPersonalizationViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Dashboard/DashboardCardTests.swift
Labels: [Type] Task, My Site Dashboard

#21088 Use UserDefaults singleton
  RELEASE-NOTES.txt
  WordPress/Classes/Services/RecentSitesService.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
Labels: [Type] Bug, Site Picker, Aztec

#21094 Fix a race condition in story media loader
  WordPress/Classes/Services/Stories/StoryMediaLoader.swift
Labels: [Type] Bug

#21132 [UI Tests] Disable testFreeToPaidCardNavigation() for investigation/maintenance.
  WordPress/UITests/JetpackUITests.xctestplan
  WordPress/UITests/Tests/DashboardTests.swift
Labels: Testing

#21111 Break retain cycle between MySiteViewController and CompliancePopoverCoordinator
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/EEUUSCompliance/CompliancePopoverCoordinator.swift
  WordPress/WordPressTest/EUUSCompliance/CompliancePopoverViewModelTests.swift
Labels: Memory Management

#21053 Change scanningDelegate to a weak reference
  WordPress/Classes/ViewRelated/QR Login/Helpers/QRLoginCameraSession.swift
  WordPress/Classes/ViewRelated/QR Login/Helpers/QRLoginProtocols.swift
  WordPress/Classes/ViewRelated/Views/RichTextView/RichTextView.swift
  WordPress/WordPressTest/QRLogin/QRLoginScanningCoordinatorTests.swift
Labels: Memory Management

#21063 Change SharingAccountViewController.delegate to be a weak reference
  WordPress/Classes/ViewRelated/Blog/SharingAccountViewController.swift
Labels: Memory Management

#21040 Use weak reference to avoid a retain cycle
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
Labels: [Type] Bug

#21051 Declare a delegate property as a weak reference in WebKitViewController
  RELEASE-NOTES.txt
  WordPress/Classes/Utility/WebKitViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/Webview/JetpackConnectionWebViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Settings/JetpackConnectionViewController.swift
Labels: Memory Management

#21052 Change Jetpack connection delegates to weak references
  RELEASE-NOTES.txt
Labels: Memory Management

#21068 Enable the weak_delegate SwiftLint rule
  .swiftlint.yml
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
  WordPress/WordPressTest/Dashboard/BlazeCampaignsStreamTests.swift
  WordPress/WordPressTest/Mention/SuggestionTableViewTests.swift
  WordPress/WordPressTest/ReferrerDetailsViewModelTests.swift
Labels: [Type] Enhancement

#21125 Blaze Manage Campaigns: Show Blaze overlay only once
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Blaze/Helpers/BlazeEventsTracker.swift
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeFlowCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignsCardView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazePromoCardView.swift
Labels: [Type] Task, Blaze

#21135 Blaze Manage Campaigns: Use abbreviated numbers for campaign stats
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignSingleStatView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/DashboardBlazeCampaignView.swift
  WordPress/WordPressTest/Dashboard/BlazeCampaignViewModelTests.swift
Labels: [Type] Task, Blaze

#21106 Fix crashes when posing a comment and no associated post is found
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/System/WordPressAppDelegate.swift
Labels: [Type] Crash

#21137 Jetpack Social: Update remaining shares string
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialSettingsRemainingSharesView.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController+JetpackSocial.swift
Labels: [Type] Task, Part of a WIP Feature, Jetpack Social

#21130 Add build phase to detect nested frameworks
  Scripts/BuildPhases/LintNestedFrameworks.sh
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#21112 Fix a crash when multiple instances of Reader are opened after tapping on blogging prompts
  RELEASE-NOTES.txt
  WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift
  WordPress/Classes/System/RootViewPresenter.swift
  WordPress/Classes/System/StaticScreensTabBarWrapper.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
Labels: [Type] Crash, Reader, Blogging Prompts

#21149 Blaze Manage Campaigns: Update CTA for empty campaigns screen
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
Labels: [Type] Task, Blaze

#21140 Check for a feed ID before attempting a site topic lookup
  RELEASE-NOTES.txt
  WordPress/Classes/Models/ReaderSiteTopic+Lookup.swift
  WordPress/Classes/Services/Reader Post/ReaderPostService.m
Labels: [Type] Crash, Reader

#21143 Fix failing UI tests after React Native upgrade in Gutenberg
  .buildkite/cache-builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
Labels: Testing

#21136 Stats: Fix 'Can't add self as subview' crash in Posting Activity
  RELEASE-NOTES.txt
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Utility/StoryboardLoadable.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Posting Activity/PostingActivityViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
Labels: [Type] Crash, Stats

#21152 Remove unused WPTableImageSource and its cache
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/Utility/WPTableImageSource.h
  WordPress/Classes/Utility/WPTableImageSource.m
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#21142 Remove unused URLCache extensions
  WordPress/Classes/Extensions/NSURLCache+Helpers.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#21153 [EU/US Compliance] Use WordPress colors in compliance popover
  WordPress/Classes/ViewRelated/Site Creation/Web Address/DesignSystem/Color+DesignSystem.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/DesignSystem/Colors.xcassets/Foundation/Theme/brandWordPress.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen.colorset/Contents.json
Labels: [Type] Bug, Account Settings

#21158 Remove unused Memoize.swift
  WordPress/Classes/ViewRelated/Activity/Memoize.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task

#21122 [UI Tests] - Part 1 - Update structure of Login and Editor related screens
  WordPress/UITests/Flows/LoginFlow.swift
  WordPress/UITestsFoundation/Screens/ActionSheetComponent.swift
  WordPress/UITestsFoundation/Screens/ActivityLogScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/AztecEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/ChooseLayoutScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorNoticeComponent.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPostSettings.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPublishEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorSettingsComponents/CategoriesComponent.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorSettingsComponents/TagsComponent.swift
  WordPress/UITestsFoundation/Screens/Editor/FeaturedImageScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LinkOrPasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginCheckMagicLinkScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEmailScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginPasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginSiteAddressScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginUsernamePasswordScreen.swift
  WordPress/UITestsFoundation/Screens/Login/WelcomeScreen.swift
  WordPress/UITestsFoundation/Screens/Login/WelcomeScreenLoginComponent.swift
  WordPress/UITestsFoundation/Screens/Signup/SignupCheckMagicLinkScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/SignupEmailScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/SignupEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Signup/WelcomeScreenSignupComponent.swift
Labels: Testing, [Type] Task

#21159 Integrate gutenberg-mobile release 1.100.1
  Gutenberg/version.rb
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#21133 [UI Tests] - Part 2 - Update screens to use same structure
  WordPress/UITests/Flows/LoginFlow.swift
  WordPress/UITests/Tests/EditorAztecTests.swift
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITestsFoundation/Screens/CommentsScreen.swift
  WordPress/UITestsFoundation/Screens/DomainsScreen.swift
  WordPress/UITestsFoundation/Screens/DomainsSuggestionsScreen.swift
  WordPress/UITestsFoundation/Screens/Editor/EditorPublishEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Me/ContactUsScreen.swift
  WordPress/UITestsFoundation/Screens/Me/SupportScreen.swift
  WordPress/UITestsFoundation/Screens/MeTabScreen.swift
  WordPress/UITestsFoundation/Screens/Media/MediaPickerAlbumListScreen.swift
  WordPress/UITestsFoundation/Screens/Media/MediaPickerAlbumScreen.swift
  WordPress/UITestsFoundation/Screens/MediaScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/UITestsFoundation/Screens/MySitesScreen.swift
  WordPress/UITestsFoundation/Screens/NotificationsScreen.swift
  WordPress/UITestsFoundation/Screens/PagesScreen.swift
  WordPress/UITestsFoundation/Screens/PeopleScreen.swift
  WordPress/UITestsFoundation/Screens/PlanSelectionScreen.swift
  WordPress/UITestsFoundation/Screens/PostsScreen.swift
  WordPress/UITestsFoundation/Screens/ReaderScreen.swift
  WordPress/UITestsFoundation/Screens/SiteIntentScreen.swift
  WordPress/UITestsFoundation/Screens/SiteSettingsScreen.swift
  WordPress/UITestsFoundation/Screens/StatsScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
Labels: Testing, [Type] Task

#21154 Fix navigation bar colors in prepublishing sheet
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/PrepublishingViewController.swift
Labels: [Type] Enhancement, Jetpack Social

#21166 Blaze Manage Campaigns: Update blaze campaign status colors
  WordPress/Classes/ViewRelated/Blaze Campaigns/BlazeCampaignsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Blaze/BlazeCampaignStatusView.swift
Labels: [Type] Task, Blaze

#21165 Merge finalized release 22.8
  WordPress/Classes/ViewRelated/Site Creation/Web Address/DesignSystem/Color+DesignSystem.swift
  WordPress/Classes/ViewRelated/Site Creation/Web Address/DesignSystem/Colors.xcassets/Foundation/Theme/brandWordPress.colorset/Contents.json
  WordPress/ColorPalette.xcassets/JetpackGreen.colorset/Contents.json
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  WordPress/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/ar-SA/release_notes.txt
  fastlane/jetpack_metadata/de-DE/release_notes.txt
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/fr-FR/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/ja/release_notes.txt
  fastlane/jetpack_metadata/ko/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/pt-BR/release_notes.txt
  fastlane/jetpack_metadata/ru/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/jetpack_metadata/tr/release_notes.txt
  fastlane/jetpack_metadata/zh-Hans/release_notes.txt
  fastlane/jetpack_metadata/zh-Hant/release_notes.txt
  fastlane/metadata/ar-SA/release_notes.txt
  fastlane/metadata/de-DE/release_notes.txt
  fastlane/metadata/es-ES/release_notes.txt
  fastlane/metadata/fr-FR/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ja/release_notes.txt
  fastlane/metadata/ko/release_notes.txt
  fastlane/metadata/nl-NL/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
  fastlane/metadata/sv/release_notes.txt
  fastlane/metadata/tr/release_notes.txt
  fastlane/metadata/zh-Hans/release_notes.txt
  fastlane/metadata/zh-Hant/release_notes.txt
Labels: Releases

#21076 Fix a crash due to Core Data Concurrency Violation in the Weekly Roundup Background Task
  RELEASE-NOTES.txt
  WordPress/Classes/Models/Notifications/NotificationSettings.swift
  WordPress/Classes/Services/NotificationSettingsService.swift
  WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift
Labels: [Type] Crash, Core Data

#21169 Fix an issue with avatars not loading in suggestions
  WordPress/Classes/Utility/WPAvatarSource.m
Labels: [Type] Bug, Reader

#21156 Reduce GIF buffer limits
  WordPress/Classes/Utility/Media/GIFPlaybackStrategy.swift
Labels: Memory Management

#21167 Fix a crash caused by cellForRowAtIndexPath method in BlogDetailsViewController returning a nil cell
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: [Type] Crash, My Site

#21148 [UI Tests] Run disableAutoFillPasswords once before all the UI Tests.
  WordPress/UITests/JetpackUITests-Info.plist
  WordPress/UITests/Utils/XCTest+Extensions.swift
  WordPress/UITests/WordPressUITests-Info.plist
  WordPress/UITestsFoundation/TestObserver.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing

#21161 Update Gifu to 3.3.1
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Media/CachedAnimatedImageView.swift
Labels: [Type] Crash

#21164 Add tests for `ReaderSiteService` set blocked/unblocked
  WordPress/WordPressTest/ReaderSiteServiceTests.swift
Labels: Testing

#20973 Report discarded notification observer as errors
  .swiftlint.yml
Labels: [Type] Enhancement

#21170 Minor tweaks to Core Data API usage in Weekly Roundup Background Task
  WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift
Labels: [Type] Enhancement, Core Data

#21147 performQuery should not return NSManagedObject
  WordPress/Classes/Services/ReaderSiteService.swift
Labels: Core Data

#21016 Blog Reminders: Replace `localSettings` with lookup method calls
  RELEASE-NOTES.txt
  WordPress/Classes/Models/BloggingPromptSettings+CoreDataClass.swift
  WordPress/Classes/Services/BloggingPromptsService.swift
  WordPress/Classes/Utility/Blogging Prompts/ReminderScheduleCoordinator.swift
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduler.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Prompts/BloggingPromptCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowSettingsViewController.swift
  WordPress/WordPressTest/ReminderScheduleCoordinatorTests.swift
Labels: Blogging Reminders, Blogging Prompts

#21146 Move Core Data updates to background in Editor Settings
  RELEASE-NOTES.txt
  WordPress/Classes/Services/EditorSettingsService.swift
  WordPress/WordPressTest/EditorSettingsServiceTests.swift
Labels: Core Data

#21171 Jetpack Social: Add social accounts screen in the pre-publishing flow
  WordPress/Classes/Models/PublicizeService.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing Nudge/PrepublishingNavigationController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingAutoSharingView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21174 Merge 22.9 code freeze
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/release_notes.txt
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#21179 Jetpack Social: Add footer and subscribe flow for prepublishing social accounts
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsTableFooterView.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21120 Fix high memory usage in Reader
  Podfile
  Podfile.lock
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/UIAlertControllerProxy.m
  WordPress/Classes/Utility/WPError.m
  WordPress/Classes/Utility/WPWebViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingAuthorizationHelper.m
  WordPress/Classes/ViewRelated/Blog/SharingConnectionsViewController.m
  WordPress/Classes/ViewRelated/Blog/SharingDetailViewController.m
  WordPress/Classes/ViewRelated/Comments/EditCommentViewController.m
  WordPress/Classes/ViewRelated/Me/Views/Header/MeHeaderView.m
  WordPress/Classes/ViewRelated/Media/AnimatedImageCache.swift
  WordPress/Classes/ViewRelated/Media/MemoryCache.swift
  WordPress/Classes/ViewRelated/Menus/MenusViewController.m
  WordPress/Classes/ViewRelated/Post/FeaturedImageViewController.m
  WordPress/Classes/ViewRelated/Post/WPStyleGuide+Pages.m
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Tools/SettingsTextViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Memory Management

#21188 Jetpack Social: Add delegate methods for the social accounts sheet
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController+JetpackSocial.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingViewController.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21180 Jetpack Social: Create Jetpack Social no connection dashboard card
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/DashboardJetpackSocialCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/Classes/ViewRelated/Blog/BlogPersonalization/BlogDashboardPersonalizationViewModel.swift
  WordPress/Classes/ViewRelated/Jetpack/Social/JetpackSocialNoConnectionView.swift
  WordPress/Jetpack/Classes/Utility/JetpackSocialError.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Blog Dashboard/Cards/DashboardJetpackSocialCardCellTests.swift
  WordPress/WordPressTest/BlogBuilder.swift
Labels: [Type] Enhancement, Part of a WIP Feature, Jetpack Social

#21192 Centralize commands to config Sim in UI tests in aggregate target
  Scripts/BuildPhases/ConfigureSimulatorForUITesting.sh
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Testing

#21193 Add editorialized release notes for version 22.9
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#20956 [Gutenberg] Upgrade React Native `0.71.11`
  .buildkite/cache-builder.yml
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
  Gemfile
  Gemfile.lock
  Gutenberg/cocoapods_helpers.rb
  Gutenberg/version.rb
  Podfile
  Podfile.lock
  RELEASE-NOTES.txt
  Scripts/BuildPhases/CopyGutenbergJS.inputs.xcfilelist
  Scripts/BuildPhases/CopyGutenbergJS.sh
  Scripts/BuildPhases/LintNestedFrameworks.sh
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergImageLoader.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergFilesAppMediaSource.swift
  WordPress/UITestsFoundation/Screens/Editor/BlockEditorScreen.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/GutenbergFilesAppMediaSourceTests.swift
Labels: Gutenberg

#21168 Increase performance of Total Likes cell attributed guide text creation
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Stats/Insights/StatsTotalInsightsCell.swift
Labels: [Type] Bug, Stats

#21067 Fix app hangs in StatsPeriodStore
  RELEASE-NOTES.txt
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Stores/StatsInsightsCache.swift
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodCache.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/Stores/StatsRevampStore.swift
  WordPress/Classes/Stores/StoreContainer.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: App Hanging

#21187 [UI Tests] - Re-enable testFreeToPaidCardNavigation() test
  WordPress/UITests/Flows/LoginFlow.swift
  WordPress/UITests/JetpackUITests.xctestplan
  WordPress/UITests/Tests/DashboardTests.swift
  WordPress/UITests/Tests/EditorAztecTests.swift
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/MenuNavigationTests.swift
  WordPress/UITests/Tests/PostTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITests/WPUITestCredentials.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
Labels: Testing, [Type] Task

#21198 [UI Tests] - Refactor login flows
  WordPress/JetpackScreenshotGeneration/JetpackScreenshotGeneration.swift
  WordPress/UITests/Flows/LoginFlow.swift
  WordPress/UITests/Tests/DashboardTests.swift
  WordPress/UITests/Tests/EditorAztecTests.swift
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITests/Tests/MainNavigationTests.swift
  WordPress/UITests/Tests/MenuNavigationTests.swift
  WordPress/UITests/Tests/PostTests.swift
  WordPress/UITests/Tests/ReaderTests.swift
  WordPress/UITests/Tests/StatsTests.swift
  WordPress/UITestsFoundation/Screens/Login/LoginEpilogueScreen.swift
  WordPress/UITestsFoundation/Screens/Login/LoginSiteAddressScreen.swift
  WordPress/UITestsFoundation/Screens/MySiteScreen.swift
  WordPress/WordPressScreenshotGeneration/WordPressScreenshotGeneration.swift
Labels: Testing, [Type] Task

#21200 Fix flaky iPad UI Test - testWPcomLoginLogout
  WordPress/UITests/Tests/LoginTests.swift
  WordPress/UITestsFoundation/Screens/MeTabScreen.swift
  WordPress/UITestsFoundation/Screens/TabNavComponent.swift
Labels: Testing

#21204 Fix incorrect size of thumbnails in media picker
  RELEASE-NOTES.txt
  WordPress/Classes/Services/MediaThumbnailCoordinator.swift
  WordPress/Classes/Services/MediaThumbnailService.swift
Labels: [Type] Bug, Media

#21205 Change a directory name from "What's New" to "WhatsNew"
  WordPress/Classes/ViewRelated/WhatsNew/Data store/AnnouncementsDataSource.swift
  WordPress/Classes/ViewRelated/WhatsNew/Data store/AnnouncementsStore.swift
  WordPress/Classes/ViewRelated/WhatsNew/Data store/Cache/AnnouncementsCache.swift
  WordPress/Classes/ViewRelated/WhatsNew/Data store/StoriesIntroDataSource.swift
  WordPress/Classes/ViewRelated/WhatsNew/Dependency container/RootViewCoordinator+WhatIsNew.swift
  WordPress/Classes/ViewRelated/WhatsNew/Presenter/WhatIsNewScenePresenter.swift
  WordPress/Classes/ViewRelated/WhatsNew/Views/AnnouncementCell.swift
  WordPress/Classes/ViewRelated/WhatsNew/Views/DashboardCustomAnnouncementCell.swift
  WordPress/Classes/ViewRelated/WhatsNew/Views/FindOutMoreCell.swift
  WordPress/Classes/ViewRelated/WhatsNew/Views/GridCell.swift
  WordPress/Classes/ViewRelated/WhatsNew/Views/StoriesIntroViewController.swift
  WordPress/Classes/ViewRelated/WhatsNew/Views/WhatIsNewView.swift
  WordPress/Classes/ViewRelated/WhatsNew/Views/WhatIsNewViewAppearance.swift
  WordPress/Classes/ViewRelated/WhatsNew/Views/WhatIsNewViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement
