Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2024-07, with the labels that each got.

#23403 Bump Fastlane `xcodebuild -showBuildSettings` interval to try avoid timeouts
  fastlane/Fastfile
Labels: Tooling

#23402 Explicitly set mac queue in Buildkite pipeline
  .buildkite/pipeline.yml
  .buildkite/release-builds.yml
Labels: Tooling

#23395 Move more pods to SPM
  Podfile
  Podfile.lock
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/ViewRelated/Me/Views/Header/MeHeaderView.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Tooling

#23405 Declare app dependencies in Package.swift file
  .gitignore
  Modules/Package.swift
  Modules/Sources/XcodeSupport/XcodeTarget_App/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_DraftActionExtension/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_Intents/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_NotificationServiceExtension/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_ShareExtension/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_StatsWidget/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_UITestsFoundation/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_WordPressAuthentificator/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_WordPressAuthentificatorTests/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_WordPressKit/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_WordPressKitTests/Empty.swift
  Modules/Sources/XcodeSupport/XcodeTarget_WordPressTests/Empty.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/JetpackStatsWidgets/Model/TodayWidgetStats.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogServiceTest.m
  WordPress/WordPressTest/Extensions/UIImage+XCAssetTests.swift
  WordPress/WordPressTest/Extensions/UITextFieldTextHelperTests.swift
  WordPress/WordPressTest/LocalCoreDataServiceTests.m
  WordPress/WordPressTest/MediaServiceUpdateTests.m
  WordPress/WordPressTest/MenusServiceTests.m
  WordPress/WordPressTest/PostCategoryServiceTests.m
  WordPress/WordPressTest/PostCompactCellGhostableTests.swift
  WordPress/WordPressTest/PostTagServiceTests.m
  WordPress/WordPressTest/PushAuthenticationManagerTests.swift
  WordPress/WordPressTest/PushNotificationsManagerTests.m
  WordPress/WordPressTest/ReaderPostTest.m
  WordPress/WordPressTest/ThemeServiceTests.m
  WordPress/WordPressTest/ViewRelated/Blog/Style/WPStyleGuide+BlogTests.swift
  WordPress/WordPressTest/WPAnalyticsTrackerAutomatticTracksTests.m
  WordPress/WordPressTest/WPAppAnalyticsTests.m
  WordPress/WordPressTest/WordPressUIBundleTests.swift
  WordPressKit/Tests/WordPressKitTests/Tests/BlogServiceRemoteRESTTests.m
  WordPressKit/Tests/WordPressKitTests/Tests/MenusServiceRemoteTests.m
  WordPressKit/Tests/WordPressKitTests/Tests/PostServiceRemoteRESTTests.m
  WordPressKit/Tests/WordPressKitTests/Tests/TaxonomyServiceRemoteRESTTests.m
  WordPressKit/Tests/WordPressKitTests/Tests/ThemeServiceRemoteTests.m
Labels: [Type] Enhancement, Tooling

#23386 Remove Alamofire dependency from WordPressKit
  Modules/Package.swift
  WordPressKit/Tests/CoreAPITests/MultipartFormTests.swift
  WordPressKit/Tests/WordPressKitTests/Tests/Models/Stats/V2/Insights/StatsDotComFollowersInsightTests.swift
Labels: [Type] Task

#23387 Remove UIDeviceIdentifier dependency from WordPressKit
  Modules/Package.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPressKit/Sources/WordPressKit/Services/NotificationSettingsServiceRemote.swift
  WordPressKit/Sources/WordPressKit/Utility/UIDevice+Extensions.swift
Labels: [Type] Task

#23396 Reduce App Size – Assets (2)
  WordPress/Classes/Extensions/UIImage+Assets.swift
  WordPress/Classes/Extensions/UIImage+Extensions.swift
  WordPress/Jetpack/AppImages.xcassets/Prologue/JPBackground.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Prologue/JPBackground.imageset/background-light_Normal.png
  WordPress/Jetpack/AppImages.xcassets/Prologue/JPBackground.imageset/background-light_Normal@2x.png
  WordPress/Jetpack/AppImages.xcassets/Prologue/JPBackground.imageset/background-light_Normal@3x.png
  WordPress/Jetpack/AppImages.xcassets/Prologue/JPBackground.imageset/jetpack-firstrun-background.svg
  WordPress/Jetpack/Classes/NUX/JetpackPrologueStyleGuide.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#23415 Exclude Modules build directory from swiftlint
  .swiftlint.yml
Labels: [Type] Enhancement

#23417 [Gutenberg] - Gallery block - Fix getMediaItems
  Gutenberg/config.yml
  Podfile.lock
Labels: Gutenberg

#23411 [Gutenberg] - Remove Gallery V1 and experimental flags
  Gutenberg/config.yml
  Podfile.lock
  WordPress/Classes/Models/BlockEditorSettingElement+CoreDataProperties.swift
  WordPress/Classes/Models/BlockEditorSettings+GutenbergEditorSettings.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditorAnalyticsSession.swift
  WordPress/UITests/Tests/EditorGutenbergTests.swift
  WordPressKit/Sources/WordPressKit/Models/RemoteBlockEditorSettings.swift
Labels: Gutenberg

#23414 Improve "Submit Feedback" Flow
  WordPress/Classes/Utility/In-App Feedback/InAppFeedbackPromptCoordinator.swift
  WordPress/Classes/Utility/In-App Feedback/SubmitFeedbackViewController.swift
  WordPress/Classes/Utility/In-App Feedback/ZendeskAttachmentsSection.swift
  WordPress/Classes/Utility/Media/MediaExporter.swift
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Task, User Feedback

#23419 Fix grammar of Reader sync alert
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: [Type] Enhancement, Reader

#23425 Remove SwiftLint from Package.swift
  Modules/Package.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Tooling

#23421 Add support for video attachments in "Send Feedback" form
  WordPress/Classes/Utility/In-App Feedback/ZendeskAttachmentsSection.swift
  WordPress/Classes/Utility/Media/MediaFileManager.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
Labels: Support

#23422 Remove subject field from the feedback form
  WordPress/Classes/Utility/In-App Feedback/SubmitFeedbackViewController.swift
Labels: Support

#23423 Remove unused code from WordPressShared
  Modules/Sources/WordPressShared/Analytics/AnalyticsEvent.swift
  Modules/Sources/WordPressShared/Utility/CollectionType+Helpers.swift
  Modules/Sources/WordPressShared/Utility/ConsoleLogger.swift
  Modules/Sources/WordPressShared/Utility/NSBundle+WordPressShared.swift
  Modules/Sources/WordPressShared/Utility/NSDate+Helpers.swift
  Modules/Sources/WordPressShared/Utility/NSMutableData+Helpers.swift
  Modules/Sources/WordPressShared/Utility/RichContentFormatter.swift
  Modules/Sources/WordPressShared/Utility/Secret.swift
  Modules/Sources/WordPressShared/Utility/String+Helpers.swift
  Modules/Sources/WordPressShared/Utility/String+RemovingMatches.swift
  Modules/Sources/WordPressShared/Views/WPStyleGuide+DynamicType.swift
  Modules/Sources/WordPressShared/Views/WPStyleGuide+SerifFonts.swift
  Modules/Sources/WordPressShared/WordPressShared.swift
  Modules/Sources/WordPressSharedObjC/Logging/WPSharedLogging.m
  Modules/Sources/WordPressSharedObjC/Private/WPShared-Swift.h
  Modules/Sources/WordPressSharedObjC/Utility/DateUtils.m
  Modules/Sources/WordPressSharedObjC/Utility/NSString+Helpers.m
  Modules/Sources/WordPressSharedObjC/Utility/NSString+Util.m
  Modules/Sources/WordPressSharedObjC/Utility/UIDevice+Helpers.m
  Modules/Sources/WordPressSharedObjC/Utility/WPDeviceIdentification.m
  Modules/Sources/WordPressSharedObjC/Utility/WPFontManager.m
  Modules/Sources/WordPressSharedObjC/Utility/WPMapFilterReduce.m
  Modules/Sources/WordPressSharedObjC/Views/WPNUXUtility.m
  Modules/Sources/WordPressSharedObjC/Views/WPStyleGuide.m
  Modules/Sources/WordPressSharedObjC/Views/WPTableViewCell.m
  Modules/Sources/WordPressSharedObjC/WordPressShared.h
  Modules/Sources/WordPressSharedObjC/include/DateUtils.h
  Modules/Sources/WordPressSharedObjC/include/NSString+Helpers.h
  Modules/Sources/WordPressSharedObjC/include/UIDevice+Helpers.h
  Modules/Sources/WordPressSharedObjC/include/WPDeviceIdentification.h
  Modules/Sources/WordPressSharedObjC/include/WPMapFilterReduce.h
  Modules/Sources/WordPressSharedObjC/include/WPNUXUtility.h
  Modules/Sources/WordPressSharedObjC/include/WPSharedLogging.h
  Modules/Sources/WordPressSharedObjC/include/WPStyleGuide.h
  Modules/Sources/WordPressSharedObjC/include/WPTableViewCell.h
  Modules/Sources/WordPressUI/Extensions/NSBundle+ResourceBundle.swift
  Modules/Tests/WordPressSharedObjCTests/LoggingTests.m
  Modules/Tests/WordPressSharedObjCTests/WPMapFilterReduceTest.m
  Modules/Tests/WordPressSharedTests/LoggingTests.swift
  WordPress/Classes/Extensions/JSONDecoderExtension.swift
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/Services/LikeUserHelpers.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Logging/WPLogger.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPressAuthenticator/Sources/Extensions/FancyAlertViewController+LoginError.swift
  WordPressAuthenticator/Sources/NUX/WPNUXPrimaryButton.h
  WordPressAuthenticator/Sources/NUX/WPNUXPrimaryButton.m
  WordPressAuthenticator/Sources/NUX/WPWalkthroughOverlayView.h
  WordPressAuthenticator/Sources/NUX/WPWalkthroughOverlayView.m
  WordPressAuthenticator/Sources/NUX/WPWalkthroughTextField.m
  WordPressAuthenticator/Sources/WordPressAuthenticator.h
Labels: [Type] Task

#23429 Remove Gravatar related deprecated types and replace with Gravatar SDK
  Modules/Package.swift
  Modules/Sources/WordPressUI/Extensions/Gravatar/Gravatar.swift
  Modules/Sources/WordPressUI/Extensions/UIImageView+Gravatar.swift
  Modules/Sources/WordPressUIObjC/Extensions/NSString+Gravatar.h
  Modules/Sources/WordPressUIObjC/Extensions/NSString+Gravatar.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPressAuthenticator/Sources/Signin/LoginLinkRequestViewController.swift
  WordPressAuthenticator/Sources/Signin/UIImageView+Additions.swift
  WordPressAuthenticator/Sources/Unified Auth/View Related/Reusable Views/GravatarEmailTableViewCell.swift
Labels: [Type] Tech Debt

#23431 Integrate gutenberg-mobile release v1.121.0
  Gutenberg/config.yml
  Podfile.lock
  RELEASE-NOTES.txt
Labels: Gutenberg

#23434 Disable voice-to-content FF
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+FAB.swift
Labels: [Type] Task

#23430 Site List – Refactor & Redesign
  Modules/Sources/DesignSystem/Components/FAB.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/SharedStrings.swift
  WordPress/Classes/Utility/StringRankedSearch.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListSiteView.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListView.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SiteSwitcherView.swift
  WordPress/Classes/ViewRelated/System/Floating Create Button/FloatingActionButton.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogBuilder.swift
  WordPress/WordPressTest/BlogListViewModelTests.swift
  docs/localization.md
Labels: Site Management

#23432 Site List – Features
  Modules/Sources/WordPressUI/Views/WebView.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/SharedStrings.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListSiteView.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListView.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SiteSwitcherView.swift
Labels: Site Management

#23441 Remove some Objective-C code from WordPressUIObjC
  Modules/Sources/WordPressUIObjC/Categories/UIColor+Helpers.h
  Modules/Sources/WordPressUIObjC/Categories/UIColor+Helpers.m
  Modules/Sources/WordPressUIObjC/Categories/UILabel+SuggestSize.h
  Modules/Sources/WordPressUIObjC/Categories/UILabel+SuggestSize.m
  Modules/Sources/WordPressUIObjC/include/NSString+Gravatar.h
  WordPress/Classes/ViewRelated/Blog/WPStyleGuide+Sharing.swift
  WordPress/Classes/ViewRelated/Post/PostSettingsViewController.m
  WordPressAuthenticator/Sources/Extensions/WPStyleGuide+Login.swift
Labels: [Type] Tech Debt

#23445 Merge 25.2 release notes to trunk
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#23449 Show "All Domains" in split view's details view
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
Labels: [Type] Bug

#23450 Add WordPress REST API Helpers
  WordPress/Classes/Models/Blog+SelfHosted.swift
  WordPress/Classes/Models/SelfHostedLoginDetails.swift
  WordPress/Classes/Utility/BlogQuery.swift
  WordPress/Classes/Utility/KeychainUtils.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Blog+RestAPITests.swift
  WordPress/WordPressTest/TestKeychain.swift
Labels: [Type] Enhancement, Core Data
