Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2024-10, with the labels that each got.

#23642 Add Not Now to review prompt
  WordPress/Classes/Utility/In-App Feedback/InAppFeedbackPromptCoordinator.swift
Labels: User Feedback

#23653 Stop handling WordPress.com links in the WordPress app
  WordPress/WordPress-Alpha.entitlements
  WordPress/WordPress-Internal.entitlements
  WordPress/WordPress.entitlements
  WordPress/WordPressTest/MediaURLExporterTests.swift
Labels: Universal Links

#23631 feat: Synchronize content with GutenbergKit
  Modules/Package.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift
Labels: [Type] Enhancement, Gutenberg

#23643 Refresh stats after switching back to the app
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsInsightsDetailsTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/Stats/Subscribers/StatsSubscribersViewController.swift
Labels: [Type] Bug

#23655 Disable outdated Reader announcements
  WordPress/Classes/ViewRelated/Reader/ReaderAnnouncementHeaderView.swift
Labels: [Type] Bug, iPad

#23647 Fix an issue with Me header view alignment
  WordPress/Classes/ViewRelated/Me/Views/MeHeaderView.swift
Labels: [Type] Bug

#23656 Rename Personalize home tab
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/BlogDashboardPersonalizeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/BlogPersonalization/BlogDashboardPersonalizationView.swift
Labels: iPad

#23659 Add a note about Feedback vs Support
  WordPress/Classes/Utility/In-App Feedback/SubmitFeedbackViewController.swift
Labels: Support

#23660 Add Gutenberg Experimental Editor Switch
  WordPress/Classes/ViewRelated/Me/App Settings/ExperimentalFeaturesDataProvider.swift
Labels: Gutenberg

#23648 Add TipKit for Sidebar
  WordPress/Classes/ViewRelated/Blog/My Site/Header/HomeSiteHeaderViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SiteMenuViewController.swift
  WordPress/Classes/ViewRelated/Tips/AppTips.swift
Labels: iPad

#23661 Enable TipKit FF
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
Labels: General

#23664 Fix crash in TipKit
  WordPress/Classes/ViewRelated/Blog/My Site/Header/HomeSiteHeaderViewController.swift
  WordPress/Classes/ViewRelated/Tips/AppTips.swift
Labels: General

#23646 Add tracking for post sync errors
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/WPInstrumentation.swift
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Labels: General

#23663 Remove Sidebar FF and WPSplitViewController with related code
  Modules/Sources/WordPressUI/Extensions/UIViewController+Helpers.swift
  WordPress/Classes/Extensions/UINavigationController+SplitViewFullscreen.swift
  WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift
  WordPress/Classes/System/RootViewCoordinator.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/ViewModel/BlogDashboardViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewModel.swift
  WordPress/Classes/ViewRelated/Comments/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPSplitViewController.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/MySiteViewModelTests.swift
Labels: iPad

#23668 Reader: Menu improvements
  WordPress/Classes/System/ReaderPresenter.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarSubscriptionsSection.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarTagsSection.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionAddButton.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionCell.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionHelper.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionNotificationSettingsView.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionsView.swift
  WordPress/Classes/ViewRelated/Reader/Tags/ReaderTagsHelper.swift
Labels: Reader

#23644 Find the right WP.com account for Jetpack connected sites
  WordPress/Classes/Services/BlogSyncFacade.m
Labels: [Type] Bug

#23669 Reader: Remove legacy code
  WordPress/Classes/ViewRelated/Reader/ReaderAnnouncementHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader

#23672 Merge 25.4 release notes to `release/25.4`
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#23667 Reader: Add new menu
  Modules/Package.swift
  Modules/Sources/WordPressShared/Utility/Lazy.swift
  Modules/Tests/WordPressSharedTests/LazyTests.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/System/ReaderPresenter.swift
  WordPress/Classes/System/SplitViewRootPresenter+Reader.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Reader/ReaderAnnouncementHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSearchViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarSubscriptionsSection.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarTagsSection.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionAddButton.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionCell.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionHelper.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionNotificationSettingsView.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionsView.swift
  WordPress/Classes/ViewRelated/Reader/Tags/ReaderTagsHelper.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/UITests/Utils/XCTest+Extensions.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader

#23674 [Tooling] `finalize_release` lane: Add back hotfix validation and remove unused lane parameter
  fastlane/Fastfile
  fastlane/lanes/release.rb
Labels: Tooling

#23678 Push various code signing related settings to `xcconfig`
  WordPress/WordPress.xcodeproj/project.pbxproj
  config/Common.debug.xcconfig
  config/Common.enterprise.xcconfig
  config/Common.xcconfig
  config/Jetpack.alpha.xcconfig
  config/Jetpack.debug.xcconfig
  config/Jetpack.internal.xcconfig
  config/WordPress.alpha.xcconfig
  config/WordPress.debug.xcconfig
  config/WordPress.internal.xcconfig
  config/WordPressAuthenticator.enterprise.xcconfig
Labels: Tooling

#23624 feat: Handle remote editor load failure
  Modules/Package.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: [Type] Enhancement, Gutenberg

#23683 Rename LoginClient to SelfHostedSiteAuthenticator
  WordPress/Classes/Login/LoginWithUrlView.swift
  WordPress/Classes/Login/SelfHostedSiteAuthenticator.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/AddSiteController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Tech Debt

#23687 Revert split view changes
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/System/Sidebar/SiteMenuViewController.swift
Labels: [Type] Bug

#23690 Fix crash in ImageDownloader
  WordPress/Classes/Utility/Media/ImageDownloader.swift
Labels: [Type] Crash

#23689 Add support for opening detail for individual posts in Stats / Authors
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
Labels: Stats, [Type] Task

#23692 Improve post sharing in Reader
  WordPress/Classes/Utility/Sharing/SafariActivity.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationTableViewCell.swift
  WordPress/Classes/ViewRelated/Post/PostSharingController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNewHeaderView.swift
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Safari.png
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Safari@2x.png
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Safari@2x~ipad.png
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Safari~ipad.png
  WordPress/WordPressTest/Posts/PostSharingControllerTests.swift
Labels: Reader

#23698 Merge `release/25.4.1` into trunk using cherry picked commits
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/Utility/Media/ImageDownloader.swift
  WordPress/Classes/Utility/Sharing/SafariActivity.m
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationTableViewCell.swift
  WordPress/Classes/ViewRelated/Post/PostSharingController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailNewHeaderView.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/SiteStatsPeriodViewModel.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SiteMenuViewController.swift
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Safari.png
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Safari@2x.png
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Safari@2x~ipad.png
  WordPress/Resources/AppImages.xcassets/Safari.imageset/Safari~ipad.png
  WordPress/WordPressTest/Posts/PostSharingControllerTests.swift
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#23697 [Tooling] Use bot for release management git operations
  .buildkite/commands/complete-code-freeze.sh
  .buildkite/commands/configure-git-for-release-management.sh
  .buildkite/commands/finalize-hotfix.sh
  .buildkite/commands/finalize-release.sh
  .buildkite/commands/log-outdated-pods.sh
  .buildkite/pipeline.yml
  .buildkite/release-pipelines/code-freeze.yml
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/finalize-hotfix.yml
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/new-beta-release.yml
  .buildkite/release-pipelines/new-hotfix.yml
  .buildkite/release-pipelines/publish-release.yml
  .buildkite/release-pipelines/update-app-store-strings.yml
  .xcode-version
Labels: Tooling

#23681 Look up account by username instead of using the default account
  WordPress/Classes/Services/AccountService.m
Labels: Login

#23703 Fix up acknowledgements
  Scripts/BuildPhases/GenerateAcknowledgementsBundle.sh
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#23711 Fix an issue with missing Sidebar button when you have no sites
  WordPress/Classes/System/SplitViewRootPresenter+Welcome.swift
Labels: iPad

#23670 Reader: Implement new cells
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/Media/FaviconService.swift
  WordPress/Classes/Utility/Media/ImageView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderCardsStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostMenu.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTableConfiguration.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderBlockingHelper.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionCell.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionHelper.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionNotificationSettingsView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader

#23682 Prevent signing in with another WP.com account
  WordPress/Classes/Login/WordPressDotComAuthenticator.swift
  WordPress/Classes/Services/BloggingPrompts/BloggingPromptsService.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
  WordPress/WordPressTest/BloggingPromptsServiceTests.swift
  WordPress/WordPressTest/PromptRemindersSchedulerTests.swift
Labels: Jetpack, Login

#23716 Move StringRankedSearch to WordPressShared
  Modules/Sources/WordPressShared/Utility/StringRankedSearch.swift
  Modules/Tests/WordPressSharedTests/StringRankedSearchTests.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift
  WordPress/Classes/ViewRelated/Post/Search/PostSearchSuggestionsService.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionsView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Self-hosted

#23723 Remove unnecessary `try`s
  WordPress/WordPressTest/Blog Dashboard/Cards/DashboardBloganuaryCardCellTests.swift
  WordPress/WordPressTest/Blog Dashboard/Cards/DashboardJetpackSocialCardCellTests.swift
  WordPress/WordPressTest/ReminderScheduleCoordinatorTests.swift
Labels: [Type] Tech Debt

#23712 Fix bar chart colors
  WordPress/Classes/Utility/App Configuration/AppColor.swift
Labels: Stats

#23710 Fix an issue with a missing "Reply" button in Notifications / Comments
  WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
  WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Reply.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Comments

#23676 Reader: Add Discover Channels
  Modules/Package.swift
  Modules/Sources/WordPressShared/Utility/ManagedObjectsObserver.swift
  Modules/Sources/WordPressUI/Extensions/UITextView+Extensions.swift
  Modules/Sources/WordPressUI/Extensions/UIView+AutoLayout.swift
  Modules/Sources/WordPressUI/Extensions/UIView+Helpers.swift
  Modules/Tests/WordPressUITests/Extensions/UIView+ChangeLayoutMarginsTests.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/Extensions/Font/UIFont+Weight.swift
  WordPress/Classes/Models/ReaderTagTopic.swift
  WordPress/Classes/Services/ReaderCardService.swift
  WordPress/Classes/System/ReaderPresenter.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
  WordPress/Classes/ViewRelated/Reader/Manage/ReaderTagsTableViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDiscoverHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDiscoverViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamTitleView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Ghost.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderCardServiceTests.swift
  WordPress/WordPressTest/ReaderTabViewModelTests.swift
Labels: Reader

#23701 Update Gravatar to 3.0.0
  Modules/Package.swift
  Modules/Sources/WordPressUI/Extensions/UIImage+Crop.swift
  Modules/Tests/WordPressUITests/Extensions/UIImage+CropTests.swift
  RELEASE-NOTES.txt
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/Services/GravatarService.swift
  WordPress/WordPressTest/GravatarServiceTests.swift
Labels: [Type] Enhancement, Gravatar

#23700 Reader: Minor Improvements
  WordPress/Classes/System/ReaderPresenter.swift
  WordPress/Classes/Utility/Media/ImageView.swift
  WordPress/Classes/Utility/SharedStrings.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDiscoverHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderDiscoverViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCellViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarSubscriptionsSection.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSiteHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamTitleView.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Ghost.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Helper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionCell.swift
  WordPress/Classes/ViewRelated/Reader/Tags/ReaderTagsAddTagView.swift
Labels: Reader

#23725 Remove saved credentials when removing self-hosted sites
  WordPress/Classes/Models/Blog+SelfHosted.swift
  WordPress/Classes/Models/Blog.m
  WordPress/Classes/Utility/KeychainUtils.swift
  WordPress/WordPressTest/TestKeychain.swift
Labels: [Type] Bug

#23731 Fixes for 24.5.2
  WordPress/Classes/Extensions/UINavigationController+SplitViewFullscreen.swift
  WordPress/Classes/System/SplitViewRootPresenter+Welcome.swift
  WordPress/Classes/Utility/App Configuration/AppColor.swift
  WordPress/Classes/ViewRelated/Notifications/ReplyTextView/ReplyTextView.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
Labels: [Type] Bug

#23734 Merge 25.4.2 final to trunk
  config/Version.internal.xcconfig
  config/Version.public.xcconfig
Labels: Releases

#23733 [Tooling] Update the Xcode image from 16.1 RC to 16.1
  .xcode-version
Labels: Tooling

#23736 Use Folders for Classes
  Gemfile.lock
  Podfile
  Podfile.lock
  WordPress/Classes/ViewRelated/Aztec/Extensions/Header+WordPress.swift
  WordPress/Classes/ViewRelated/Aztec/Extensions/TextList+WordPress.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
Labels: [Type] Enhancement, [Type] Tech Debt

#23722 Reader: Update cross-post cells
  WordPress/Classes/Models/ReaderPost+Searchable.swift
  WordPress/Classes/Models/ReaderPost.h
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/Models/ReaderPostContentProvider.h
  WordPress/Classes/Networking/MediaHost+ReaderPost.swift
  WordPress/Classes/Services/CommentService.m
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/Utility/Media/ImageView.swift
  WordPress/Classes/ViewRelated/Comments/Views/Detail/ContentRenderer/RichCommentContentRenderer.swift
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderBlockedSiteCell.swift
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderCardDiscoverAttributionView.swift
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderCrossPostCell.swift
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderCrossPostCell.xib
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderPostCell.swift
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderPostCellViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderStreamBaseCell.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderCellConfiguration.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderTableConfiguration.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailToolbar.swift
  WordPress/Classes/ViewRelated/Reader/Headers/ReaderListStreamHeader.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPost+Display.swift
  WordPress/Classes/ViewRelated/Reader/Style/WPStyleGuide+Reader.swift
  WordPress/Classes/ViewRelated/Reader/Views/ReaderAvatarView.swift
  WordPress/Resources/AppImages.xcassets/_WordPressDesignLibrary/wpl-shuffle.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/_WordPressDesignLibrary/wpl-shuffle.imageset/wpl-shuffle.pdf
Labels: Reader

#23737 Add Dependabot
  .github/dependabot.yml
Labels: Tooling
