Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2024-09, with the labels that each got.

#23530 Sidebar: Refactor Reader root navigation
  WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift
  WordPress/Classes/System/RootViewPresenter.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/System/StaticScreensTabBarWrapper.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCellViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLater+Analytics.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSaveForLaterAction.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: iPad

#23531 Automatically switch site when current blog is deleted
  WordPress/Classes/System/SplitViewRootPresenter.swift
Labels: iPad

#23535 Sidebar: Notifications Cleanup
  WordPress/Classes/Models/Notifications/NotificationSettings.swift
  WordPress/Classes/Services/NotificationSettingsService.swift
  WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingStreamsViewController.swift
  WordPress/Resources/AppImages.xcassets/Notifications/notifications-bell.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Notifications/notifications-bell.imageset/notifications-bell.pdf
  WordPress/Resources/AppImages.xcassets/Notifications/notifications-email.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Notifications/notifications-email.imageset/notifications-email.pdf
  WordPress/Resources/AppImages.xcassets/Notifications/notifications-phone.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/Notifications/notifications-phone.imageset/notifications-phone.pdf
  WordPress/Resources/AppImages.xcassets/_WordPressDesignLibrary/wpl-bell.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/_WordPressDesignLibrary/wpl-bell.imageset/bell.pdf
  WordPress/Resources/AppImages.xcassets/_WordPressDesignLibrary/wpl-mail.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/_WordPressDesignLibrary/wpl-mail.imageset/Source.pdf
  WordPress/Resources/AppImages.xcassets/_WordPressDesignLibrary/wpl-phone.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/_WordPressDesignLibrary/wpl-phone.imageset/mobile.pdf
  WordPress/WordPressTest/NotificationSettingsServiceTests.swift
Labels: Notifications

#23522 Fix a crash when log out
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarProfileView.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewModel.swift
Labels: [Type] Crash, iPad

#23540 Hide sidebar when switching site
  WordPress/Classes/System/SplitViewRootPresenter.swift
Labels: iPad

#23541 Fix an issue where sidebar reload when it does not need to
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: iPad

#23549 Remove an unused function in RootViewPresenter
  WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift
  WordPress/Classes/System/RootViewPresenter.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
Labels: [Type] Tech Debt

#23551 Update `SwiftSoup` to address privacy manifest warning
  Modules/Package.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependencies

#23532 Sidebar: Improve Me Header View
  Modules/Sources/WordPressUI/Extensions/UIEdgeInsets+Extensions.swift
  Modules/Sources/WordPressUI/Extensions/UIView+Helpers.swift
  WordPress/Classes/Extensions/UIEdgeInsets.swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/BlogDashboardPersonalizeCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/BloggingPromptsAttribution.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Me/Views/Header/MeHeaderView.h
  WordPress/Classes/ViewRelated/Me/Views/Header/MeHeaderView.m
  WordPress/Classes/ViewRelated/Me/Views/Header/MeHeaderViewConfiguration.swift
  WordPress/Classes/ViewRelated/Me/Views/MeHeaderView.swift
  WordPress/Classes/ViewRelated/Media/SiteMedia/Controllers/SiteMediaPreviewViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationTableViewCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/StatsTotalInsightsCell.swift
  WordPress/Classes/ViewRelated/Support/SupportTableViewControllerConfiguration.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarProfileView.swift
  WordPress/Classes/ViewRelated/Views/List/NotificationsList/AvatarView.swift
  WordPress/Classes/ViewRelated/Views/List/NotificationsList/NotificationsTableViewCellContent.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Success card/MigrationSuccessCardView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: iPad

#23545 Sidebar: Fix styles in Me screen
  WordPress/Classes/Utility/WPImmuTableRows.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
Labels: iPad

#23542 Update `complete_code_freeze` to use named block arguments
  fastlane/lanes/release.rb
Labels: Tooling

#23556 Fix Notification List Accessibility
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationTableViewCell.swift
  WordPress/Classes/ViewRelated/Views/List/NotificationsList/NotificationsTableViewCellContent.swift
Labels: Accessibility

#23547 Sidebar: Add Reader sidebar
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabView.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderTabViewModelTests.swift
Labels: iPad

#23552 Sidebar: Add missing Help
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
Labels: iPad

#23555 Sidebar: Reader Subscriptions
  WordPress/Classes/Stores/NoticeStore.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Reader/ReaderFollowedSitesViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewModel.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
Labels: Reader, iPad

#23525 Sidebar: Site Picker Popover
  WordPress/Classes/Extensions/UIBarButtonItem+Extensions.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/BlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/My Site/Header/HomeSiteHeaderViewController+SiteActions.swift
  WordPress/Classes/ViewRelated/Blog/My Site/Header/HomeSiteHeaderViewController+SiteIcon.swift
  WordPress/Classes/ViewRelated/Blog/My Site/Header/HomeSiteHeaderViewController.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/AddSiteController.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SitePickerView.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/SiteSwitcherView.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: iPad

#23557 Fix concurrency warning in WordpressUICacheAdapter
  WordPress/Classes/Utility/Media/MemoryCache.swift
Labels: General

#23550 Remove `RootViewPresenter.meViewController`
  WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift
  WordPress/Classes/System/RootViewPresenter+AppSettingsNavigation.swift
  WordPress/Classes/System/RootViewPresenter+MeNavigation.swift
  WordPress/Classes/System/RootViewPresenter.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/System/StaticScreensTabBarWrapper.swift
  WordPress/Classes/System/WPTabBarController+RootViewPresenter.swift
  WordPress/Classes/Utility/Universal Links/Routes+Me.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+MeTab.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
Labels: iPad

#23560 Do not store Core Data objects in MediaHost error types
  WordPress/Classes/Networking/MediaHost+AbstractPost.swift
  WordPress/Classes/Networking/MediaHost+Blog.swift
  WordPress/Classes/Networking/MediaHost+ReaderPostContentProvider.swift
Labels: [Type] Tech Debt

#23559 Cache authToken in WPAccount instances
  WordPress/Classes/Models/WPAccount.m
Labels: Performance

#23570 Simplify navigating to the Notifications tab
  WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift
  WordPress/Classes/System/RootViewPresenter.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/System/StaticScreensTabBarWrapper.swift
  WordPress/Classes/System/WPTabBarController+RootViewPresenter.swift
  WordPress/Classes/Utility/Universal Links/Routes+Notifications.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
Labels: [Type] Tech Debt

#23573 Fix a few warnings
  WordPress/Classes/Models/Page.swift
  WordPress/Classes/Networking/MediaHost+AbstractPost.swift
  WordPress/Classes/Utility/Media/MediaFileManager.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+FAB.swift
  WordPress/Classes/ViewRelated/Post/Revisions/Browser/RevisionBrowserState.swift
  WordPress/Classes/ViewRelated/Post/Revisions/Views/Operation/RevisionOperation.swift
Labels: [Type] Tech Debt

#23558 Sidebar: Reader Subscriptions
  Modules/Sources/WordPressUI/Views/EmptyStateView.swift
  WordPress/Classes/Extensions/EmptyStateView+Extensions.swift
  WordPress/Classes/Utility/SharedStrings.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/SiteTagsViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionAddButton.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionCell.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionHelper.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionNotificationSettingsView.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionsView.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionsViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader, iPad

#23576 Sidebar: Fix an issue with SidebarProfileView not reloading
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarProfileView.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewModel.swift
Labels: [Type] Bug, iPad

#23499 GutenbergKit - Initial API Support
  Modules/Package.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift
Labels: Gutenberg

#23577 Sidebar: Reader selection
  WordPress/Classes/Stores/UserPersistentRepositoryUtility.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewModel.swift
Labels: Reader, iPad

#23579 Validate site icon URL
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/SiteIconViewModel.swift
Labels: [Type] Bug, Reader

#23583 Fix login background colors
  WordPress/Classes/Utility/App Configuration/AppColor.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/ViewModel/JetpackPromptsConfiguration.swift
Labels: General

#23580 Sidebar: Remove isFollowingReaderGuide
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/System/FilterTabBar.swift
Labels: iPad

#23581 Sidebar: Add FAB to Post and Page lists
  WordPress/Classes/ViewRelated/Pages/PageListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostListViewController.swift
Labels: iPad

#23575 Reader: Update cells for iPad
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCell.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
Labels: Reader, iPad

#23574 Sidebar: Reader Lists and Organization
  WordPress/Classes/Utility/SharedStrings.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarListsSection.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewModel.swift
  WordPress/Classes/ViewRelated/Reader/Sidebar/ReaderSidebarOrganizationSection.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader, iPad

#23459 Remove PostSignUpInterstitialViewController
  Modules/Sources/WordPressUI/Views/EmptyStateView.swift
  WordPress/Classes/System/RootViewCoordinator.swift
  WordPress/Classes/System/RootViewPresenter+EditorNavigation.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/My Site/NoSitesView.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.swift
  WordPress/Classes/ViewRelated/NUX/Post Signup Interstitial/PostSignUpInterstitialViewController.xib
  WordPress/Classes/ViewRelated/NUX/UnifiedProloguePages.swift
  WordPress/Classes/ViewRelated/NUX/UnifiedPrologueViewController.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewModel.swift
  WordPress/Jetpack/AppImages.xcassets/wp-illustration-construct-site-jetpack.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/wp-illustration-construct-site-jetpack.imageset/jetpack-empty-state-dark.pdf
  WordPress/Jetpack/AppImages.xcassets/wp-illustration-construct-site-jetpack.imageset/jetpack-empty-state-light.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: iPad

#23586 Interactive Prompt Attributions
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/BloggingPromptsAttribution.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
Labels: [Type] Enhancement

#23582 Sidebar: Show Site Settings in modal on iPad
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: iPad

#23590 Remove unused willDisplayPostSignupFlow
  WordPress/Classes/System/RootViewPresenter.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/System/StaticScreensTabBarWrapper.swift
  WordPress/Classes/System/WPTabBarController+RootViewPresenter.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
Labels: General

#23596 [Tooling] Do not cancel GitHub Actions running jobs
  .github/workflows/run-danger.yml
Labels: Tooling

#23563 feat: Remote editor
  Modules/Package.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift
Labels: [Type] Enhancement, Gutenberg

#23600 Revert post & pages readable content guide change
  WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift
Labels: iPad

#23594 Minor changes to `MySiteCoordinator`
  WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
  WordPress/Classes/Utility/Universal Links/Routes+Start.swift
  WordPress/Classes/Utility/Universal Links/Routes+Stats.swift
  WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: iPad

#23593 Sidebar: Fixes and Improvements
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/BlogDashboardViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/ViewModel/BlogDashboardViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/SiteIconView.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Media/SiteMedia/SiteMediaViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationCommentDetailViewController.swift
  WordPress/Classes/ViewRelated/People/PeopleViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsBaseTableViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewModel.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Success card/Table View/MigrationSuccessCell.swift
Labels: iPad

#23595 Sidebar: Fix an issue with sidebar showing incorrect selection
  WordPress/Classes/System/SplitViewRootPresenter.swift
Labels: iPad

#23599 Reader: simplified ghost cells
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController+Ghost.swift
Labels: Reader

#23578 Display previously viewed screen when switching back to Site, Notification, and Reader
  WordPress/Classes/System/SplitViewRootPresenter+Notifications.swift
  WordPress/Classes/System/SplitViewRootPresenter+Reader.swift
  WordPress/Classes/System/SplitViewRootPresenter+Site.swift
  WordPress/Classes/System/SplitViewRootPresenter+Welcome.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SiteMenuViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: iPad

#23592 [Tooling] Automate Release Publishing
  .buildkite/release-pipelines/publish-release.yml
  Gemfile
  Gemfile.lock
  fastlane/lanes/build.rb
  fastlane/lanes/release.rb
Labels: Tooling

#23601 Fix a crash which may be caused by a nil WPAccount.email
  WordPress/Classes/Networking/WordPressClient.swift
Labels: [Type] Bug

#23605 Sidebar: Global Reader Navigation
  WordPress/Classes/System/MySitesCoordinator+RootViewPresenter.swift
  WordPress/Classes/System/RootViewPresenter.swift
  WordPress/Classes/System/SplitViewRootPresenter+Reader.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/System/StaticScreensTabBarWrapper.swift
  WordPress/Classes/System/WordPressAppDelegate+openURL.swift
  WordPress/Classes/Utility/Spotlight/SearchManager.swift
  WordPress/Classes/Utility/Universal Links/Routes+MySites.swift
  WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/DashboardPromptsCardCell.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Navigation/ReaderNavigationPath.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
  WordPress/Classes/ViewRelated/System/Coordinators/ReaderCoordinator.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController.h
  WordPress/Classes/ViewRelated/System/WPTabBarController.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Reader, iPad

#23597 Fix issues with user profile pictures in Reader
  WordPress/Classes/Utility/Media/ImageView.swift
  WordPress/Classes/Utility/Media/ImageViewController.swift
  WordPress/Classes/Utility/Media/MemoryCache.swift
  WordPress/Classes/Utility/Media/UIImageView+ImageDownloader.swift
  WordPress/Classes/ViewRelated/Gravatar/UIImageView+Gravatar.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPressAuthenticator/Sources/Signin/UIImageView+Additions.swift
Labels: Reader

#23589 Remove unused `release_management_in_ci.rb` lanes
  fastlane/Fastfile
  fastlane/lanes/release_management_in_ci.rb
Labels: Tooling

#23608 Sidebar: State restoration when switching to a split view mode
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Reader/Navigation/ReaderNavigationPath.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/WPTabBarController+ReaderTabNavigation.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SiteMenuViewController.swift
Labels: iPad

#23611 Sidebar: Minor Improvements
  WordPress/Classes/Stores/UserPersistentRepositoryUtility.swift
  WordPress/Classes/System/SplitViewRootPresenter+Site.swift
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/Utility/App Configuration/AppColor.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+SectionHelpers.swift
  WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewModel.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SiteMenuViewController.swift
Labels: iPad

#23617 Sidebar: Enable FF
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/UITests/Utils/XCTest+Extensions.swift
Labels: iPad

#23619 Update dark mode color
  WordPress/Classes/Utility/App Configuration/AppColor.swift
Labels: General

#23607 [Tooling] Don't cancel in-progress Issue Validation GitHub Action jobs
  .github/workflows/validate-issues.yml
Labels: Tooling

#23616 Refactor: Rename showPostTab
  WordPress/Classes/System/3DTouch/WP3DTouchShortcutHandler.swift
  WordPress/Classes/System/RootViewPresenter+EditorNavigation.swift
  WordPress/Classes/Utility/Universal Links/Route+Page.swift
  WordPress/Classes/Utility/Universal Links/Routes+Post.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+FAB.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabViewController.swift
  WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift
Labels: General, [Type] Tech Debt

#23621 Fix UIColor primary
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/Utility/App Configuration/AppColor.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Countries/Map/CountriesMapView.swift
  WordPress/JetpackStatsWidgets/Views/Cards/ListRow.swift
Labels: [Type] Bug

#23627 Sidebar: Enhance split view behavior
  WordPress/Classes/System/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Reader/ReaderSidebarViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SiteMenuViewController.swift
  WordPress/WordPressTest/MediaURLExporterTests.swift
Labels: iPad

#23635 Address a build failure in the tests because of unhandled `XCTSkip`
  WordPress/WordPressTest/MediaURLExporterTests.swift
Labels: Testing

#23637 Minor update to the log functions API
  WordPress/Classes/Extensions/UIImageView+SiteIcon.swift
  WordPress/Classes/Services/CommentService+Likes.swift
  WordPress/Classes/Services/Domains/DomainsService.swift
  WordPress/Classes/Services/GravatarService.swift
  WordPress/Classes/Services/PeopleService.swift
  WordPress/Classes/Services/PlanService.swift
  WordPress/Classes/Services/PostService+Likes.swift
  WordPress/Classes/Services/UsersService.swift
  WordPress/Classes/Stores/ActivityStore.swift
  WordPress/Classes/Stores/PluginStore.swift
  WordPress/Classes/Utility/AccountHelper.swift
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduler.swift
  WordPress/Classes/Utility/Logging/CocoaLumberjack.swift
  WordPress/Classes/Utility/Logging/WordPressLibraryLogger.swift
  WordPress/Classes/Utility/PingHubManager.swift
  WordPress/Classes/Utility/Universal Links/Routes+Reader.swift
  WordPress/Classes/ViewRelated/Blog/SharingButtonsViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergWeb/GutenbergWebNavigationViewController.swift
  WordPress/Classes/ViewRelated/Jetpack/Install/Webview/JetpackConnectionWebViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift
  WordPress/Classes/ViewRelated/Reader/Filter/FilterProvider.swift
  WordPress/Classes/ViewRelated/Reader/ReaderActionHelpers.swift
  WordPress/Classes/ViewRelated/Reader/ReaderPostCardCellViewModel.swift
  WordPress/Classes/ViewRelated/Reader/ReaderTagCell.swift
  WordPress/Classes/ViewRelated/Reader/Tab Navigation/ReaderTabItemsStore.swift
  WordPress/Jetpack/Classes/Utility/DataMigrator.swift
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
Labels: [Type] Tech Debt
