Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2025-05, with the labels that each got.

#24511 Fix how local Modules are added
  WordPress.xcworkspace/contents.xcworkspacedata
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24514 Remove duplicated SFHFKeychainUtils dependency from WordPressUnitTests
  Modules/Package.swift
Labels: Testing

#24519 Add missing NSURL-IDN package
  Modules/Package.swift
Labels: General

#24517 Remove unused `WPDATA` preprocessor macro
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Tech Debt

#24522 Application passwords reauthentication flow
  Modules/Package.swift
  Sources/WordPressData/Swift/Blog+SelfHosted.swift
  Tests/KeystoneTests/Tests/Models/Blog+RestAPITests.swift
  Tests/KeystoneTests/Tests/Services/UserListViewModelTests.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/Login/ApplicationPasswordReAuthenticationView.swift
  WordPress/Classes/Login/SelfHostedSiteAuthenticator.swift
  WordPress/Classes/Networking/WordPressClient.swift
  WordPress/Classes/Plugins/Views/InstalledPluginsListView.swift
  WordPress/Classes/Users/ViewModel/UserListViewModel.swift
  WordPress/Classes/Users/Views/UserListView.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackConnectionViewModel.swift
  WordPress/Classes/ViewRelated/NUX/Helpers/WordPressAuthenticationManager.swift
Labels: Login, Self-hosted

#24525 Point NSURL-IDN package to version using "-" instead of "+"
  Modules/Package.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Tooling

#24526 [Tooling] Remove leftover references to Cocoapods
  WordPress/WordPress.xcodeproj/project.pbxproj
  fastlane/lanes/release.rb
Labels: Tooling

#24528 Address a few warnings in WordPressData
  Sources/WordPressData/Objective-C/ReaderPost.m
  Sources/WordPressData/Swift/Media.swift
Labels: [Type] Tech Debt, Tech Debt

#24527 Add/more error logging
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardService.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
Labels: [Type] Bug, User Feedback

#24531 Cherry pick #24525 into 25.9 release branch
  Modules/Package.swift
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Tooling

#24518 Reset Modules as an Xcode local package with tests in CI
  .buildkite/commands/complete-code-freeze.sh
  .buildkite/commands/shared-set-up.sh
  .gitignore
  Modules/Package.resolved
  Modules/Package.swift
  Modules/Tests/WordPressFluxTests/WordPressFluxTests.xctestplan
  Tests/KeystoneTests/WordPressUnitTests.xctestplan
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/OCLint.xcscheme
Labels: Testing

#24515 feat: GutenbergKit internationalization
  Modules/Package.resolved
  Modules/Package.swift
  WordPress/Classes/ViewRelated/NewGutenberg/NewGutenbergViewController.swift
Labels: [Type] Enhancement, i18n, Gutenberg

#24539 Merge 25.9 release notes to trunk
  WordPress/Jetpack/Resources/AppStoreStrings.po
  WordPress/Jetpack/Resources/release_notes.txt
  WordPress/Resources/AppStoreStrings.po
  WordPress/Resources/release_notes.txt
Labels: Releases

#24542 Post account change notification from the main thread
  Sources/WordPressData/Swift/WPAccount+RestApi.swift
Labels: [Type] Bug

#24540 Implement a wordpress-rs backed MediaServiceRemote
  Modules/Package.resolved
  Modules/Package.swift
  Sources/WordPressData/Objective-C/Blog.m
  Sources/WordPressData/Swift/Blog+SelfHosted.swift
  WordPress/Classes/Networking/WordPressClient.swift
  WordPress/Classes/Services/MediaRepository.swift
  WordPress/Classes/Services/MediaService.m
  WordPress/Classes/Services/MediaServiceRemoteCoreREST.swift
Labels: Media, Self-hosted

#24513 Add Subscribers screen
  Modules/Package.resolved
  Modules/Package.swift
  Modules/Sources/DesignSystem/Foundation/AppColor.swift
  Modules/Sources/UITestsFoundation/Screens/MySiteMoreMenuScreen.swift
  Modules/Sources/UITestsFoundation/Screens/PeopleScreen.swift
  Modules/Sources/UITestsFoundation/Screens/UsersScreen.swift
  Modules/Sources/WordPressUI/Views/LoadMoreFooterView.swift
  RELEASE-NOTES.txt
  WordPress/Classes/Extensions/EmptyStateView+Extensions.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/SharedStrings.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Strings.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Swift.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Blog/Subscribers/Details/SubscriberDetailsHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/Details/SubscriberDetailsView.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/Details/SubsriberDetailsViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/Helpers/SubscribersBlog.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/Helpers/SubscribersServiceRemote+Extensions.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/Invite/SubscriberInviteView.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/List/SubscriberRowView.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/List/SubscribersMenu.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/List/SubscribersPaginatedResponse.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/List/SubscribersView.swift
  WordPress/Classes/ViewRelated/Blog/Subscribers/List/SubscribersViewModel.swift
  WordPress/Classes/ViewRelated/People/Controllers/InvitePersonViewController.swift
  WordPress/Classes/ViewRelated/People/Controllers/PeopleViewController.swift
  WordPress/Classes/ViewRelated/Stats/Subscribers/StatsSubscribersStore.swift
  WordPress/Classes/ViewRelated/Stats/Subscribers/StatsSubscribersViewController.swift
  WordPress/Classes/ViewRelated/Stats/Subscribers/StatsSubscribersViewModel.swift
  WordPress/UITests/Tests/MySiteTests.swift
Labels: People Management, My Site

#24543 [Tooling] Skip jobs if there are no relevant code changes
  .buildkite/commands/build-for-testing.sh
  .buildkite/commands/lint-localized-strings-format.sh
  .buildkite/commands/prototype-build-jetpack.sh
  .buildkite/commands/prototype-build-wordpress.sh
  .buildkite/commands/run-ui-tests.sh
  .buildkite/commands/run-unit-tests-reader.sh
  .buildkite/commands/run-unit-tests.sh
  .buildkite/commands/should-skip-job.sh
  .buildkite/pipeline.yml
  .buildkite/shared-pipeline-vars
Labels: Tooling

#24487 Remove long-unused Iterable deep links handling
  Sources/Reader/Reader.entitlements
  WordPress/Classes/System/Root View/WPTabBarController+RootViewPresenter.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Jetpack/JetpackDebug.entitlements
  WordPress/Jetpack/JetpackRelease-Alpha.entitlements
  WordPress/Jetpack/JetpackRelease.entitlements
  WordPress/WordPress-Alpha.entitlements
  WordPress/WordPress.entitlements
Labels: [Type] Enhancement, Enhancement

#24558 Fix 25.9 localization
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/bg.lproj/Localizable.strings
  WordPress/Resources/cs.lproj/Localizable.strings
  WordPress/Resources/cy.lproj/Localizable.strings
  WordPress/Resources/da.lproj/Localizable.strings
  WordPress/Resources/de.lproj/Localizable.strings
  WordPress/Resources/en-AU.lproj/Localizable.strings
  WordPress/Resources/en-CA.lproj/Localizable.strings
  WordPress/Resources/en-GB.lproj/Localizable.strings
  WordPress/Resources/en.lproj/Localizable.strings
  WordPress/Resources/es.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/hr.lproj/Localizable.strings
  WordPress/Resources/hu.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/is.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/nb.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/pl.lproj/Localizable.strings
  WordPress/Resources/pt-BR.lproj/Localizable.strings
  WordPress/Resources/pt.lproj/Localizable.strings
  WordPress/Resources/ro.lproj/Localizable.strings
  WordPress/Resources/ru.lproj/Localizable.strings
  WordPress/Resources/sk.lproj/Localizable.strings
  WordPress/Resources/sq.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/Resources/th.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  WordPress/Resources/zh-Hant.lproj/Localizable.strings
  fastlane/lanes/localization.rb
Labels: Localization

#24560 Merge `25.9` final to `trunk`
  WordPress/Resources/ar.lproj/Localizable.strings
  WordPress/Resources/bg.lproj/Localizable.strings
  WordPress/Resources/cs.lproj/Localizable.strings
  WordPress/Resources/cy.lproj/Localizable.strings
  WordPress/Resources/da.lproj/Localizable.strings
  WordPress/Resources/de.lproj/Localizable.strings
  WordPress/Resources/en-AU.lproj/Localizable.strings
  WordPress/Resources/en-CA.lproj/Localizable.strings
  WordPress/Resources/en-GB.lproj/Localizable.strings
  WordPress/Resources/es.lproj/Localizable.strings
  WordPress/Resources/fr.lproj/Localizable.strings
  WordPress/Resources/he.lproj/Localizable.strings
  WordPress/Resources/hr.lproj/Localizable.strings
  WordPress/Resources/hu.lproj/Localizable.strings
  WordPress/Resources/id.lproj/Localizable.strings
  WordPress/Resources/is.lproj/Localizable.strings
  WordPress/Resources/it.lproj/Localizable.strings
  WordPress/Resources/ja.lproj/Localizable.strings
  WordPress/Resources/ko.lproj/Localizable.strings
  WordPress/Resources/nb.lproj/Localizable.strings
  WordPress/Resources/nl.lproj/Localizable.strings
  WordPress/Resources/pl.lproj/Localizable.strings
  WordPress/Resources/pt-BR.lproj/Localizable.strings
  WordPress/Resources/pt.lproj/Localizable.strings
  WordPress/Resources/ro.lproj/Localizable.strings
  WordPress/Resources/ru.lproj/Localizable.strings
  WordPress/Resources/sk.lproj/Localizable.strings
  WordPress/Resources/sq.lproj/Localizable.strings
  WordPress/Resources/sv.lproj/Localizable.strings
  WordPress/Resources/th.lproj/Localizable.strings
  WordPress/Resources/tr.lproj/Localizable.strings
  WordPress/Resources/zh-Hans.lproj/Localizable.strings
  WordPress/Resources/zh-Hant.lproj/Localizable.strings
  config/Version.public.xcconfig
  fastlane/jetpack_metadata/es-ES/release_notes.txt
  fastlane/jetpack_metadata/he/release_notes.txt
  fastlane/jetpack_metadata/id/release_notes.txt
  fastlane/jetpack_metadata/it/release_notes.txt
  fastlane/jetpack_metadata/nl-NL/release_notes.txt
  fastlane/jetpack_metadata/sv/release_notes.txt
  fastlane/metadata/he/release_notes.txt
  fastlane/metadata/id/release_notes.txt
  fastlane/metadata/it/release_notes.txt
  fastlane/metadata/ru/release_notes.txt
Labels: Releases

#24548 Delete pre-saved local comment when the server fails to create a comment
  WordPress/Classes/Services/CommentService.m
Labels: [Type] Bug

#24565 Add secrets to JetpackStatsWidgets
  Scripts/BuildPhases/GenerateCredentials.sh
  Sources/JetpackStatsWidgets/Sources/StatsWidgets.swift
  WordPress/JetpackIntents/IntentHandler.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressShareExtension/Sources/UI/MainShareViewController.swift
Labels: [Type] Bug

#24561 Show an card to prompt application password authentication
  Modules/Package.resolved
  Modules/Package.swift
  Sources/WordPressData/Swift/Blog+SelfHosted.swift
  Tests/KeystoneTests/Tests/Models/Blog+RestAPITests.swift
  WordPress/Classes/Login/ApplicationPasswordReAuthenticationView.swift
  WordPress/Classes/Login/ApplicationPasswordRequiredView.swift
  WordPress/Classes/Login/SelfHostedSiteAuthenticator.swift
  WordPress/Classes/Networking/WordPressClient.swift
  WordPress/Classes/Services/CommentServiceRemoteFactory.swift
  WordPress/Classes/Services/MediaRepository.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/ApplicationPasswordAuthenticationCard.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Swift.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.h
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
Labels: Login
