Repository wordpress-mobile/WordPress-iOS, pull requests merged in 2025-03, with the labels that each got.

#24134 Fix notification settings issues and add settings to Site Details
  RELEASE-NOTES.txt
  WordPress/Classes/Models/ReaderSiteTopic.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSiteSubscriptionViewController.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderStreamViewController+Sharing.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Headers/ReaderSiteHeaderView.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionCell.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionHelper.swift
  WordPress/Classes/ViewRelated/Reader/Subscriptions/ReaderSubscriptionNotificationSettingsButton.swift
Labels: Reader

#24135 Fix an issue with P2 sites and follow conversation
  RELEASE-NOTES.txt
  WordPress/Classes/Models/ReaderPost+Swift.swift
  WordPress/Classes/Services/FollowCommentsService.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsHeader.swift
Labels: Reader

#24137 Fix missing featured images in Reader
  Modules/Package.swift
  RELEASE-NOTES.txt
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderPostCellViewModel.swift
Labels: Reader

#24136 Add WKWebView warmup
  WordPress/Classes/Extensions/WKWebView+UserAgent.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
Labels: Comments

#24139 More Reader Comments Improvements
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Comments/Controllers/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Comments/Controllers/Editor/CommentComposerReplyCommentView.swift
  WordPress/Classes/ViewRelated/Comments/Views/Detail/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/Views/Detail/CommentContentTableViewCell.xib
  WordPress/Classes/ViewRelated/Notifications/Views/CommentLargeButton.swift
  WordPress/Classes/ViewRelated/People/Controllers/PeopleViewController.swift
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderPostCell.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.h
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
  WordPress/Classes/ViewRelated/Reader/User/ReaderUserProfileView.swift
Labels: Reader

#24143 Comments: minor changes
  WordPress/Classes/ViewRelated/Comments/Views/Detail/CommentContentTableViewCell.swift
Labels: Comments

#24150 Fix ReaderReadMoreView gradient
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderReadMoreView.swift
Labels: Reader

#24155 Revert "Convert `ReaderGapMarker` no-op subclass to Swift"
  WordPress/Classes/Models/ReaderGapMarker.h
  WordPress/Classes/Models/ReaderGapMarker.m
  WordPress/Classes/Models/ReaderGapMarker.swift
  WordPress/Classes/Services/Reader Post/ReaderPostService.m
  WordPress/Classes/System/WordPress-Bridging-Header.h
Labels: Reader

#24100 Change if statements to switch-case statements
  WordPress/Classes/Plugins/Views/AddNewPluginView.swift
  WordPress/Classes/Plugins/Views/PluginDetailsView.swift
Labels: Self-hosted

#24156 Remove CocoaPods checks from releases
  fastlane/lanes/release.rb
Labels: Tooling, Releases

#24146 Rewrite remaining parts of ReaderCommentsViewController in Swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/Utility/ContentCoordinator.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationCommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsTableViewController.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.h
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.m
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderPostActions/ReaderCommentAction.swift
Labels: Comments

#24154 Remove an unused `Coordinate` model
  WordPress/Classes/Models/Coordinate.h
  WordPress/Classes/Models/Coordinate.m
  WordPress/Classes/Models/ValueTransformers.swift
  WordPress/Classes/Services/PostService.m
  WordPress/Classes/System/WordPress-Bridging-Header.h
Labels: [Type] Enhancement

#24157 Move `WPException` to `WordPressSharedObjC`
  Modules/Sources/WordPressSharedObjC/ErrorHandling/WPException.m
  Modules/Sources/WordPressSharedObjC/include/WPException.h
  WordPress/Classes/Utility/WPTableViewHandler.m
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
Labels: [Type] Enhancement

#24160 Remove WPRichContentView
  Modules/Sources/AsyncImageKit/Views/AsyncImageView.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/NSAttributedString+WPRichText.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPHorizontalRuleAttachment.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextEmbed.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextFormatter.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextImage.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPRichTextMediaAttachment.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachment.swift
  WordPress/Classes/ViewRelated/Views/WPRichText/WPTextAttachmentManager.swift
  WordPress/Resources/HTML/richEmbedScript.js
  WordPress/Resources/HTML/richEmbedTemplate.html
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ViewRelated/Views/WPRichText/WPRichContentViewTests.swift
  WordPress/WordPressTest/ViewRelated/Views/WPRichText/WPRichTextFormatterTests.swift
Labels: Reader

#24161 Remove unused More alert in Gutenberg
  WordPress/Classes/Utility/Analytics/WPAnalyticsEvent.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+MoreActions.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift
Labels: Gutenberg

#24168 Remove unused Plans code
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Plans/Controllers/PlanComparisonViewController.swift
  WordPress/Classes/ViewRelated/Plans/Controllers/PlanDetailViewController.swift
  WordPress/Classes/ViewRelated/Plans/Controllers/PlanListViewController.swift
  WordPress/Classes/ViewRelated/Plans/Plans.storyboard
  WordPress/Classes/ViewRelated/Plans/ViewModels/FeatureItemRow.swift
  WordPress/Classes/ViewRelated/Plans/ViewModels/PlanDetailViewModel.swift
  WordPress/Classes/ViewRelated/Plans/ViewModels/PlanListRow.swift
  WordPress/Classes/ViewRelated/Plans/ViewModels/PlanListViewModel.swift
  WordPress/Classes/ViewRelated/Plans/Views/FeatureItemCell.swift
  WordPress/Classes/ViewRelated/Plans/Views/PlansLoadingIndicatorView.swift
  WordPress/Classes/ViewRelated/System/PagedViewController.swift
  WordPress/Classes/ViewRelated/System/PagedViewController.xib
  WordPress/Resources/AppImages.xcassets/plan-business-loading.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/plan-business-loading.imageset/plan-business-loading.pdf
  WordPress/Resources/AppImages.xcassets/plan-free-loading.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/plan-free-loading.imageset/plan-free-loading.pdf
  WordPress/Resources/AppImages.xcassets/plan-placeholder.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/plan-placeholder.imageset/plan-placeholder.pdf
  WordPress/Resources/AppImages.xcassets/plan-premium-loading.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/plan-premium-loading.imageset/plan-premium-loading.pdf
Labels: General

#24169 Fix WPException compilation
  Modules/Sources/WordPressSharedObjC/Utility/WPException.m
  Modules/Sources/WordPressSharedObjC/WordPressShared.h
  WordPress/Classes/Utility/CoreData/CoreDataHelper.swift
  WordPress/Classes/Utility/CoreData/TaggedManagedObjectID.swift
  WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsTableViewDelegate.swift
Labels: General

#24175 Remove EditCommentViewController
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Comments/Controllers/EditCommentViewController.h
  WordPress/Classes/ViewRelated/Comments/Controllers/EditCommentViewController.m
  WordPress/Classes/ViewRelated/Comments/Views/EditCommentViewController.xib
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
Labels: General

#24073 Remove Garamond from the WordPress app
  WordPress/Classes/ViewRelated/NUX/Controllers/SplashPrologue/SplashPrologueStyleGuide.swift
  WordPress/Fonts/EBGaramond-Regular.ttf
  WordPress/Fonts/OFL - EBGaramond-Regular.txt
  WordPress/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Tech Debt

#24174 Remove WPAnimatedBox
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/ViewRelated/Views/NoResultsViewController.swift
  WordPress/Classes/ViewRelated/Views/WPAnimatedBox.h
  WordPress/Classes/ViewRelated/Views/WPAnimatedBox.m
  WordPress/Resources/AppImages.xcassets/animatedBox.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/animatedBox.imageset/animatedBox-1.pdf
  WordPress/Resources/AppImages.xcassets/animatedBox.imageset/animatedBox-dark.pdf
  WordPress/Resources/AppImages.xcassets/animatedBoxBack.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/animatedBoxBack.imageset/animatedBoxBack-dark.pdf
  WordPress/Resources/AppImages.xcassets/animatedBoxBack.imageset/animatedBoxBack.pdf
  WordPress/Resources/AppImages.xcassets/animatedBoxPage1.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/animatedBoxPage1.imageset/animatedBoxPage1-dark.pdf
  WordPress/Resources/AppImages.xcassets/animatedBoxPage1.imageset/animatedBoxPage1.pdf
  WordPress/Resources/AppImages.xcassets/animatedBoxPage2.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/animatedBoxPage2.imageset/animatedBoxPage2-dark.pdf
  WordPress/Resources/AppImages.xcassets/animatedBoxPage2.imageset/animatedBoxPage2.pdf
  WordPress/Resources/AppImages.xcassets/animatedBoxPage3.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/animatedBoxPage3.imageset/animatedBoxPage3-dark.pdf
  WordPress/Resources/AppImages.xcassets/animatedBoxPage3.imageset/animatedBoxPage3.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressDraftActionExtension/WordPressDraftActionExtension-Bridging-Header.h
  WordPress/WordPressShareExtension/WordPressShare-Bridging-Header.h
Labels: General

#24177 Remove unused notification content extension
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/NotificationSupportService.swift
  WordPress/Classes/System/Constants/Constants.h
  WordPress/Classes/System/Constants/Constants.m
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressNotificationContentExtension/Info-Alpha.plist
  WordPress/WordPressNotificationContentExtension/Info-Internal.plist
  WordPress/WordPressNotificationContentExtension/Info.plist
  WordPress/WordPressNotificationContentExtension/Sources/NotificationViewController.swift
  WordPress/WordPressNotificationContentExtension/Sources/Tracks/Tracks+ContentExtension.swift
  WordPress/WordPressNotificationContentExtension/Sources/Views/NotificationContentView.swift
  WordPress/WordPressNotificationContentExtension/Sources/WordPressNotificationContentExtension-Bridging-Header.h
  WordPress/WordPressNotificationContentExtension/WordPressNotificationContentExtension-Alpha.entitlements
  WordPress/WordPressNotificationContentExtension/WordPressNotificationContentExtension-Internal.entitlements
  WordPress/WordPressNotificationContentExtension/WordPressNotificationContentExtension.entitlements
Labels: General

#24178 Remove some unused icons
  WordPress/Jetpack/AppImages.xcassets/Login Empty State/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Login Empty State/jetpack-empty-state-illustration.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Login Empty State/jetpack-empty-state-illustration.imageset/jetpack-empty-state-dark.pdf
  WordPress/Jetpack/AppImages.xcassets/Login Empty State/jetpack-empty-state-illustration.imageset/jetpack-empty-state-light.pdf
  WordPress/Jetpack/AppImages.xcassets/Prologue/circle-particle.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Prologue/circle-particle.imageset/circle-particle.pdf
  WordPress/Jetpack/AppImages.xcassets/Tab Bar/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Tab Bar/icon-tab-notifications-unread-jetpack.imageset/Contents.json
  WordPress/Jetpack/AppImages.xcassets/Tab Bar/icon-tab-notifications-unread-jetpack.imageset/icon-tab-notifications-unread-muriel-dark.pdf
  WordPress/Jetpack/AppImages.xcassets/Tab Bar/icon-tab-notifications-unread-jetpack.imageset/icon-tab-notifications-unread-muriel.pdf
  WordPress/Resources/AppImages.xcassets/illustration-posts.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/illustration-posts.imageset/illustration-posts.pdf
Labels: General

#23748 [UI Tests] Re-enable Reader tests
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_sites_106707880_posts_439_likes.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/posts/rest_sites_106707880_posts_439_related.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/reader_tags.json
  API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/reader/reader_tags_follow.json
  Modules/Sources/UITestsFoundation/Screens/CommentsScreen.swift
  Modules/Sources/UITestsFoundation/Screens/ReaderMenuScreen.swift
  Modules/Sources/UITestsFoundation/Screens/ReaderScreen.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderDiscoverViewController.swift
  WordPress/UITests/Tests/ReaderTests.swift
Labels: Testing

#24183 Remove more dead code
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockActionsTableViewCell.xib
  WordPress/Classes/ViewRelated/Views/VerticallyStackedButton.h
  WordPress/Classes/ViewRelated/Views/VerticallyStackedButton.m
Labels: General

#24184 Remove NoteBlockCommentTableViewCell and related code
  WordPress/Classes/Extensions/UIAlertController+Helpers.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Style/WPStyleGuide+Notifications.swift
  WordPress/Classes/ViewRelated/Notifications/Views/LongPressGestureLabel.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.swift
  WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockCommentTableViewCell.xib
Labels: General

#24185 Move AsyncOperation and AsyncBlockOperation to WordPressShared
  Modules/Sources/WordPressShared/AsyncOperation/AsyncBlockOperation.swift
  Modules/Sources/WordPressShared/AsyncOperation/AsyncOperation.swift
  Modules/Tests/WordPressSharedTests/AsyncOperationTests.swift
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/NotificationSyncMediator.swift
  WordPress/Classes/Stores/RemoteFeatureFlagStore.swift
  WordPress/Classes/Utility/CoreData/ContextManager.swift
  WordPress/Classes/ViewRelated/Stats/Operation/StatsPeriodAsyncOperation.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#24193 Remove `Constants.h` import from `Blog`
  WordPress/Classes/Models/Blog/Blog.m
Labels: Core Data

#24196 Move `KeyValueDatabase` to WordPressShared
  Modules/Sources/WordPressShared/Utility/KeyValueDatabase.swift
  WordPress/Classes/Services/MediaSettings.swift
  WordPress/Classes/Services/NullBlogPropertySanitizer.swift
  WordPress/Classes/Services/RecentSitesService.swift
  WordPress/Classes/Stores/UserPersistentRepository.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlagOverrideStore.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlagRolloutStore.swift
  WordPress/Classes/Utility/BuildInformation/RemoteConfigOverrideStore.swift
  WordPress/Classes/Utility/Editor/GutenbergRollout.swift
  WordPress/Classes/Utility/Editor/GutenbergSettings.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderCSS.swift
  WordPress/Classes/ViewRelated/Reader/Views/ReaderInterestsCoordinator.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/BlogListViewModelTests.swift
  WordPress/WordPressTest/EditorSettingsServiceTests.swift
  WordPress/WordPressTest/FeatureFlagTests.swift
  WordPress/WordPressTest/GutenbergSettingsTests.swift
  WordPress/WordPressTest/MediaSettingsTests.swift
  WordPress/WordPressTest/NullBlogPropertySanitizerTests.swift
  WordPress/WordPressTest/NullMockUserDefaults.swift
  WordPress/WordPressTest/ReaderCSSTests.swift
  WordPress/WordPressTest/ReaderSelectInterestsCoordinatorTests.swift
  WordPress/WordPressTest/RecentSitesServiceTests.swift
Labels: Core Data

#24192 Extract SFHFKeychainUtils to dedicated Swift package
  Modules/Package.swift
  Modules/Sources/SFHFKeychainUtils/SFHFKeychainUtils.m
  Modules/Sources/SFHFKeychainUtils/include/SFHFKeychainUtils.h
  WordPress/Classes/Models/Blog/Blog.m
  WordPress/Classes/Models/WPAccount.m
  WordPress/Classes/Services/CredentialsService.swift
  WordPress/Classes/Services/NotificationSupportService.swift
  WordPress/Classes/Services/ShareExtensionService.swift
  WordPress/Classes/Stores/StatsWidgetsStore.swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/FormattableContent/Actions/FormattableContentActionCommand.swift
  WordPress/Classes/Utility/FormattableContent/FormattableContentStyles.swift
  WordPress/Classes/Utility/KeychainUtils.swift
  WordPress/Classes/Utility/Migrations/10-11/BlogToAccount.m
  WordPress/Classes/Utility/Migrations/10-11/BlogToJetpackAccount.m
  WordPress/Classes/Utility/Migrations/32-33/BlogToBlog32to33.swift
  WordPress/Classes/ViewRelated/Aztec/Extensions/FormatBarItemProviders.swift
  WordPress/Classes/ViewRelated/Aztec/Extensions/TextList+WordPress.swift
  WordPress/Classes/ViewRelated/NUX/Helpers/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationTextContent.swift
  WordPress/JetpackStatsWidgets/Remote service/StatsWidgetsService.swift
  WordPress/JetpackStatsWidgets/Supporting Files/JetpackStatsWidgets-Bridging-Header.h
  WordPress/Shared/SharePost.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressDraftActionExtension/WordPressDraftActionExtension-Bridging-Header.h
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressNotificationServiceExtension/Sources/WordPressNotificationServiceExtension-Bridging-Header.h
  WordPress/WordPressShareExtension/UINavigationController+Extensions.swift
  WordPress/WordPressShareExtension/WordPressShare-Bridging-Header.h
  WordPress/WordPressTest/KeychainTest.m
  WordPress/WordPressTest/KeychainUtilsTests.swift
Labels: Core Data

#24198 Remove unused code
  WordPress/Classes/System/3D Touch/WP3DTouchShortcutCreator.swift
  WordPress/Classes/System/Constants/Constants.h
  WordPress/Classes/System/Constants/Constants.m
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/ViewRelated/NUX/Helpers/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/System/WPTabBarController+Swift.swift
  WordPress/Jetpack/AppConfiguration.swift
  WordPress/Jetpack/AppConstants.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24200 [25.8] Fix highlighted comment design
  WordPress/Classes/ViewRelated/Comments/Views/Detail/CommentContentTableViewCell.swift
  WordPress/Classes/ViewRelated/Comments/Views/Detail/CommentContentTableViewCell.xib
Labels: Comments

#24202 Remove FetureFlags from app extensions
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24203 Extract TextBundle module
  Modules/Package.swift
  Modules/Sources/TextBundle/TextBundleWrapper.m
  Modules/Sources/TextBundle/include/TextBundleWrapper.h
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressDraftActionExtension/WordPressDraft-Lumberjack.m
  WordPress/WordPressDraftActionExtension/WordPressDraftActionExtension-Bridging-Header.h
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressShareExtension/WordPressShare-Bridging-Header.h
  WordPress/WordPressShareExtension/WordPressShare-Lumberjack.m
Labels: General

#24207 Move a few utils shared with data layer to WordPressShared
  Modules/Sources/WordPressShared/Utility/FileManager+FolderSize.swift
  Modules/Sources/WordPressShared/Utility/URL+IncrementalFileName.swift
  Modules/Tests/WordPressSharedTests/URLIncrementalFilenameTests.swift
  WordPress/Classes/Extensions/URL+Helpers.swift
  WordPress/Classes/Utility/Media/MediaFileManager.swift
Labels: Core Data

#24209 Update `.editorconfig` to indent Swift with 4 spaces outside Xcode
  .editorconfig
Labels: Tooling

#24219 Remove unused values from Constants.h
  WordPress/Classes/System/Constants/Constants.h
  WordPress/Classes/System/Constants/Constants.m
Labels: General

#24220 Remove feature flags from conditionally included AppConfiguration file
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Classes/Utility/AppIcon.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+SectionHelpers.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/AddSiteController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/NUX/Helpers/WordPressAuthenticationManager.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/System/Fancy Alerts/FancyAlertViewController+AppIcons.swift
  WordPress/Jetpack/AppConfiguration.swift
Labels: General

#24221 JetpackStatsWidgets
  Modules/Sources/JetpackStatsWidgetsCore/Model/AllTimeWidgetStats.swift
  Modules/Sources/JetpackStatsWidgetsCore/Model/HomeWidgetAllTimeData.swift
  Modules/Sources/JetpackStatsWidgetsCore/Model/HomeWidgetThisWeekData.swift
  Modules/Sources/JetpackStatsWidgetsCore/Model/HomeWidgetTodayData.swift
  Modules/Sources/JetpackStatsWidgetsCore/Model/TodayWidgetStats.swift
  Modules/Sources/JetpackStatsWidgetsCore/WidgetStatsConfiguration.swift
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/Stores/StatsWidgetsStore.swift
  WordPress/Classes/Utility/Analytics/WidgetAnalytics.swift
  WordPress/Classes/ViewRelated/Widgets/WidgetCenter+JetpackWidgets.swift
  WordPress/JetpackIntents/SitesDataProvider.swift
  WordPress/JetpackStatsWidgets/Helpers/WidgetDataReader.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/Configs/LockScreenAllTimePostsBestViewsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/Configs/LockScreenAllTimeViewsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/Configs/LockScreenAllTimeViewsVisitorsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/Configs/LockScreenStatsWidgetConfig.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/Configs/LockScreenTodayLikesCommentsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/Configs/LockScreenTodayViewsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/Configs/LockScreenTodayViewsVisitorsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/LockScreenSiteListProvider.swift
  WordPress/JetpackStatsWidgets/Model/AllTimeWidgetStats.swift
  WordPress/JetpackStatsWidgets/Model/HomeWidgetAllTimeData.swift
  WordPress/JetpackStatsWidgets/Model/HomeWidgetThisWeekData.swift
  WordPress/JetpackStatsWidgets/Model/HomeWidgetTodayData.swift
  WordPress/JetpackStatsWidgets/Model/TodayWidgetStats.swift
  WordPress/JetpackStatsWidgets/Remote service/StatsWidgetsService.swift
  WordPress/JetpackStatsWidgets/SiteListProvider.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetAllTime.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetThisWeek.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetToday.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/Classes/Stores/StatsWidgetsStoreTests.swift
Labels: General

#24218 Remove WPAppGroupName and WPAppKeychainAccessGroup from Constants.h (Part 2)
  Modules/Package.swift
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/NotificationSupportService.swift
  WordPress/Classes/Stores/StatsWidgetsStore.swift
  WordPress/Classes/System/Constants/Constants.h
  WordPress/Classes/System/Constants/Constants.m
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduler.swift
  WordPress/Classes/Utility/Migration/ContentMigrationCoordinator.swift
  WordPress/Jetpack/Classes/Utility/DataMigrator.swift
  WordPress/Jetpack/Classes/Utility/SharedDataIssueSolver.swift
  WordPress/JetpackIntents/Info.plist
  WordPress/JetpackIntents/SitesDataProvider.swift
  WordPress/JetpackStatsWidgets/Helpers/WidgetDataReader.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/LockScreenSiteListProvider.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/LockScreenStatsWidget.swift
  WordPress/JetpackStatsWidgets/Model/HomeWidgetData.swift
  WordPress/JetpackStatsWidgets/Remote service/StatsWidgetsService.swift
  WordPress/JetpackStatsWidgets/SiteListProvider.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetAllTime.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetThisWeek.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetToday.swift
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/MainShareViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
  WordPress/WordPressShareExtension/ShareMediaFileManager.swift
  WordPress/WordPressShareExtension/SharedCoreDataStack.swift
Labels: General

#24224 Move pushNotificationAppID to BuildSettings
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  WordPress/Classes/Services/NotificationSettingsService.swift
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Info.plist
  WordPress/Jetpack/AppConstants.swift
  WordPress/Jetpack/Info.plist
  config/Jetpack.alpha.xcconfig
  config/Jetpack.debug.xcconfig
  config/Jetpack.release.xcconfig
  config/WordPress.alpha.xcconfig
  config/WordPress.debug.xcconfig
  config/WordPress.release.xcconfig
Labels: General

#24225 Remove BuildConfiguration.testingOverride
  WordPress/Classes/Utility/BuildInformation/BuildConfiguration.swift
  WordPress/WordPressTest/GutenbergSettingsTests.swift
Labels: General

#24226 Remove bridging headers from app extensions
  WordPress/Classes/Utility/FormattableContent/FormattableRangesFactory.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/FormattableCommentContent.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/FormattableUserContent.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationContentFactory.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Ranges/FormattableNoticonRange.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Ranges/NotificationCommentRange.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Ranges/NotificationContentRange.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Ranges/NotificationContentRangeFactory.swift
  WordPress/JetpackIntents/Supporting Files/JetpackIntents-Bridging-Header.h
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressDraftActionExtension/WordPressDraftActionExtension-Bridging-Header.h
  WordPress/WordPressNotificationServiceExtension/Sources/WordPressNotificationServiceExtension-Bridging-Header.h
  WordPress/WordPressShareExtension/WordPressShare-Bridging-Header.h
  WordPress/WordPressTest/WordPressTest-Prefix.pch
Labels: General

#24229 Remove tests for deleted 91 to 92 Core Data migration
  WordPress/WordPressTest/CoreDataMigrationTests.m
Labels: Testing, Core Data

#24223 Move AppLocalizedString to WordPressShared
  Modules/Sources/WordPressShared/Utility/AppLocalizedString.swift
  WordPress/Classes/Utility/FormattableContent/Actions/FormattableContentAction.swift
  WordPress/Classes/ViewRelated/Aztec/Extensions/FormatBarItemProviders.swift
  WordPress/Classes/ViewRelated/Aztec/Extensions/TextList+WordPress.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/Double+Stats.swift
  WordPress/Classes/ViewRelated/Views/List/NotificationsList/NotificationsTableViewCellContent.swift
  WordPress/JetpackStatsWidgets/Model/GroupedViewData.swift
  WordPress/JetpackStatsWidgets/Model/ListViewData.swift
  WordPress/JetpackStatsWidgets/Views/Cards/FlexibleCard.swift
  WordPress/JetpackStatsWidgets/Views/Cards/ListRow.swift
  WordPress/JetpackStatsWidgets/Views/Cards/LockScreenFlexibleCard.swift
  WordPress/JetpackStatsWidgets/Views/Cards/LockScreenVerticalCard.swift
  WordPress/JetpackStatsWidgets/Views/Cards/VerticalCard.swift
  WordPress/JetpackStatsWidgets/Views/Localization/LocalizableStrings.swift
  WordPress/JetpackStatsWidgets/Views/MultiStatsView.swift
  WordPress/JetpackStatsWidgets/Views/UnconfiguredView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressShareExtension/ShareData.swift
  WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressShareExtension/ShareNoticeConstants.swift
Labels: General

#24235 Remove remaining internal build references
  WordPress/Classes/Services/Page Layouts/PageLayoutService.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/BuildInformation/BuildConfiguration.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackRedirector.swift
  WordPress/Classes/ViewRelated/NUX/Helpers/WordPressAuthenticationManager.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24236 Move `URL` helpers to WordPressShared
  Modules/Sources/WordPressShared/URL+Helpers.swift
  WordPress/Classes/Categories/Media+Extensions.m
  WordPress/Classes/Services/MediaService.m
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: Enhancement

#24234 Move Double+Stats to WordPressShared
  Modules/Sources/WordPressShared/Utility/Double+Stats.swift
  WordPress/Classes/ViewRelated/Stats/Charts/DonutChartView.swift
  WordPress/Classes/ViewRelated/Stats/Extensions/NumberFormatter+Stats.swift
  WordPress/JetpackStatsWidgets/Views/Cards/StatsValueView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24233 BuildSettingsKit v2
  Modules/Sources/BuildSettingsKit/BuildSettings+Live.swift
  Modules/Sources/BuildSettingsKit/BuildSettings+Preview.swift
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  Modules/Sources/BuildSettingsKit/BuildSettingsEnvironment.swift
  WordPress/Classes/Services/NotificationSettingsService.swift
  WordPress/Classes/Services/NotificationSupportService.swift
  WordPress/Classes/Services/ShareExtensionService.swift
  WordPress/Classes/Stores/StatsWidgetsStore.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduler.swift
  WordPress/Classes/Utility/Migration/ContentMigrationCoordinator.swift
  WordPress/Jetpack/Classes/Utility/DataMigrator.swift
  WordPress/Jetpack/Classes/Utility/SharedDataIssueSolver.swift
  WordPress/JetpackDraftActionExtension/Info.plist
  WordPress/JetpackIntents/Info.plist
  WordPress/JetpackIntents/SitesDataProvider.swift
  WordPress/JetpackNotificationServiceExtension/Info.plist
  WordPress/JetpackShareExtension/Info.plist
  WordPress/JetpackStatsWidgets/Cache/HomeWidgetCache.swift
  WordPress/JetpackStatsWidgets/Helpers/WidgetDataReader.swift
  WordPress/JetpackStatsWidgets/Info.plist
  WordPress/JetpackStatsWidgets/LockScreenWidgets/LockScreenSiteListProvider.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/LockScreenStatsWidget.swift
  WordPress/JetpackStatsWidgets/Model/HomeWidgetData.swift
  WordPress/JetpackStatsWidgets/Remote service/StatsWidgetsService.swift
  WordPress/JetpackStatsWidgets/SiteListProvider.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetAllTime.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetThisWeek.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetToday.swift
  WordPress/WordPressDraftActionExtension/Info.plist
  WordPress/WordPressNotificationServiceExtension/Info.plist
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/Info.plist
  WordPress/WordPressShareExtension/MainShareViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
  WordPress/WordPressShareExtension/ShareMediaFileManager.swift
  WordPress/WordPressShareExtension/SharedCoreDataStack.swift
  WordPress/WordPressTest/Classes/Stores/StatsWidgetsStoreTests.swift
  WordPress/WordPressTest/DataMigratorTests.swift
  WordPress/WordPressTest/ReaderPostBackupTests.swift
  WordPress/WordPressTest/SharedDataIssueSolverTests.swift
Labels: General

#24241 Fix #21473: Do not show the login screen if the user is already logged in
  WordPress/Classes/System/Root View/SplitViewRootPresenter.swift
Labels: Login

#24216 Extract WPUserAgent to WordPressShared
  Modules/Sources/WordPressShared/WKWebView+UserAgent.swift
  Modules/Sources/WordPressShared/WPUserAgent.swift
  Modules/Tests/WordPressSharedTests/WPUserAgentTests.swift
  WordPress/Classes/Login/WordPressDotComAuthenticator.swift
  WordPress/Classes/Models/Blog/Blog.m
  WordPress/Classes/Models/ReaderListTopic+Creation.swift
  WordPress/Classes/Models/WPAccount+RestApi.swift
  WordPress/Classes/Networking/WordPressOrgRestApi+WordPress.swift
  WordPress/Classes/Services/AuthenticationService.swift
  WordPress/Classes/Services/BloggingPrompts/BloggingPromptsService.swift
  WordPress/Classes/Services/Page Layouts/PageLayoutService.swift
  WordPress/Classes/Services/PostServiceRemoteFactory.swift
  WordPress/Classes/Services/PushAuthenticationService.swift
  WordPress/Classes/Services/ReaderCardService.swift
  WordPress/Classes/Services/ReaderSiteSearchService.swift
  WordPress/Classes/Services/ReaderTopicService+FollowedInterests.swift
  WordPress/Classes/Services/ReaderTopicService+FollowedSites.swift
  WordPress/Classes/Services/ReaderTopicService+Interests.swift
  WordPress/Classes/Services/ReaderTopicService+SiteInfo.swift
  WordPress/Classes/Services/ReaderTopicService+Subscriptions.swift
  WordPress/Classes/Services/SiteAddressService.swift
  WordPress/Classes/Services/SiteAssemblyService.swift
  WordPress/Classes/Services/SiteSegmentsService.swift
  WordPress/Classes/Stores/ActivityStore.swift
  WordPress/Classes/Stores/PluginStore.swift
  WordPress/Classes/Stores/StatsInsightsStore.swift
  WordPress/Classes/Stores/StatsPeriodStore.swift
  WordPress/Classes/Stores/StatsRevampStore.swift
  WordPress/Classes/Stores/TimeZoneStore.swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerWPCom.m
  WordPress/Classes/Utility/Automated Transfer/AutomatedTransferHelper.swift
  WordPress/Classes/Utility/Networking/WordPressComRestApi+Defaults.swift
  WordPress/Classes/Utility/WPUserAgent.h
  WordPress/Classes/Utility/WPUserAgent.m
  WordPress/Classes/Utility/WPUserAgent.swift
  WordPress/Classes/Utility/WebViewController/WPWebViewController.m
  WordPress/Classes/ViewRelated/Blaze/Webview/BlazeWebViewController.swift
  WordPress/Classes/ViewRelated/Reader/Navigation/ReaderNavigationPath.swift
  WordPress/Classes/ViewRelated/Sharing/ShareAppContentPresenter.swift
  WordPress/Classes/ViewRelated/Site Creation/Design Selection/Preview/TemplatePreviewViewController.swift
  WordPress/Classes/ViewRelated/Site Creation/Design Selection/SiteDesignSectionLoader.swift
  WordPress/Classes/ViewRelated/Site Creation/Final Assembly/AssembledSiteView.swift
  WordPress/Classes/ViewRelated/Stats/Subscribers/StatsSubscribersStore.swift
  WordPress/Classes/ViewRelated/WhatsNew/Dependency container/RootViewCoordinator+WhatIsNew.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/WPUserAgentTests.m
Labels: [Type] Enhancement

#24249 Move `JSONDecoderExtension` utils to WordPressShared
  Modules/Sources/WordPressShared/Utility/JSONDecoderExtension.swift
Labels: Enhancement

#24253 Remove TracksConfiguration
  Modules/Sources/BuildSettingsKit/BuildSettings+Live.swift
  Modules/Sources/BuildSettingsKit/BuildSettings+Preview.swift
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  WordPress/Classes/Utility/Analytics/WPAnalytics+Domains.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.h
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Info.plist
  WordPress/Jetpack/AppConstants.swift
  WordPress/Jetpack/Info.plist
  WordPress/Jetpack/TracksConfiguration.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/Tracks.swift
  WordPress/WordPressShareExtension/TracksConfiguration.swift
  WordPress/WordPressTest/WPAnalyticsTrackerAutomatticTracksTests.m
  WordPress/WordPressTest/WPAppAnalyticsTests.m
Labels: General

#24251 Add `NO_ESCAPE` to the block argument in objcTry
  Modules/Sources/WordPressSharedObjC/Utility/WPException.m
  Modules/Sources/WordPressSharedObjC/include/WPException.h
Labels: Tech Debt

#24230 Move `WPAccount` `wordPressComRestAPI` definition to Swift
  WordPress/Classes/Models/WPAccount+RestApi.swift
  WordPress/Classes/Models/WPAccount.h
  WordPress/Classes/Models/WPAccount.m
  WordPress/Classes/Services/PostServiceRemoteFactory.swift
  WordPress/Classes/Services/PushAuthenticationService.swift
  WordPress/Classes/Services/ReaderSiteSearchService.swift
  WordPress/Classes/Services/ReaderSiteService.swift
  WordPress/Classes/Services/ReaderTopicService+Subscriptions.swift
  WordPress/Classes/Services/SiteSuggestionService.swift
  WordPress/Classes/Services/SuggestionService.swift
  WordPress/WordPressTest/MediaServiceUpdateTests.m
  WordPress/WordPressTest/MenusServiceTests.m
  WordPress/WordPressTest/PostCategoryServiceTests.m
  WordPress/WordPressTest/PostTagServiceTests.m
  WordPress/WordPressTest/ThemeServiceTests.m
  WordPress/WordPressTest/WPAccount+LookupTests.swift
Labels: Core Data, Enhancement

#24248 Remove some unused imports
  WordPress/Classes/Models/ReaderPost.m
  WordPress/Classes/Models/SourcePostAttribution.m
Labels: Enhancement

#24222 Update JetpackStatsWidget
  Modules/Sources/JetpackStatsWidgetsCore/HomeWidgetCache.swift
  WordPress/Classes/Stores/StatsWidgetsStore.swift
  WordPress/Jetpack/WidgetConfiguration.swift
  WordPress/JetpackIntents/SitesDataProvider.swift
  WordPress/JetpackStatsWidgets/LocalizationConfiguration.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/LockScreenSiteListProvider.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/ViewProvider/LockScreenMultiStatWidgetViewProvider.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/ViewProvider/LockScreenSingleStatWidgetViewProvider.swift
  WordPress/JetpackStatsWidgets/Model/HomeWidgetData.swift
  WordPress/JetpackStatsWidgets/Remote service/StatsWidgetsService.swift
  WordPress/JetpackStatsWidgets/SiteListProvider.swift
  WordPress/JetpackStatsWidgets/Supporting Files/JetpackStatsWidgets-Bridging-Header.h
  WordPress/JetpackStatsWidgets/Views/UnconfiguredView.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24257 Move String+Helper to WordPressShared
  Modules/Sources/WordPressShared/Utility/String+Helpers.swift
  WordPress/Classes/Extensions/String+Helpers.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24255 Extract TracksMini
  Modules/Package.swift
  Modules/Sources/TracksMini/Tracks.swift
  WordPress/JetpackStatsWidgets/LockScreenWidgets/LockScreenStatsWidget.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetAllTime.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetThisWeek.swift
  WordPress/JetpackStatsWidgets/Widgets/HomeWidgetToday.swift
  WordPress/Tracks+ShareExtension.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressDraftActionExtension/Tracks+DraftAction.swift
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressNotificationServiceExtension/Sources/Tracks/Tracks+ServiceExtension.swift
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/MainShareViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
Labels: General

#24243 Sync blogs upon launch
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/System/WordPressAppDelegate.swift
Labels: My Site

#24256 Update JetpackIntents
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24250 Ignore an Objective-C exception
  WordPress/Classes/ViewRelated/System/Coordinators/MySitesCoordinator.swift
Labels: Tech Debt

#24259 Add NotificationServiceExtensionCore and ShareExtensionCore
  Modules/Package.swift
  Modules/Sources/NotificationServiceExtensionCore/NotificationServiceExtensionConfiguration.swift
  Modules/Sources/ShareExtensionCore/ShareExtensionConfiguration.swift
  Modules/Sources/ShareExtensionCore/ShareExtensionService.swift
  WordPress/Classes/Services/AccountService.m
  WordPress/Classes/Services/NotificationSupportService.swift
  WordPress/Classes/Services/ShareExtensionService.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/App Configuration/ExtensionConfiguration.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Jetpack/ExtensionConfiguration.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressNotificationServiceExtension/Sources/NotificationService.swift
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/MainShareViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionAbstractViewController.swift
  WordPress/WordPressShareExtension/ShareExtensionSessionManager.swift
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressShareExtension/ShareModularViewController.swift
Labels: General

#24263 Move iTunesAppID to BuildSettings
  Modules/Sources/BuildSettingsKit/BuildSettings+Live.swift
  Modules/Sources/BuildSettingsKit/BuildSettings+Preview.swift
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  WordPress/Classes/Services/AppUpdate/AppStoreSearchService.swift
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/Utility/In-App Feedback/AppRatingsUtility.swift
  WordPress/Info.plist
  WordPress/Jetpack/AppConstants.swift
  WordPress/Jetpack/Info.plist
Labels: General

#24264 Cleanup String+Extensions in Share app extension
  Modules/Sources/WordPressShared/Utility/String+Helpers.swift
  Modules/Tests/WordPressSharedTests/StringHelperTests.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/String+Extensions.swift
  WordPress/WordPressTest/Extensions/StringExtensionsTests.swift
Labels: General

#24272 Extract shared code from Share app extensions
  Modules/Package.swift
  Modules/Sources/AztecExtensions/FormatBarItemProviders.swift
  Modules/Sources/AztecExtensions/Header+WordPress.swift
  Modules/Sources/AztecExtensions/ImgUploadProcessor.swift
  Modules/Sources/AztecExtensions/TextList+WordPress.swift
  Modules/Sources/AztecExtensions/URL+LinkNormalization.swift
  Modules/Sources/ShareExtensionCore/RemotePostCategory+Extensions.swift
  Modules/Sources/ShareExtensionCore/ShareMediaFileManager.swift
  Modules/Sources/ShareExtensionCore/ShareNoticeConstants.swift
  Modules/Sources/ShareExtensionCore/SharePost.swift
  Modules/Sources/WordPressShared/Utility/String+RangeConveresion.swift
  Modules/Sources/WordPressShared/Utility/String+RegEx.swift
  Modules/Sources/WordPressShared/Utility/UIImage+Color.swift
  Modules/Sources/WordPressUI/Tools/TableViewKeyboardObserver.swift
  WordPress/Classes/Extensions/AbstractPost+fixLocalMediaURLs.swift
  WordPress/Classes/Extensions/NSAttributedStringKey+Conversion.swift
  WordPress/Classes/Extensions/UIApplication+MainWindow.swift
  WordPress/Classes/Models/SharePost+UIActivityItemSource.swift
  WordPress/Classes/Services/AcknowledgementsService.swift
  WordPress/Classes/Services/Domains/DomainsService.swift
  WordPress/Classes/Services/PostCoordinator.swift
  WordPress/Classes/Utility/AppIcon.swift
  WordPress/Classes/Utility/Notifications/InteractiveNotificationsManager.swift
  WordPress/Classes/Utility/Sharing/ShareExtensionSessionManager.swift
  WordPress/Classes/Utility/Sharing/ShareNoticeNavigationCoordinator.swift
  WordPress/Classes/Utility/Sharing/ShareNoticeViewModel.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Post/PostTagPickerViewController.swift
  WordPress/Classes/ViewRelated/Reader/Cards/ReaderBlockedSiteCell.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderStreamViewController+Sharing.swift
  WordPress/Classes/ViewRelated/Reader/Style/WPStyleGuide+ReaderComments.swift
  WordPress/Classes/ViewRelated/Tools/TableViewKeyboardObserver.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/AppExtensionsService.swift
  WordPress/WordPressShareExtension/ExtensionNotificationManager.swift
  WordPress/WordPressShareExtension/ShareExtensionEditorViewController.swift
  WordPress/WordPressShareExtension/ShareExtractor.swift
  WordPress/WordPressShareExtension/ShareNoticeConstants.swift
  WordPress/WordPressShareExtension/ShareTagsPickerViewController.swift
  WordPress/WordPressShareExtension/SharedCoreDataStack.swift
  WordPress/WordPressTest/System/3DTouch/WP3DTouchShortcutCreatorTests.swift
Labels: General

#24270 Add task `:lintfix` to automatically fix linting errors
  Rakefile
Labels: Tooling

#24279 Remove UIImage-Extensions from NotificationServiceExtension
  WordPress/Classes/Extensions/UIImage+Extensions.swift
  WordPress/Resources/AppImages.xcassets/gravatar-unapproved.imageset/Contents.json
  WordPress/Resources/AppImages.xcassets/gravatar-unapproved.imageset/gravatar-unapproved.pdf
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24275 Extract Core Data to ShareExtensionCore
  Modules/Package.swift
  Modules/Sources/ShareExtensionCore/Data/MediaUploadOperation.swift
  Modules/Sources/ShareExtensionCore/Data/PostUploadOperation.swift
  Modules/Sources/ShareExtensionCore/Data/SharedCoreDataStack.swift
  Modules/Sources/ShareExtensionCore/Data/UploadOperation.swift
  Modules/Sources/ShareExtensionCore/Resources/EXTENSION_MIGRATIONS.md
  Modules/Sources/ShareExtensionCore/Resources/Extensions.xcdatamodeld/.xccurrentversion
  Modules/Sources/ShareExtensionCore/Resources/Extensions.xcdatamodeld/Extensions 2.xcdatamodel/contents
  Modules/Sources/ShareExtensionCore/Resources/Extensions.xcdatamodeld/Extensions 3.xcdatamodel/contents
  Modules/Sources/ShareExtensionCore/Resources/Extensions.xcdatamodeld/Extensions 4.xcdatamodel/contents
  Modules/Sources/ShareExtensionCore/Resources/Extensions.xcdatamodeld/Extensions.xcdatamodel/contents
  WordPress/JetpackStatsWidgets/Views/Cards/ListRow.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/AppExtensionsService.swift
Labels: General

#24172 Add a banner to ask user to validate their email
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/VerifyEmailRow.swift
Labels: Account Settings

#24276 Move BuildConfiguration to BuildSettingsKit
  Modules/Sources/BuildSettingsKit/BuildConfiguration.swift
  Modules/Sources/BuildSettingsKit/BuildSettings+Live.swift
  Modules/Sources/BuildSettingsKit/BuildSettings+Preview.swift
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  WordPress/Classes/Services/Page Layouts/PageLayoutService.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/BuildInformation/BuildConfiguration.swift
  WordPress/Classes/Utility/BuildInformation/FeatureFlag.swift
  WordPress/Classes/Utility/BuildInformation/RemoteFeatureFlag.swift
  WordPress/Classes/Utility/KeychainTools.swift
  WordPress/Classes/Utility/Logging/WPCrashLoggingProvider.swift
  WordPress/Classes/Utility/Universal Links/UniversalLinkRouter.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/App Settings/DebugMenuViewController.swift
  WordPress/Classes/ViewRelated/NUX/Helpers/WordPressAuthenticationManager.swift
  WordPress/Info.plist
  WordPress/Jetpack/Classes/Utility/DataMigrator.swift
  WordPress/Jetpack/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/DataMigratorTests.swift
  WordPress/WordPressTest/EUUSCompliance/CompliancePopoverViewModelTests.swift
  config/Jetpack.alpha.xcconfig
  config/Jetpack.debug.xcconfig
  config/Jetpack.release.xcconfig
  config/WordPress.alpha.xcconfig
  config/WordPress.debug.xcconfig
  config/WordPress.release.xcconfig
Labels: General

#24278 Extract more shared code from Share Extension
  Modules/Sources/DesignSystem/Foundation/BuildSettings+Brand.swift
  Modules/Sources/WordPressUI/Extensions/WPStyleGuide+Shared.swift
  Modules/Sources/WordPressUI/Views/WPReusableTableViewCells.swift
  WordPress/Classes/Extensions/Colors and Styles/WPStyleGuide+ApplicationStyles.swift
  WordPress/Classes/Extensions/UIButton+Extensions.swift
  WordPress/Classes/Utility/App Configuration/AppStyleGuide.swift
  WordPress/Classes/Utility/ViewLoading/NibReusable.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Ghost/DashboardFailureCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Stats/DashboardSingleStatView.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/BlogDetailHeaderView.swift
  WordPress/Classes/ViewRelated/Blog/Site Settings/LanguageSelectorViewController.swift
  WordPress/Classes/ViewRelated/Blog/Style/WPStyleGuide+BloggingPrompts.swift
  WordPress/Classes/ViewRelated/Cells/TextWithAccessoryButtonCell.swift
  WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainDetails/ViewController/RegisterDomainDetailsViewController.swift
  WordPress/Classes/ViewRelated/NUX/Views/Epilogues/EpilogueUserInfoCell.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSettingDetailsViewController.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsTableViewCells.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24282 Add AppURLScheme to BuildSettings
  Modules/Sources/BuildSettingsKit/BuildSettings+Live.swift
  Modules/Sources/BuildSettingsKit/BuildSettings+Preview.swift
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  WordPress/Classes/System/Constants/Constants.h
  WordPress/Classes/System/Constants/Constants.m
  WordPress/Classes/System/WordPressAppDelegate+openURL.swift
  WordPress/Classes/Utility/Analytics/WPAnalytics+Domains.swift
  WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m
  WordPress/Classes/ViewRelated/NUX/Helpers/WordPressAuthenticationManager.swift
  WordPress/Info.plist
  WordPress/Jetpack/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressDraftActionExtension/WordPressDraftPrefix.pch
  WordPress/WordPressShareExtension/WordPressSharePrefix.pch
  WordPress/WordPressTest/WPAppAnalyticsTests.m
  WordPress/WordPress_Prefix.pch
  config/Jetpack.alpha.xcconfig
  config/Jetpack.debug.xcconfig
  config/Jetpack.release.xcconfig
  config/WordPress.alpha.xcconfig
  config/WordPress.debug.xcconfig
  config/WordPress.release.xcconfig
Labels: General

#24284 Remove WordPressKit xcconfigs
  WordPress/WordPress.xcodeproj/project.pbxproj
  config/WordPressKit.xcconfig
  config/WordPressKitTests.xcconfig
Labels: General

#24286 Remove unused constants
  WordPress/Classes/System/Constants/Constants.h
  WordPress/Classes/System/Constants/Constants.m
Labels: General

#24277 Ensure current site is always displayed in Sidebar List
  RELEASE-NOTES.txt
  WordPress/Classes/ViewRelated/Blog/Site Picker/BlogList/BlogListViewModel.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
  WordPress/WordPressTest/BlogListViewModelTests.swift
Labels: iPad, UI, Tech Debt

#24287 Remove Jetpack variant of AppConfiguration
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  WordPress/Classes/Utility/App Configuration/AppConfiguration.swift
  WordPress/Jetpack/AppConfiguration.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24290 Move InfiniteScrollView to WordPressUI
  Modules/Sources/WordPressUI/Views/InfiniteScrollerView.swift
  WordPress/Jetpack/Classes/NUX/JetpackPrologueViewController.swift
  WordPress/Jetpack/Classes/NUX/New Landing Screen/Views/InfiniteScrollerViewDelegate.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24289 Convert JepackStatsWidget to a synchronized folder
  WordPress/JetpackStatsWidgets/Sources/Helpers/HomeWidgetDataFileReader.swift
  WordPress/JetpackStatsWidgets/Sources/Helpers/WidgetDataReader.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Configs/LockScreenAllTimePostsBestViewsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Configs/LockScreenAllTimeViewsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Configs/LockScreenAllTimeViewsVisitorsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Configs/LockScreenStatsWidgetConfig.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Configs/LockScreenTodayLikesCommentsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Configs/LockScreenTodayViewsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Configs/LockScreenTodayViewsVisitorsStatWidgetConfig.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/LockScreenSiteListProvider.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/LockScreenStatsWidget.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Models/LockScreenMultiStatViewModel.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Models/LockScreenSingleStatViewModel.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Models/LockScreenStatsWidgetEntry.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Models/LockScreenUnconfiguredViewModel.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/ViewProvider/LockScreenMultiStatWidgetViewProvider.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/ViewProvider/LockScreenSingleStatWidgetViewProvider.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Views/LockScreenFieldView.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Views/LockScreenMultiStatView.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Views/LockScreenSingleStatView.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Views/LockScreenSiteTitleView.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Views/LockScreenStatsWidgetsView.swift
  WordPress/JetpackStatsWidgets/Sources/LockScreenWidgets/Views/LockScreenUnconfiguredView.swift
  WordPress/JetpackStatsWidgets/Sources/Model/GroupedViewData.swift
  WordPress/JetpackStatsWidgets/Sources/Model/HomeWidgetData.swift
  WordPress/JetpackStatsWidgets/Sources/Model/ListViewData.swift
  WordPress/JetpackStatsWidgets/Sources/Model/StatsWidgetEntry.swift
  WordPress/JetpackStatsWidgets/Sources/Services/StatsWidgetsService.swift
  WordPress/JetpackStatsWidgets/Sources/SiteListProvider.swift
  WordPress/JetpackStatsWidgets/Sources/StatsWidgets.swift
  WordPress/JetpackStatsWidgets/Sources/Views/Cards/FlexibleCard.swift
  WordPress/JetpackStatsWidgets/Sources/Views/Cards/ListRow.swift
  WordPress/JetpackStatsWidgets/Sources/Views/Cards/LockScreenFlexibleCard.swift
  WordPress/JetpackStatsWidgets/Sources/Views/Cards/LockScreenVerticalCard.swift
  WordPress/JetpackStatsWidgets/Sources/Views/Cards/StatsValueView.swift
  WordPress/JetpackStatsWidgets/Sources/Views/Cards/VerticalCard.swift
  WordPress/JetpackStatsWidgets/Sources/Views/Helpers/iOS17WidgetAPIs.swift
  WordPress/JetpackStatsWidgets/Sources/Views/ListStatsView.swift
  WordPress/JetpackStatsWidgets/Sources/Views/Localization/LocalizableStrings.swift
  WordPress/JetpackStatsWidgets/Sources/Views/MultiStatsView.swift
  WordPress/JetpackStatsWidgets/Sources/Views/SingleStatView.swift
  WordPress/JetpackStatsWidgets/Sources/Views/StatsWidgetsView.swift
  WordPress/JetpackStatsWidgets/Sources/Views/UnconfiguredView.swift
  WordPress/JetpackStatsWidgets/Sources/Widgets/HomeWidgetAllTime.swift
  WordPress/JetpackStatsWidgets/Sources/Widgets/HomeWidgetThisWeek.swift
  WordPress/JetpackStatsWidgets/Sources/Widgets/HomeWidgetToday.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24291 Remove WordPressKit.h
  WordPress/WordPressKit/WordPressKit.h
Labels: General

#24254 Fix #24244: Dismiss the 'Delete Site' view controller
  WordPress/Classes/ViewRelated/Blog/Site Management/DeleteSiteViewController.swift
Labels: Site Management, iPad

#24285 Remove ALPHA_BUILD preprocessor macro
  Modules/Sources/BuildSettingsKit/BuildSettings+Live.swift
  Modules/Sources/BuildSettingsKit/BuildSettings+Preview.swift
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  WordPress/Classes/ViewRelated/Jetpack/Branding/Coordinator/JetpackRedirector.swift
  WordPress/Info.plist
  WordPress/Jetpack/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
  config/Common.debug.xcconfig
  config/Common.enterprise.xcconfig
  config/Common.xcconfig
  config/Jetpack.alpha.xcconfig
  config/Jetpack.debug.xcconfig
  config/Jetpack.release.xcconfig
Labels: General

#24292 Remove AppDependency.swift
  WordPress/Classes/Jetpack/JetpackAuthenticationManager.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Analytics/MigrationAnalyticsTracker.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Analytics/MigrationEvent.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/MigrationAppDetection.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/MigrationAppearance.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/MigrationDependencyContainer.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/MigrationEmailService.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/MigrationState.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Navigation/MigrationFlowCoordinator.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Navigation/MigrationNavigationController.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Navigation/MigrationStep.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Views/Configuration/MigrationActionsConfiguration.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Views/Configuration/MigrationCenterViewConfiguration.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Views/Configuration/MigrationHeaderConfiguration.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Views/Configuration/MigrationStepConfiguration.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Views/MigrationActionsView.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Views/MigrationCenterView.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Views/MigrationHeaderView.swift
  WordPress/Classes/Jetpack/JetpackMigration/Common/Views/MigrationStepView.swift
  WordPress/Classes/Jetpack/JetpackMigration/DeleteWordPress/MigrationDeleteWordPressViewController.swift
  WordPress/Classes/Jetpack/JetpackMigration/DeleteWordPress/MigrationDeleteWordPressViewModel.swift
  WordPress/Classes/Jetpack/JetpackMigration/Done/MigrationDoneViewController.swift
  WordPress/Classes/Jetpack/JetpackMigration/Done/MigrationDoneViewModel.swift
  WordPress/Classes/Jetpack/JetpackMigration/LoadWordPress/MigrationLoadWordPressViewController.swift
  WordPress/Classes/Jetpack/JetpackMigration/LoadWordPress/MigrationLoadWordPressViewModel.swift
  WordPress/Classes/Jetpack/JetpackMigration/NotificationsPermission/MigrationNotificationsCenterView.swift
  WordPress/Classes/Jetpack/JetpackMigration/NotificationsPermission/MigrationNotificationsViewController.swift
  WordPress/Classes/Jetpack/JetpackMigration/NotificationsPermission/MigrationNotificationsViewModel.swift
  WordPress/Classes/Jetpack/JetpackMigration/SuccessCard/CollectionView/DashboardMigrationSuccessCell.swift
  WordPress/Classes/Jetpack/JetpackMigration/SuccessCard/MigrationSuccessActionHandler.swift
  WordPress/Classes/Jetpack/JetpackMigration/SuccessCard/MigrationSuccessCardView.swift
  WordPress/Classes/Jetpack/JetpackMigration/SuccessCard/TableView/MigrationSuccessCell.swift
  WordPress/Classes/Jetpack/JetpackMigration/Welcome/MigrationWelcomeViewController.swift
  WordPress/Classes/Jetpack/JetpackMigration/Welcome/MigrationWelcomeViewModel.swift
  WordPress/Classes/Jetpack/NUX/JetpackPrologueStyleGuide.swift
  WordPress/Classes/Jetpack/NUX/JetpackPrologueViewController.swift
  WordPress/Classes/Jetpack/NUX/JetpackPrologueViewController.xib
  WordPress/Classes/Jetpack/NUX/LandingScreen/ViewModel/JetpackPromptsConfiguration.swift
  WordPress/Classes/Jetpack/NUX/LandingScreen/Views/JetpackLandingScreenView.swift
  WordPress/Classes/Jetpack/Utility/DataMigrationError.swift
  WordPress/Classes/Jetpack/Utility/DataMigrator.swift
  WordPress/Classes/Jetpack/Utility/JetpackSocialError.swift
  WordPress/Classes/Jetpack/Utility/SharedDataIssueSolver.swift
  WordPress/Classes/System/JetpackWindowManager.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/App Configuration/AppDependency.swift
  WordPress/Jetpack/AppDependency.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Delete WordPress/UIButton+Dismiss.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Success card/Collection View/DashboardMigrationSuccessCell+Jetpack.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Success card/Collection View/DashboardMigrationSuccessCell+WordPress.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Success card/Table View/MigrationSuccessCell+Jetpack.swift
  WordPress/Jetpack/Classes/ViewRelated/WordPress-to-Jetpack Migration/Success card/Table View/MigrationSuccessCell+WordPress.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24293 Remove localized strings from AppConstants
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AppAboutScreenConfiguration.swift
  WordPress/Classes/ViewRelated/Me/App Settings/AppSettingsViewController.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+AppRatings.swift
  WordPress/Classes/ViewRelated/Sharing/ShareAppContentPresenter+TableView.swift
  WordPress/Classes/ViewRelated/Support/LogOutActionHandler.swift
  WordPress/Classes/ViewRelated/WhatsNew/Presenter/WhatIsNewScenePresenter.swift
  WordPress/Jetpack/AppConstants.swift
Labels: General

#24296 Add remaining files to the shared codebase
  WordPress/Classes/System/Root View/SplitViewRootPresenter.swift
  WordPress/Classes/ViewRelated/Domains/Views/SiteDomainsView.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewController.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24294 Remove AppConstants
  Modules/Sources/BuildSettingsKit/BuildSettings+Live.swift
  Modules/Sources/BuildSettingsKit/BuildSettings+Preview.swift
  Modules/Sources/BuildSettingsKit/BuildSettings.swift
  WordPress/Classes/Models/WPAccount+AccountSettings.swift
  WordPress/Classes/Models/WPAccount.m
  WordPress/Classes/Services/CredentialsService.swift
  WordPress/Classes/Utility/KeychainTools.swift
  WordPress/Classes/Utility/ZendeskUtils.swift
  WordPress/Classes/ViewRelated/Me/App Settings/About/AppAboutScreenConfiguration.swift
  WordPress/Classes/ViewRelated/Me/Me Main/MeViewController.swift
  WordPress/Classes/ViewRelated/WhatsNew/Data store/AnnouncementsStore.swift
  WordPress/Info.plist
  WordPress/Jetpack/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24265 Move some content group and styles to FormattableContentKit
  Modules/Package.swift
  Modules/Sources/FormattableContentKit/Groups/HeaderContentGroup.swift
  Modules/Sources/FormattableContentKit/Groups/SubjectContentGroup.swift
  Modules/Sources/FormattableContentKit/Styles/SnippetsContentStyles.swift
  Modules/Sources/FormattableContentKit/Styles/SubjectContentStyles.swift
  Modules/Sources/FormattableContentKit/Styles/WPStyleGuide+Notifications.swift
  WordPress/Classes/Models/Notifications/Notification.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Groups/HeaderContentGroup.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Groups/SubjectContentGroup.swift
  WordPress/Classes/ViewRelated/Notifications/FormattableContent/Styles/SnippetsContentStyles.swift
  WordPress/Classes/ViewRelated/Notifications/Views/LikeUserTableViewCell.swift
Labels: Enhancement

#24306 Rename Common.enterprise.xcconfig
  WordPress/WordPress.xcodeproj/project.pbxproj
  config/Common.alpha.xcconfig
  config/Jetpack.alpha.xcconfig
  config/WordPress.alpha.xcconfig
  config/WordPressAuthenticator.enterprise.xcconfig
Labels: General

#24215 Offer "Log in with a different account" when OAuth is denied
  WordPress/Classes/Login/WordPressDotComAuthenticator.swift
  WordPress/WordPressTest/Login/WordPressDotComAuthenticatorTests.swift
Labels: Login

#24303 Remove IS_JETPACK compilation conditions
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24305 Remove some unused resources outside of .xcassets
  WordPress/Resources/Images/animatedBox.png
  WordPress/Resources/Images/animatedBox@2x.png
  WordPress/Resources/Images/animatedBoxBack.png
  WordPress/Resources/Images/animatedBoxBack@2x.png
  WordPress/Resources/Images/animatedBoxPage1.png
  WordPress/Resources/Images/animatedBoxPage1@2x.png
  WordPress/Resources/Images/animatedBoxPage2.png
  WordPress/Resources/Images/animatedBoxPage2@2x.png
  WordPress/Resources/Images/animatedBoxPage3.png
  WordPress/Resources/Images/animatedBoxPage3@2x.png
  WordPress/Resources/Images/approve.png
Labels: General

#24310 Remove unused `PostAnnotation` object
  WordPress/Classes/Models/PostAnnotation.h
  WordPress/Classes/Models/PostAnnotation.m
Labels: Core Data

#24267 Move `ReachabilityUtils` to WordPressShared
  Modules/Package.swift
  Modules/Sources/WordPressShared/Reachability/Notification+Reachability.swift
  Modules/Sources/WordPressShared/Reachability/ReachabilityAlert.swift
  Modules/Sources/WordPressShared/Reachability/ReachabilityUtils.swift
  Modules/Sources/WordPressShared/Utility/UIAlertController+Presentation.swift
  Modules/Sources/WordPressShared/Utility/UIApplication+MainWindow.swift
  WordPress/Classes/Extensions/Notifications/NotificationName+Names.swift
  WordPress/Classes/Extensions/UIAlertController+Helpers.swift
  WordPress/Classes/Models/Notifications/Actions/ApproveComment.swift
  WordPress/Classes/Models/Notifications/Actions/TrashComment.swift
  WordPress/Classes/Services/SiteSuggestionService.swift
  WordPress/Classes/Services/SuggestionService.swift
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/Reachability/ReachabilityUtils+OnlineActions.swift
  WordPress/Classes/Utility/Reachability/ReachabilityUtils.h
  WordPress/Classes/Utility/Reachability/ReachabilityUtils.m
  WordPress/Classes/Utility/WebViewController/WPWebViewController.m
  WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
  WordPress/Classes/ViewRelated/Domains/DomainSelectionViewController.swift
  WordPress/Classes/ViewRelated/Gutenberg/GutenbergMediaInserterHelper.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/Restore Options/Coordinators/JetpackBackupOptionsCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Restore/Restore Warning/Coordinators/JetpackRestoreWarningCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanCoordinator.swift
  WordPress/Classes/ViewRelated/Jetpack/Jetpack Scan/JetpackScanHistoryCoordinator.swift
  WordPress/Classes/ViewRelated/Likes/LikesListController.swift
  WordPress/Classes/ViewRelated/Plugins/ViewModels/PluginListViewModel.swift
  WordPress/Classes/ViewRelated/Plugins/ViewModels/PluginViewModel.swift
  WordPress/Classes/ViewRelated/Post/Controllers/AbstractPostListViewController.swift
  WordPress/Classes/ViewRelated/Post/Prepublishing/PrepublishingSocialAccountsViewController.swift
  WordPress/Classes/ViewRelated/QR Login/Helpers/QRLoginInternetConnectionChecker.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderWebView.swift
  WordPress/Classes/ViewRelated/Site Creation/Final Assembly/SiteAssemblyWizardContent.swift
  WordPress/Classes/ViewRelated/Stats/StatsViewController.m
  WordPress/Classes/ViewRelated/System/NetworkAware.swift
  WordPress/Classes/ViewRelated/Tools/Time Zone/TimeZoneSelectorViewModel.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPress.xcodeproj/xcshareddata/xcschemes/WordPressUITests.xcscheme
  WordPress/WordPressTest/NetworkStatus.swift
  WordPress/WordPressTest/TestingAppDelegate.h
Labels: Enhancement

#24314 Prepare for Keystone (p1)
  WordPress/Classes/Services/BlogService.m
  WordPress/Classes/Services/LocalCoreDataService.h
  WordPress/Classes/System/WordPress-Bridging-Header.h
  WordPress/Classes/Utility/UIAlertControllerProxy.h
  WordPress/Classes/Utility/WPError.h
  WordPress/Classes/Utility/WPTableViewHandler.h
  WordPress/Classes/Utility/WebViewController/WPStyleGuide+WebView.h
  WordPress/Classes/Utility/WebViewController/WPStyleGuide+WebView.m
  WordPress/Classes/Utility/WebViewController/WPWebViewController.m
  WordPress/Classes/ViewRelated/Blog/Sharing/SharingAuthorizationHelper.h
  WordPress/Classes/ViewRelated/Blog/Site Settings/SiteSettingsViewController.m
  WordPress/Classes/ViewRelated/Menus/Categories/Menu+ViewDesign.h
  WordPress/Classes/ViewRelated/Menus/Controllers/MenuItemAbstractPostsViewController.m
  WordPress/Classes/ViewRelated/Menus/Controllers/MenuItemSourceResultsViewController.m
  WordPress/Classes/ViewRelated/Pages/Style/WPStyleGuide+Pages.h
  WordPress/Classes/ViewRelated/Pages/Style/WPStyleGuide+Pages.m
  WordPress/Classes/ViewRelated/Stats/StatsViewController.h
  WordPress/WordPress_Prefix.pch
Labels: General

#24260 Support WordPress.com magic link login
  WordPress/Classes/Login/WordPressDotComAuthenticator.swift
  WordPress/Classes/System/WordPressAppDelegate+openURL.swift
  WordPress/WordPressTest/Login/WordPressDotComAuthenticatorTests.swift
Labels: Login

#24325 Remove unused `setOptions:` method from `Blog.m`
  WordPress/Classes/Models/Blog/Blog.m
Labels: Tech Debt

#24322 Make WordPressAppDelegate public
  WordPress/Classes/System/WordPressAppDelegate+openURL.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
Labels: General

#24327 Fix an issue with WordPressComRestApi instance not being cached by WPAccount
  WordPress/Classes/Models/WPAccount+RestApi.swift
  WordPress/Classes/Models/WPAccount.h
  WordPress/Classes/Models/WPAccount.m
  WordPress/WordPressTest/AccountSettingsServiceTests.swift
  WordPress/WordPressTest/MediaServiceUpdateTests.m
  WordPress/WordPressTest/MenusServiceTests.m
  WordPress/WordPressTest/PostCategoryServiceTests.m
  WordPress/WordPressTest/PostTagServiceTests.m
  WordPress/WordPressTest/ThemeServiceTests.m
Labels: General

#24331 Decouple some model implementations from the app targets
  WordPress/Classes/Models/BloggingPromptSettings+CoreDataClass.swift
  WordPress/Classes/Models/BloggingPromptSettingsReminderDays+CoreDataClass.swift
  WordPress/Classes/Models/PostVisibility.swift
  WordPress/Classes/Utility/Blogging Reminders/BloggingRemindersScheduler.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/BloggingPromptsAttribution+Strings.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Prompts/BloggingPromptsAttribution.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Service/BlogDashboardPersonalizationService.swift
  WordPress/Classes/ViewRelated/Post/PostVisibilityPicker.swift
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/NullMockUserDefaults.swift
Labels: Core Data, Enhancement

#24326 Update access level for types that will go into WordPressData
  WordPress/Classes/Extensions/Array+Page.swift
  WordPress/Classes/Models/AbstractPost+Autosave.swift
  WordPress/Classes/Models/AbstractPost+Blaze.swift
  WordPress/Classes/Models/AbstractPost+Local.swift
  WordPress/Classes/Models/AbstractPost+Searchable.swift
  WordPress/Classes/Models/BasePost.swift
  WordPress/Classes/Models/Blocking/BlockedAuthor.swift
  WordPress/Classes/Models/Blocking/BlockedSite.swift
  WordPress/Classes/Models/Blog/Blog+BlockEditorSettings.swift
  WordPress/Classes/Models/Blog/Blog+BlogAuthors.swift
  WordPress/Classes/Models/Blog/Blog+Capabilities.swift
  WordPress/Classes/Models/Blog/Blog+HomepageSettings.swift
  WordPress/Classes/Models/Blog/Blog+Jetpack.swift
  WordPress/Classes/Models/Blog/Blog+Plans.swift
  WordPress/Classes/Models/Blog/Blog+Post.swift
  WordPress/Classes/Models/Blog/Blog+Quota.swift
  WordPress/Classes/Models/Blog/BlogSettings.swift
  WordPress/Classes/Models/Gutenberg/BlockEditorSettingElement+CoreDataProperties.swift
  WordPress/Classes/Models/JetpackState.swift
  WordPress/Classes/Models/Page.swift
  WordPress/Classes/Models/Post.swift
  WordPress/Classes/Services/BloggingPrompts/BloggingPromptRemoteObject.swift
  WordPress/Classes/Utility/BlogQuery.swift
  WordPress/Classes/Utility/CoreData/Migrator/CoreDataIterativeMigrator.swift
  WordPress/Classes/Utility/Spotlight/Protocols/SearchableItemConvertable.swift
Labels: Core Data

#24334 Remove unused LocationService
  WordPress/Classes/Utility/LocationService.h
  WordPress/Classes/Utility/LocationService.m
Labels: General

#24199 [Tooling] Migrate Prototype Builds from App Center to Firebase App Distribution
  Gemfile
  Gemfile.lock
  WordPress/Credentials/Secrets-example.swift
  docs/feature-flags.md
  fastlane/Fastfile
  fastlane/env/project.env-example
  fastlane/env/user.env-example
  fastlane/lanes/build.rb
Labels: Tooling

#24330 Remove unused resources
  WordPress/Resources/HTML/defaultPostTemplate.html
  WordPress/Resources/HTML/defaultPostTemplate_old.html
  WordPress/Resources/HTML/loader.html
  WordPress/Resources/HTML/postPreview.html
  WordPress/Resources/HTML/xhtml1-transitional.dtd
  WordPress/Resources/HTML/xhtmlValidatorTemplate.xhtml
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressTest/ReaderCardServiceTests.swift
  WordPress/WordPressTest/ReaderPostStreamServiceTest.swift
Labels: General

#24335 Cleanup Resources
  WordPress/Misc/Emoji.txt
  WordPress/Misc/Images/wpcom-blog-icon.png
  WordPress/Misc/Images/wporg-blog-icon.png
  WordPress/Misc/Lottie/JetpackAllFeaturesLogosAnimation_ltr.json
  WordPress/Misc/Lottie/JetpackAllFeaturesLogosAnimation_rtl.json
  WordPress/Misc/Lottie/JetpackInstallPluginLogoAnimation_ltr.json
  WordPress/Misc/Lottie/JetpackInstallPluginLogoAnimation_rtl.json
  WordPress/Misc/Lottie/JetpackNotificationsLogoAnimation_ltr.json
  WordPress/Misc/Lottie/JetpackNotificationsLogoAnimation_rtl.json
  WordPress/Misc/Lottie/JetpackReaderLogoAnimation_ltr.json
  WordPress/Misc/Lottie/JetpackReaderLogoAnimation_rtl.json
  WordPress/Misc/Lottie/JetpackStatsLogoAnimation_ltr.json
  WordPress/Misc/Lottie/JetpackStatsLogoAnimation_rtl.json
  WordPress/Misc/Lottie/JetpackWordPressLogoAnimation_ltr.json
  WordPress/Misc/Lottie/JetpackWordPressLogoAnimation_rtl.json
  WordPress/Misc/Reader/reader.css
  WordPress/Misc/SupportChat/support_chat_error_handler.js
  WordPress/Misc/SupportChat/support_chat_widget.css
  WordPress/Misc/SupportChat/support_chat_widget.js
  WordPress/Misc/SupportChat/support_chat_widget_page.css
  WordPress/Misc/SupportChat/support_chat_widget_page.html
  WordPress/Misc/world-map.svg
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24336 Remove JP_SCHEME
  WordPress/Info.plist
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24343 Remove unused OCLint target
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24344 Convert custom app icons to synchronized folders
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24346 Extract wpAssertion to WordPressShared
  Modules/Sources/WordPressShared/Utility/Instrumentation.swift
  WordPress/Classes/Models/AbstractPost.swift
  WordPress/Classes/RemotePost+Metadata.swift
  WordPress/Classes/Services/PostCoordinator+Notices.swift
  WordPress/Classes/Services/PostHelper+Metadata.swift
  WordPress/Classes/Services/PostRepository+Helpers.swift
  WordPress/Classes/System/WordPressAppDelegate.swift
  WordPress/Classes/Utility/AssertionLogger.swift
  WordPress/Classes/Utility/TrackableError.swift
  WordPress/Classes/Utility/Version.swift
  WordPress/Classes/ViewRelated/Blog/My Site/MySiteViewController+FAB.swift
  WordPress/Classes/ViewRelated/Blog/Site Picker/AddSiteController.swift
  WordPress/Classes/ViewRelated/Comments/Controllers/Create/CommentCreateViewModel.swift
  WordPress/Classes/ViewRelated/Comments/Controllers/Edit/CommentEditViewModel.swift
  WordPress/Classes/ViewRelated/Comments/Views/Detail/CommentCellViewModel.swift
  WordPress/Classes/ViewRelated/Media/MediaPicker/Helpers/MediaPickerMenuController.swift
  WordPress/Classes/ViewRelated/Media/MediaPicker/Menu/MediaPickerMenu+ImagePlayground.swift
  WordPress/Classes/ViewRelated/Post/EditPostViewController.swift
  WordPress/Classes/ViewRelated/Post/Utils/PostNoticeNavigationCoordinator.swift
  WordPress/Classes/ViewRelated/System/Sidebar/SidebarViewModel.swift
  WordPress/Classes/ViewRelated/Tools/Time Zone/Views/TimeZoneSearchHeaderView.swift
Labels: General

#24345 Remove AppConstants
  WordPress/Classes/Utility/App Configuration/AppConstants.swift
  WordPress/Jetpack/AppConstants.swift
Labels: General

#24341 Push some build settings to project level
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24349 Decouple some model implementations from the app targets - Round 2
  WordPress/Classes/Models/Blog/Blog+Capabilities.swift
  WordPress/Classes/Models/Comment/Comment+CoreDataClass.swift
  WordPress/Classes/Models/GravatarProfile.swift
  WordPress/Classes/Models/Notifications/Notification+AppsTargets.swift
  WordPress/Classes/Models/Notifications/Notification.swift
  WordPress/Classes/Models/Revisions/DiffAbstractValue+Attributes.swift
  WordPress/Classes/Models/Revisions/RevisionDiff.swift
  WordPress/Classes/Models/UserProfile.swift
  WordPress/Classes/Models/WPAccount+AccountSettings.swift
  WordPress/Classes/Models/WPAccount+Keychain.swift
  WordPress/Classes/Services/NotificationSyncMediator.swift
  WordPress/Classes/Services/NotificationSyncMediatorProtocol.swift
  WordPress/Classes/Services/SiteManagementService.swift
  WordPress/Classes/Utility/BlogQuery.swift
  WordPress/Classes/Utility/CoreData/ContextManager.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderHelpers.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/SiteOrganizationType.swift
Labels: Core Data

#24352 Remove unused `appRatingUtility` from `AppEnvironment`
  WordPress/Classes/Utility/Environment/AppEnvironment.swift
Labels: [Type] Tech Debt

#24350 Replace `asURL()` call with `URL(string:)`
  WordPress/Classes/Networking/WordPressOrgRestApi+WordPress.swift
  WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergMediaEditorImage.swift
  WordPress/Classes/ViewRelated/Media/StockPhotos/StockPhotosMedia.swift
Labels: General

#24342 Convert share and draft extensions to synchronized folders
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressShareExtension/Sources/Extensions/NSExtensionContext+Extensions.swift
  WordPress/WordPressShareExtension/Sources/Extensions/RemoteBlog+Capabilities.swift
  WordPress/WordPressShareExtension/Sources/Extensions/RemotePost+ShareData.swift
  WordPress/WordPressShareExtension/Sources/Extensions/UIImage+Extensions.swift
  WordPress/WordPressShareExtension/Sources/Extensions/UINavigationController+Extensions.swift
  WordPress/WordPressShareExtension/Sources/Extensions/WPStyleGuide+Share.swift
  WordPress/WordPressShareExtension/Sources/Services/AppExtensionsService.swift
  WordPress/WordPressShareExtension/Sources/Services/CategoryTree.swift
  WordPress/WordPressShareExtension/Sources/Services/ExtensionNotificationManager.swift
  WordPress/WordPressShareExtension/Sources/Services/ExtensionTransitioningManager.swift
  WordPress/WordPressShareExtension/Sources/Services/ShareData.swift
  WordPress/WordPressShareExtension/Sources/Services/ShareExtractor.swift
  WordPress/WordPressShareExtension/Sources/UI/ExtensionPresentationAnimator.swift
  WordPress/WordPressShareExtension/Sources/UI/ExtensionPresentationController.swift
  WordPress/WordPressShareExtension/Sources/UI/MainInterface.storyboard
  WordPress/WordPressShareExtension/Sources/UI/MainShareViewController.swift
  WordPress/WordPressShareExtension/Sources/UI/ShareCategoriesPickerViewController.swift
  WordPress/WordPressShareExtension/Sources/UI/ShareExtension.storyboard
  WordPress/WordPressShareExtension/Sources/UI/ShareExtensionAbstractViewController.swift
  WordPress/WordPressShareExtension/Sources/UI/ShareExtensionEditorViewController.swift
  WordPress/WordPressShareExtension/Sources/UI/ShareModularViewController.swift
  WordPress/WordPressShareExtension/Sources/UI/SharePostTypePickerViewController.swift
  WordPress/WordPressShareExtension/Sources/UI/ShareTagsPickerViewController.swift
  WordPress/WordPressShareExtension/Sources/Utilities/ShareSegueHandler.swift
Labels: General

#24354 Rewrite `Notification.ContentType` as `ContentType`
  Modules/Sources/FormattableContentKit/NotificationContentFactory.swift
Labels: General

#24351 Remove `AppEnvironment` from `WordPressOrgRestApi`
  WordPress/Classes/Networking/WordPressOrgRestApi+WordPress.swift
Labels: General

#24353 Move `areBloggingRemindersAllowed()` to dedicated file
  WordPress/Classes/Models/Blog/Blog+Capabilities.swift
  WordPress/Classes/ViewRelated/Blog/BloggingReminders/Blog+BloggingRemindersFlow.swift
Labels: Core Data

#24357 Remove WordPressAuthentificator xcconfigs
  WordPress/WordPress.xcodeproj/project.pbxproj
  config/WordPressAuthenticator.enterprise.xcconfig
  config/WordPressAuthenticator.xcconfig
  config/WordPressAuthenticatorTests.xcconfig
Labels: General

#24316 Rewrite WPAppAnalytics extensions in Swift
  WordPress/Classes/Models/AbstractPost.swift
  WordPress/Classes/Services/MediaCoordinator.swift
  WordPress/Classes/Services/SharingService.swift
  WordPress/Classes/Stores/PluginStore.swift
  WordPress/Classes/System/Root View/RootViewPresenter+EditorNavigation.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics+Extensions.swift
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.h
  WordPress/Classes/Utility/Analytics/WPAppAnalytics.m
  WordPress/Classes/Utility/Sharing/ShareNoticeNavigationCoordinator.swift
  WordPress/Classes/Utility/Spotlight/SearchManager.swift
  WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Pages/DashboardPagesListCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Posts/DashboardPostsListCardCell.swift
  WordPress/Classes/ViewRelated/Blog/Blog Dashboard/Cards/Quick Actions/DashboardQuickActionsCardCell.swift
  WordPress/Classes/ViewRelated/Blog/My Site/Header/HomeSiteHeaderViewController.swift
  WordPress/Classes/ViewRelated/Blog/Sharing/SharingButtonsViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/DeleteSiteViewController.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/SiteSettingsViewController+SiteManagement.swift
  WordPress/Classes/ViewRelated/Blog/Site Management/StartOverViewController.swift
  WordPress/Classes/ViewRelated/Comments/Controllers/CommentDetailViewController.swift
  WordPress/Classes/ViewRelated/Comments/Views/Detail/CommentCellViewModel.swift
  WordPress/Classes/ViewRelated/Feature Introduction/Blogging Prompts/BloggingPromptsIntroductionPresenter.swift
  WordPress/Classes/ViewRelated/Jetpack/Login/JetpackLoginViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaItemViewController.swift
  WordPress/Classes/ViewRelated/Media/MediaNoticeNavigationCoordinator.swift
  WordPress/Classes/ViewRelated/Media/SiteMedia/Controllers/SiteMediaCollectionViewController.swift
  WordPress/Classes/ViewRelated/Media/SiteMedia/SiteMediaViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController+JetpackPrompt.swift
  WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift
  WordPress/Classes/ViewRelated/Pages/Controllers/PageListViewController.swift
  WordPress/Classes/ViewRelated/People/Controllers/PeopleViewController.swift
  WordPress/Classes/ViewRelated/Plugins/Controllers/PluginDirectoryViewController.swift
  WordPress/Classes/ViewRelated/Post/Controllers/PostListViewController.swift
  WordPress/Classes/ViewRelated/Post/PostEditor+Publish.swift
  WordPress/Classes/ViewRelated/Post/PostListEditorPresenter.swift
  WordPress/Classes/ViewRelated/Post/Utils/PostNoticePublishSuccessView.swift
  WordPress/Classes/ViewRelated/Reader/Comments/ReaderCommentsViewController.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderStreamViewController+Sharing.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/ReaderStreamViewController.swift
  WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailCoordinator.swift
  WordPress/Classes/ViewRelated/Stats/Helpers/BottomScrollAnalyticsTracker.swift
  WordPress/Classes/ViewRelated/Stats/Insights/StatsBaseCell.swift
  WordPress/Classes/ViewRelated/Stats/Insights/Two Column Stats/TwoColumnCell.swift
  WordPress/Classes/ViewRelated/Stats/Period Stats/Overview/OverviewCell.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/Date Chooser/SiteStatsTableHeaderView.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/StatsTotalRow.swift
  WordPress/Classes/ViewRelated/Stats/Shared Views/ViewMoreRow.swift
  WordPress/Classes/ViewRelated/Stats/SiteStatsDashboardViewController.swift
  WordPress/Classes/ViewRelated/Stats/Traffic/StatsTrafficDatePickerViewModel.swift
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
  WordPress/WordPressTest/Analytics/EditorAnalytics/PostEditorAnalyticsSessionTests.swift
  WordPress/WordPressTest/Analytics/Utils/TestAnalyticsTracker.swift
  WordPress/WordPressTest/ContextManagerTests.swift
  WordPress/WordPressTest/RootViewCoordinatorTests.swift
  WordPress/WordPressTest/SiteCreation/SiteSegmentsCellTests.swift
  WordPress/WordPressTest/SiteCreation/TitleSubtitleHeaderTests.swift
  WordPress/WordPressTest/WPAppAnalyticsTests.m
Labels: General

#24338 Add Keystone Target
  Sources/Keystone/Keystone.h
  Sources/Keystone/Keystone_Prefix.pch
  WordPress/WordPress.xcodeproj/project.pbxproj
Labels: General

#24361 Fix typos in localizable string keys
  WordPress/Classes/Plugins/Views/InstalledPluginsListView.swift
Labels: [Type] Tech Debt

#24348 Update access level for types that will go into WordPressData – Round 2
  WordPress/Classes/Extensions/NSManagedObject.swift
  WordPress/Classes/Jetpack/Utility/SharedDataIssueSolver.swift
  WordPress/Classes/Models/AbstractPost.swift
  WordPress/Classes/Models/Account Settings/ManagedAccountSettings+CoreDataProperties.swift
  WordPress/Classes/Models/Account Settings/ManagedAccountSettings.swift
  WordPress/Classes/Models/Blog/Blog+Capabilities.swift
  WordPress/Classes/Models/BloggingPrompt+CoreDataClass.swift
  WordPress/Classes/Models/BloggingPromptSettings+CoreDataClass.swift
  WordPress/Classes/Models/BloggingPromptSettingsReminderDays+CoreDataClass.swift
  WordPress/Classes/Models/Comment/Comment+CoreDataClass.swift
  WordPress/Classes/Models/Domain.swift
  WordPress/Classes/Models/Gutenberg/PageTemplateCategory+CoreDataProperties.swift
  WordPress/Classes/Models/Gutenberg/PageTemplateLayout+CoreDataProperties.swift
  WordPress/Classes/Models/Page+CoreDataProperties.swift
  WordPress/Classes/Models/People Management/ManagedPerson+CoreDataProperties.swift
  WordPress/Classes/Models/People Management/ManagedPerson.swift
  WordPress/Classes/Models/Post+CoreDataProperties.swift
  WordPress/Classes/Models/PostCategory+Creation.swift
  WordPress/Classes/Models/PostCategory+Lookup.swift
  WordPress/Classes/Models/PublicizeInfo+CoreDataClass.swift
  WordPress/Classes/Models/PublicizeService.swift
  WordPress/Classes/Models/ReaderAbstractTopic+Lookup.swift
  WordPress/Classes/Models/ReaderCard+CoreDataClass.swift
  WordPress/Classes/Models/ReaderPost+Searchable.swift
  WordPress/Classes/Models/ReaderSiteTopic+Lookup.swift
  WordPress/Classes/Models/ReaderSiteTopic.swift
  WordPress/Classes/Models/ReaderTagTopic.swift
  WordPress/Classes/Models/Revisions/DiffAbstractValue.swift
  WordPress/Classes/Models/Revisions/DiffContentValue.swift
  WordPress/Classes/Models/Revisions/DiffTitleValue.swift
  WordPress/Classes/Models/Revisions/Revision.swift
  WordPress/Classes/Models/Revisions/RevisionDiff+CoreData.swift
  WordPress/Classes/Models/Revisions/RevisionDiff.swift
  WordPress/Classes/Models/Role.swift
  WordPress/Classes/Models/SharingButton+Lookup.swift
  WordPress/Classes/Models/SharingButton.swift
  WordPress/Classes/Models/SiteSuggestion+CoreDataClass.swift
  WordPress/Classes/Models/ThemeIdHelper.swift
  WordPress/Classes/Models/UserSettings.swift
  WordPress/Classes/Models/UserSuggestion+CoreDataClass.swift
  WordPress/Classes/Services/NullBlogPropertySanitizer.swift
  WordPress/Classes/Services/PostHelper+Metadata.swift
  WordPress/Classes/Services/PostRepository+Helpers.swift
  WordPress/Classes/Services/PostServiceRemoteFactory.swift
  WordPress/Classes/Utility/CoreData/ContextManager.swift
  WordPress/Classes/Utility/CoreData/CoreDataHelper.swift
  WordPress/Classes/Utility/CoreData/NSManagedObject+Lookup.swift
  WordPress/Classes/Utility/CoreData/TaggedManagedObjectID.swift
  WordPress/Classes/Utility/Media/MediaFileManager.swift
  WordPress/Classes/Utility/Spotlight/Protocols/SearchableActivityConvertable.swift
  WordPress/Classes/Utility/Spotlight/Protocols/SearchableItemConvertable.swift
  WordPress/Classes/Utility/Spotlight/Utils/SearchIdentifierGenerator.swift
  WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController+Activity.swift
  WordPress/Classes/ViewRelated/Reader/Controllers/SiteOrganizationType.swift
Labels: Core Data

#24262 Enable remote search in Themes if custom themes are supported
  WordPress.xcworkspace/xcshareddata/swiftpm/Package.resolved
  WordPress/Classes/Services/ThemeService.h
  WordPress/Classes/Services/ThemeService.m
  WordPress/Classes/ViewRelated/Themes/ThemeBrowserViewController.swift
  WordPress/WordPressTest/ThemeServiceTests.m
Labels: [Type] Bug, Themes

#24365 Move WordPressAuthenticatorTests to Tests and use sync folders
  Tests/WordPressAuthenticatorTests/Analytics/AnalyticsTrackerTests.swift
  Tests/WordPressAuthenticatorTests/Authenticator/PasteboardTests.swift
  Tests/WordPressAuthenticatorTests/Authenticator/WordPressAuthenticator+TestsUtils.swift
  Tests/WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorDisplayTextTests.swift
  Tests/WordPressAuthenticatorTests/Authenticator/WordPressAuthenticatorTests.swift
  Tests/WordPressAuthenticatorTests/Authenticator/WordPressSourceTagTests.swift
  Tests/WordPressAuthenticatorTests/Credentials/CredentialsTests.swift
  Tests/WordPressAuthenticatorTests/EmailClientPicker/AppSelectorTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/Character+URLSafeTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/CodeVerifier+Fixture.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/CodeVerifierTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/Data+Base64URLTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/Data+SHA256Tests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/DataGettingStub.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/GoogleClientIdTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/GoogleOAuthTokenGetterTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/GoogleOAuthTokenGettingStub.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/IDTokenTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/JSONWebToken+Fixtures.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/JWTokenTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/NewGoogleAuthenticatorTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/OAuthRequestBody+GoogleSignInTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/OAuthTokenRequestBodyTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/OAuthTokenResponseBody+Fixture.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/ProofKeyForCodeExchangeTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/Result+ConvenienceInitTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/URL+GoogleSignInTests.swift
  Tests/WordPressAuthenticatorTests/GoogleSignIn/URLRequest+GoogleSignInTests.swift
  Tests/WordPressAuthenticatorTests/Logging/LoggingTests.m
  Tests/WordPressAuthenticatorTests/Logging/LoggingTests.swift
  Tests/WordPressAuthenticatorTests/MemoryManagementTests.swift
  Tests/WordPressAuthenticatorTests/Mocks/MockNavigationController.swift
  Tests/WordPressAuthenticatorTests/Mocks/ModalViewControllerPresentingSpy.swift
  Tests/WordPressAuthenticatorTests/Mocks/WordPressAuthenticatorDelegateSpy.swift
  Tests/WordPressAuthenticatorTests/Mocks/WordpressAuthenticatorProvider.swift
  Tests/WordPressAuthenticatorTests/Model/LoginFieldsTests.swift
  Tests/WordPressAuthenticatorTests/Model/LoginFieldsValidationTests.swift
  Tests/WordPressAuthenticatorTests/Model/WordPressComSiteInfoTests.swift
  Tests/WordPressAuthenticatorTests/Navigation/NavigationToEnterAccountTests.swift
  Tests/WordPressAuthenticatorTests/Navigation/NavigationToEnterSiteTests.swift
  Tests/WordPressAuthenticatorTests/Services/LoginFacadeTests.m
  Tests/WordPressAuthenticatorTests/SingIn/AppleAuthenticatorTests.swift
  Tests/WordPressAuthenticatorTests/SingIn/LoginViewControllerTests.swift
  Tests/WordPressAuthenticatorTests/SingIn/SiteAddressViewModelTests.swift
  Tests/WordPressAuthenticatorTests/WordPressAuthenticator.xctestplan
  WordPress/WordPress.xcodeproj/project.pbxproj
  WordPress/WordPressAuthenticator/WordPressAuthenticator.h
Labels: General
